### ISSUE TITLE
stuck on a certain algo.ccminer KlausT

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#1]
![default](https://cloud.githubusercontent.com/assets/16507768/21136955/742aaa64-c130-11e6-88ba-4447df25bc32.PNG)
skein is need to work, but still works noescrypt.

**Comment by lyolyalya** [comment]
opposite situation=)
![2](https://cloud.githubusercontent.com/assets/16507768/21138303/185c8a08-c136-11e6-88ad-1eff3207e77e.PNG)

**Comment by aaronsace** [comment]
I'll release a new version later this week that will support different configurations better. 
In the mean time, please can you post the ps1 file here as you have it configured and I'll check it.

**Comment by lyolyalya** [comment]
sure thing=)


[MultiPoolMiner.txt](https://github.com/aaronsace/MultiPoolMiner/files/648977/MultiPoolMiner.txt)

**Comment by aaronsace** [comment]
Found the error. 

Change this line: 
from
`if($CurrentMiner -eq $null -or ($CurrentMiner.Path -ne $NewMiner.Path -and $CurrentMiner.Arguments -ne $NewMiner.Arguments))`
to
`if($CurrentMiner -eq $null -or $CurrentMiner.Path -ne $NewMiner.Path -or $CurrentMiner.Arguments -ne $NewMiner.Arguments)`

**Comment by lyolyalya** [comment]
okay=)i'll try it immidiately=)
