### ISSUE TITLE
Version 2.5.0 new warning / error?

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#100]
[2017-05-14_06-56-38.txt](https://github.com/aaronsace/MultiPoolMiner/files/999568/2017-05-14_06-56-38.txt)
Version 2.5 shows me this now what i start it?
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5>powershell -version 5.0 -noexit -executionpolic
y bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username lankyman -worker
name multipoolminer -interval 60 -location europe -ssl -type amd,cpu -algorithm cryptonigh
t,ethash,equihash -poolname miningpoolhub -currency btc,usd -donate 15"
Transcript started, output file is .\Logs\2017-05-14_02-35-06.txt
Value was either too large or too small for a Decimal.
At C:\Users\icsoka\Desktop\MultiPoolMinerV2.5\Include.ps1:58 char:5
+     $Stat = [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

Log file for 2.5.0 attached

**Comment by aaronsace** [comment]
Don't think that will cause any major issues. 

Can you upload the log file to your GitHub post to check?

**Comment by imrecsoka** [comment]
Log uploaded in original post... above

**Comment by aaronsace** [comment]
Sorry, I missed this. I think you are running it on the wrong PowerShell version. Use 'Windows PowerShell' not 'Windows PowerShell (x86)'.
