### ISSUE TITLE
Autoexchange delay or not working?

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#101]
Miningpoolhub exchange - waited for 2 weeks.
Not sure if i need to wait more.

This is the screen shot of what i see: (attached)
![autoexchange](https://cloud.githubusercontent.com/assets/25494601/26033961/53a0a08a-38b5-11e7-9bb4-6ef06c787309.PNG)

**Comment by aaronsace** [comment]
Just leave it; it's only a small amount and MiningPoolHub does a clean-up of the balances now and then.
