### ISSUE TITLE
sgminer building bins for nvidia

### ISSUE THREAD

**Issue by gazm** [aaronsace/MultiPoolMiner#102]
For some reason I cant get any sgminer algo to work, when it boots up it builds bins for my nvidia cards instead of AMD (mixed rig) is there something I can put into the sgminer powershell script to set the device ids?

**Comment by aaronsace** [comment]
I think I need to add ' --gpu-platform 0' to the command line; will push the change now.

**Comment by gazm** [comment]
yes that was it but on my system nvidia is 0 and amd is 1. Must start with whatever gpu 0 is. Easy fix for me not sure how easy it would be for you to code that check in though

**Comment by aaronsace** [comment]
Bummer; thanks for letting me know.
