### ISSUE TITLE
command is wrong for Lyra2z-AMD\sgminer.exe 

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#103]
Bin\Lyra2z-AMD\sgminer.exe --api-listen -k lyra2z **--worksize 32** --intensity 13 -o
                                               stratum+ssl://europe.lyra2z-hub.miningpoolhub.com:17025 -u Etherion.wk1 -p x

**Comment by aaronsace** [comment]
I think I amended this now but there is a problem with that release still.

**Comment by aaronsace** [comment]
https://github.com/djm34/sgminer-msvc2015/issues/4
