### ISSUE TITLE
MPM launches a second instance of same miner

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#106]
I noticed that MPM sometimes launches another instance of the same miner. Is this due to MPM losing connection to the miner api port and if so, why and how? How can I fix it?

**Comment by aaronsace** [comment]
It's probably just launching a miner per GPU. What miner(s) is it?

**Comment by fonyo** [comment]
Claymore's ethash. Not a good sign.

**Comment by aaronsace** [comment]
I'm not quite sure what the issue would be. I'll be uploading a new release soon and haven't noted that issue with it.

**Comment by fonyo** [comment]
It hasn't happened for a while probably why I was passive about it. But when it was happening, it was constant and night over night.
