### ISSUE TITLE
benchmarking freezes/doesnt complete, lots of red error messages

### ISSUE THREAD

**Issue by SS2006** [aaronsace/MultiPoolMiner#108]
Version 2.5 works fine, i can't get the new versions to work or complete benchmarking

log: https://drive.google.com/open?id=0B6j4YvbzGgOgZE1lTFY4Y0NweGM

**Comment by aaronsace** [comment]
You are missing the binary files from the release zip.

**Comment by SS2006** [comment]
they wont be found in MultiPoolMinerV2.5.1.2.zip ? So I should download v2.4.3.5 ?

**Comment by aaronsace** [comment]
#107
