### ISSUE TITLE
Sia algorithm doesn't work

### ISSUE THREAD

**Issue by czjlj** [aaronsace/MultiPoolMiner#109]
`Stratum extranonce answer id was not correct!
Stratum connection interrupted`

Pls check it,thanks！

**Comment by aaronsace** [comment]
Is there a problem with the pool? I can't get SIA to work in anything but Claymore.

**Comment by aaronsace** [comment]
https://bitcointalk.org/index.php?topic=472510.msg19115045#msg19115045

**Comment by killrlite** [comment]
so how do we resolve this

**Comment by aaronsace** [comment]
Not sure, waiting for MiningPoolHub's advice.

**Comment by miningpoolhub** [comment]
Siacoin pool only supports Claymore protocol. Too sad that there's many siacoin mining protocols out there.

**Comment by imrecsoka** [comment]
I really cant stand SGminer or CGMiner or any of those tools, they dont seem to perform well..... or they crash and they say stuff like Engine failed or some thing, its just bizzare why they also like to clear the screen or quit - u can not troubleshoot the error . I dont know, i am not an expert also, i am waiting for somebody to help me and show me the light.

**Comment by aaronsace** [comment]
This is not fixable so I'm closing the issue.
