### ISSUE TITLE
NVIDIA Mining

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#11]
so. i run start.bat. i had some zip archive and last screen i saw before crashing my system is - 
![default](https://cloud.githubusercontent.com/assets/16507768/21467729/9b8aeb72-ca00-11e6-83a6-e0b386f58c26.PNG)
first of all.it seems that scrypt is running ccminer and sgminer simultaneosly...
then - need option to choose sgminer or ccminer i guess...or maybe nvidia and amd rig and then scrypt must set ccminer or sgminer to use.if it can remember my choice - would be great.
then - need option to skip the benchmarking.i want to write hasrates by myself cause i don't use tpruvot miner...
then - i use 2 different versions of ccminer (nanashi for lyra and klaust for others) - how can i add two paths to run appropriate miner?
and so on...if i can start it normally...

**Comment by aaronsace** [comment]
Miner files can be added/removed/edited in the 'miners' folder. 
Please provide links to the miners that you use and what you use them for.

**Comment by lyolyalya** [comment]
https://github.com/KlausT/ccminer/releases
this is miners for anything except lyra(ccminer_nanashi for lyra i get from nicehash's miner bin directory).
but i can see that in ccminer.ps1 is only one path to it...i need minimum two of them.
so.if i don't use sgminer what should i delete and where?

**Comment by aaronsace** [comment]
If you don't have an AMD card then it will attempt to benchmark sgminer but it will just mark it as a zero hash rate. Is it still trying to mine sgminer even after the benchmark? That may have been an oversight if it is; delete 'sgminer.ps1' for now. 

Does the release of ccminer that I included not mine everything? If not, what algorithms are missing? 

To edit ccminer: 
Copy and paste 'ccminer.ps1'. 
Call one 'ccminer1.ps1' and the other 'ccminer2.ps1'. 
Set the miner path at the top. 
Set the hashrate to 'ccminer1' or 'ccminer2' instead of 'ccminer'. 
Remove any unused algorithms in each file.

**Comment by lyolyalya** [comment]
benchmark not passed cause sgminer and ccminer starts together and then system crashes and reboot.
tpruvot is not that fast as klaust on neoscrypt and skein.and tpruvot and klaust not that fast as nanashi in lyra.but now thats three algos+zec is most profitable so need to get as much as ccminer can get.
i'll try to delete sgminer and duplicate ccminer tomorrow.
and one more question - delta.what measure of it?% or BTC?

**Comment by aaronsace** [comment]
Are you sure sgminer crashed your system because you don't have any AMD cards? What happens if you open sgminer? Does it not just close straight away? 

I see, will look at adding different versions then let them benchmark. 

Delta is a decimal percentage so it can be used consistently.

**Comment by lyolyalya** [comment]
read carefully and look at first screen=)i start start.bat.benchmarking begins. and because ccminer and sgminer due this process starting together - system freezes and after few seconds - crash.
why delta not in btc?
and you again forget to add in ccminer stratum+tcp:// in -o option=)without it ccminer tries http connection and fail.

**Comment by lyolyalya** [comment]
ok.i removed sgminer.ps1? added stratum+tcp://.everything seems going up but eth+sia benchmark with dcri 40 runing in a circle already by 5 times.
![image](https://cloud.githubusercontent.com/assets/16507768/21470050/5752c2c4-ca80-11e6-8ddc-975da08c1658.png)

**Comment by aaronsace** [comment]
I think I know what the issue is. 
Remove 'AMD' from the claymore .ps1 files for now.

**Comment by lyolyalya** [comment]
in ccminer cmd... -a skein -o stratum+tcp://$..... or ccminer can't connect to the pool.
not mining!benchmarking.orrr...this was mining already?hmmm.maybe...sorry.my bet.will try again and put my ccminers in...

**Comment by lyolyalya** [comment]
no.this can't be mining.where is the list of profit?or in v2 there is not btc/day list?

**Comment by aaronsace** [comment]
I meant '.txt'. Profit is still there; maximize your window or scroll up.

**Comment by lyolyalya** [comment]
nahhh...it's bencmarking!now circuling on lyra...
![image](https://cloud.githubusercontent.com/assets/16507768/21471605/f4ecbf00-cabf-11e6-9380-6b566bd86711.png)
.

**Comment by lyolyalya** [comment]
emm.so?any thoughts about endless benchmarking?

**Comment by aaronsace** [comment]
Your stats name probably doesn't match; have a look in the stats folder. 

It says ccminer on mine but your filename is ccminer1 or ccminer2 now. 
HashRates = [PSCustomObject]@{Lyra2RE2 = '$($Stats.**Ccmine**r_Lyra2RE2_HashRate.Day)'}

**Comment by lyolyalya** [comment]
you say that i if i want to use 2 different versions of ccminer i need to duplicate, rename, and add algos.i did that...where this line is?

**Comment by aaronsace** [comment]
In the ccminer '.ps1' files: 
"Set the hashrates to 'ccminer1' or 'ccminer2' instead of 'ccminer'."

It's basically the filename.

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/21484796/489228ca-cba1-11e6-910c-d68c8cf5a5c9.png)
here?

**Comment by aaronsace** [comment]
Yep, that's it.

**Comment by lyolyalya** [comment]
finally.benchmark is done.but.need to insert this zec miner for nvidia https://bitcointalk.org/index.php?topic=1707546.0
would you help?

**Comment by lyolyalya** [comment]
rewrite part of code for it.can you check syntax?
"Type":  ["NVIDIA"],
        "Path":  ".\\Bin\\NVIDIA\\miner.exe",
        "Arguments":  "--server $($Pools.Equihash.Host) --port $($Pools.Equihash.Port) --user $($Pools.Equihash.User) --pass x --cuda_devices 0 1 2",
        "HashRates":  {"Equihash":  "$($Stats.EBFW_Equihash_HashRate.Day)"},
        "API":  "EWBF"
if miners argument is 
miner --server zec.coinmine.pl --user user.1 --pass x --port 7007 --cuda_devices 0 1 2
 is it matter "API": "EWBF"???

**Comment by aaronsace** [comment]
The syntax looks correct buy I don't know what the API is for that. You will have to enter your hash rate manually: 
"HashRates": {"Equihash": "1000"},

**Comment by lyolyalya** [comment]
and thah's all?no extra files?and what to do with api line?delete it?left empty?

**Comment by aaronsace** [comment]
Leave the API set as you have it; it won't matter. 

Every algorithm gets an initial 10% boost when benchmarking. The speed will level out once mining.

**Comment by lyolyalya** [comment]
strange boost...well.seems like everthing else working fine.but again - v1.3 - better as for me=)

**Comment by aaronsace** [comment]
Not many people want to wait ages for a 100% accurate benchmark or get lots of manual readings. But as you can see the miner files are highly editable, glad you've got it working well.

**Comment by lyolyalya** [comment]
why ages? run miner for 5-10 minutes and there is result=)

**Comment by aaronsace** [comment]
Times that by at least 30.

**Comment by lyolyalya** [comment]
but no 10%=)

**Comment by lyolyalya** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/38
