### ISSUE TITLE
Miner sw switch delay issues

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#112]
One of my RX 480s is a bit more sensitive and doesn't like the current switch delay between miners therefore the driver either crashes, computer gets BSOD or occasionally the gpu gets a random coloured screen of death. Where can I change this? There should be a parameter added to the start.bat by default that we could adjust to our needs.

**Comment by aaronsace** [comment]
There is no delay; I could add one but the loading and closing of the miners is slow as it is. 

Have you been editing the clock/voltage settings on your GPUs? 
I recommend not going to extreme if you have; just slightly undervolting the processing chip and slightly overclocking the memory will do.

**Comment by fonyo** [comment]
Yeah, my screen GPU has vanilla BIOS. The best mining BIOS for RX480 would not even let my PC through the loading windows screen. I do have an integrated GPU on the motherboard which I'm considering to utilise or at least try out soon. Even vbios+ is unstable so I assumed it was a weaker card hence the request here. Sometimes the switching delay is just not long enough and murders the card. That's also true with the nicehash miner but I could adjust it there at least. That's why I thought it should work with MPM as well.

**Comment by imrecsoka** [comment]
Hi, i want to understand what you guys are talking about here, are we talking about when MultiMiner checks and finds a more profitable coin which in turn then starts mining it?
I didnt even know this actually works?
Maybe my batch file is wrong? I only have 3 values separated with comma, so not sure?

**Comment by fonyo** [comment]
Well, that's the whole point of MPM. Otherwise you can just use MPH's 17xxx ports to mine a single algo without MPM and the pool switches the coins for you. This, unless you want to change the dcri value automatically when dual mining to make it more profitable. And then you have to relaunch the miner and then sometimes your cards need more time or they freeze.

**Comment by aaronsace** [comment]
I'll an optional delay parameter.

**Comment by fonyo** [comment]
Brilliant!

**Comment by imrecsoka** [comment]
for my -interval option i use a value of 180, is this fine?

**Comment by aaronsace** [comment]
The default is 60. 180 is fine but I wouldn't recommend setting it any higher.

**Comment by imrecsoka** [comment]
what does it do anyways, because i noticed my cpu miner gets slow every now and then but when i increased the time to 180 it doesnt hapen for a while  it actually took ages i kept waiting but didnt see the hash rate drop.

**Comment by aaronsace** [comment]
It checks miningpoolhub every 60 seconds.

**Comment by imrecsoka** [comment]
Checks it to do what? coin profit-checking?

**Comment by aaronsace** [comment]
Yes, that's what this program does.

**Comment by aaronsace** [comment]
I've locked this, if there is an issue, raise a new one. Thanks.
