### ISSUE TITLE
Stats are broken completely?

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#115]
![image](https://cloud.githubusercontent.com/assets/25494601/26333615/2e4daf66-3f5f-11e7-9635-1f4ab37c8ee2.png)

I spend over 1 hour running benchmark my goodness and now the stats are broken

**Comment by aaronsace** [comment]
What happened; was it correct at some point? 
Can you post the log?

**Comment by fonyo** [comment]
Mine is much _better_. 68K usd per day. I think MPH is submitting incorrect info re profitability. Sc is running at dcri 39 which is definitely wrong.

**Comment by czjlj** [comment]
![101958](https://cloud.githubusercontent.com/assets/17327321/26335868/78721e28-3fa1-11e7-9ad1-b4875d7273ab.png)

**Comment by aaronsace** [comment]
Yes but it is 3:30am.

**Comment by fonyo** [comment]
Yeah, that worked great. All back to normal except _MPM is 9460% more profitable than conventional mining_. I think I'll keep that for a laugh.

**Comment by aaronsace** [comment]
It most likely screwed up the average because it was so large. MiningPoolHub still doesn't provide actual daily figures.

**Comment by fonyo** [comment]
Does that mean it went even higher than that? It is quite usual in crypto for a coin to do this. Care to share how it is calculated exactly or where can I see it in the code please?

**Comment by aaronsace** [comment]
I've not seen it do that before to that extreme. It does rectify itself but I'm not sure how long it would have taken as I didn't have it running all night due to getting the latest release out and testing. 

I don't think clearing the results is a good idea unless they are wrong. I could cap the extreme spikes?

**Comment by fonyo** [comment]
That would not reflect the truth, either. I would leave it as is or make it so it changes (back) quicker. The delta would stop it from switching too quickly, right?

**Comment by zaptrem** [comment]
I ran into the same problem this morning, I guess I can quit my job now?

**Comment by aaronsace** [comment]
Reset the stat, I'm looking at preventing this.

**Comment by fonyo** [comment]
68K USD per day? I would create a real pool of coins like the one Dagobert has. @zaptrem :D

**Comment by imrecsoka** [comment]
Hi Lee, i have rolled back to the previous version of you suite.
