### ISSUE TITLE
SGminer 5.3.1 better speed for Skein algo

### ISSUE THREAD

**Issue by MandarKarhade** [aaronsace/MultiPoolMiner#116]
Hi, Rather than using Cgminer for Skein algo, please use SGminer 5.3.1 which does skein at about 40% higher rate. That will be more profitable . Thank you

UPDATE: NVM you are using sgminer but the intensity is set to 11 and work size to 64 which is too low for any newer AMD card. Work size 256 and intensity 22-23 works best. So you might want to integrate that

**Comment by aaronsace** [comment]
What card are you using? 

If anyone has any suggestions one what settings are safe and what would be optimal for newer cards then I would appreciate it: 

```
    Lyra2z = ' --worksize 32 --intensity 18'
    Equihash = ' --gpu-threads 2 --worksize 256'
    Cryptonight = ' --gpu-threads 1 --worksize 8 --rawintensity 896'
    Ethash = ' --gpu-threads 1 --worksize 192 --xintensity 1024'
    Sia = ''
    Yescrypt = ' --worksize 4 --rawintensity 256'
    BlakeVanilla = ' --intensity d'
    Lyra2RE2 = ' --gpu-threads 2 --worksize 128 --intensity d'
    Skein = ' --gpu-threads 2 --worksize 64 --intensity 11'
    Qubit = ' --gpu-threads 2 --worksize 128 --intensity d'
    NeoScrypt = ' --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64'
    X11 = ' --gpu-threads 2 --worksize 128 --intensity d'
    MyriadGroestl = ' --gpu-threads 2 --worksize 64 --intensity d'
    Groestl = ' --gpu-threads 2 --worksize 128 --intensity d'
    Keccak = ''
    Scrypt = ''
```

**Comment by MandarKarhade** [comment]
Hi Aaron ! 
I am using RX480 and Skein algo is the one that I am pointing out
  Skein = ' --gpu-threads 2 --worksize 256 --intensity 23'
works best for me. about 250-270mh Skein at 70W power usage with rock stable performance. With intensity 11 and worksize 64 it is too low

**Comment by aaronsace** [comment]
I'll update the settings on that algorithm.

Do the other algorithms perform as expected? I have an RX480 but tweaking setting takes forever so I haven't checked that they are the best. 

I'm worried they will crash older cards as well so I don't like to mess with them unless anyone reports it.

**Comment by bandit420** [comment]
[Sgminermph.txt](https://github.com/aaronsace/MultiPoolMiner/files/1026545/Sgminermph.txt)

Still using the "old" SGminer 5.3.1 from Miningpoolhub and in my opinion still the fastest, and can also confirm its faster with the mentioned parameters (5*RX480, around 1.3 GH).

**Comment by aaronsace** [comment]
The only improvement to the actual miner that he made was adding skein; everything else is the same.

**Comment by jjziets** [comment]
I am not getting 5.3.1 to work on any of my systems so can't test. But my 6x RX480 8Gb gets 1,55 GH/s with reorder/cgminer.exe. (i 13) That looks to be the sam as what @bandit420 get with 5.3.1. I can push this to +300 by lifting my power limits. But running at 89C is not good for the cards so I am happy with 270 at 75c

"--gpu-threads 2 --worksize 64 --intensity 13"

**Comment by bandit420** [comment]
[worksize256_i_22.txt](https://github.com/aaronsace/MultiPoolMiner/files/1027368/worksize256_i_22.txt)
[worksize_256i_d.txt](https://github.com/aaronsace/MultiPoolMiner/files/1027369/worksize_256i_d.txt)
[worksize_64_i_d.txt](https://github.com/aaronsace/MultiPoolMiner/files/1027370/worksize_64_i_d.txt)
[worksize64_i11.txt](https://github.com/aaronsace/MultiPoolMiner/files/1027371/worksize64_i11.txt)

So weird thing: reorder and sgminer (nicehash 5.6.1) allways failing. But sgminer is also not recognizing the kernel and falls back to the standard ckolivas kernel. Maybe a problem  of cpu, because I had only 1 core free to test of 8. Worksize 256 and Itensity d with sgminer from MPH seem to be the best results (labeld "sgminermph" on the benchmarks).

**Comment by bandit420** [comment]
Just as an addition: running -15% on the core and +150 on memory clocks, and newest driver (AMD 17.5.2) for the benchmarks.

**Comment by lekiet0917** [comment]
Please give me sgminer release for skein and conf. Thanks
