### ISSUE TITLE
[2017-05-24 20:01:30] : Compiling code and initializing GPUs. This will take a while... [2017-05-24 20:01:31] : Selected OpenCL device index 4 doesn't exist.

### ISSUE THREAD

**Issue by acaciosc** [aaronsace/MultiPoolMiner#118]
Multiple prompt commands of cryptonight are initialized with this very same message. Only one works, but still there are some command prompt/firewall SPAMs from time to time. The worst is that it's mining monero in the first place, which clearly isn't the best coin to GPU mine at all.

![gah](https://cloud.githubusercontent.com/assets/7469089/26429405/074db5a0-40bd-11e7-8ba9-0b32150b351f.png)

![gah2](https://cloud.githubusercontent.com/assets/7469089/26429418/22fb91fa-40bd-11e7-8ef5-464bcf08bf75.png)

**Comment by acaciosc** [comment]
Check also my log file:


**********************
Início da transcrição do Windows PowerShell
Hora de início: 20170524201411
Nome de usuário: DESKTOP-CVITQ6K\acaciosc
Executar como Usuário: DESKTOP-CVITQ6K\acaciosc
Computador: DESKTOP-CVITQ6K (Microsoft Windows NT 10.0.15063.0)
Aplicativo Host: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\MultiPoolMiner.ps1'
ID do Processo: 4268
PSVersion: 5.1.15063.296
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.296
BuildVersion: 10.0.15063.296
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcrição iniciada, o arquivo de saída é .\Logs\2017-05-24_08-14-11.txt
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."
PS>TerminatingError(Get-Content): "O comando em execução parou porque a variável preferencial "ErrorActionPreference" ou o parâmetro comum está definido como Stop: Não é possível localizar o caminho 'C:\Users\acaciosc\Documents\MultiPoolMiner 2.5.2\Bin\Excavator\default_command_file.json' porque ele não existe."

**Comment by acaciosc** [comment]
![gah3](https://cloud.githubusercontent.com/assets/7469089/26429563/fad89a6e-40bd-11e7-9fc8-4da81f089887.png)

**Comment by acaciosc** [comment]
![gah4](https://cloud.githubusercontent.com/assets/7469089/26429595/38811062-40be-11e7-8a56-3ed52ceb7896.png)

**Comment by aaronsace** [comment]
I think you are missing the point of what is happening here. 

It is benchmarking everything. I recommend using the 'start.bat' file as it is quicker.

**Comment by acaciosc** [comment]
So are you telling me that the SPAMs are something expected to happen? I mean... being spammed numerous times with prompt commands that quickly appear and disappear (some even don't disappear - the ones I'm asking you why I got an error message notifying that the "Selected OpenCL device index 4 doesn't exist"), even after a couple of minutes? How long does it usually take?

**Comment by aaronsace** [comment]
It takes 1 minute test (it tests CPU, AMD and NVIDA in one test). 

I'm working on removing the firewall warning messages at the moment. 
Just click allow or add the firewall eceptions yourself.

**Comment by acaciosc** [comment]
Not to mention that I don't see the point in starting the very same algo in multiple instances at once. 

About the firewall thing, I'm not being spammed anymore after I allowed it, but the command prompts SPAMs were still happening, even after 1 minute. But now there is only one cmd.exe open... a blank one.

**Comment by aaronsace** [comment]
It's fine; it's just benchmarking. Don't worry.

**Comment by acaciosc** [comment]
Not to mention that I don't see the point in starting the very same algo in multiple instances at once. 

About the firewall thing, I'm not being spammed anymore after I allowed it, but the command prompts SPAMs were still happening, even after 1 minute. But now there is only one cmd.exe open...

I don't think you noticed (because you didn't comment about it), but there were "failed" messages.

![gaah](https://cloud.githubusercontent.com/assets/7469089/26429981/c21d64f4-40c0-11e7-9277-7b69b4f2e6c9.png)

It's happening again even after a couple of minutes! Didn't you say it would take only 1 minute to test everything? Will it test every single time that the start.bat is launched?!

**Comment by aaronsace** [comment]
1 minute per test. Read the MultiPoolMiner screen. Don't worry, it's benchmarking,

**Comment by acaciosc** [comment]
Where does it say that it will take 1 minute per test?!

**Comment by aaronsace** [comment]
I know it takes 1 minute because that's the delay that I set. 
Look at the MultiPoolMiner screen, it's benchmarking.

**Comment by acaciosc** [comment]
Where does it say that it will take 1 minute per test?!

Besides, you said earlier that "It takes 1 minute test (it tests CPU, AMD and NVIDA in one test)", which implies that it would take 1 minute to test everythink. Ah, and it has been passed more than 20 minutes, but it tested only cryptonight - and it is still mining cryptonight, probably for your pool, because it didn't start mining anything to mine (pun not intended).

I didn't mean that you don't know how long it takes, obviously. I meant that there is no such thing informing us regarding this matter.

**Comment by acaciosc** [comment]
You know what? I gave up your crap. It's not trustworthy, professional and functional, and you don't offer a good support, even though you get 1% in "donation" for using your software. I hope you haven't put any malware on my PC with it. I will stick with Nicehash for multi-algo mining, or use a proper miner for the coin I want to mine to.

**Comment by aaronsace** [comment]
It's a free script, you are very rude. I'm helping you at 1am.

**Comment by acaciosc** [comment]
It's not free. I have seen that you (or somebody else) get 1% for using it through "donation". I'm being rude because that's how you acted, and even closed this issue earlier, although I clearly hadn't my issue solved. And I don't know if you are "helping" me at 1 AM or 1 PM, because there is a thing called "world time zone", and it's different from place to place - I have no clue about where you are from; I, for example, am from Brazil. It's 21 PM here.

**Comment by aaronsace** [comment]
I understand man. I trying my best at life.

**Comment by acaciosc** [comment]
Trying your best to steal and lie?

**Comment by aaronsace** [comment]
I'm sorry, everyone can see the script is plain text. You can read it yourself.

**Comment by acaciosc** [comment]
How can 1% be considered "free"?

**Comment by acaciosc** [comment]
Huh? Do you "answer" a question with an off-topic one? I will ask one more time: how can 1% be considered "free"?

**Comment by aaronsace** [comment]
There is no 1% fee.

**Comment by aaronsace** [comment]
"Monitors crypto mining pools in real-time in order to find the most profitable for your machine. Controls any miner that is available via command line."

**Comment by aaronsace** [comment]
I'm going to look this thread as it is benchmarking correctly. Post a new issue if it fails to work. Thank you.

**Comment by aaronsace** [comment]
"To speak evil of no one, to avoid quarreling, to be gentle, and to show perfect courtesy toward all people. "
