### ISSUE TITLE
Nanashi ccminer 'does not validate on CPU'

### ISSUE THREAD

**Issue by SS2006** [aaronsace/MultiPoolMiner#119]
GPU #0: result for 0ec637f3 does not validate on CPU!

keep getting this error message, not sure its actually mining, the powershell shows 22 USD daily but i am not sure if thats just showing what it expects, because I dont feel the ccminer is doing anything with all those error messages, seeing no accepted shares. Any ideas?
Thanks

**Comment by aaronsace** [comment]
If there is a hashrate on MultiPoolMiner then there must be a live hashrate coming from a miner that is open. 

I not sure what that error means.

**Comment by aaronsace** [comment]
It's the active miners section on MultiPoolMiner that has the live hashrate.

**Comment by aaronsace** [comment]
That miner might need a lower intensity to work on older cards; it's just using the defaults at the moment.

**Comment by SS2006** [comment]
Using GTX 1080 btw. will try your suggestions. thanks

**Comment by lyolyalya** [comment]
does not validate on CPU - than an error.change the miner.i suggest you alexis ccminer.

**Comment by aaronsace** [comment]
Both tpruvot and nanashi ccminers work with lyra2re2 and are included.

**Comment by aaronsace** [comment]
@lyolyalya Have you got a link to the page that has the binaries for alexis ccminer? 
Also, what's better compared to tpruvot?

**Comment by lyolyalya** [comment]
yes.i have.using this - https://mega.nz/#!V85h3JSA!VxhPPXQqDy4NGXJIxxZpER-NsT1D-Hi-fg8-TJBs7fQ
also if you can compile the source it would be much more algos working - https://github.com/alexis78/ccminer/
