### ISSUE TITLE
sgminer auto benchmarking

### ISSUE THREAD

**Issue by Nightworker88** [aaronsace/MultiPoolMiner#12]
[2016-12-26_01-24-15.txt](https://github.com/aaronsace/MultiPoolMiner/files/673169/2016-12-26_01-24-15.txt)
[2016-12-25_05-13-11.txt](https://github.com/aaronsace/MultiPoolMiner/files/673170/2016-12-25_05-13-11.txt)

Hallo,

these are my two log files

First -to be able to use your batch to not allways have to write user name, i had to change policy group to "bypass"

(fresh win 64bit install)
{ Set-ExecutionPolicy -Scope Process Bypass }

just for info.

Problems: sgminer don´t benchmark all coins, just stop benchmarking when he wants!?

claymore equihash starts, i stop, he starts again, ok, quiet good, but no claymore ethash starting benchmarking

(on another rig, clamore ethash benchmarked sia 20, sia 40, but not sia 30

on another rig, like i said ms win64 all clones of one fresh install, claymore benchmarking all.

but one after teh other.)

sgminer: as you see in log, claymore equihash has so high benchmark, not possible to start the sgminer, of course , but cannot be right benchmarked, also i tried - changend sgminer I to high, about 20 then default 8.

some ideas? -

**Comment by aaronsace** [comment]
Don't seem to have experienced that before with the execution policy; tried it on 3 machines. Maybe I set it a while ago but forgotten... will look at adding the bypass option. 

All the coins have benchmarked on your machine. The calculations look correct; the other coins have very little profit on your machine. You can calculate it yourself; times the hash rate in (GH/s) by the pay rate (BTC/GH/Day). 

I'm worried about Ethash not being up there though as they may have benchmarked as zero. Check the stats folder; are the claymore ethash stats zero? Zip the stats folder up and upload if you want me to look.

**Comment by Nightworker88** [comment]
this is what i mean: it´s a r9 270x in testrig.

all "claymores" miners incl. gpu (and cpu) ,zce, eth, classic exp, sia.... work perfect and hash everytime cal.correct.

if i start sgminer, read out hash, write in v1,3 same issues for all coins - too little to switch miner compared to equihash and ethash.

**Comment by Nightworker88** [comment]
did not want close comment

**Comment by Nightworker88** [comment]
but also why sgminer do not finish benchmarking all coins and v2.0 do not start claymore ethash miner benchmarking? with hand never problem

**Comment by aaronsace** [comment]
All the coins have benchmarked as it no longer says benchmarking; look in the stats folder, you can see every benchmark. 

What are your manual hash rate readings? Which hash rates are incorrect? Remember to get the scale correct (G Hash, M Hash, K Hash, Hash).

**Comment by Nightworker88** [comment]
Thanks for replaying fast and your time.

next days i will  give me some more tries to maybe understand the different issues. 
(-also i took care for math (g,m,k,h -hash))


AND also i dont want take too much from your time cause i can not handle my things!


But i have one request:
 if you find something in script what should be changed, even it´s only some signs, please do it like minor updates to your version and don´t wait for one big major update, e.g. V2.0.0.1

Sure this can help us much!

**Comment by aaronsace** [comment]
Check the latest release: [https://github.com/aaronsace/MultiPoolMiner/releases](url)
