### ISSUE TITLE
Request to facilitate proxy usage

### ISSUE THREAD

**Issue by TheAlexP** [aaronsace/MultiPoolMiner#120]
While using a limited network, it's not very easy to mine while using a proxy. To solve this on my end, I added -Proxy [proxy] to every Invoke-WebRequest on every powershell script. I'm not sure if this applies to every internet connection, but it seems to help...

An example

$Currency | ForEach {$Rates | Add-Member $_ (Invoke-WebRequest "https://api.cryptonator.com/api/ticker/btc-$_" -UseBasicParsing | ConvertFrom-Json).ticker.price}

was replaced with

$Currency | ForEach {$Rates | Add-Member $_ (Invoke-WebRequest "https://api.cryptonator.com/api/ticker/btc-$_" -UseBasicParsing -Proxy http://192.0.0.1:8080 | ConvertFrom-Json).ticker.price}

Is there any way you can facilitate this by adding an optional parameter?

**Comment by aaronsace** [comment]
That should be fine, I'll add the option in. 

Do the miners themselves work? Is it just the web requests?

**Comment by TheAlexP** [comment]
I haven't done every benchmark on a limited network (since I did it prior to having this limitation) but I can confirm my top 3 miners all work within the limited network with no proxy whatsoever.

**Comment by aaronsace** [comment]
Awesome, thank you testing.

**Comment by aaronsace** [comment]
See above commit.

**Comment by TheAlexP** [comment]
Fixed with commit bc315929402c4a012361fddcd862d5720742c058
