### ISSUE TITLE
How to monitor the rigs working state？

### ISSUE THREAD

**Issue by czjlj** [aaronsace/MultiPoolMiner#121]
How to monitor the lots of rigs working state？

**Comment by aaronsace** [comment]
It doesn't support remote monitoring; it would be a useful feature but I'm not sure how yet. 
Remote Desktop is probably the best option at the moment.

**Comment by aaronsace** [comment]
Show your interest in monitoring the workers as a whole on the pool forum; MiningPoolHub is considering features like that: 
https://bitcointalk.org/index.php?topic=472510.new;topicseen#new
