### ISSUE TITLE
Log file attached "decimal errror slowing down my miner"

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#122]
D:\MultiPoolMiner\MultiPoolMinerV2.5\Logs
[2017-05-06_01-14-57.zip](https://github.com/aaronsace/MultiPoolMiner/files/1031117/2017-05-06_01-14-57.zip)

Hello, i dont think i have submitted this issue before, and know you asked for the log to see the error regarding the decimal error.

Thanks

**Comment by aaronsace** [comment]
There is no decimal error in that log. If you upgrade to the latest version, I did fix a decimal error problem.

**Comment by imrecsoka** [comment]
Hi, maybe it didnt echo to the log.
I used the latest version and started fresh with bench marking which takes forever and then let it mine for me but that RED text with a decimal error keeps occurring and while it displays this it is like it is doing something because my CPU miner goes down in hash speed.
Very strange

**Comment by aaronsace** [comment]
Issue not present in the upcoming release.

**Comment by imrecsoka** [comment]
Cool, lets see.
I wish i could understand the code to help.
Powershell looks so much more advanced than dos , cause im okay with Dos batch files and Pascal.
Thats as far as i get.
