### ISSUE TITLE
Hub Worker default name "multipoolminer", can it be changed ?

### ISSUE THREAD

**Issue by callmebambi** [aaronsace/MultiPoolMiner#123]
MPM V2.5.2 running on Windows 10 Pro x64.
MPM gives my Hub Worker the default name "multipoolminer", is there any way that I can change this to a name of my choice.

**Comment by aaronsace** [comment]
Yes, check the 'start.bat' example.

**Comment by callmebambi** [comment]
Ooops! my bad - there was no problem after all.
I had changed the start.bat file with my worker name, but I had not deleted the old 'multipoolminer' worker from Hub Workers list and thought MPM was still using this name.
