### ISSUE TITLE
erros on start

### ISSUE THREAD

**Issue by Fcases** [aaronsace/MultiPoolMiner#125]
PS>TerminatingError(Split-Path): "Cannot bind argument to parameter 'Path' because it is null."
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\clay\MultiPoolMiner-master\MultiPoolMiner.ps1:109 char:28
+             if((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.P ...
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : 
ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\clay\MultiPoolMiner-master\MultiPoolMiner.ps1:109 char:28
+             if((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.P ...
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand

**Comment by aaronsace** [comment]
You are missing files in the bin folder. 
Download the release build: https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by Fcases** [comment]
what script are you talking about ?

Just right click and run the script then enter your MiningPoolHub username once prompted; that’s it.

**Comment by aaronsace** [comment]
Sorry, I don't understand what you mean. 

Download the release build: https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by Fcases** [comment]
i did, it works with amd 280 but a nvidia 1080 i get a HARD CRAS?H on or aoround X11. , is it possible to not benchmark or mine anything apart from eth and equi ?

**Comment by aaronsace** [comment]
Yes, use the 'start.bat' file.

**Comment by Fcases** [comment]
omg you dont speak english ;)

i found how to disable coins... remove the .ps1 from miners and put elsewhere it wont benchmark them.

Hablas espanol ?  ou est-ce que tu parles francais ?

**Comment by aaronsace** [comment]
That's one way of doing it. :)
