### ISSUE TITLE
TPruvot ccminer params do not recognize more than 1 GPU

### ISSUE THREAD

**Issue by bhahn1800** [aaronsace/MultiPoolMiner#127]
When running some of the NVIDIA-TPruvot ccminer programs (with algos myr-gr, neoscript, and skein) it will only run 1 GPU and ignore the others even if they are showing up as a device in Device Manager.

**Comment by aaronsace** [comment]
Can you try the other versions of ccminer from within the 'bin' folder?

**Comment by bhahn1800** [comment]
sorry, I'm relatively new to the program... is there an easy way to disable specific miners inside MulitPoolMiner other than explicitly removing the algo?

**Comment by aaronsace** [comment]
Yes, check the 'start.bat' example.

**Comment by bhahn1800** [comment]
I'm just seeing where you can specify the algorithms you want to run not the specific miner folders: 
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,usd -donate 10"

**Comment by aaronsace** [comment]
Ah, you've got it then. 

`-algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia`

**Comment by bhahn1800** [comment]
ok, what seems to be the problem on my end is that when ccminer runs the first time, it utilizes all 6 GPUs.  But when I restart it (which MPM does as well), it will only use 1 GPU moving forward.  Any ideas or thoughts?  I'll go ahead and close this issue

**Comment by aaronsace** [comment]
Have you changed the voltage/clock settings on your GPUs?

**Comment by bhahn1800** [comment]
I have not... do you think I should increase them?  If so, what would you recommend? I'm running NVIDIA 1070s Armor

**Comment by aaronsace** [comment]
I recommend not messing with the settings but with 6 GPUs people can get all sorts of problems with power and the risers. 

Slightly undervolting would easy the power requirement and heat produced but generally you risk make your cards unstable by messing with the settings. 

Take TPruvot ccminer out for now and maybe seek support else where.

**Comment by bhahn1800** [comment]
ok thanks... I did try the prior version of TPruvot ccminer and it still had the same issue.

**Comment by bhahn1800** [comment]
is there a command-line arg to exclude specific miners or do I just need to specify all the ones I want to use?

**Comment by aaronsace** [comment]
Exclude would be useful but the is only include at the moment.
