### ISSUE TITLE
Mixed GPU multialgo

### ISSUE THREAD

**Issue by Ondalf** [aaronsace/MultiPoolMiner#128]
How about throwing an RX480, GTX 750Ti, 1070 and 1080 in the same machine? Makes head hurt and proper way coding it quite challenge. I can say, I got it working somehow, but its completely ugly hack using similar loop per device as Excavator[0-6] has. Simply make TPruvot etc. 0-6 and throw threading information in, change api port and device number. With nVidia, the numbers for devices are quite stable, unlike AMD. My 1080 has been set as #0 for a long time now. To tidy up the list and make it show somehow per-device, I also added Device = 'NVIDIA',$ThreadIndex etc. to show the devices separate in the list.

PS. Sorry for awful copypaste! Not sure how well this github plays with Notepad++ copies...
There is just an example (well, from my live settings, but anyhow...):

Gorgeously destroyed by github quality code -tag.
[Pastebin.com](https://pastebin.com/51SkBr26)

**Comment by Ondalf** [comment]
This could be one version of somehow working end-user-product...

![1080and750tis](https://cloud.githubusercontent.com/assets/7473344/26730377/6be6402e-47b9-11e7-8091-923c183caaf9.png)

**Comment by aaronsace** [comment]
If/when I get all the miners to work per device then formatting it like that would be quite useful. 

AMD miners only count AMD devices and NVIDIA miners only count NVIDIA devices. Miners that work on both AMD and NVIDIA count all the devices. All very confusing, I think I have the counting systems working together for now.
