### ISSUE TITLE
Using multipool function - algo values sums up

### ISSUE THREAD

**Issue by Ondalf** [aaronsace/MultiPoolMiner#129]
I'm using both zpool and miningpoolhub and seems atleast skein adds up from zpool API call and miningpoolhub. Both shows value of 0.0035xxx and yet it shows as 0.007x in the listing of BTC/GH/Day. So somehow they sum up while they are parsed. Dropping MPH and going back to zpool only for a while.

**Comment by Ondalf** [comment]
Hmm, right after dropping skein off, the price of that algo halved. Actually even more, so it has to be summed up while creating pools data. So pools aren't right now properly separated, but more like combined.

**Comment by aaronsace** [comment]
I haven't had chance to test zpool yet. I merged the pull request and sorted out the formatting. 
I'm away this weekend but the zpool API may need to use Minutes_5 instead of Live. 

I also want zpool to work as a backup even if set to miningpoolhub only.

**Comment by Ondalf** [comment]
Mind if I experiment a little and try to write something and make pull request based on it? I mean, if I have time. Got something to do as well. Thus having this as automatic as possible is a good thing. I got zpool as "my main" pool and I'd hope to either fix myr-gr for zpool algo list, OR add miningpoolhub as secondary option. For some reason I've ran into wall with that "-" in the algo name and that's why it doesn't get listed anywhere.

**Comment by aaronsace** [comment]
The new 'Get-Algorithm' function should remove the hyphens and ensure consistent naming. 

Hack away at it, welcome people submitting changes. 🙂

**Comment by snakethejake81** [comment]
For Myr-Gr you need to add the following in the CcminerKlaust.ps1 file, under $Algorithms:

MyrGr = 'myr-gr'

Then add MyrGr to your Algo list when launching, if you are specifying any specific ones.  I'll add a commit and pull request or aaron can just put it in when he has time.

**Comment by Ondalf** [comment]
Today I accidentally found that, but thanks! Now what I'm looking for, is how to implement a parameter, that defines max Cuda devices count. Also, somehow replace like ccMinerTpruvoT# with just single file. I'll look into it... 

zPool seemed to shut down bitcore, so that algo can be left out.

**Comment by snakethejake81** [comment]
Bitcore is back, looks like they were just doing maintenance on it or something.

**Comment by snakethejake81** [comment]
If you are looking to customize parameters for a miner and algo, you can specify them in the miner's .ps1 file under the $Optimizations section.  It will tack the parameters you specify, on the the end of the command line when it runs that miner/algo combination.

**Comment by Ondalf** [comment]
If you check my repo/branch, you might notice, what I mean. Per-GPU for mixed cards miner.

On the other hand, hmq1725 really requires defined difficulty. Also, I'd recommend changing zPool.ps1 password line to 'c=BTC,stats' since d=1 effectively destroys many things. Like zPool difficulty docs says, it is fixed diff. Yiimp github confirms this.

**Comment by Ondalf** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/128
That's, how I run it right now, except running only zPool, due this issue. Values summing up.

About hmq1725, 128 for 750Ti and 512 for 1080 from experience... And like suggested before, I'm running 5 minutes time window.

**Comment by snakethejake81** [comment]
The difficulty (d=1) is what I use on my rigs.  zpool does use a variable diff and you can set a fixed one like I have and the pool will adjust it if its too high or too low.  The only algo I have found that it doesn't work well on is lbry, but I don't mine that much.  I may add to the optimization to raise its diff.

http://zpool.ca/site/diff

This is on a 6x GPU GTX 1070 rig.

I wouldn't use or recommend a mixed GPU rig so I can't really comment on that.

**Comment by Ondalf** [comment]
We now see results of fixed diff d=1 in the zpool.ps1 by looking some posts at zpool forum thread in bitcointalk. [This](https://bitcointalk.org/index.php?topic=1751272.msg19421637#msg19421637) is perfect example of it. [This](https://github.com/tpruvot/yiimp/blob/next/stratum/client_difficulty.cpp#L49-L71) shows, what happens when fixed difficulty is set and why rigs are failing. Thus created pull request for removal of this madness.

**Comment by Ondalf** [comment]
Skein and Blake2s seems to be quite problematic algos, when hashrate is high. It could be best to trial and error the sweet spot of difficulty straight to miner $Optimizations. Values that I use for single 1080 for skein is d=1 and blake2s d=6. Remember, this is just for single card. You might have to rise it by times of GPU you have. So assuming you have 6x1070, I'd try with skein d=6 and blake2s d=36 or d=32. Somewhere around those. Try to get ~5-10 submits per minutes. That would be the optimum/sweet spot.

**Comment by nitrobg** [comment]
Interesting. How do you enable both zpool and MPH in the same MPM instance?

**Comment by Ondalf** [comment]
By leaving -pool off from start script. But there is a caveat. Like this thread shows, the values per algo sums up. It finds MPH Blake2s and zPool Blake2s, and does wizardry in form of MPH_value + zPool_value = Blake2s profitability, which skews quite hard the profit for algos. It somewhat knows, which pool for which algo is better, but adding values causes it to fail.

**Comment by Ondalf** [comment]
Also, the proper name for parameter to choose pool is just simple <code>-pool</code>
