### ISSUE TITLE
monero support?

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#13]
hey?are you planing monero support?
and if it's not so hard - what i need to add in v1.3 to mine monero?

**Comment by aaronsace** [comment]
Yes, will add try and add Claymore as the api will be the same.

**Comment by lyolyalya** [comment]
claymore...nvidia sucks again=)crack minergate miner anybody=)it gives 700 hs from 1070=)

**Comment by lyolyalya** [comment]
i'm have right understanding?just add this in 1.3 for mine monero?
$Miners += [PSCustomObject]@{
        Path = $ccminer_Path
        Arguments = "-a cryptonight -r 0 -o stratum+tcp://[Cryptonight.Host]:[Cryptonight.Port] -u [Cryptonight.User] -p x"
        HashRates = @{Cryptonight = 2070} #SET YOUR HASH RATE!
    }

**Comment by lyolyalya** [comment]
oops...just forked your miner by mistake...how to deleti it?=)

**Comment by aaronsace** [comment]
Check the latest release: [https://github.com/aaronsace/MultiPoolMiner/releases](url)

**Comment by lyolyalya** [comment]
i already added cryptonight in v1.3.with klaustT ccminer cryptonight and EWBF zec miner i guess...cryptonight don't start yet. with 2100 h\s is not so much profit but it listed at least.don't like v2=(to much files and confuse...sorry...can i change locations in v 1.3?or you don't support v1.3 fundamentally?

**Comment by aaronsace** [comment]
I'm trying to get the hash rate from EWBF. Please right click and run this test file? 
It should open EWBF miner and output a text file. 

[test2.zip](https://github.com/aaronsace/MultiPoolMiner/files/691815/test2.zip)

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/21747900/cd137d74-d57e-11e6-908e-1023b4eadab9.png)
not starting...

**Comment by lyolyalya** [comment]
update...starting but no miner window.few processes miner.exe instead
![image](https://cloud.githubusercontent.com/assets/16507768/21747934/938e04ce-d57f-11e6-8976-68372bc8bc0f.png)

**Comment by lyolyalya** [comment]
update2...seems like all starting cause gpu load also 83%.but no miner window.i changed argument line to
![image](https://cloud.githubusercontent.com/assets/16507768/21747991/4abfff16-d581-11e6-9657-0074f35706ac.png)
and then
[test.txt](https://github.com/aaronsace/MultiPoolMiner/files/691937/test.txt)

**Comment by lyolyalya** [comment]
update3.yep.your scrypt starts too,gpu load 83% but no test file records and powershell not closing by itself.

**Comment by aaronsace** [comment]
Ah, so the command line options I entered were freezing EWBF. That must of been why it wasn't working...

What does that cuda_devices option do?

**Comment by lyolyalya** [comment]
i don't know what it actually doing, i'm just writing it like in example.maybe something wrong with your test worker or so.i tried to add --cuda_devices 0 1 2 to your command line but it's not working anyway.
my command line also not shows ewbf miner window? but it completes the test and gives test.txt with closing powershell.maybe need to enter my miningpoolhub worker?
![image](https://cloud.githubusercontent.com/assets/16507768/21752062/acb28fd2-d5da-11e6-8ccb-821e12059227.png)
seems like you are right.if not specified - then it uses all devices available.sooo...you worker seems wrong or something...

**Comment by lyolyalya** [comment]
damn=)we are working hard,man=)
europe.equihash-hub.miningpoolhub.com not *hub.miningpoolhib.com*=)

**Comment by aaronsace** [comment]
europe.equihash-hub.miningpoolhub.com not hub.miningpoolhub.com? 
So was that what crashed it? Or was it the cuda_devices option?

**Comment by lyolyalya** [comment]
look at screenshot=)it says - without this option all devices are used=)
we are about connecting to the wrong adress=)

**Comment by aaronsace** [comment]
I'm getting confused. Please can you let me know the correct command line?

**Comment by lyolyalya** [comment]
testing=)few minutes.

**Comment by aaronsace** [comment]
Cheers. 

Really want to avoid having to enter the cuda device list.

**Comment by lyolyalya** [comment]
emmm...strange...
![image](https://cloud.githubusercontent.com/assets/16507768/21752369/571acab2-d5df-11e6-94b1-f32df2226776.png)
it connects...it mines...but not finish test...look at script maybe.
my command line now
![image](https://cloud.githubusercontent.com/assets/16507768/21752396/bd458c82-d5df-11e6-84d1-f18ad67d33ec.png)

**Comment by aaronsace** [comment]
So it just hangs at '0'? 
Even though the miner is mining?

**Comment by lyolyalya** [comment]
yep...but on coinmine it passed well...

**Comment by aaronsace** [comment]
This makes no sense... I have no idea how mining at a different pool could possible change the output...

**Comment by lyolyalya** [comment]
but it DOES!
with this
![image](https://cloud.githubusercontent.com/assets/16507768/21752444/a5750190-d5e0-11e6-8c44-180237c600ff.png)
it passed just right now.port maybe?

**Comment by lyolyalya** [comment]
[test.txt](https://github.com/aaronsace/MultiPoolMiner/files/692337/test.txt)

**Comment by aaronsace** [comment]
Wow, so that works. 

Try connecting to miningpoolhub again but try port 20570 instead.

**Comment by lyolyalya** [comment]
tried already.not working.

**Comment by aaronsace** [comment]
When you mine with miningpoolhub normally, have you noticed anything different on the screen compared to using coinmine?

**Comment by lyolyalya** [comment]
no...i use 
![image](https://cloud.githubusercontent.com/assets/16507768/21752486/a7846a24-d5e1-11e6-90bc-dab3e0c921e0.png)
in v1.3 without any problem.

**Comment by lyolyalya** [comment]
i tried 12023 port like it says in FAQ on miningpoolhub.
maybe it hepls
![image](https://cloud.githubusercontent.com/assets/16507768/21752573/931f464c-d5e3-11e6-8ed1-96205fe9d3ad.png)

**Comment by aaronsace** [comment]
Looks like the miner closed. 

Try test 3:

**Comment by lyolyalya** [comment]
-lt 120 =120 seconds?right?want to shorten test by now.

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/21752775/252e3ec8-d5e7-11e6-9841-c35105dd197d.png)

**Comment by lyolyalya** [comment]
crazy(you drive me) - awww...(c)Britney Spears=)
first - is it ebfw window must appear?

**Comment by lyolyalya** [comment]
then...-lt 10
test3 with your cmd line - nothing
test3 with --server zec.coinmine.pl --user lyolyalya.1 --pass 111 --port 7007 --cuda_devices 0 1 2 gives just
![image](https://cloud.githubusercontent.com/assets/16507768/21752930/3c866584-d5ea-11e6-9ccc-b30d279f5c3f.png)

so test3 seems not working at all

**Comment by lyolyalya** [comment]
ok...with test2  i have infinite mining in background with
![image](https://cloud.githubusercontent.com/assets/16507768/21752997/751ab926-d5eb-11e6-961f-3b565a4c64ef.png)
and with this settings i have this txt
![image](https://cloud.githubusercontent.com/assets/16507768/21753007/961db8da-d5eb-11e6-8d46-9ab8efc76f33.png)
[test.txt](https://github.com/aaronsace/MultiPoolMiner/files/692405/test.txt)
pool...

**Comment by aaronsace** [comment]
Please check what I've wrote here is correct:
https://bitcointalk.org/index.php?topic=1707546.msg17444916#msg17444916

**Comment by lyolyalya** [comment]
i will do screen capture withing next 12 hours i guess just to be clear.
