### ISSUE TITLE
Failure Enhancement

### ISSUE THREAD

**Issue by jakewarren81** [aaronsace/MultiPoolMiner#130]
I've ran into an issue where a particular algorithm on the pool has failed and isn't responding and therefore isn't showing any hashrate.  It would be nice if under this condition, say 5 minutes of zero hashrate from an algo, if the miner can simply switch to the next best available algo.  Then after an internal (30 minutes?), if that algo is still (or back on top), check it again by running the miner against it?

I'm not sure if the intervals would be best but the end goal is to detect an inactive miner and switch to the next one on the list and then periodically check back on that algo to see if it's back up; but only if its still more profitable.  This way, way keep mining no matter what happens on the pool.  

Maybe this could work with the "Failed" mechanism you already have, but allow it to be recehcked periodically and re-enable i automatically.

**Comment by aaronsace** [comment]
Agreed. It will come. 🙂
