### ISSUE TITLE
--gpu-platform 2

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#135]
I am running 7 XFX RX480 on windows then.

Out the box 2.5.2 does not work. I have to add --gpu-platform 2 to AMD-NiceHash sgminer and Gatelessgate.txt

**Comment by aaronsace** [comment]
If you don't specify a platform then it should use them all. Do you know what is causing the problem?

**Comment by aaronsace** [comment]
Maybe gpu-platform 0 is the default. Not quite sure how to solve that if this is the case because the platform numbers are just random.

**Comment by jjziets** [comment]
gpu-platform 0 is the default. That is the problem. I see Gatelessgate is for both Nvidia and AMD. But I have a dual systems and it does not run on all. have you tested this?

**Comment by fonyo** [comment]
According to sgminer's documentation it defaults to _none_. I have always had the gpu-platform parameter set to **2** when mining with sgminer (AMD HD, R9 and RX series). I think it should be included in the config. Not sure about Gatelessgate.

**Comment by aaronsace** [comment]
#210 

Please can you check this matches for order of gpu-platform on sgminer: 

`Get-WmiObject -class CIM_VideoController -namespace root/cimv2 | Select-Object -ExpandProperty AdapterCompatibility`

**Comment by aaronsace** [comment]
If this works, then I can mark a final release. 
This can then be then be used further in the next version for full device detection and mapping the miners to GPUs and CPUs. 

```
Get-WmiObject -class CIM_VideoController
Get-WmiObject -class Win32_Processor
```
