### ISSUE TITLE
Active Time skew

### ISSUE THREAD

**Issue by jakewarren81** [aaronsace/MultiPoolMiner#136]
There seems to be an issue when adding up the active time for each miner.  Sometimes it gets skewed like this and never corrects:

![image](https://cloud.githubusercontent.com/assets/12677849/26756648/51b9f526-485c-11e7-9ba0-d9c17165f3d9.png)

**Comment by merlinsbeard69** [comment]
I have the same error with same weird number of days.

![active time](https://cloud.githubusercontent.com/assets/29152869/26756725/3fb3d6a6-4877-11e7-85f3-352f271f1535.png)

**Comment by aaronsace** [comment]
It doesn't effect the functioning. I had it appear a couple of times before but wasn't quite sure what caused it. 

Will have to check through it but I may make changes to this anyway and allow it to launch miners on other machines (not just local).

**Comment by snakethejake81** [comment]
Yeah no effect, just nice to see how long each miner is running so you have a better idea of what algo its spending the most on.  Not crucial obviously.
