### ISSUE TITLE
benchmark not populating data

### ISSUE THREAD

**Issue by timhaire** [aaronsace/MultiPoolMiner#138]
I'm getting a number of miners/algos for CPU that open during bench, and work properly, yet the program reads them at 0.00 as if they were nonfunctional. Suggestions?

**Comment by timhaire** [comment]
It appears they stay 0 until finalizing, and disappear if they dont appear utile?

**Comment by timhaire** [comment]
Ok, I'm not entirely crazy. It isn't logging stats on benchmarks for CPU skein variants. Running 2.5.2. They work fine yet all get listed as 0 in the stats

**Comment by timhaire** [comment]
With the exception of vanilla noted in another issue, the rest of these are functional, but are not being read as functional. The stat logs have nonzero values, however upon finalizing it will drop them from the list of available miner-algo combos. 
Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a skein -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20527 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a scrypt -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20463 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a qubit -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20517 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a vanilla -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20533 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a skein -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20527 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\AMD-NiceHash\sgminer.exe --api-listen -k skeincoin -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20527 -u
                                               _.multipoolminer -p x --gpu-threads 2 --worksize 256 --intensity
                                               23
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a keccak -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20461 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-corei7.exe -a myr-gr -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20499 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a lyra2v2 -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20507 -u
                                               _.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a qubit -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20517 -u
                                               _.multipoolminer -p x


   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\CPU-TPruvot\cpuminer-gw64-avx2.exe -a vanilla -o
                                               stratum+tcp://us-east.hub.miningpoolhub.com:20533 -u
                                               _.multipoolminer -p x

**Comment by timhaire** [comment]
upon finalizing bench all skein cpu variants are logged in stats as 0s, although they were not.

**Comment by Ondalf** [comment]
Are stats folder files filled with zeroes as well?

**Comment by timhaire** [comment]
With few exceptions, yes. This is not something that happens with my gpu miner benchmarks, and many of the cpu benches still went through fine. I attempted to copy the stats from a properly logged one over under the same file name as a 0 value one in order to trigger the launch, but no luck. Unfortunately, some of these are the more profitable combinations for me.

**Comment by timhaire** [comment]
Type: CPU

Miner                   Algorithm            Speed      BTC/Day  BTC/GH/Day Pool
-----                   ---------            -----      -------  ---------- ----
FireiceCpu8             Cryptonight    285.79  H/s      0.00038 1,334.57857 MiningPoolHubCoins-Monero
CpuminerJayddeeAessse42 Cryptonight    260.00  H/s      0.00035 1,334.57857 MiningPoolHubCoins-Monero
FireiceCpu6             Cryptonight    252.90  H/s      0.00034 1,334.57857 MiningPoolHubCoins-Monero
CpuminerJayddeeAesavx   Cryptonight    250.00  H/s      0.00033 1,334.57857 MiningPoolHubCoins-Monero
CpuminerTpruvotCore2    Cryptonight    220.00  H/s      0.00029 1,334.57857 MiningPoolHubCoins-Monero
CpuminerTpruvotCore2    Yescrypt         3.10 KH/s      0.00029    93.60876 MiningPoolHubCoins-MyriadcoinYescrypt
FireiceCpu4             Cryptonight    207.10  H/s      0.00028 1,334.57857 MiningPoolHubCoins-Monero
CpuminerTpruvotCorei7   Cryptonight    200.00  H/s      0.00027 1,334.57857 MiningPoolHubCoins-Monero
CpuminerJayddeeSse42    Lyra2z         285.57 KH/s      0.00022     0.76985 MiningPoolHubCoins-Zcoin
CpuminerJayddeeSse2     Lyra2z         269.11 KH/s      0.00021     0.76985 MiningPoolHubCoins-Zcoin
CpuminerJayddeeAessse42 Lyra2z         256.92 KH/s      0.00020     0.76985 MiningPoolHubCoins-Zcoin
CpuminerJayddeeSse42    Cryptonight    140.00  H/s      0.00019 1,334.57857 MiningPoolHubCoins-Monero
CpuminerJayddeeSse2     Cryptonight    140.00  H/s      0.00019 1,334.57857 MiningPoolHubCoins-Monero
CpuminerJayddeeAesavx   Lyra2z         241.81 KH/s      0.00019     0.76985 MiningPoolHubCoins-Zcoin
FireiceCpu2             Cryptonight    105.00  H/s      0.00014 1,334.57857 MiningPoolHubCoins-Monero
NheqminerCpu6           Equihash        15.07  H/s      0.00007 4,654.75996 MiningPoolHubCoins-Zcash
NheqminerCpu4           Equihash        11.47  H/s      0.00005 4,654.75996 MiningPoolHubCoins-Zcash
CpuminerTpruvotCorei7   Groestl          1.03 MH/s      0.00004     0.04173 MiningPoolHubCoins-Groestlcoin
CpuminerTpruvotCore2    Groestl        814.19 KH/s      0.00003     0.04173 MiningPoolHubCoins-Groestlcoin
CpuminerTpruvotCore2    NeoScrypt       18.21 KH/s      0.00003     1.81337 MiningPoolHubCoins-Feathercoin
NheqminerCpu8           Equihash         6.80  H/s      0.00003 4,654.75996 MiningPoolHubCoins-Zcash
CpuminerTpruvotCore2    BlakeVanilla  Benchmarking Benchmarking     0.00000 MiningPoolHubCoins-Vcash
CpuminerTpruvotCorei7   X11           Benchmarking Benchmarking     0.00834 MiningPoolHubCoins-Crevacoin
CpuminerTpruvotCorei7   Skein         Benchmarking Benchmarking     0.00957 MiningPoolHubCoins-DigibyteSkein
CpuminerTpruvotCorei7   Yescrypt      Benchmarking Benchmarking    93.60876 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerTpruvotAvx2     Keccak        Benchmarking Benchmarking     0.00000 MiningPoolHubCoins-Maxcoin
CpuminerTpruvotAvx2     BlakeVanilla  Benchmarking Benchmarking     0.00000 MiningPoolHubCoins-Vcash
CpuminerTpruvotAvx2     Lyra2RE2      Benchmarking Benchmarking     0.05339 MiningPoolHubCoins-Vertcoin
CpuminerTpruvotAvx2     Yescrypt      Benchmarking Benchmarking    93.60876 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerTpruvotAvx2     X11           Benchmarking Benchmarking     0.00834 MiningPoolHubCoins-Crevacoin
CpuminerTpruvotCorei7   Scrypt        Benchmarking Benchmarking     0.04463 MiningPoolHubCoins-VergeScrypt
CpuminerTpruvotCore2    Skein         Benchmarking Benchmarking     0.00957 MiningPoolHubCoins-DigibyteSkein
CpuminerTpruvotCore2    Lyra2RE2      Benchmarking Benchmarking     0.05339 MiningPoolHubCoins-Vertcoin
CpuminerTpruvotCore2    Scrypt        Benchmarking Benchmarking     0.04463 MiningPoolHubCoins-VergeScrypt
CpuminerTpruvotCore2    MyriadGroestl Benchmarking Benchmarking     0.06654 MiningPoolHubCoins-DigibyteGroestl
CpuminerTpruvotCore2    Qubit         Benchmarking Benchmarking     0.02082 MiningPoolHubCoins-DigibyteQubit
CpuminerTpruvotCorei7   Qubit         Benchmarking Benchmarking     0.02082 MiningPoolHubCoins-DigibyteQubit
CpuminerTpruvotCorei7   Lyra2RE2      Benchmarking Benchmarking     0.05339 MiningPoolHubCoins-Vertcoin
CpuminerTpruvotCorei7   MyriadGroestl Benchmarking Benchmarking     0.06654 MiningPoolHubCoins-DigibyteGroestl
CpuminerTpruvotCore2    Keccak        Benchmarking Benchmarking     0.00000 MiningPoolHubCoins-Maxcoin
CpuminerTpruvotCorei7   Keccak        Benchmarking Benchmarking     0.00000 MiningPoolHubCoins-Maxcoin

vs post bench

Type: CPU

Miner                   Algorithm           Speed BTC/Day  BTC/GH/Day Pool
-----                   ---------           ----- -------  ---------- ----
FireiceCpu8             Cryptonight   286.44  H/s 0.00040 1,390.99091 MiningPoolHubCoins-Monero
CpuminerJayddeeAessse42 Cryptonight   260.00  H/s 0.00036 1,390.99091 MiningPoolHubCoins-Monero
FireiceCpu6             Cryptonight   252.90  H/s 0.00035 1,390.99091 MiningPoolHubCoins-Monero
CpuminerJayddeeAesavx   Cryptonight   250.00  H/s 0.00035 1,390.99091 MiningPoolHubCoins-Monero
CpuminerTpruvotCore2    Cryptonight   220.00  H/s 0.00031 1,390.99091 MiningPoolHubCoins-Monero
FireiceCpu4             Cryptonight   207.10  H/s 0.00029 1,390.99091 MiningPoolHubCoins-Monero
CpuminerTpruvotCorei7   Cryptonight   200.00  H/s 0.00028 1,390.99091 MiningPoolHubCoins-Monero
CpuminerTpruvotCorei7   Yescrypt        3.82 KH/s 0.00027    69.92433 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerTpruvotCore2    Yescrypt        3.10 KH/s 0.00022    69.92433 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerJayddeeSse42    Lyra2z        285.57 KH/s 0.00021     0.73370 MiningPoolHubCoins-Zcoin
CpuminerJayddeeSse2     Lyra2z        269.11 KH/s 0.00020     0.73370 MiningPoolHubCoins-Zcoin
CpuminerJayddeeSse42    Cryptonight   140.00  H/s 0.00019 1,390.99091 MiningPoolHubCoins-Monero
CpuminerJayddeeSse2     Cryptonight   140.00  H/s 0.00019 1,390.99091 MiningPoolHubCoins-Monero
CpuminerJayddeeAessse42 Lyra2z        256.92 KH/s 0.00019     0.73370 MiningPoolHubCoins-Zcoin
CpuminerJayddeeAesavx   Lyra2z        241.81 KH/s 0.00018     0.73370 MiningPoolHubCoins-Zcoin
FireiceCpu2             Cryptonight   105.00  H/s 0.00015 1,390.99091 MiningPoolHubCoins-Monero
CpuminerTpruvotCorei7   Skein          35.84 MH/s 0.00013     0.00350 MiningPoolHubCoins-DigibyteSkein
NheqminerCpu6           Equihash       15.07  H/s 0.00007 4,882.58596 MiningPoolHubCoins-Zclassic
CpuminerTpruvotCorei7   Groestl         1.03 MH/s 0.00007     0.06467 MiningPoolHubCoins-Groestlcoin
NheqminerCpu4           Equihash       11.47  H/s 0.00006 4,882.58596 MiningPoolHubCoins-Zclassic
CpuminerTpruvotCore2    Groestl       814.19 KH/s 0.00005     0.06467 MiningPoolHubCoins-Groestlcoin
CpuminerTpruvotCore2    MyriadGroestl   1.35 MH/s 0.00005     0.03807 MiningPoolHubCoins-MyriadcoinGroestl
CpuminerTpruvotCore2    NeoScrypt      18.21 KH/s 0.00005     2.81464 MiningPoolHubCoins-Feathercoin
NheqminerCpu8           Equihash        6.80  H/s 0.00003 4,882.58596 MiningPoolHubCoins-Zclassic
CpuminerTpruvotCorei7   MyriadGroestl 682.70 KH/s 0.00003     0.03807 MiningPoolHubCoins-MyriadcoinGroestl

**Comment by Ondalf** [comment]
What CPU you have there? Noted some missing values due that.

**Comment by timhaire** [comment]
AMD FX-8370. I've had success with most cpu miners/algos. I actually can't think of any exceptions.

**Comment by Ondalf** [comment]
Well, missing avx2 is explained by that. Not sure, why skein fails though. Perhaps too high network difficulty? I'll look it.

**Comment by timhaire** [comment]
Check out the other comment I posted yesterday. I was able to hook it manually, but not through MPM.

**Comment by timhaire** [comment]
Thanks for taking a look!

**Comment by Ondalf** [comment]
Ah, misaligned ports...

**Comment by timhaire** [comment]
I thought it wouldve been a separate issue as I would expect the port to have nothing to do with the benchmark logs propagating properly, but I haven't a clue where thats at or in what file.

**Comment by timhaire** [comment]
Hmm I just pulled more errors on another miner. xmr stak Cryptonight CPU8. Not my best few days mining. I have 2x8gb. Not sure whats up with this either or if its related or not. 

[2017-06-04 15:52:16] : MEMORY INIT ERROR: Obtaning SeLockMemoryPrivilege failed.
[2017-06-04 15:52:16] : MEMORY ALLOC FAILED: VirtualAlloc failed.
[2017-06-04 15:52:16] : MEMORY ALLOC FAILED: VirtualAlloc failed.
-------------------------------------------------------------------
XMR-Stak-CPU mining software, CPU Version.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 1.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-06-04 15:52:16] : Starting single thread, no affinity.
[2017-06-04 15:52:16] : MEMORY ALLOC FAILED: VirtualAlloc failed.

**Comment by timhaire** [comment]
To reiterate misaligned ports happened in some cases, but this thread was on the topic of miners that ran fine at benchmarking, but MPM appeared to have a disconnect as neither the logs nor the powershell window registered anything but zero for most, and lastly they fell off the list of miner/algo combos to choose from.

**Comment by Ondalf** [comment]
Not absolutely sure, but https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics does not provide information about port for vanilla algo. That could be one reason for it not to work. 
https://miningpoolhub.com/index.php?page=api&action=getminingandprofitsstatistics indeed shows information, but also shows zero for profits etc.

**Comment by Ondalf** [comment]
Also, raise Windows virtual memory size to 16, even 24gb by hand to ensure proper operation for various miners. That is separate to physical memory.

**Comment by Ondalf** [comment]
And about SeLockMemoryPrivilege:
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows

**Comment by aaronsace** [comment]
CPU miner only reports the speed on the API if a block was found otherwise it is zero. Are you find any blocks? If it is a slow CPU and/or the difficulty is too high then you may not find anything. Try increase the interval from 60 seconds to 180.

**Comment by aaronsace** [comment]
Lyra2z and Cryptonight are the most important.

**Comment by aaronsace** [comment]
Vcash (Vanillacoin) pool closed.

**Comment by timhaire** [comment]
Thanks. I've had my vmem set at 16gb, but will further increase to 20gb (capped). I also added the privilege, so thanks for that quick resolution for the off point hiccup. @Ondalf 

@aaronsace I definitely found blocks as I let it run over 10min each, and noted that at the time. Makes sense about Vcash, hadn't caught that (perhaps should pull it from the available options). I tend to get the best monetary rates through skein although those two are my second usually. Appreciate the response.

**Comment by fonyo** [comment]
There hasn't been an update for almost a month therefore I'm closing this issue. If the problem persists, please create a NEW thread.

**Comment by vitor900000** [comment]
![screenshot 38](https://user-images.githubusercontent.com/2219886/34319360-6e99e484-e7c7-11e7-8760-475b0558ec30.png)
![screenshot 39](https://user-images.githubusercontent.com/2219886/34319361-6eb7a62c-e7c7-11e7-8ce0-bc4a9817c834.png)
the problem still there....

**Comment by aaronsace** [comment]
It's not finding anything. It can only wait so long.
