### ISSUE TITLE
(Update miner) Claymore's Dual Ethereum AMD+NVIDIA GPU Miner v9.4 

### ISSUE THREAD

**Issue by Vasya93** [aaronsace/MultiPoolMiner#139]
Hello!
Could you update Claymore miner?

https://bitcointalk.org/index.php?topic=1433925.0

**Comment by snakethejake81** [comment]
You can always download and copy the latest version into the the proper folder under the /Bin directory; since new miner releases won't necessarily coincide with new multipoolminer releases.  This way you can stay up to date and test new miners without waiting for new releases here.

**Comment by aaronsace** [comment]
When I upload a new release I'll change it. As @snakethejake81 said, just swap the files in the 'bin' folder for now.

**Comment by aaronsace** [comment]
All the miners will be the latest versions in the next release.

**Comment by fonyo** [comment]
@aaronsace please hold on with updating to Claymore Dual v9.6 for a while. We are seeing a decrease in hash rate compared to earlier versions.
