### ISSUE TITLE
SSL - Claymore

### ISSUE THREAD

**Issue by pbuva** [aaronsace/MultiPoolMiner#14]
can be in next version?

[
    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Claymore\\Equihash\\ZecMiner64.exe",
        "Arguments":  "-zpool ssl://$($Pools.Equihash.Host):$($Pools.Equihash.Port) -zwal $($Pools.Equihash.User) -zpsw x",
        "HashRates":  {"Equihash":  "$($Stats.Claymore_Equihash_HashRate.Day)"},
        "API":  "Claymore"
    },
    {
        "Type":  ["AMD","NVIDIA"],
        "Path":  ".\\Bin\\Claymore\\Ethash\\EthDcrMiner64.exe",
        "Arguments":  "-epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw x -esm 3 -allpools 1",
        "HashRates":  {"Ethash":  "$($Stats.Claymore_Ethash_HashRate.Day)"},
        "API":  "Claymore"
    }
]

**Comment by aaronsace** [comment]
Will look into adding it; don't want it on by default so would need to add a switch. Also, all the miners may not be compatible.

**Comment by pbuva** [comment]
This is only for Claymore with Equihash, right?

"Path": ".\Bin\Claymore\Equihash\ZecMiner64.exe",
"Arguments": "-zpool ssl://$($Pools.Equihash.Host):$($Pools.Equihash.Port) -zwal $($Pools.Equihash.User) -zpsw x",

**Comment by aaronsace** [comment]
Yes.

**Comment by aaronsace** [comment]
Check the latest release: [https://github.com/aaronsace/MultiPoolMiner/releases](url)
