### ISSUE TITLE
First try, massive error sequence

### ISSUE THREAD

**Issue by FuurioBR** [aaronsace/MultiPoolMiner#141]
![capture](https://cloud.githubusercontent.com/assets/12569002/26794311/8e0462a4-49f7-11e7-8894-e36a0a7b0535.PNG)

I have an GTX 1080 and an i7-5960X.
What is this and what should I do?

**Comment by aaronsace** [comment]
Delete the fireice miners the 'bin' folder so that they download.

**Comment by FuurioBR** [comment]
![image](https://cloud.githubusercontent.com/assets/12569002/26798231/1f00d0a4-4a06-11e7-9a80-7ef911bb509a.png)

**Comment by FuurioBR** [comment]
![image](https://cloud.githubusercontent.com/assets/12569002/26798348/750d1084-4a06-11e7-847f-eb8711d5e8ab.png)

**Comment by FuurioBR** [comment]
![image](https://cloud.githubusercontent.com/assets/12569002/26798367/82a96684-4a06-11e7-90a5-c23eaa7aa4c3.png)

**Comment by aaronsace** [comment]
You are missing files in the 'bin' folder. I've just download the zip file to check it's all still working fine and it downloaded all the miners. 

Are you having problems with your internet connection? Do you have full access write to read and write files?

**Comment by aaronsace** [comment]
GitHub went down.

**Comment by FuurioBR** [comment]
Redownloaded, same errors...
It's on the desktop, I'm administrator, all files are in place, my internet have some issues but even stable it give errors.
It does download files, but with these errors showing for each round.
If not an issue with download manager (IDM) or PowerArchiver, then I'm missing some step of pre configuration.

![image](https://cloud.githubusercontent.com/assets/12569002/26799769/3e760bb4-4a0d-11e7-9a2f-e9b81db8c09d.png)

**Comment by FuurioBR** [comment]
What should I do? Let it download even with the errors showing up?
Did not found any information of how to set this up, one guy just showed it already working so I don't know how it supposed to look like or if he forgot an important step.

**Comment by aaronsace** [comment]
GitHub is back up.

**Comment by FuurioBR** [comment]
Now it's like this:
![image](https://cloud.githubusercontent.com/assets/12569002/26806506/a1fd2fd6-4a27-11e7-9d2c-c91a645a5673.png)

**Comment by FuurioBR** [comment]
Main folder like this:
![image](https://cloud.githubusercontent.com/assets/12569002/26806596/1002952a-4a28-11e7-9935-6da2960decfb.png)

**Comment by FuurioBR** [comment]
Bin like this:
![image](https://cloud.githubusercontent.com/assets/12569002/26806603/1bdce332-4a28-11e7-89c2-09fc231c4839.png)

**Comment by FuurioBR** [comment]
Maybe it's having issues to extract the files (?)

**Comment by fonyo** [comment]
I've never seen desktop icons that big! :) Are you still having these issues?

**Comment by FuurioBR** [comment]
Thanks, I like this way haha
Just hover the icons, hold CTRL and roll the scroll on the mouse, it's cool for displaying games and cool looking icons, with no need of third part apps :D

Reinstalled the whole Windows 10, problem persists, I don't think I'll still trying if no one can explain or give a solution :/
