### ISSUE TITLE
Current NeoScrypt setting crash some cards

### ISSUE THREAD

**Issue by aladar42** [aaronsace/MultiPoolMiner#142]
Hey, I have an AMD R9 290, running Catalyst 15.2 and current NeoScrypt optimizations (NeoScrypt = ' --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64') is crashing my card; first try will crash the drivers, second try locks up the PC and causes it to BSOD or outright restart. 

Changing settings manually to --intensity 11 solves the issue.

Of course it's easy to edit it manually, but maybe you should consider tweaking the default settings for users that don't know how?

**Comment by fonyo** [comment]
I tested this using 280x and RX480 cards and can confirm intensity 13 is too high and renders system unstable.
