### ISSUE TITLE
Sgminer skeincoin not loading

### ISSUE THREAD

**Issue by aladar42** [aaronsace/MultiPoolMiner#143]
For some reason, Sgminer's skencoin kernel decided not to load anymore. It worked fine up until now, after I'm redoign benchmarks (just cleared the stats, touched nothing else), it's only loading ckolivas.cl.

This is the command it's trying to execute:

> Bin\AMD-NiceHash\sgminer.exe
>                                                --api-listen -k skeincoin -o str
>                                                atum+tcp://hub.miningpoolhub.com
>                                                :17016 -u
>                                                Aladar42.multipoolminer -p x
>                                                --gpu-threads 2 --worksize 64
>                                                --intensity 11

**Comment by tomdmeredith** [comment]
I've had a similar issue with Reorder Skein and Ccminer Skein. They were being mined last night, then we I checked this morning they were no longer one the list. 

The only way I've been able to work around this is to start from scratch and load a new instance of MPM.

**Comment by Ondalf** [comment]
If they drop from list, stop the Powershell, remove that certain hashrate file from stats folder, start again. It benchmarks it again and continues, like nothing happened. Not sure, what causes dropping algo off completely, unless 2 failures to start it in a row.

**Comment by fonyo** [comment]
I'm closing this thread now. If you encounter this issue again, please create a NEW thread.
