### ISSUE TITLE
failover for skein net

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#144]
Hi. Please add safe-hub.miningpoolhub.com:17016 as a fail over in your next update.

**Comment by jjziets** [comment]
I suggest having the retry limited to 10 and then run the miner again but pointing to safe-hub.miningpoolhub.com:17016. You can make a loop like that with PS I am sure.

**Comment by fonyo** [comment]
Yes yes yes please I second this new feature

**Comment by jjziets** [comment]
miningpoolhub has confirmed that safe-hub.miningpoolhub.com also adds to once credit. 

my ps now point there as i get much fewer retries from it. But ccminer does not support failover. it does, however, support retry attempts. so if the strics for all ccminer can flip between hub and safe-hub to the tray and find working port it would really help when there is a ddos.

**Comment by jjziets** [comment]
how do i prevent mining to mph for skein?

![image](https://user-images.githubusercontent.com/19214485/31246699-8481a986-aa0e-11e7-832c-1b659d6a0362.png)

**Comment by aaronsace** [comment]
Use the 'start.bat' example.

**Comment by jjziets** [comment]
I want it to mine to zpool for skien.

**Comment by jjziets** [comment]
zpool.ca port 4933

**Comment by jjziets** [comment]
some rigs ccminersp works fine to mph for skien but on others not 

![image](https://user-images.githubusercontent.com/19214485/31247358-9bbfe714-aa10-11e7-871e-d57f4c8f9c1d.png)
 
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -username Etherion -workername wk3 -ssl -region europe -currency btc,usd -type cpu,nvidia -poolname zpool,miningpoolhub,miningpoolhubcoins,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sib,Lyra2RE2,MyriadGroestl,skein -donate 10"

**Comment by aaronsace** [comment]
Use the 'start-zpool.bat' example instead.

**Comment by jjziets** [comment]
where do i get that bat file? i can remote mining pool hub but that will remove other coins.

**Comment by jjziets** [comment]
o i see it

**Comment by aaronsace** [comment]
This one: 
https://github.com/aaronsace/MultiPoolMiner/blob/master/Start-Zpool.bat

You can add more algorithms.

**Comment by jjziets** [comment]
![image](https://user-images.githubusercontent.com/19214485/31248411-ec11496c-aa13-11e7-96b9-90dfc8671763.png)
clearly something wrong on this rig

**Comment by aaronsace** [comment]
Odd, if it is working on your other rigs then there must be something set wrong on that system.

**Comment by jjziets** [comment]
so i made a bat file and it works fine if i do that.

![image](https://user-images.githubusercontent.com/19214485/31248771-3bb5604c-aa15-11e7-9afa-a6450f0bfb3c.png)


ccminer.exe -a skein -o stratum+tcp://skein.mine.zpool.ca:4933 -u 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -p wk3,c=BTC -r 20

when i use 
ccminer.exe -a skein -o stratum+tcp://hub.miningpoolhub.com:17016 -u Etherion.wk3 -p x -r 20

![image](https://user-images.githubusercontent.com/19214485/31248877-9ec9c916-aa15-11e7-9845-86fd50f64d2f.png)

but with the shell/wrapper it is blocked?

**Comment by jjziets** [comment]
![image](https://user-images.githubusercontent.com/19214485/31248954-df71fad8-aa15-11e7-8f6e-097d53451f09.png)

**Comment by jjziets** [comment]
and now it works. after doing nothing. you really need a failover for this. 

![image](https://user-images.githubusercontent.com/19214485/31249326-32dff0ca-aa17-11e7-9b8d-2cdabc4c1375.png)

**Comment by aaronsace** [comment]
Very odd... So it works if you turn the firewall off?

**Comment by jjziets** [comment]
well not rig 3 works but rig 5 and 6 cant connect any more to mph/ skein.

you really need to flip between zpool and mph if both have the same coin. or be able to set a preferred pool

**Comment by aaronsace** [comment]
Yes but the root cause needs fixing on the rigs. Whatever I implement is going to be a last resort failover attempts.

**Comment by jjziets** [comment]
I have 6 rigs connected to one 8mbs ASDL router. As that rooter only have 1 public IP could that be why i can get 1 or 2 rigs not to connect to mph?

**Comment by jjziets** [comment]
my gut feel is that there is some issue with ccminer-sp mod and mph.

**Comment by jjziets** [comment]
ok so i have tested this for the last 20min. skein.mine.zpool.ca:4933 connects every time 
NVIDIA-SP/ccminer.exe -a skein -o stratum+tcp://skein.mine.zpool.ca:4933 -u 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -p wk3,c=BTC -r 20 

stratum+tcp://europe.hub.miningpoolhub.com:20527 
stratum+tcp://hub.miningpoolhub.com:17016
stratum+tcp://safe-hub.miningpoolhub.com:17016
could not get it to work in the 20m

testing NVIDIA-TPruvot and NVIDIA-KlausT passed all.

so i conclude that this is a ccminer-sp-mod problem with mph. pitty as spmod is so much faster

**Comment by aaronsace** [comment]
Best reporting it to sp and mph. 

Maybe something similar to this: 
https://github.com/KlausT/ccminer/issues/36

**Comment by jjziets** [comment]
👍
