### ISSUE TITLE
Sia not supported any longer?

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#145]
Hello Lee, when is your next release of MPM , looking forward to it.
Since i notice that Sia coin is no longer being auto-exchanged, is it possible that you next version or version thereafter can cater for this maybe, different exchange?
:-(

**Comment by Ondalf** [comment]
Requires Claymore miner. Only Claymore protocol is supported AFAIK.

**Comment by imrecsoka** [comment]
I dont follow?
Claymore is being called by this suite, so whats the issue?

**Comment by Ondalf** [comment]
https://siacoin.miningpoolhub.com
No idea, if it's not being exchanged. Where does it say so?

**Comment by imrecsoka** [comment]
Under auto exchange availability
Siacoin 	X 	X 	X    so as far as i know this means it is no longer exchanged for you.

**Comment by Ondalf** [comment]
Well, then it simply means, you have to do it yourself. Doesn't affect mining though. Requires bit more work on your side.

**Comment by imrecsoka** [comment]
Thus my initial comment/request.

**Comment by Ondalf** [comment]
https://bitcointalk.org/index.php?topic=472510.msg19396341#msg19396341
Seems network difficulty is through the roof compared to miners hash rate. Not sure, why exchanges are shut for Sia. Code in MPM has been same for Claymore, so basically this doesn't belong to MPM issues. I'd point at pool. There lies the problem.

**Comment by Ondalf** [comment]
Found this: What we are doing about Poloniex withdrawals.
https://www.reddit.com/r/siacoin/comments/6er35v/what_we_are_doing_about_poloniex_withdrawals/

**Comment by fonyo** [comment]
This issue happened at pool/exchange side, it had nothing to do with MPM and has been resolved since (Sia wallet is out of maintenance mode).
