### ISSUE TITLE
Profitability question

### ISSUE THREAD

**Issue by vatrak** [aaronsace/MultiPoolMiner#147]
Hello!

It might be a really stupid question, but I was just wondering why those 2 display a different value since MultiPoolMiner uses the 2nd miner to mine anyway?
Shouldn't they be the same?

![miners](https://user-images.githubusercontent.com/29268454/26911135-7022c40e-4bd9-11e7-99ee-71b06f147c62.png)

**Comment by Ondalf** [comment]
Upper one is damped average and lower is live value.

**Comment by vatrak** [comment]
Got it! Thanks!

**Comment by nitrobg** [comment]
> Upper one is damped average and lower is live value.

Average for 24h uninterrupted mining (best case scenario) or the average for my actual results?
