### ISSUE TITLE
Can't load phymem.sys

### ISSUE THREAD

**Issue by natv** [aaronsace/MultiPoolMiner#148]
Windows 10. It's complaining that it's an unsigned driver.

I tried this and rebooted:
bcdedit.exe /set nointegritychecks on

But I still get the same error.  Any known other workaround? 

Thanks

**Comment by Ondalf** [comment]
Hmm, where does this happen? With some miner software? If so, please head to certain miner software thread in bitcointalk.org. That will be your best bet. MPM is just Powershell script, which *should* work with Windows without any extra bells and whistles.

**Comment by natv** [comment]
Sorry this is actually part of excavator and not your code, I'm posting the issue on the excavator github as well, but if you happen to know the fix that would be awesome
