### ISSUE TITLE
The 'projected' income, is that real time, or theoretical if all cards were running. Can we specify which devices to include?

### ISSUE THREAD

**Issue by SS2006** [aaronsace/MultiPoolMiner#149]
Hi. At the bottom of the power shell, where it says 'Multipoolminer is 20% more profitable etc''
It shows my daily income (i assume its daily), in BTC, and USD, and any other currency i choose in the options. My question is though, is this assuming my nvidia, amd and CPu are all running? In my case I only have a GeForce GTX 1080 and a i7, and no AMD, it shows 0 ofcourse for the AMD miner, but it still launches and 'runs'. Does the power shell know this, that the AMD miner is contributing nothing, or are the numbers its showing as my daily income assume my AMD is running as well? Meaning the numbers shown are over exaggerated.  I have always wondered this.

That being said, can there be an option you can add, where the user can specify which hardware we do (CPU only, CPU+Nvidia, CPU+Nvidia+AMD etc) have, so it doesnt have to launch the amd miner, or try to benchmark it the very first time, for nothing

Thanks!

**Comment by Ondalf** [comment]
Start.bat has parameter called -type where you can set, which devices to use. It has amd,nvidia,cpu by default for show purposes. I suggest using only nvidia, unless your electricity is unmetered and you don't want to Finnish with own personal sauna next to you. It is enough, we (Finns) have those in our apartments. 

That estimation based on the momentary profit for miner combo is based on devices, that it was able to find and benchmark. Not imaginary ones. That "MPM is xyz profitable" just means, it shows damped average for whole week. So it's just mere indicator. Nothing else. 

Remember, MPH sends coins to exchange with quite long delay, so you can count -5% - -20% to estimation at worst for the assumption of the money you make. Of course, there are days, when price rises for coin-BTC pair. In the long run, that weekly average is quite handy and truthful.

**Comment by Ondalf** [comment]
Just another reminder, MPH requires some BTC to use manual cash out and some BTC for auto cash out. zPool pays these for you. Values I'm talking about are shown in MPOS wallet, where you can set autopayouts.

**Comment by SS2006** [comment]
thanks for the info. so those numbers it shows as profit, is that daily or weekly?

**Comment by SS2006** [comment]
also i dont use start.bat, i usually will open the multipoolminer.ps1 file, lets me see different currencies and stuff. I suppose I can't edit that file to specify which devices i want, ill try the start.bat

**Comment by Ondalf** [comment]
It should be daily, except when you run it like that. It combines and sums up both pools values with some wizardry. 
If you've used nicehashminer before, expect 2-3x daily profit. (This on nvidia)
For start.bat, just choose pool, leave algos unset for biggest variety. If you got it fully working, pass only -pool miningpoolhub via start. That way it should do. 
Also, for first "payday", expect long wait. Like day extra. Just to make sure coins have gone through via exchanges.
