### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#150]
Can we please have an updated release that includes all the changes and the new claymore ethash miner v9.5?

**Comment by dvwzj** [comment]
you can update miner for manually

**Comment by Ondalf** [comment]
Download miner from claymore repository and place it in place of the last one.

**Comment by fonyo** [comment]
> and all the changes 

Hence the request. The decimal and other errors are pretty annoying and there were some new features requested as well. I know how to update a miner.

**Comment by Ondalf** [comment]
Well, updating the release is the same. Download master as zip and copy over the old, except for start.bat.

**Comment by fonyo** [comment]
Yes, all true, I have other reasons for this request which I'd rather not say.

@aaronsace 
Can you please do the needful and create a new official release?

**Comment by ValenMX** [comment]
Release can be good, copy/pasting changes from current dev branch gives....some unexpected errors.

**Comment by chocoborider** [comment]
+1
