### ISSUE TITLE
Is it possible to choose how many GPU's we want to allocate to mining ? 

### ISSUE THREAD

**Issue by sypher9** [aaronsace/MultiPoolMiner#151]
I would like only 1 of the 2x 1080 Ti gpus allocated to mining in order to game with the other.

**Comment by Ondalf** [comment]
So far this is not doable.

**Comment by sypher9** [comment]
Thanks for the quick response!

**Comment by fonyo** [comment]
While directly not doable using the start.bat you can launch MPM then disable gpu0 in the miner program it launches prior to closing MPM. This way you can still quick-start mining and play a game but will obviously lose algorithm switching which is not a big deal as we are only talking about a single GPU. You can still earn a good chunk with your secondary gpu while gaming/not in use. Make sure to close MPM so it doesn't switch miner programs (which will lead you to mining on your first GPU enabled again).
