### ISSUE TITLE
Myriadcoin-groestl support

### ISSUE THREAD

**Issue by Leass** [aaronsace/MultiPoolMiner#152]
Hi, after relaunching app I figured out there is no longer that algo on list. That's kinda shame, because I mine my Digibytes with it. I have working for me command line for sg miner, is it a way to manually put myriad-groestl into app with my command line? Sometimes it's really worth switching for it, especially only half of my cards can dig ethash now :)

**Comment by dvwzj** [comment]
try "myriadgroestl" instead

**Comment by lee-aaron** [comment]
If it doesn't show when you run start.bat, then you might have to clear your stats folder. Otherwise, you can add this to the start.bat file: -algorithm myriadgroestl

**Comment by Leass** [comment]
Oh, I think that there should be some syntax guides, thanks guys!

**Comment by tomdmeredith** [comment]
I found that quite a few algorithms didn't run from the start.bat file (although they did run from the MutliPoolMiner.ps1 file).

I was able to get all of the algos to run by removing the -algorithm argument from the bat file. But, that also ran some algos with no associated pool.

**Comment by aaronsace** [comment]
@tomdmeredith I am working on that. Making tweaks to integrate zpool correctly.

**Comment by Leass** [comment]
@aaronsace you are making amazing job! For sake of not creating another issue - where can I find eth claymore parameters? I've tried to input some into start.bat or .conf in eth folder but it's not working. I need to adjust fan speed but and WattMan is so crappy it stop switching profiles after few round and drop to default for some reason :(

**Comment by aaronsace** [comment]
Thanks. Check 'claymore.txt' in the miners folder.
