### ISSUE TITLE
Transcript doesn't respect 12/24h at all

### ISSUE THREAD

**Issue by Ondalf** [aaronsace/MultiPoolMiner#153]
At clock 13.xx the transcript starts from 01-xyz. I'll submit patch to circle around this with more universal solution.

**Comment by aaronsace** [comment]
Have I just forgotten to set it to universal time?

**Comment by Ondalf** [comment]
Throw in
<code>
$TimeStamp = Get-Date -Format o | foreach {$_ -replace ":", "."}

Start-Transcript ".\Logs\$TimeStamp.txt"
</code>
since my github seems to require hard reset to avoid useless commits...

**Comment by Ondalf** [comment]
Finally! Submitted PR including that change. Had to redo whole repo for my account. This is what you get, when trying to learn many things at a time.

Anyhow, that is RFC'd timestamp format, so it should be "universal" and it ignores the computer localization settings.
