### ISSUE TITLE
Integrate Excavator API: $ActiveMiner.LogFile not updated on algo switch

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#1548]
as per title.

Scenario:
Excavator starts for the first time (e.g. with algo neoscrypt)
-> $ActiveMiner{neoscrypt }.LogFile get set OK 

After some time MPM switches Excavator algo  (e.g. to pascal)
->$ActiveMiner{pascal}.LogFile remains $null

Question: Should $ActiveMiner{neoscrypt}.Logfile get cleared?

**Comment by aaronsace** [comment]
@UselessGuru It should be $null because the current log encompasses all Excavator Active Miners. Where is the $ActiveMiner.LogFile currently being set?

**Comment by UselessGuru** [comment]
> Where is the $ActiveMiner.LogFile currently being set?

in the wrong place - I forgot to remove a line from tests for https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1439

> It should be $null

It is now $null for Excavator
But it breaks the functionality that grant required in the first place.
@Grant: Dou you still need it?

**Comment by aaronsace** [comment]
It will need a static variable instead if you want the service log location. 
static [String]$ServiceLogFile

**Comment by grant** [comment]
I don't need that.

**Comment by UselessGuru** [comment]
@Grant: I meant @grantemsley :-)

**Comment by grantemsley** [comment]
@UselessGuru If we want it to show the logs in the GUI, yes, I need the the /runningminers API call to return the path to the log file.

I can handle it being null, but then won't be able to automatically bring up the logs for it.  Which isn't that big a deal in this particular case, since the excavator window is shown anyways.
