### ISSUE TITLE
Is something wrong with timespan?

### ISSUE THREAD

**Issue by Leass** [aaronsace/MultiPoolMiner#156]
![image](https://user-images.githubusercontent.com/29311200/27010778-0df01c42-4ead-11e7-8d51-21094f7a1405.png)
Well, i don't want to be rude, but mining 10h per day for dev is ... :D 
Any way to fix it, those hundreds of days keeps me from calculating my income :D 
Thx ^^

**Comment by aaronsace** [comment]
It's a know bug, it's a display issue only. I will fix eventually. Not sure what causes it at the moment.
