### ISSUE TITLE
possible to map miners, algorithms or CPUs/GPUs for difference pools

### ISSUE THREAD

**Issue by dvwzj** [aaronsace/MultiPoolMiner#157]
personally I want to mine a gpu's miners on zpool and cpu's miners on miningpoolhub
or
I want to mine ethash's miners on miningpoolhub otherwise go zpool

how possible or it may future function for configs/settings

ps. sorry for my bad english

**Comment by aaronsace** [comment]
Not sure why you would want to do that but you could run two different copies of MultiPoolMiner. Set the second one as CPU only linked to just MiningPoolHub.
