### ISSUE TITLE
No ccminers starting?

### ISSUE THREAD

**Issue by Jaerin** [aaronsace/MultiPoolMiner#158]
Pulled the latest commits and tried firing it up with the following in the start.bat

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username jaerin -workername saturn -interval 60 -location us -ssl -type nvidia -algorithm skein,myr-gr,cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,usd -donate 10"

Miners are in the miners directory:
![image](https://user-images.githubusercontent.com/7770920/27020803-a500986c-4f09-11e7-81bd-0276b6fcc8a5.png)

But none of them seem to want to benchmark or show:
![image](https://user-images.githubusercontent.com/7770920/27020764-74f325b8-4f09-11e7-9fa0-58b105a1ad25.png)

No errors are shown for anything, they just never seem to get included even though I've selected nvidia.

**Comment by aaronsace** [comment]
I think that is related to the mistake I've made. Will be fixed in the next commit.

**Comment by Jaerin** [comment]
Know you've been out of town this weekend, any idea when that fix will come?  Just looking to try it on MPH, been running Ondalf's on zpool just fine.

**Comment by aaronsace** [comment]
Tonight.

**Comment by Jaerin** [comment]
Sounds good keep up the great work!
