### ISSUE TITLE
Proposal: Add ETH enhancing pill support

### ISSUE THREAD

**Issue by huyxm** [aaronsace/MultiPoolMiner#1597]
Recently, a doping application has been released to improve ETH hashing up to about 50% here, https://github.com/OhGodACompany/OhGodAnETHlargementPill
It is not a miner. It seems to work just like advertising but it has to be taken before mining. The problem is that it crashes my system when MPM switches algo (x16r and hmq1725 specifically). Algos like equihash and lyra2v2 seem to work just fine with the pill in the background. Maybe the team can somehow develop a way to call and quit the enhancer only when an ETH miner is switched on/off?

**Comment by thinkplaystudios** [comment]
It has no mention of how it works.  Anyone else in the community running this?  There's no source access, no idea if this is legitimate or intended with maligned activity.

**Comment by slovke** [comment]
it works i use it for few days 50 to 54 depend on Ti model on ETH Algos

**Comment by slovke** [comment]
![untitled](https://user-images.githubusercontent.com/21175543/39366144-646b71c0-4a33-11e8-8db1-631524f4aa77.png)

**Comment by slovke** [comment]
![image](https://user-images.githubusercontent.com/21175543/39366186-7f81df62-4a33-11e8-9572-bc46dce0f264.png)
