### ISSUE TITLE
when using zcash h/s 

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#16]
in your benchmarking 1000H/s = 0.00001 

you need to add a few more 0's 

so that 580H/s is not 0.00001 or 0.000000
not sure if you are rounding up or not.

**Comment by aaronsace** [comment]
Will look into a more adaptable display of the figures.

**Comment by aaronsace** [comment]
Check the latest release: [https://github.com/aaronsace/MultiPoolMiner/releases](url)
