### ISSUE TITLE
claymore dual

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#160]
the claymore dual miner calculates wrong btc/day (switches hashspeed in calculation) 
other algo combo's show correct

*the decred algo calculates wrong, that algo-combo switches hashpower for the calculation of proffits

**Comment by aladar42** [comment]
Can confirm, Claymore's hashrate always takes about 2 minutes to settle to actual values (first minute mines up to 2Mh/s faster), a fix would probably be letting Claymore benchmark for 3 minutes or so to get more accurate results.

**Comment by aaronsace** [comment]
It measures variance in the readings until they are steady; I think it's benchmarking fine. I don't think Zpool is release ready yet. I'm working on it.

**Comment by scaras** [comment]
take a look at the log file and you'll understand what i mean ;)

[2017-06-13_19-43-04.txt](https://github.com/aaronsace/MultiPoolMiner/files/1072358/2017-06-13_19-43-04.txt)

**Comment by aaronsace** [comment]
Looks like it's the wrong way around. I'll definitely fix before release.

**Comment by scaras** [comment]
looks to me this is happening cuz the script assigns the miner $... in alphabetical order but not the btc/day.
this error is only in the calculation, the fact that the script pots it in alphabetical order on the screen is not the big issue here.
