### ISSUE TITLE
Update benchmarks from live mining?

### ISSUE THREAD

**Issue by Jaerin** [aaronsace/MultiPoolMiner#161]
I don't believe the script does this yet, but is it possible for it to update the benchmarks based on the hashrates you're getting from actual mining.  I'm sure if I benchmarked for 5 mins or something for each algo it likely would have more accurate results.  Might be a nice feature though if it sensed that it has been mining with an algo for >5 mins it updates the benchmark with the current hashrate.

**Comment by aaronsace** [comment]
It takes a week average of the hash rate so there is no need to worry about miner discrepancies in the initial benchmark.

**Comment by scaras** [comment]
if you set the time out at 300 seconds you also have a better benchmark. (maybe an option for a switch and scrollable windows for type (amd/nvidia/cpu/amd-nvidia) individual (with on/off switch)

**Comment by aaronsace** [comment]
It's in the command options; set to 60 by default. It will adjust whist running anyway so I don't recommend increasing.

**Comment by scaras** [comment]
i only set it higher for a 1ste benchmark, after that i set it somewhere between 30 and 60
