### ISSUE TITLE
Mining estimates seem to be double

### ISSUE THREAD

**Issue by appliedi** [aaronsace/MultiPoolMiner#162]
When running MPM I see a daily profit for say ccminer as $18.42 but if I go to whattomine and put in that particular algo and currency I tend to get $9.21 and if I take the btc estimates for that currency I get $9.21.  Maybe this is unique to me but I thought I'd report it just in case.

**Comment by aaronsace** [comment]
Multiply the hash rate by the btc/gh to check it. There maybe something wrong with your stats. Delete the profit stat in the 'stats' folder will reset it.

**Comment by fonyo** [comment]
Also, don't forget, if are dual-mining ETH-SC and SC's profitability and price is high (closer to the dcri 30 range and above) you cannot compare it to whattomine results as fredeq's site does not account for dual mining.

**Comment by fonyo** [comment]
I am closing this issue. Post here if you are still having trouble.
