### ISSUE TITLE
sgminer with skein algorithm (and more)

### ISSUE THREAD

**Issue by dvwzj** [aaronsace/MultiPoolMiner#163]
When I start mine with -type cpu,amd,nvidia -algorithm skein
cpuminer and ccminer working fine but sgminer are not start

I think $Commands variable in sgminer miner is not recognized "skein" but "skeincoin"
If I change -algorithm to "skeincoin"
the cpuminer+ccminer  will not recognized "skeincoin" too

and I think "myriadgroestl" is same issue (for sgminer, "myr-gr" should be "myriad-groestl")
But "myriadgroestl" it work fine with ccminer and cpuminer

and maybe some algorithms like qubit, lyra2v2 and groestl is the same issue too

ps. sorry for my bad english

**Comment by aaronsace** [comment]
Fix coming soon. Just need to add them to the list.

**Comment by aaronsace** [comment]
Done.
