### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by siimsuu** [aaronsace/MultiPoolMiner#164]
I get errors like that when i launch start.bat file first time. I changed username ja miner name. I'm not running start.bat file as administrator. Firewall is off. 

PS>TerminatingError(Split-Path): "Cannot bind argument to parameter 'Path' because it is null."
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\i5 K\Downloads\MultiPoolMiner-master\MultiPoolMiner-master\MultiPoolMiner.ps1:114 char:28
+             if((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.P ...
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Smiley [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathComm

**Comment by aaronsace** [comment]
Get the bin files from the release.

**Comment by siimsuu** [comment]
Can you be more specific?

**Comment by aaronsace** [comment]
This is the page: https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by aaronsace** [comment]
The unreleased version still needs finishing and testing.

**Comment by zonenord** [comment]
hello
i m getting the same error

**Comment by zonenord** [comment]
using v252

**Comment by aaronsace** [comment]
This is the page: https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by fonyo** [comment]
@zonenord can you post your error message please?

**Comment by zonenord** [comment]
![screenshot_6](https://user-images.githubusercontent.com/29761917/27699003-843db88e-5d01-11e7-97fc-bc456f8cc48f.png)

**Comment by aaronsace** [comment]
I'm quite sure you are missing files from the bin folder. Either your virus checker removed them or you downloaded the code instead of the release. 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.5.2/MultiPoolMinerV2.5.2.zip

**Comment by zonenord** [comment]
yeah, it seems that windows defender removes some files

**Comment by zonenord** [comment]
![screenshot_8](https://user-images.githubusercontent.com/29761917/27701764-9a5541d8-5d0a-11e7-973c-2cdf7d671531.png)

**Comment by aaronsace** [comment]
@zonenord Tell it not to remove the files. Add the whole folder to the virus exceptions list.

**Comment by fonyo** [comment]
Who knows? Source code is closed, it could actually be a trojan ;) (BTW, I am joking but the possibility is still there).

Many of the miners apps are detected as false positive as sometimes they are recompiled/rebundled with malicious code eg. to create botnets etc. 

Then their signature is recorded in antivirus software's database and then detected as false positive later on.

**Comment by fonyo** [comment]
I am reopening this as a reminder to include information in the FAQ. I hope that's OK.

**Comment by somidax** [comment]
Can anyone advice why MPM not working with Windows 8 ? As I just
updated.  Also the AMD version for lyra2z not working asking for API
missing files.

As for Windows, can you advise best practice  as older mining cards not
working with its claymore monero for it requires activating the "a 3" which
I can locate on d miners folders of MPM.

Awaiting your feedback and happy new months to you all. Keep up d great
work.
