### ISSUE TITLE
miners reset automaticly.

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#165]
why are the miners resetting every ±10 min?
even with only one or 2 algo and a big price difference they stop and start again. (claymore dual has a big loss cuz of loading the DAG...)

**Comment by aaronsace** [comment]
Are you using Zpool? 
Zpool is not ready yet.

**Comment by scaras** [comment]
no, it is mining to miningpoolhub with claymore dual and amd gpu.  with the nvidia gpu sometimes a good paying algo to zpool with one algo but not with claymore.

**Comment by aaronsace** [comment]
I've one change to make for Zpool to work correctly then I'll be running a lot of testing to try and iron out the issues. Hopefully I can then post a working release and move on to implementing some suggested improvements.

**Comment by fonyo** [comment]
I have noticed lately Claymore v9.3 is resetting the DAG quite frequently without restarting. I am not sure whether it does it because there are some issues or because MPM is sending work for a different ethash coin. Any ideas why?

**Comment by lee-aaron** [comment]
I notice for me that the pool changes for the Ethash algo. Sometimes it's ETC or ETH and rarely Musicoin. But I haven't really paid attention to whether or not the DAG resets. I also use the non-updated version of Claymore that's in this repo (9.3/9.4?). Well I know that the pool changes because of profitability in mining in terms of shares and difficulty. Not sure what else I can say.

**Comment by scaras** [comment]
after some observation, claymore change the pools between the following combinations: 
       -epool europe.ethash-hub.miningpoolhub.com:20535 -dpool hub.miningpoolhub.com:17022 
       -epool europe.ethash-hub.miningpoolhub.com:20535 -dpool europe.hub.miningpoolhub.com:20550
       -epool europe.ethash-hub.miningpoolhub.com:17020 -dpool europe.hub.miningpoolhub.com:20550
       -epool europe.ethash-hub.miningpoolhub.com:17020 -dpool hub.miningpoolhub.com:17022

**Comment by scaras** [comment]
changed line 20 from miningpoolhubcoins.ps1 to
 `$MiningPoolHub_Port = $_.direct_mining_algo_port`
now it will stay at the 17xxx ports (less coding shit with the $workername shit i think)

**Comment by aaronsace** [comment]
@scaras It already does this in the 'start.bat' example: 
`-poolname miningpoolhub`

**Comment by scaras** [comment]
i don't use the .bat file. (have some other small adjustments for algos that are not on multipoolhub)
i just noticed that you assign different in miningpoolhub.ps1 and miningpoolhubcoins.ps1
with this adjustment they use the same ports

**Comment by aaronsace** [comment]
You don't need 'miningpoolhubcoins.ps1', just get rid of it.

**Comment by scaras** [comment]
are there more files that are just taking space on my HD that are not used? this way i know faster where to look for errors and where not to
