### ISSUE TITLE
Few issues, mostly related with benchmarking

### ISSUE THREAD

**Issue by ValenMX** [aaronsace/MultiPoolMiner#166]
Sorry if Im asking stupid things, im pretty new to your script.
Running 2 NVIDIA rigs on Win10. Script stricted to NVIDIA (cpu benchmarks is separate issue, dont want to discuss it here).

```
Built with VC++ 2013 and nVidia CUDA SDK 8.0 64-bits

Originally based on Christian Buchner and Christian H. project
Include some algos from alexis78, djm34, sp, tsiv and klausT.

[2017-06-14 15:40:10] Starting on stratum+tcp://:
[2017-06-14 15:40:10] NVML GPU monitoring enabled.
[2017-06-14 15:40:10] NVAPI GPU monitoring enabled.
[2017-06-14 15:40:10] 2 miner threads started, using 'blakecoin' algorithm.
[2017-06-14 15:40:13] Stratum connection failed: Failed to connect to  port 80: Connection refused
[2017-06-14 15:40:13] ...retry after 30 seconds
```
So far tprucot cminer-x64 benchmark getting no pool address?
Take a look here:

```
0.00 PH/s 00 Days 00 Hours 02 Minutes 2 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a x17 -o stratum+tcp://: -u  -p
0.00 PH/s 00 Days 00 Hours 07 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a x11evo -o stratum+tcp://: -u  -p
0.00 PH/s 00 Days 00 Hours 03 Minutes 2 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a sib -o stratum+tcp://: -u  -p
0.00 PH/s 00 Days 00 Hours 06 Minutes 2 Times  Bin\NVIDIA-TPruvot\ccminer-x64.exe -a blakecoin -o stratum+tcp://: -u
                                               -p
0.00 PH/s 00 Days 00 Hours 06 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a timetravel -o stratum+tcp://: -u
                                               -p
```
All benchmarks running against no pool address.
Another thing with tpruvot ccminer agains sia, script gets pool address, but pool answering about wrong id, extranonce, dont remember full text.

Now to excavator part.

```
Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p 53456 -c decred5.json
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p 13456 -c decred1.json
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p 23456 -c decred2.json
```
Every excavator benchmark failing, no matter what json going in. It's just not starting. Looks like something with exe itself or access rights.

All bins is default, no manual replacement.
Summary:
Quite a lot of benchmark failing, 3 biggest issues is: no-no start for excavator, empty pool addresses for "new" algos, and errors from pool. If you can direct me to right place in logs or stats to collect more info, Im glad to provide it.

**Comment by dvwzj** [comment]
it look like you mine coins that's not available on MiningPoolHub

**Comment by ValenMX** [comment]
nah, i used latest script changes from master branch MPM. It looks like empty pool addresses related with new algo fix by aaron. Once again, I not changed anything in MPM. Took release version. Updated with latest changes. Run. Sure I did test with no new commits first, problems with excavator and wrong id answer from pool still there.

**Comment by dvwzj** [comment]
I'm not sure. but I try to help as I can.

Can you show your start.bat ?

And I have some questions:
You want to mine on MPH only ?
What coins or algorithms you want to mine ?

As I understand, sia on MPH with ccminer still stuck

ps. sorry for my bad english

**Comment by ValenMX** [comment]
```
setx .......
powershell -version 5.0 -noexit -executionpolicy bypass 
-windowstyle maximized -command "&.\MultiPoolMiner.ps1 
-username xxxx -workername xxxx 
-interval 60 -location europe 
-ssl -type nvidia 
-poolname miningpoolhub 
-currency btc,eur -donate 10

```
No list of algos, just use all.

Yes, atm I plan to do MPH only. Looking into MC for more pools, but need time to learn all the tricks.

I want to use MPH for auto switch, so I dont care what algos mining atm, any with best profit. At least any my set of NVIDIAs can handle.

I dont care much that some algos not yet supported, its clear and I understand it.
What makes me nervous, some miners + algo combo already scripted in MPM, not benchmarking correctly on my rigs. That was my issue post about. Most worries about excavactor wont run any benchmark on my rigs. As a result Im gettin feeling that my MPM running not most profitable miners/algos. Just going thru stats and see half of it zero, means not benchmarked.

**Comment by aaronsace** [comment]
It's most likely the new algos that are on Zpool only. I've not finished this yet, you are best limiting which algorithms to use in the command line for now.

**Comment by ValenMX** [comment]
Ok, what about excavator not benchmarking on any algo?
As I understand Im getting this message on my test machine
```
MultiPoolMiner is 12% more profitable:
Miner          btc     eur
-----          ---     ---
MultiPoolMiner 0.00588 13.76176
EWBF0-Equihash 0.00526 12.32312
```

because EWBF0-Equihash running on my side, less profitable than calculated profit with best algo+miner? Funny that I do run MPM and getting this message. That makes me thing best combo is not becnchmarked on my side and not in use.

**Comment by snakethejake81** [comment]
If you want to run NVIDIA against zpool, delete (or move) all miner ps1 files other than the ccminer files a EWBF.  It works much better this way as I've found the FireIce especially, to be very unstable.

**Comment by ValenMX** [comment]
Thanx for answer, but  seems my English is not good enough to explain problem. I never said Im interested in zpool. I was just hoping all miners and algos that is included in MPM by default, can start and do benchmarking(yes, im talking about excavator). It's really important, because I found that ccminer-klaust(my mpm running it most) hangs up randomly, sometimes it works ok, woke up today and found it was silently do nothing after "starting 7 threads" for at least half of night. With no software watchdog on cards load, it can happen any time ( after that I replaced exe with latest 8.08 and in few hours problem raised again). So I have exclude it too. That leads me to very few combos left as choice for auto switch.

**Comment by snakethejake81** [comment]
Even for MPH, I would still remove all but ccminer, ewbf and claymore (since mph has ethash).

If Klaust is the only one crashing, remove it for now and see if the rest run for now.  If you still have issues with the miners crashing then that is outside of what multipoolminer can handle.

You would have to stabilize you rig with the miners you want to use before having mpm control them.

Generally I start with a clean load of windows 10, and install just the system drivers, nvidia drivers and mpm.  I have two six gpu nvidia rigs running 24/7 for months with these scripts and miners.

**Comment by ValenMX** [comment]
My env. is same, clean win10 1703 with nvidia drivers + afterburner. 
You right, I have to do tests one by one, miners problem not belong to switch script scope. Good I already found that KlausT can freeze after start randomly.

**Comment by Jaerin** [comment]
In your miners folder there is a file for each algo named excavator#.ps1, CcminerTpruvot#.ps1, ect.  The # is the device number of the GPU it will try to launch.  By default there are 0-4 so if you only have 2 GPU's you'll want to delete all the files ending in 2-4 because you don't have devices with those numbers.

**Comment by fonyo** [comment]
Closing issue. If you have further questions related to OP, please post them here.
