### ISSUE TITLE
Benchmarking not completing

### ISSUE THREAD

**Issue by SS2006** [aaronsace/MultiPoolMiner#167]
Been 12 hours, i feel its this error message:

"cannot find excacator.exe'

**Comment by Mikhail5555** [comment]
Please download 
You may need 'excavator.exe' if you don't already have it:
https://github.com/nicehash/excavator/releases

And place4 it in /Bin/Excavator/

**Comment by aaronsace** [comment]
@SS2006 BTW, it's quicker limiting which algorithms you use with the 'start.bat' example.

**Comment by SS2006** [comment]
thats true but if i remove equihash, then i lose that entire mining ability correct, ewbf miner works still, its just the excavator that wasnt
