### ISSUE TITLE
 Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.

### ISSUE THREAD

**Issue by digitaldemon** [aaronsace/MultiPoolMiner#168]
This error keep popping up during the benchmark test. Can you please help me solve this issue ?

**Comment by digitaldemon** [comment]
I am using 4 x rx580 . they are recognized in device manager as well

**Comment by aaronsace** [comment]
Hi @digitaldemon, you will need to provide more information as I've never heard of that error before.

**Comment by lee-aaron** [comment]
It has to do with drivers. Not attached to the MPM at all. I only have NVIDIA cards but I have seen that issue once. I resolved it by searching for some drivers (don't remember which ones).

**Comment by aaronsace** [comment]
Ah, you can ignore it or remove and from the command line. Check the 'start.bat' example.

**Comment by fonyo** [comment]
Closing issue. Please post here if you have further questions.
