### ISSUE TITLE
Algo disappearing completely

### ISSUE THREAD

**Issue by Leass** [aaronsace/MultiPoolMiner#169]
Hi, 
Again having problems with myriadcoin-groestl algo and yescrypt. Today after computer took its rest I've started MPM and noticed that those two algos went missing again. So I cleared my hashrate files in stat folder and restart MPM. 
Then make clear version ...
Still nothing :x 
Any chance to got this working? : )

**Comment by aaronsace** [comment]
Sorry, trying to find time. I think I've fixed that, I'll push it now.
