### ISSUE TITLE
Active time showing very large numbers occasionally

### ISSUE THREAD

**Issue by Jaerin** [aaronsace/MultiPoolMiner#176]
Not sure if its getting some erroneous value from the process closing or what, but I've noticed the active will be very large sometimes.

As you can see below it's not just one of the miners either as it happened on both Alexis and EWBF

![Image of issue](https://i.imgur.com/U3Y0x7i.png)

**Comment by aaronsace** [comment]
The display issue is know; on my to-do.

**Comment by fonyo** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/136

**Comment by Jaerin** [comment]
As far as I can tell this seems to have been resolved.  Haven't seen it pop up in the latest commits.
