### ISSUE TITLE
Driver Crash Windows 10

### ISSUE THREAD

**Issue by brunowasb** [aaronsace/MultiPoolMiner#177]
Hello there community and devs,

I have downloaded the Miner and ran the Powershell. All miners were downloaded and the Benchmarks have began.
The problem is, that somewhen the application tries to benchmark XMR-stak-Nvidia and windows start to popup windows with GraphiCards Driver crash error and ask for a reboot.

Is there a way to edit the Application to only benchmark for Nvidia and ignore CPU, AMD and also ignore the XMR-stak?

Thank you in advance. Great job you are doing here.

Windows 10 as uptodate as possible.
GTX 970 / 2*GTX 1060 / GTX 1070 / GTX 1080 / GTX 1080 TI
Asus Z270-P

**Comment by fonyo** [comment]
You need to edit the start.bat file to achieve that.

`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,usd -donate 10"`

After -type you should only have nvidia
`-type nvidia`

You could remove specifically Monero by removing cryptonight after -algorithm 
`-algorithm ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia`
