### ISSUE TITLE
Crash with reboot

### ISSUE THREAD

**Issue by pbuva** [aaronsace/MultiPoolMiner#18]
Hi, after some time is rig restarted :(

[2016-12-30_10-58-03.txt](https://github.com/aaronsace/MultiPoolMiner/files/678520/2016-12-30_10-58-03.txt)

**Comment by aaronsace** [comment]
I assume one the miners crashed your system whilst benchmark; does it work after rebooting? 

I think it maybe one of these, do you want to test it in command prompt: 

```
cd "[enter your path here]\Bin\Nanashi\"
ccminer.exe -a yescrypt -o stratum+tcp://hub.miningpoolhub.com:17021 -u pbuva.multipoolminer -p x
```

```
cd "[enter your path here]\Bin\Equihash\"
nheqminer.exe -a 3336 -l europe.equihash-hub.miningpoolhub.com:17023 -u pbuva.multipoolminer -t 0 -od 0 1 2
```

```
cd "[enter your path here]\Bin\CPU\"
cpuminer_x64_AVX2.exe -a myr-gr -o stratum+tcp://hub.miningpoolhub.com:17005 -u pbuva.multipoolminer -p x
```

**Comment by pbuva** [comment]
Only missing driver for nheqmine (i have AMD), but no crash.
After reboot still the same, run - reboot :(

**Comment by aaronsace** [comment]
They were the 3 miners that it was last activating. 

Send your log again; is it the same miners?

**Comment by aaronsace** [comment]
BTW, nheqminer shouldn't have missing drivers. Try removing the 'NheqminerAmd.ps1'.

**Comment by pbuva** [comment]
[2016-12-30_04-05-42.txt](https://github.com/aaronsace/MultiPoolMiner/files/678803/2016-12-30_04-05-42.txt)

I have only last log, only one run-reboot

**Comment by aaronsace** [comment]
ccminer is the common problem then. 

Try this to test: 

```
cd "[enter your path here]\Bin\NVIDIA\"
ccminer.exe -a groestl -o hub.miningpoolhub.com:17004 -u pbuva.MultiPoolMiner -p x
```

```
cd "[enter your path here]\Bin\AMD\"
sgminer.exe --api-listen -k skeincoin -o hub.miningpoolhub.com:17016 -u pbuva.MultiPoolMiner -p x

```

**Comment by aaronsace** [comment]
If it's still fine then try deleting files in the 'miners' folder until you find the one causing the problem.

**Comment by aaronsace** [comment]
Sorry but I'm unable to reproduce this. 
It is a problem with one of the miners and/or your graphics card setup.
