### ISSUE TITLE
Solutions to null Path and Excavator Timeout

### ISSUE THREAD

**Issue by lee-aaron** [aaronsace/MultiPoolMiner#180]
Some people have been mentioning that they have null Paths or the MPM hangs at Excavator.
Solution to null Paths:
`**if($Miner.URI -eq $null -or $Miner.Path -eq $null)
{
Write-Host "$($Miner.Name) has no URI or Path"
}**
elseif((Split-Path $Miner.URI -Leaf) -eq (Split-Path $Miner.Path -Leaf))
{
New-Item (Split-Path $Miner.Path) -ItemType "Directory" | Out-Null
Invoke-WebRequest $Miner.URI -OutFile $_.Path -UseBasicParsing
}`
I added the if statement at the beginning with the asterisks to avoid that error from appearing in the MPM.ps1. Hopefully this could be used. I also just added the URI links into the txt files if that's an option too.

Solution to Excavator:
`Invoke-WebRequest $Uri -OutFile $FileName -UseBasicParsing **-TimeoutSec 10**`
In the Include.ps1, I added the timeout if the MPM hangs at the URI request.

Meanwhile, I will continue messing around in Powershell for Linux. Let me know if there's anything else I can do to help.

Edit: Not sure why the webrequest doesn't exit after it goes to the excavator link? Perhaps that the link is valid but isn't downloading anything since it's just a release link?

**Comment by aaronsace** [comment]
I currently set all the miners to search the computer (offline) if it cannot download it (online) but only if the miner has a unique filename otherwise it will only look online.
