### ISSUE TITLE
MSVCR120.dll' 

### ISSUE THREAD

**Issue by digitaldemon** [aaronsace/MultiPoolMiner#182]
Missing MSVCR120.dll'  keeps displaying when bench marking . However I do have this file in windows /system32  ...

**Comment by lee-aaron** [comment]
It's supposed to be in the same folder as the miner itself. Search for it on the miner's page.

**Comment by aaronsace** [comment]
https://github.com/djm34/sgminer-msvc2015/issues/4

**Comment by aaronsace** [comment]
https://www.microsoft.com/en-gb/download/details.aspx?id=40784
