### ISSUE TITLE
Help with errors please

### ISSUE THREAD

**Issue by digitaldemon** [aaronsace/MultiPoolMiner#183]
This is what seems to be freezing my rig. I would greatly appreciate some help on this . This error just scrolls through then stops and repeats the entire time .

**Comment by Leass** [comment]
Can you upload screenshot of stated error? I doubt that anyone would be able to help You without it :)

**Comment by scaras** [comment]
delete the stats folder and see if that helps. 
if the miner isn't closed the normal way (pc crash) you get an error and this seems to help for me.

;)

**Comment by fonyo** [comment]
@digitaldemon Can you post details of the issue? Either log file or screenshot would be sufficient.

**Comment by scaras** [comment]
it's an error that it can't "Get-..." and it seems to be one of the files in the stats folder...

**Comment by fonyo** [comment]
Cool, I'm closing the thread. Post here if further issues occur related to this.
