### ISSUE TITLE
Is Vertcoin mining fully implemented?

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#185]
I have been a huge VTC supporter for many years. Finally, I have NVIDIA cards that I can use to mine VTC. Even if I force MPM to mine it by creating a new miner file based on one of the ccminerxyz.ps1, almost all variables return nothing. Even if I make pool, port, user, worker as static, it would not get out of the benchmarking phase. I also tried creating a Vertcoin.txt based on the claymore miner files but issue persists. (Still running 2.5.2, though.)

**Comment by scaras** [comment]
try this.


` . .\Include.ps1

$Path = ".\Bin\VERT\ccminer-x64.exe"
$Uri = "https://github.com/tpruvot/ccminer/releases/download/v2.0-tpruvot/ccminer-2.0-release-x64-cuda-8.0.7z"

$Commands = [PSCustomObject]@{

    "lyra2v2" = "" #Lyra2RE2

}

$Name = "VERT"

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = "-a your.pool.here:port -u pool.username -p pasw $($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week}
        API = "Ccminer"
        Port = 4068
        Wrap = $false
        URI = $Uri
    }
}`

**Comment by scaras** [comment]
it is the 0$ rule. 

what pool do you mine to? set a divisor in the pool file. (the 3 lines below)


```
 switch ($xyzpool_Algorithm) {
          "vert"   {$Divisor /= 1000} 
 }
```

**Comment by scaras** [comment]
try this as pool file (Vert_pool.ps1)


```
. .\Include.ps1

$Name = "Vert"


    $Vertpool_host = "mine.vert.now:port"
    $vertpool_Algorithm = "lyra2v2"
    $Vertpool_Coin = "Vert"

    $Divisor = 1

    $Stat = Set-Stat -Name "Vertpool_Profit" -Value ([Double] 100 / $Divisor)


        if ($UserName) {
            [PSCustomObject]@{
                Algorithm     = $Vertpool_Algorithm
                Info          = $Vertpool_Coin
                Price         = $Stat.Live
                StablePrice   = $Stat.Week
                MarginOfError = $Stat.Fluctuation
                Protocol      = "stratum+tcp"
                Host          = $Vertpool_Hosts 
                User          = "$UserName.$WorkerName"
                Pass          = "x"
                SSL           = $false
            }
        
            [PSCustomObject]@{
                Algorithm     = $Vertpool_Algorithm
                Info          = $Vertpool_Coin
                Price         = $Stat.Live
                StablePrice   = $Stat.Week
                MarginOfError = $Stat.Week_Fluctuation
                Protocol      = "stratum+ssl"
                Host          = $Vertpool_Hosts 
                User          = "$UserName.$WorkerName"
                Pass          = "x"
                SSL           = $true
            }
```

**Comment by fonyo** [comment]
Thanks. I haven't had time to test it just yet as I started running Vertcoin without MPM to grab some more then my pci-e splitters arrived and had to take everything apart to install 3 more cards. It just worries me that VTC mining is not working out of the box. Don't get me wrong I do appreciate your input but the point is to make MPM better and not creating workarounds (hence the issue). That being said, this will make me look into the code base even more which I'm grateful for. :)
