### ISSUE TITLE
claymore dual. 

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#187]
the changes you made to claymore dual (adding the algo's).
the ETH speed is different with every algo combination. MPM takes for all the same speed.
also i only have rejected shares for sia.

**Comment by fonyo** [comment]
Yes, should be changed/implemented before MPH has the new coins. At that point, it becomes a bug.

**Comment by scaras** [comment]
sia problem was already solved.
now the eth-decred calculation...  if it runs MPM tels me i be a millionair in a few weeks and can buy the white house, grate wall of china, eifeltower, ... and still have money left ;)

**Comment by fonyo** [comment]
Nice one @scaras. Have you tested 9.6? 9.5 is dreadful, and along with 9.3 they just can't handle the higher dcri values. 9.4 is running like champ with huge OC and at around dcri 90.

**Comment by fonyo** [comment]
I will add the bug label now as a reminder.

**Comment by scaras** [comment]
i use the 9.6 for my 390x. 29.4 mhz eth and 735mh sia @ dcri 25
claymore is one of the only miners for amd that functions with a dual (nvidia/amd) setup without to mush problems (for the amd miners)
for nvidia eth is not good. 
on my 1080 bitcore: 19.9Mh, blake2s: 5.15Gh neoscrypt +1Gh, blake 6.25gh, c11 20.15mh (all more proffit than eth at this moment (bitcore 75% more)

**Comment by fonyo** [comment]
My 6 nvidia 1070s are getting 160MH/s+ ethash with 4900+ Sia. That sum beats equihash and other algos by 6-9 bucks a day. Using MPH only so sometimes I am missing out on some of the juicier coins, although, this difference could also be higher or compensated if Decred/LBRY/Pascal coins were supported.

**Comment by scaras** [comment]
Lbry and decred are on zpool 
this is running now for my 1080:
 `CcminerTpruvot  hmq1725     11,51 MH/s 0,00486    0,42236 zpool-Unknown`
and here are some other numbers for one 1080 (±2000mhz clock 0.975v and 5005 mem)
```
CcminerAlexis78 Blake2s      5,24 GH/s 0,00689    0,00132 zpool-Unknown
CcminerAlexis78 Veltor      43,42 MH/s 0,00286    0,06586 zpool-Unknown
```
