### ISSUE TITLE
Help me again plz . excavation lost 0 sol / s

### ISSUE THREAD

**Issue by themangda** [aaronsace/MultiPoolMiner#188]
**********************
Windows PowerShell transcript start
Start time: 20170627132359
Username: FIRST-PC\Administrator
RunAs User: FIRST-PC\Administrator
Machine: FIRST-PC (Microsoft Windows NT 10.0.15063.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command &.\multipoolminer.ps1 -username themangda -workername DaRig1 multipoolminer -interval 3600 -location asia -ssl -type nvidia -algorithm ethash,equihash -poolname miningpoolhub -currency btc
Process ID: 4280
PSVersion: 5.1.15063.296
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.296
BuildVersion: 10.0.15063.296
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-06-27_01-23-59.txt
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Administrator\Desktop\MultiPoolMinerV2.5.2\Bin\Excavator\default_command_file.json' because it does not exist."

   Type: NVIDIA

Miner            Algorithm        Speed      BTC/Day  BTC/GH/Day Pool
-----            ---------        -----      -------  ---------- ----
NheqminerNvidia1 Equihash   278.93  H/s      0.00096 3,458.48476 MiningPoolHub-Zclassic
NheqminerNvidia0 Equihash   271.20  H/s      0.00094 3,458.48476 MiningPoolHub-Zclassic
NheqminerNvidia5 Equihash   269.20  H/s      0.00093 3,458.48476 MiningPoolHub-Zclassic
NheqminerNvidia4 Equihash   269.13  H/s      0.00093 3,458.48476 MiningPoolHub-Zclassic
NheqminerNvidia3 Equihash   265.60  H/s      0.00092 3,458.48476 MiningPoolHub-Zclassic
NheqminerNvidia2 Equihash   265.13  H/s      0.00092 3,458.48476 MiningPoolHub-Zclassic
EWBF2            Equihash  Benchmarking Benchmarking 3,458.48476 MiningPoolHub-Zclassic
EWBF0            Equihash  Benchmarking Benchmarking 3,458.48476 MiningPoolHub-Zclassic
EWBF1            Equihash  Benchmarking Benchmarking 3,458.48476 MiningPoolHub-Zclassic

   Type: {AMD, NVIDIA}

Miner          Algorithm                            Speed                      BTC/Day         BTC/GH/Day Pool
-----          ---------                            -----                      -------         ---------- ----
Gatelessgate   Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
Gatelessgate   Ethash                        Benchmarking                 Benchmarking            0.04781 MiningPool...
Claymore       Ethash                        Benchmarking                 Benchmarking            0.04781 MiningPool...
Excavator5     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
ClaymoreDual40 {Ethash, Sia} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.04781, 0.00062} {MiningPoo...
Excavator0     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
ClaymoreDual20 {Ethash, Sia} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.04781, 0.00062} {MiningPoo...
ClaymoreDual30 {Ethash, Sia} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.04781, 0.00062} {MiningPoo...
Excavator3     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
Excavator4     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
Excavator1     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...
Excavator2     Equihash                      Benchmarking                 Benchmarking        3,458.48476 MiningPool...

   Status: Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 13456 -c Equihash1.json
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 53456 -c Equihash5.json
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 23456 -c Equihash2.json
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 33456 -c Equihash3.json
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 3456 -c Equihash0.json
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Excavator\excavator.exe -p 43456 -c Equihash4.json

**Comment by scaras** [comment]
download the next zip file and extract it in MPM/bin/excavator/

https://github.com/nicehash/excavator/releases/download/v1.2.8a/excavator_v1.2.8a_Win64.zip

**Comment by themangda** [comment]
thank you so much.

**Comment by themangda** [comment]
Sorry again because of the multi-run and then check every 1 hour and then run the auto but the excavation lost 0 sol / s have to fix it.

**Comment by themangda** [comment]
i'm use program afterburnner Is this the reason.

Can I share?

**Comment by scaras** [comment]
no, i use it to. but not all miners and algo's like the same oc. there are more miners not working for me. but that is cuz i have 1 AMD 390x and a gtx 1080 in one pc

**Comment by themangda** [comment]
thank you so much.

**Comment by fonyo** [comment]
I am closing this now. Please create a NEW thread if you encounter other issues
