### ISSUE TITLE
v2.1 C:\MultiPoolMinerv2.1\Bin\Claymore\

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#19]
this dir is missing after first run

errors in log:

Convert-Path : Cannot find path 'C:\MultiPoolMinerv2.1\Bin\Claymore\Cryptonight\NsGpuCNMiner.exe' because it does not 
exist.
At C:\MultiPoolMinerv2.1\multipoolminer.ps1:72 char:23
+         $Miner.Path = Convert-Path $Miner.Path
+                       ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\MultiPoolMin...sGpuCNMiner.exe:String) [Convert-Path], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand
Convert-Path : Cannot find path 'C:\MultiPoolMinerv2.1\Bin\Claymore\Cryptonight\NsGpuCNMiner.exe' because it does not
exist.
At C:\MultiPoolMinerv2.1\multipoolminer.ps1:72 char:23
+         $Miner.Path = Convert-Path $Miner.Path
+                       ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\MultiPoolMin...sGpuCNMiner.exe:String) [Convert-Path], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

there is more about the other miners that would live in that dir

but I copied over the dir from v2 and it worked ok with them, I managed to manually add the above miner and now this error has gone, not sure if download of all the miners failed or some thing else.

Boysie

**Comment by aaronsace** [comment]
NsGpuCNMiner.exe is already included in the release. 

Has your virus checker removed the '.exe'? Have a look and see if 'C:\MultiPoolMinerv2.1\Bin\Claymore\Cryptonight\NsGpuCNMiner.exe' exists.

**Comment by boysie123** [comment]
nope the whole \Bin\Claymore\ folder is never created, so all 3 miners are missing or never downloaded. it works ok in v2.

**Comment by boysie123** [comment]
it looks like you dont log any thing about the download process so I dont have any errors to show you. just that on a fresh first time run the /bin/claymore folder does not exist on v2.1 but does on v2

**Comment by aaronsace** [comment]
Claymore is included in the release download manually. Did you download the code instead of the release?

**Comment by boysie123** [comment]
yes I cloned master.
