### ISSUE TITLE
How long is benchmarking supposed to take?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#191]
I have dual RX 480 and its benchmarking for an hour now. When will it end?

**Comment by aaronsace** [comment]
Try benchmarking less algorithms.

**Comment by mjmeans** [comment]
I used start.bat with only single change... my user name.

**Comment by aaronsace** [comment]
Are you using version 2.5.2? Is anything happening?

**Comment by mjmeans** [comment]
I just downloaded it today form the releases page. And yes, it's v2.5.2. It finally finished. Took forever. Could it be because the start.bat included CPU and the computer is a very low power mobo with a Sempron. Maybe I should disable CPU.

**Comment by aaronsace** [comment]
Yes, don't bother with cpu unless you got a decent cpu. It had probably already finished benchmarking the gpu.
