### ISSUE TITLE
Claymore Dual mining issues?

### ISSUE THREAD

**Issue by idealisticfool** [aaronsace/MultiPoolMiner#192]
Hello, 

 I have tried adding the new claymore dual mining txt files, I seem to be having an issue with decred,lbry,pascal while eth/sia still works fine. ETH connects fine, but decred,pascal,lbry all seem to not actually connect to a port?

what Iam I missing?

any help welcomed and thanks

**Comment by aaronsace** [comment]
You need to enable zpool.

**Comment by chocoborider** [comment]
How do i enable zpool?

**Comment by scaras** [comment]
in the start.bat you see -poolname miningpoolhub 
put "Zpool" after MPH

`-poolname miningpoolhub Zpool`

**Comment by idealisticfool** [comment]
ok thank you guys for the help so far, i have added the zpool argument and it is currently going though the benchmarking, I do have another question.. where would I add my zpool username/btc address?

**Comment by scaras** [comment]
ceep in mind that the eth-decred calculation can be wrong (at least it is wrong on my miner)

**Comment by chocoborider** [comment]
I'm using MPM v2.5.2 and Zpool does nothing, but i can see that in the pools folder there isn't any zpool file. I guess zpool wasn't included in that release. What can i do?

**Comment by scaras** [comment]
open MultiPoolMiner.ps1 with wordpad and change this line
`  [String]$Wallet, `  to  ` [String]$Wallet = "YOUR_BTC_ADRES", `

**Comment by Jaerin** [comment]
You should be able to add -wallet <wallet address> to your start.bat command to specify the wallet address.

**Comment by idealisticfool** [comment]
OK so a bit of a follow up.
I started with a fresh clone of today's fixes.
I tried adding the -wallet argument, the caused crashes at launch.
I tried multipoolminer.psi edit ([String]$Wallet, to [String]$Wallet = "YOUR_BTC_ADRES",) tho this will not throw an error it still didnt point the hash at my wallet ( in the launched command still said -dwal zpool)
What ended up working was to manually edit the ClaymoreDualXX.txt to reflect my BTC addy.

**Comment by scaras** [comment]
strange, cuz this section in zpool.ps1 places the $Wallet string as the username for zpool 
be shure to put every "space" . , " $ [ (and so on) correct. a computer is realy a dumb object, it only knows what you tell it to know

 ```
if ($Wallet) {
        [PSCustomObject]@{
            Algorithm     = $Zpool_Algorithm
            Info          = $Zpool_Coin
            Price         = $Stat.Live
            StablePrice   = $Stat.Week
            MarginOfError = $Stat.Week_Fluctuation
            Protocol      = "stratum+tcp"
            Host          = $Zpool_Host
            Port          = $Zpool_Port
            User          = $Wallet
            Pass          = "$WorkerName,c=BTC"
            Location      = $Location
            SSL           = $false
        }
```

**Comment by idealisticfool** [comment]
I will agree and yes i believe i have it formatted correctly..


param(
    [Parameter(Mandatory = $false)]
    [String]$Wallet = "BTC_addy", 
    [Parameter(Mandatory = $true)]
    [String]$UserName, 
    [Parameter(Mandatory = $false)]
    [String]$WorkerName = "multipoolminer", 
    [Parameter(Mandatory = $false)]
    [Int]$API_ID = 0, 
    [Parameter(Mandatory = $false)]
    [String]$API_Key = "", 
    [Parameter(Mandatory = $false)]
    [Int]$Interval = 60, #seconds before reading hash rate from

**Comment by Jaerin** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username jaerin -workername multipoolminer -wallet <wallet address>  -interval 60 -location us -ssl -type nvidia -algorithm x17,equihash,skein,myr-gr,nist5,lyra2re2,lbry,neoscrypt,sib,x11evo,groestl,qubit,x11,scrypt,blake2s,bitcore,hmq1725,decred,timetravel,blakecoin -poolname zpool -currency btc,usd -donate 0"

This works just fine for me when using zpool.  Notice the -wallet option in there.  What kind of error are you getting?

**Comment by idealisticfool** [comment]
ok back to tring the -wallet argument again, I was using the -poolname miningpoolhub Zpool setting and the with the -wallet it throws an error for me.. if i drop the miningpoolhub I get no errors at launch tring this... benchmarking as I type..

**Comment by Jaerin** [comment]
I don't think you can do both pools at once yet.  If you can it would likely be zpool,minginpoolhub

**Comment by idealisticfool** [comment]
well FFS...  it launched without error with zpool,miningpoolhub... benchmarking again.. will watch and see if the hash shows up at zpool..

**Comment by Jaerin** [comment]
The thing I'm not sure about is how it decides which coins to mine on which algorithms between the pools if there is coins on both for the same algo.  Like Skein is on both, but it seemed to pick DGB on miningpoolhub.  That might be the most profitable, but it might not.  Not sure.

**Comment by scaras** [comment]
you can use the 2 pools (ethash & siaCLAYMORE to mph and decred & lbry to zpool) but sia has the most proffit now (at least for me, cuz calculations for Decred are wrong with dual mining)

the proffits of mph? i don't know... if you see that on the dashboard for LTC is stated that 1LCT = 12.49usd. i'll buy lots of them if it was so

**Comment by idealisticfool** [comment]
OK well it seems that the answer to my original question was to simply add the -wallet argument to the start.bat, if I do this without adding the zpool to the -pool argument I get the results I was expecting.

I would like to thank you guys again for your help, Jaerin and scaras if you guys drop your zpool BTC addy in here I will point a card your way for a few...

**Comment by fonyo** [comment]
_Note to self to include this in FAQ and docs._

**Comment by Jaerin** [comment]
You're welcome - BTC: 1PS5CkwPKCwoxvmiFNQSMEswgEXVPoSN5Z

**Comment by scaras** [comment]
always willing to help ;)

you can pick one of these 3 (if you change the `,c=BTC` you can be payed out in all the coins they mine)
i use doge and bgd for faster payout and sell them on an exchange
```
DOGE: DPoPVBCLU23eV6T2gh9Eg9a8DNAmvDEZGQ
DGB: DQgetehpVkHmJzSsnR3sc8D39Jftx3pKkj
BTC: 1Az8xfXSq4ifeKxSqfiRD8PS9YTdr2seGD
```
