### ISSUE TITLE
How to initiate new benchmarking?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#193]
This is not specified in the readme.md file or the releases page and the wiki is empty.

Basically I have changed my GPU settings and I want to be able to restart benchmarking with alternate OC settings.

**Comment by mjmeans** [comment]
```
Miner                     eth     usd
-----                     ---     ---
MultiPoolMiner            0.02209 6.13359
ClaymoreDual20-Ethash/Sia 0.02231 6.19299
```

**Comment by snakethejake81** [comment]
In the Stats folder, remove the files with the miner/algo combos you want to benchmark again.  If you want to do them all, then just delete all the files in the folder.

**Comment by scaras** [comment]
or you can make a new miner file (based on the original) with your oc settings in the commands line and give it another name (don't forget to change the stats filename to)

for the people with nvidia cards above gtx 9xx: try your miners with " --pstate=0 " in the commands line. this can be positive for your hashrate.

**Comment by mjmeans** [comment]
Too much work to edit the miner files especially when considering new versions of mpm pending. To have to track what is changed and then have to figure out if those changes are relevant with each new version is too tedious.

But thanks for the info on how to reinitiate the benchmarking. I would like to make that a feature request for a command to force new benchmarks.

**Comment by scaras** [comment]
what is hard work editing the files?
open it, change a few parameters and safe as (new name)
if benchmark is done you know what parameters to use for all the coins.
i got a few Mh more for some coins this way (incl: Neoscrypt Sib X17...) i got lyra2z from tpruvot faster than the lyra2z miner that is provided by MPM

**Comment by fonyo** [comment]
The problem with your new feature request is that if the benchmark parameter is not removed from the start.bat, after the process is done, MPM will benchmark indefinitely so such implementation would not be intuitive/useful. It is much easier to delete relevant or all files from the stats folder. I still consider this as very low maintenance required from the user.
