### ISSUE TITLE
Exception when setting "Profit_MarginOfError"

### ISSUE THREAD

**Issue by chocoborider** [aaronsace/MultiPoolMiner#195]
With the latest files of the repo i get this error:

`
Excepción al establecer "Profit_MarginOfError": "La propiedad 'Profit_MarginOfError' no se encuentra en este objeto. Compruebe que la propiedad existe y se puede establecer."
En E:\Criptomonedas\MultiPoolMiner\MultiPoolMiner.ps1: 184 Carácter: 9
         $_.Profit_MarginOfError = 0
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
     FullyQualifiedErrorId : ExceptionWhenSetting`

**Comment by scaras** [comment]
put an # at the beginning of line 181 to 188

**Comment by aaronsace** [comment]
Oops, that's part of the coming commit. Comment that line out for now.
