### ISSUE TITLE
Dual Profit is inverted

### ISSUE THREAD

**Issue by chocoborider** [aaronsace/MultiPoolMiner#196]
I made a custom miner that only uses my GTX1060 and the speed and BTC/Day calculations are getting inverted.

`
Miner                Algorithm                                   Speed                 BTC/Day         BTC/GH/Day Pool
-----                ---------                                   -----                 -------         ---------- ----
ClaymoreDualNVIDIA30 {Ethash, Lbry}          {182,14 MH/s, 16,77 MH/s}      {0,01012, 0,00011} {0,05558, 0,00685} {MiningPoolHub-Ethereum, zpool-Unknown}
ClaymoreDualNVIDIA30 {Decred, Ethash}        {18,31 MH/s, 182,14 MH/s}      {0,00001, 0,01012} {0,00030, 0,05558} {zpool-Unknown, MiningPoolHub-Ethereum}
`

`
[
    {
        "Type":  ["NVIDIA"],
        "Path":  ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
        "Arguments":  "-epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -esm 3 -allpools 1 -dpool $($Pools.Decred.Host):$($Pools.Decred.Port) -dwal $($Pools.Decred.User) -dpsw $($Pools.Decred.Pass) -dcoin dcr -dcri 30 -di 1 -mport 10050",
        "HashRates":  {"Ethash":  "$($Stats.ClaymoreDualNVIDIA30_Ethash_HashRate.Week)","Decred":  "$($Stats.ClaymoreDualNVIDIA30_Decred_HashRate.Week)"},
        "API":  "Claymore",
        "Port":  "10050",
        "Wrap":  false
    },
    {
        "Type":  ["NVIDIA"],
        "Path":  ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
        "Arguments":  "-epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -esm 3 -allpools 1 -dpool $($Pools.Lbry.Host):$($Pools.Lbry.Port) -dwal $($Pools.Lbry.User) -dpsw $($Pools.Lbry.Pass) -dcoin lbc -dcri 30 -di 1 -mport 10050",
        "HashRates":  {"Ethash":  "$($Stats.ClaymoreDualNVIDIA30_Ethash_HashRate.Week)","Lbry":  "$($Stats.ClaymoreDualNVIDIA30_Lbry_HashRate.Week)"},
        "API":  "Claymore",
        "Port":  "10050",
        "Wrap":  false
    }
]
`

EDIT: I'm using the latest repo files

**Comment by nostrakhan** [comment]
I'm having a similar issue, here is a screenshot:  http://prntscr.com/fpfmxd.  It shows I'd be making way more ETH than I should...some stat values should be inverted like chocoborider said.  Any idea how to fix this? 

I'm using the latest files as well, and using MPH and ZPool both.

**Comment by scaras** [comment]
known bug with decred.

**Comment by nostrakhan** [comment]
Also seems to happen with eth+lbry

**Comment by scaras** [comment]
it starts to look like it takes the speed of the 1st hashing coin as `$Hashrates` and the coin that starts hashing last as` $Hashrates_dual`

**Comment by nostrakhan** [comment]
Makes sense, do you know how it can be fixed, or must we wait for aaronsace?

**Comment by scaras** [comment]
sadly i don't know how to fix this at this moment.
i just spend some free time learning how to code by looking for the bugs

**Comment by fonyo** [comment]
This has been reported already. Should be fixed in the next release.

**Comment by scaras** [comment]
i use a different miner file for all algo combinations and speeds (having both nvidia and amd)
with the example below i have no problems with Lbry (pascal i can't test for now) only having problems with decred calculation

**notice the -allcoins 1 AND -allpools 1 (they are not in the repo) and -esm 2 (3 is for nicehash)
```
{
    "Type":  ["AMD"],
    "Path":  ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
    "Arguments":  " -epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -di 0  -mode 0 -asm 1 -esm 2 -etha 1  -allcoins 1 -allpools 1 -dpool $($Pools.Lbry.Host):$($Pools.Lbry.Port) -dwal $($Pools.Lbry.User) -dpsw $($Pools.Lbry.Pass) -dcoin lbry -dcri 35",
    "HashRates":  {"Ethash":  "$($Stats.ClayAMDDual35_L_Ethash_HashRate.Week)","Lbry":  "$($Stats.ClayAMDDual35_L_Lbry_HashRate.Week)"},
    "API":  "Claymore",
    "Port":  "3333",
    "Wrap":  false
}
```

**Comment by aaronsace** [comment]
@scaras MiningPoolHub and Zpool support the NiceHash stratum protocol. 

I will add "-allcoins 1" "-allpools 1".

**Comment by scaras** [comment]
works fine with -esm 2 here (need it if i want to mine pascal)

**Comment by aaronsace** [comment]
It's alright, MiningPoolHub supports all the stratum protocols including NiceHash's (esm 3).

**Comment by scaras** [comment]
and my car can also run on 2stroke petrol mix... 
my cpu can do +5Gh on 1.8v (6700k)...  
my gtx 1080 can do 2050 on 1.075v...
just becuz it works dosn't mean it's good.

**Comment by aaronsace** [comment]
Yes but I don't think that applies in this situation, there is no standard protocol for Ethereum. NiceHash's version of the protocol works great, it was just a bit late to the game. 

Getting off topic a bit here.
