### ISSUE TITLE
Claymore v9.6 is out - please test with MPM and post your results

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#197]
https://bitcointalk.org/index.php?topic=1433925.0

1. Download and extract compressed package
2. Replace (overwrite) all files in /Bin/Ethash-Claymore folder with the new ones.
3. Post here your results about stability and thoughts of the update in general.

What's changed since v2.5?
- new GPU sorting method for AMD cards. Now GPUs are sorted by physical bus index (it matches AfterBurner list of GPUs). Also the list of temperatures/fans matches the list of GPUs automatically.
  Therefore "-di detect" and "-gmap" options are not necessary and not supported anymore.
  **WARNING: be careful if you use use separate overclock/temperature settings for every card, due to new sorting method GPUs can get different indexes!**
- added "-minspeed" option to restart miner/system if miner cannot reach specified speed.
- now watchdog monitors initialization steps too, e.g. it will restart miner even if miner hangs at GPUs initialization.
- added "-allcoins etc" option for ETC pools that require Username.Worker, in this mode devfee will be mined on some default ETC pools and DAG will not be recreated.
- added current DAG size info when "s" key is pressed.
- added 1 minute average speed for ETH when "s" key is pressed.
- fixed connection timeout issue in Linux version.
- fixed some issues related to remote management via TCP/IP.
- added "-ejobtimeout" and "-djobtimeout" options.
- fixed epoch #0 support.
- a few minor bug fixes and improvements.
- EthMan: fixed issue with lost connection to some rigs.
- EthMan: added password for webserver.
- EthMan: added separate settings for every event.
- EthMan: added "retrigger" option for lost connection event.

**Comment by fonyo** [comment]
1st attempt with RX480 rig, win 7, Driver v16.9.2
Driver crash on initial launch.

**Comment by lee-aaron** [comment]
GTX 1050 4 GB Laptop version. Windows 10. Driver 382.33

ETH-SC
ClaymoreDual40 v9.5: 10.81 MH/s ; 136.91 MH/s (probably skewed left due to benchmark)
ClaymoreDual40 v9.6: 8.5 MH/s ; 113.5 MH/s (roughly these hashrates after 8-10 min)

 It seems relatively similar to v9.5 if I remember what my hashrates were. I probably should be using dcri like 80,90,100 for GTX but eh, it's just testing.

**Comment by scaras** [comment]
dag file, network dif. , pool dif, ... all factors that influence mining speed. can't compaire 2 miners with a few days in between.

**Comment by fonyo** [comment]
@scaras I thought the same first. We are getting less and less mostly due to the DAG increase but in this case, I am actually getting better results with earlier versions of Claymore Dual.

**Comment by scaras** [comment]
all depends on the system and settings. there. 
on my system (for my 1080) the newest alexis79 mod for ccminer is faster then tpruvot, sp, ... (all tested with all algo's and different -i xx, --pstate=0, clock and mem settings)

**Comment by fonyo** [comment]
That's quite off-topic. We are measuring differences of Claymore Dual v9.6 vs <=v9.5 in order to see whether it's better to include the newer version with MPM. Of course, there can be huge differences between different forks of miners.

**Comment by scaras** [comment]
that depends on system... one will benefit other will not...
you always need to eddit the settings of a miner to your own system. you can (almost) always get better results as you did not setting your own parameters.
