### ISSUE TITLE
Nemosminer using MultiPoolMiner code?

### ISSUE THREAD

**Issue by merlinsbeard69** [aaronsace/MultiPoolMiner#198]
I downloaded the latest Nemosminer (2.05) and the program looks almost exactly like MultiPoolMiner. The folder/file structure, benchmark, ect look almost the same. Yet, there is no reference to you or multipoolminer but the name and donation address has been changed. 

https://bitcointalk.org/index.php?topic=1777336.0

**Comment by fonyo** [comment]
Yes, Nemosminer is a fork of MPM.
