### ISSUE TITLE
neoscrypt connect problems

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#2]
emmm...multipoolminer...time after time have this error and no reconect after 30 sec.only manual restarting of the scrypt is helping.
![default](https://cloud.githubusercontent.com/assets/16507768/21174893/5e71f4a8-c1e8-11e6-8cce-a7c8ff378609.PNG)

**Comment by aaronsace** [comment]
The stratum address is correct in the screenshot and if it was a problem with the username I think it would say it failed to authorize. Maybe there is a problem with ccminer or your machine. Have you or miningpoolhub ever experienced this error before when using ccminer?

**Comment by lyolyalya** [comment]
no=)i just rerun scrypt in a few seconds and everything is okay...maybe need some delay between closing old miner and opening new?

**Comment by aaronsace** [comment]
I will implement an auto start if the miner has closed. You can then set ccminer to close on error (using the '-r 0' setting) and multipoolminer will start it again.

**Comment by lyolyalya** [comment]
okay.i'll try.now testing tpruvot 1.8.3 ccminer.even with oc it changes few times without a bug...

**Comment by aaronsace** [comment]
Alright. I'll release a fix to the current version anyway as it it's good for it to keep checking if the miner is still running.

**Comment by lyolyalya** [comment]
you implemented autostart exectly for ccminer or any miner?do i need to change something in scrypt?

**Comment by aaronsace** [comment]
Set ccminer to close instead of retry when there is a connection problem. MultiPoolMiner will detect that it has closed and open it again. I believe the ccminer command it is '-r 0'

**Comment by lyolyalya** [comment]
done.will test it with tpruvot ccminer.
