### ISSUE TITLE
how to add expanse?

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#20]
Hi

I'm trying to add expanse using the following but it mines it and then is missing from the reported successful list with its profit value

    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Claymore\\Ethash\\EthDcrMiner64.exe",
        "Arguments":  "-epool europe1.expanse.miningpoolhub.com:20565 -ewal $($Pools.Ethash.User) -epsw x -esm 3 -allpools 1 -allcoins exp -tt 75 -cclock 1180 -mclock 2160 -powlim 15 -cvddc 970 -mvddc 970 -r 1",
        "HashRates":  {"Expanse":  "$($Stats.Claymore_Expanse_HashRate.Day)"},
        "API":  "Claymore"
    }

the file Claymore_Expanse_HashRate.txt contains:

{
    "Live":  99110000.0,
    "Minute":  99110000.0,
    "Minute_Fluctuation":  0,
    "Minute_5":  99110000.0,
    "Minute_5_Fluctuation":  0,
    "Minute_10":  99110000.0,
    "Minute_10_Fluctuation":  0,
    "Hour":  99110000.0,
    "Hour_Fluctuation":  0,
    "Day":  99110000.0,
    "Day_Fluctuation":  0,
    "Week":  99110000.0,
    "Week_Fluctuation":  0,
    "Updated":  "\/Date(1483122996286)\/"
}

but the reported doesn't list it.

   Type: {AMD, NVIDIA}

Miner    Algorithm   Speed BTC/Day BTC/GH/Day Pool
-----    ---------   ----- ------- ---------- ----
Claymore Ethash    94 MH/s 0.00425    0.04521 MiningPoolHub

   Type: AMD

Miner        Algorithm    Speed BTC/Day  BTC/GH/Day Pool
-----        ---------    ----- -------  ---------- ----
Claymore     Equihash  814  H/s 0.00434 5,334.39303 MiningPoolHub
NheqminerAmd Equihash   92  H/s 0.00049 5,334.39303 MiningPoolHub

**Comment by aaronsace** [comment]
I've already added Expanse; it's part of the Equihash switching port.

**Comment by aaronsace** [comment]
Expanse is not an algorithm, it's a coin.

**Comment by aaronsace** [comment]
It can support coin switching locally if you want me explain how to do it. Letting the pool handle the coin switching is more efficient though.

**Comment by aaronsace** [comment]
Please see attached. Put this in the 'pools' folder. 
[MiningPoolHubCoins.zip](https://github.com/aaronsace/MultiPoolMiner/files/679330/MiningPoolHubCoins.zip)

**Comment by aaronsace** [comment]
Correction: 
[MiningPoolHubCoins.zip](https://github.com/aaronsace/MultiPoolMiner/files/679378/MiningPoolHubCoins.zip)

**Comment by boysie123** [comment]
that's awesome thank you. 
I'm not 100% sure how your profit calculations are working but is it possible to use this coin method to have a preferred coin meaning to have it weighted in its favour because by the time you take into account the time it takes for the pool to mine a coin (long time for zcash for example like 2h) and the fluctuations in price it was prob better to mine the coin you are converting it into in the first place with all the fees for converting etc. now this might already be in your code to prevent this but it seems quite difficult to fig out in my head how you could achieve this automatically, so having a preferred coin (the one you use to exchange into on the pool side) and some way to say as long as its with in a few % just mine this one else the profit will be the same if not less by the time its gone through the exchange process.

**Comment by boysie123** [comment]
it looks like I'm struggling with coins that have a - in the name for example:

    {
        "Type":  "AMD",
        "Path":  ".\\Bin\\Claymore\\Ethash\\EthDcrMiner64.exe",
        "Arguments":  "-epool europe1.ethereum-classic.miningpoolhub.com:20555 -ewal $($Pools.Ethash.User) -epsw x -esm 3 -allpools 1 -tt 75 -cclock 1180 -mclock 2170 -powlim 15 -cvddc 970 -mvddc 970 -r 1",
        "HashRates":  {"ethereum-classic":  "$($Stats.Claymore_ethereum-classic_HashRate.Day)"},
        "API":  "Claymore"
    }

**Comment by boysie123** [comment]
it creates the file Claymore_ethereum-classic_HashRate.txt but seems to get stuck in benchmarking mode, if you rename it to Claymore_ethereum_classic_HashRate.txt (replacing the - with _) it now finds it but drops the coin from the list like a failed one and moves back to the algo's on the list.

**Comment by aaronsace** [comment]
I've updated the source code with the pool file I sent you plus the fix in the main code. 
You can add a bias by multiplying the Ethereum pool price by like 1.05 in the pool file. 

Insert it between those two lines: 
```
$Price = (($Stat.Live*(1-[Math]::Min($Stat.Hour_Fluctuation,1)))+($Stat.Hour*(0+[Math]::Min($Stat.Hour_Fluctuation,1))))

if($_.coin_name -eq 'ethereum'){$Price *= 1.05}

[PSCustomObject]@{
```
