### ISSUE TITLE
BTC/GH/Day not the same between miners

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#201]
I have noticed that none of my miners BTC/GH/Day are the same for simular coins. 

for example 
Worker1 Claymore       Ethash      **0,05173** MiningPoolHub-Ethereum
Worker2 Claymore       Ethash      **0.05162** MiningPoolHub-Ethereum
Worker3 Claymore       Ethash      **0,05296** MiningPoolHub-Ethereum

All 3 are running the same windows 10 MultiPoolMinerV2.5.2

**Comment by aaronsace** [comment]
The variance looks marginal to me. It also adjusts over days to get a more accurate reading.

**Comment by jjziets** [comment]
2.6%. 
Just strange as all 3 have been running for weeks. 

Is there a way to get the instant value?

**Comment by aaronsace** [comment]
The sats are in plain text in the 'stats' folder. Check/delete any from there.

**Comment by fonyo** [comment]
I thought that number was the current/actual value. Why is it not?

**Comment by Jaerin** [comment]
I believe one of the reasons is the instant value isn't the value you are going to likely get anyways.  It is just a snapshot of the potential of what you are going to get so using a more averaged value over time is likely to be much more accurate returns given that prices fluctuate and time to exchange.  That's my understanding anyways.

**Comment by aaronsace** [comment]
@fonyo I think they are comparing three separate machines. 
It takes a snapshot the BTC per Hash and the hash rate once per minute then shows the average for the week.

**Comment by aaronsace** [comment]
As I have changed a lot of this in the coming release and there is no real issue here, I've closed this.
