### ISSUE TITLE
calculation in mixed system.

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#203]
i'm having a dual setup (NVIDIA gtx 1080 and AMD r9 390x gpu)
if i run 1 claymore for the 2 cards it takes the combined speeds and counts it as the speed for 1 type (so ont time for amd and one time for nvidia) 

`{claymoredual25_90-Ethash/siaclaymore, claymoredual25_90-Ethash/siaclaymore, CpuminerJayddeeAesavx2-Lyra2z} 0,00757 ±50% 16,67152 ±50%`

**Comment by aaronsace** [comment]
Sorry, I'm confused by this. Please can you provide more information.

**Comment by scaras** [comment]
i have 2 gpu cards in my pc. 
all the miners that can mine amd and nvidia takes the speed from the miner (combined speed) and with the calculation he takes the speed one time for amd and one time for nvidia.

**Comment by scaras** [comment]
i don't know if you tryed to fix it, but bug is still in latest release (not that it is good mining eth with nvidia...)
