### ISSUE TITLE
SiaClaymore benchmark not populating

### ISSUE THREAD

**Issue by aelias27** [aaronsace/MultiPoolMiner#204]
Hi Aaronsace thanks a lot for you work!

While using latests version of MPM Claymore-Dual benchmarking doesn't complete, it runs indefinitely.
Ethash hashrate is being populated while SiaClaymore stays on "Benchmarking".
I didn't had this issue before Sia dual mining name changed to SiaClaymore.
Tried using clean release with same result, as a workaround i'm just deleting CalymoreDualXX.txt files
(using GTX1080ti & Win10)

Thanks for your help

**Comment by scaras** [comment]
this line is in mininghubpool(coins).ps1? (this one will be there cus he starts mining)
`if ($MiningPoolHub_Algorithm -eq "Sia") {$MiningPoolHub_Algorithm = "SiaClaymore"} #temp fix`

and the line in the clamore miner files

`"HashRates":  {"Ethash":  "$($Stats.ClaymoreDualxx_Ethash_HashRate.Week)","Sia":  "$($Stats.ClaymoreDualxx_Sia_HashRate.Week)"},`

**Comment by aelias27** [comment]
Hi scaras

Yes both lines are in MiningPoolHubCoins.ps1 and ClaymoreDualXX.txt

Commenting the "#temp fix" will make MPM use same hashrate for all Sia miner?

I'll try that

**Comment by scaras** [comment]
sorry, copyed the wrong line

`"HashRates":  {"Ethash":  "$($Stats.ClayAMDDual20_S_Ethash_HashRate.Week)","SiaClaymore":  "$($Stats.ClayAMDDual20_S_SiaClaymore_HashRate.Week)"},`

**Comment by aelias27** [comment]
no problem
I'll try tweaking the script a bit

**Comment by scaras** [comment]
make shure all sia is siaClaymore in the minerfile

**Comment by aelias27** [comment]
Thanks for your help scaras, it works !
