### ISSUE TITLE
No Pools!

### ISSUE THREAD

**Issue by Chryptofer** [aaronsace/MultiPoolMiner#205]
Hi,

Downloaded Ver. 2.5.2 ; inserted Excavator file into the right folder, this is the command line inside the start.bat file:

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet <MyWallet#> -username Chryp -workername Dig -interval 60 -location US -type nvidia  -pool zpool -currency btc,usd -donate 10"

The miner has nvidia GPUs only, and all it shows is a "No Pools!" infinite loop in screen, what can be happening?

Thank you.

**Comment by fonyo** [comment]
The correct commands are:
`-poolname miningpoolhub Zpool`

Not sure if it stays that way, it is not really intuitive, however, bear in mind the zpool update of MPM has not been finished/released yet.

**Comment by scaras** [comment]
only the zpool update? first try to get claymore dual working and profit calculation... 
on what are the prices from MPH based?on the dashboard of litecoin  is LTC/USD = 12.49 usd...
max coin is still trading on yobit (not according to mph)...
and i was thinking nicehash sucks.

**Comment by fonyo** [comment]
@aaronsace so what is the correct parameter and value now? I'll make a note to add it to the Q&A.

**Comment by aaronsace** [comment]
Should be '-poolname [name of pool file]'

**Comment by Chryptofer** [comment]
This software doesn't work in my rig, "- poolname zpool" gives me NO POOLS! error, then tried using the original settings, miningpoolhub under aaronsace account, no modifications, and it keeps showing different errors or freezing, I'm not very literate so don't know how to fix it or what do do.
