### ISSUE TITLE
Only mining ETH and SIA

### ISSUE THREAD

**Issue by TResearchG** [aaronsace/MultiPoolMiner#207]
Hey guys,

I've just started pool mining and I think I got everything to work correctly. But it's only mining for ETH and SIA.  Can anyone tell me why it's only dual mining for those coins only?  Thanks.

I am currently running two rigs.

6 x 1060s 
6 x 1070s

**Comment by Jaerin** [comment]
I believe there are some issues with dual mining on the latest commits.  That will likely need to be worked out.

**Comment by scaras** [comment]
for Lbry make a txt file named "ClaymoreDual85_L"  (having nvidia cards will give better results @ higher dcri)
```
{
    "Type":  ["NVIDIA"],
    "Path":  ".\\Bin\\Ethash-Claymore\\EthDcrMiner64.exe",
    "Arguments":  "  -epool $($Pools.Ethash.Host):$($Pools.Ethash.Port) -ewal $($Pools.Ethash.User) -epsw $($Pools.Ethash.Pass) -di 1  -mode 0 -asm 1 -esm 2 -etha 1  -allcoins 1 -allpools 1 -dpool $($Pools.Lbry.Host):$($Pools.Lbry.Port) -dwal $($Pools.Lbry.User) -dpsw $($Pools.Lbry.Pass) -dcoin Lbry -dcri 85",
    "HashRates":  {"Ethash":  "$($Stats.ClaymoreDual85_L_Ethash_HashRate.Week)","Lbry":  "$($Stats.ClaymoreDual85_L_Lbry_HashRate.Week)"},
    "API":  "Claymore",
    "Port":  "3333",
    "Wrap":  false
}
```
same changes can be made for other algo-combo's and speeds
