### ISSUE TITLE
Excavator Not Working

### ISSUE THREAD

**Issue by joesixpack** [aaronsace/MultiPoolMiner#208]
...due to missing json files.

0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p
                                               33456 -c Sia3.json
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p
                                               23456 -c Equihash2.json
0.00 PH/s 00 Days 00 Hours 00 Minutes 2 Times  Bin\Excavator\excavator.exe -p
                                               53456 -c Sia5.json

**Comment by Jaerin** [comment]
Personally I converted the Excavator into a single file instead of spawning individual threads for each GPU and modified the command in the ps1 to the following:

```$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    [PSCustomObject]@{time = 0; commands = @([PSCustomObject]@{id = 1; method = "algorithm.add"; params = @("$_", "$($Pools.$_.Host):$($Pools.$_.Port)", "$($Pools.$_.User):$($Pools.$_.Pass)")})},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "0") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "1") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "2") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "3") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "4") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 3; commands = @([PSCustomObject]@{id = 1; method = "worker.add"; params = @("0", "5") + $Commands.$_}) * $Threads},
    [PSCustomObject]@{time = 10; commands = @([PSCustomObject]@{id = 1; method = "algorithm.print.speeds"; params = @("0")})} | ConvertTo-Json -Depth 10 | Set-Content "$(Split-Path $Path)\$_$ThreadIndex.json" -Force -ErrorAction SilentlyContinue```

This add 2 threads per worker for the first 6 cards.  This seems to even work if you have less cards as well.

**Comment by aaronsace** [comment]
If you don't have 6 cards then it will crash.

**Comment by Jaerin** [comment]
Actually the code I posted works great and doesn't crash for Zpool's equihash pool even with only 2 nvidia cards.  Maybe it crashes with fewer AMD cards?  I don't have an AMD rig so can't test that.

It seems that Excavator does not work with the Equihash coins on Miningpoolhub at all from what I can tell.  At least not on Nvidia cards.  I tried your base miner files split by GPU and they still never get any hashes against the MPH pool.  I even tried the default with going directly to one of the coins and that didn't work either.  Which isn't that big of a deal because I think EBWF is faster for Nvidia anyways.

**Comment by jjziets** [comment]
Mine does not work. Not sure why


=========================== www.nicehash.com =========================
                Excavator v1.2.10a GPU Miner for NiceHash.
           Copyright (C) 2017 NiceHash. All rights reserved.
Developed by djeZo, zawawa and dropky with help and contributions from
             pallas, Vorksholk, bitbandi, ocminer, Genoil
=========================== www.nicehash.com =========================

Build time: 2017-07-07 09:02:48
Build number: 151
Provided startup commandline:
        "C:\MultiPoolMinerV2.5.3.3\Bin\Excavator\excavator.exe" -p 53456 -c equihash5.json

[16:23:55][0x000004ec][info] Log started
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] core | Found CUDA device: GeForce GTX 1070
[16:23:58][0x000004ec][info] api | Listening on 127.0.0.1:53456
[16:23:58][0x000004ec][info] core | Initialized!
[16:24:01][0x00001a60][info] wrkr5-0 | Algorithm: CUDA-equihash parameters: M=0
[16:24:01][0x00001a5c][info] wrkr5-1 | Algorithm: CUDA-equihash parameters: M=0
[16:24:08][0x00002460][info] core | Algorithm 'equihash' total speed: 0.000000 H/s
[16:25:18][0x000004ec][info] Shutting down
[16:25:18][0x000004ec][info] api | Closing

same with daggerhashimoto4.json

using 6 1070s windows 10

**Comment by litwi1rm** [comment]
@jjziets - Exact same output for me as well! I also am using 6 1070's on windows 10

**Comment by joesixpack** [comment]
I've never gotten this turd to work.  I'd suggest moving on.  It's not the fastest at anything anyway.

**Comment by joesixpack** [comment]
Also while we are at it, during NVIDIA benchmarking about 75% of the way through the list, all of the Zpool entries will suddenly come up and then disappear.
