### ISSUE TITLE
benchmark + 10% is too high

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#21]
It looks like on the first bench mark you add 10% and then use this as the hash rate.

This seems to high and some thing like 2% would be more realistic?

I'm not sure if you modify over time but I noticed a 30MH 3 card system ending up with a 99MH rate for claymore and it will never get that high so it seems 2% would be more on the money incase the recorded amt was more like 29.5 for each card.

**Comment by aaronsace** [comment]
It's a completely made up figure. It makes no difference in a perfect world but in the real world it reduces the risk of a low reading. It levels out fine and will end up with a 100% accurate reading. You can set it to 2% if you want.
