### ISSUE TITLE
Gateless Gate

### ISSUE THREAD

**Issue by joesixpack** [aaronsace/MultiPoolMiner#210]
Is defaulting to built in Intel graphics and not finding the rig cards with default -gpu-platform 0.  1 results in this:

![image](https://user-images.githubusercontent.com/23145642/27845547-28d407fe-60e5-11e7-86d4-6ae92a467757.png)

**Comment by Jaerin** [comment]
I noticed this as well on my systems.  Not sure if it is Nvidia only problem or not.

**Comment by aaronsace** [comment]
The platform numbers are random. You'll have to manually change it for now. Options are either 0,1 or 2.
