### ISSUE TITLE
"Smart quotes and dashes" - wrong encoding for ps1 files.

### ISSUE THREAD

**Issue by softgripper** [aaronsace/MultiPoolMiner#215]
Hey, I just cloned the MultiPoolMiner and it wouldn't run because of the encoding.

There are smart quotes and dashes in your *.ps1 files.

Just something easy to fix, but you'll have to check your editor settings.

I'm looking forward to a new release as I really like the algorithm list.

Thanks.

**Comment by tutulino** [comment]
same here, i must copy from code page to run, if I download source code or release some errors from characters happens.

**Comment by aaronsace** [comment]
Don't know why that came back. Fixed it again.
