### ISSUE TITLE
Questions and Small Suggestion

### ISSUE THREAD

**Issue by lee-aaron** [aaronsace/MultiPoolMiner#217]
I'm curious about how the 2gb support works. How exactly can you mine ethereum since the DAG file is over 2 gb?

Aside from that, I made some small updates to the README for clarity purposes and fixed a few typos. The README is on my forked version.

**Comment by lee-aaron** [comment]
Funny thing was that I was testing out the 2gb Claymore miner and found that when it switches to mine for the dev, the miner restarts because DAG file is too big perhaps. Then, MPM creates a new instance of the miner but doesn't close out the current one. And as a result, I think there's infinite benchmarking with Claymore's miner?

**Comment by aaronsace** [comment]
Well that's annoying. I will check the options; I may just turn the dev fee off.

**Comment by scaras** [comment]
the problem with the claymore DAG file chould not be happening if you use  -allcoins 1 and -allpools 1 
(but i don't know if that also works for the 2GB cards, but if they send the shares to the same pool and the 2Gb cards don't edit the DAG file i don't see why it chouldn't work)

**Comment by aaronsace** [comment]
The port is not coin switching so that will work.

**Comment by lee-aaron** [comment]
![capture](https://user-images.githubusercontent.com/21045039/27988937-201f249e-63e3-11e7-882b-323de40a7968.JPG)
 I attached the image so you can see how it launches a second instance of the same miner. 
[1499546422_log.txt](https://github.com/aaronsace/MultiPoolMiner/files/1133293/1499546422_log.txt)

The above log is the new instance that was created.

[1499545339_log.txt](https://github.com/aaronsace/MultiPoolMiner/files/1133295/1499545339_log.txt)

This should be the original instance of the miner.

**Comment by fonyo** [comment]
Version 2.5.2 also does that occasionally. I have no idea why MPM loses connection with the first instance of Claymore but the outcome is another instance which messes up the overall hashrate.

**Comment by aaronsace** [comment]
I store the process ID. Maybe the Claymore miners have some sort of process reset built on for failures. 

If it can be set to close on failure instead then that may help.

**Comment by scaras** [comment]
did you do this?

> For multi-GPU systems, set Virtual Memory size in Windows at least 16 GB:
> "Computer Properties / Advanced System Settings / Performance / Advanced / Virtual Memory".

**Comment by fonyo** [comment]
I have it set above 24GB on all my rigs regardless how many cards I have in them. This bug has nothing to do with the pagefile, though.

**Comment by lee-aaron** [comment]
Closing this since problem solved for me.
