### ISSUE TITLE
Ethas-Claymore never benchmarks.

### ISSUE THREAD

**Issue by jeremiahtenbrink** [aaronsace/MultiPoolMiner#224]
I have left it running for quite some time and it never seems to benchmark. 

Windows 10
Gforce 980
Gforce 970
I'm running mining pool hub.

**Comment by jeremiahtenbrink** [comment]
[Claymore_Ethash_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140433/Claymore_Ethash_HashRate.txt)
[ClaymoreDual20_Ethash_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140434/ClaymoreDual20_Ethash_HashRate.txt)
[ClaymoreDual20_SiaClaymore_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140435/ClaymoreDual20_SiaClaymore_HashRate.txt)
[ClaymoreDual40_Ethash_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140436/ClaymoreDual40_Ethash_HashRate.txt)
[ClaymoreDual40_SiaClaymore_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140437/ClaymoreDual40_SiaClaymore_HashRate.txt)

**Comment by jeremiahtenbrink** [comment]
[2017-07-11_16-53-49.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140438/2017-07-11_16-53-49.txt)

**Comment by jeremiahtenbrink** [comment]
[1499813659_log.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140440/1499813659_log.txt)
[1499811206_log.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140442/1499811206_log.txt)

These logs are from ethash-claymore log above is from the main folder logs.

**Comment by aaronsace** [comment]
It's not running ClaymoreDual30 by the looks of it. Try the latest commits instead of the release; I think it's working well now.

**Comment by jeremiahtenbrink** [comment]
I've done a git pull inside of the multipool folder. But I will try a fresh download of it.

**Comment by jeremiahtenbrink** [comment]
why did my excavator one fail.

**Comment by jeremiahtenbrink** [comment]
[2017-07-11_17-58-17.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140527/2017-07-11_17-58-17.txt)

**Comment by jeremiahtenbrink** [comment]
[2017-07-11_17-16-55.txt](https://github.com/aaronsace/MultiPoolMiner/files/1140532/2017-07-11_17-16-55.txt)

**Comment by jeremiahtenbrink** [comment]
K, looks like it went past the benchmark now. Thanks very much. Also, where would be a good place for me to get some help regarding the failed miners.

**Comment by jeremiahtenbrink** [comment]
Alright, well I'm going to close this issue I guess. Hope that's ok with the devs.
