### ISSUE TITLE
Cast XMR updated to 1.6.5

### ISSUE THREAD

**Issue by Djago** [aaronsace/MultiPoolMiner#2258]
Cast XMR Version 1.6.5 (2018/11/27)
support for RX 590 GPUs added
fixes for detecting Compute Mode on Polaris based GPUs
support for CryptoNight-SuperFast (--algo=11) for mining Free Haven Protocol (XFH)
updated switch-radeon-gpu to version 1.2.0, which includes bugfixes for newer versions of the AMD Radeon drivers

**Comment by UselessGuru** [comment]
1.6.5 will be in the next Beta.

And here:
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/051f10e8a2b21af9e9a2b648a3fd5621118683d9
