### ISSUE TITLE
algo "groestl" in ccminer_x11gost is not supported

### ISSUE THREAD

**Issue by Jumaga2015** [aaronsace/MultiPoolMiner#226]
When you run ccminer from console with launch parameters, ccminer said Unknown algo parameter 'groestl'. 

CcminerGroestl.ps1

**Comment by aaronsace** [comment]
Please show the command line.

**Comment by Jumaga2015** [comment]
Bin\Groestl-NVIDIA\ccminer_x11gost.exe -a groestl -o stratum+tcp://hub.miningpoolhub.com:17004 -u                                               Jumaga2015.proto -p x

**Comment by aaronsace** [comment]
Apologies, should be 'sib' not 'groestl'. I'll amend this then I will probably upload as a release because I'm going to be away for 10 days.
