### ISSUE TITLE
ccminer Klaust 8.09 is available

### ISSUE THREAD

**Issue by leonyoung1** [aaronsace/MultiPoolMiner#228]
Just wanted to bring to your attention that ccminer Klaust 8.09 is available

**Comment by aaronsace** [comment]
Cheers @leonyoung1

**Comment by fonyo** [comment]
Cheers! I can confirm, I have updated my rigs with v8.09 and so far I haven't seen the notorious "stratum subscribe timed out" or "stratum recv_line failed" error messages that plagued ccminer klaust and prevented me from having good night sleep. Will report back if any of them reoccurs.

**Comment by fonyo** [comment]
Unfortunately, it does occur still but not as often as with the older versions.

**Comment by fonyo** [comment]
Update: I have been advised v8.10 should fix these errors specifically.

**Comment by fonyo** [comment]
8.10 did not fix the problem.

**Comment by aaronsace** [comment]
May have to drop this miner; it just doesn't work. If it did retry after 10 seconds then it would be alright but it does nothing; just sits there. I don't think it's any faster than tpruvot anyway.

**Comment by jakewarren81** [comment]
I'm still using 8.06 (for months) without any issues on either of my rigs.  I only mine on zpool though, so maybe this is specific to MPH?

**Comment by fonyo** [comment]
It could be a pool-side issue as was suggested by multiple posts on bitcointalk but MPH could not figure it out the cause and opened an issue as well on klaust's Github page. It could also be the users themselves with laggier connections (higher pings, too many users on the network, slower Internet etc) and then just klaust being intolerant to these brief dropouts. **I do have to mention it only happens for me when the miner is launched.** It recovers if connection is interrupted after the miner has been running for a while. Ccminer klaust for my 1070 and 1080 cards are miles faster than tpruvot so I don't want to let this one go that easily.

**Comment by fonyo** [comment]
Please post your (situational) findings and issues to klaust's Github page Here:
https://github.com/KlausT/ccminer/issues/36

**Comment by aaronsace** [comment]
I think the new version is working...?

**Comment by fonyo** [comment]
@aaronsace I have been testing v8.11 over a day on 2 rigs and the issue is not gone at all. It just displays the error in a different way. 

Eg. "gpu0 is waiting for data from pool"

First it was running fine for hours but then it started happening. Every error seems to be blaming the pool for either not responding or not providing data. I really start to think it is (also) a pool-side issue (as the info from the Internet suggests) but then how come tpruvot's ccminer is not plagued with these errors? I just cannot wrap my head around it.

**Comment by aaronsace** [comment]
Shame, it looked like it is was working. Don't understand why the pool connection would be different to tpruvot's either, surely the changes should just be on the algorithm itself.

**Comment by fonyo** [comment]
That's what I thought! It took me 30 tries today to finally get it going by restarting MPM. It only lasted around 30 minutes and I started struggling with it again. After considering loss of time in mining (+ my time messing with it) versus tpruvot's slightly lower hash with a few algorithms, I came to a conclusion of deleting the dang klaust miner file (still quite angry about it). Months of patience has reached its limits. I suggest anyone experiencing this to do the same.

**Comment by fonyo** [comment]
**I have just tested 8.13 and the issue seems to be fixed finally!**

**Comment by nemosminer** [comment]
8.14beta-cuda 9 is released, im seeing speed improvements on my 1060 and 1070 test rigs sadly 1080ti seems to still be faster with tpruvot 2.2 cuda 8.  im not getting any connection issues so far : 

https://github.com/KlausT/ccminer/releases/download/8.14beta/ccminer-814beta-x64-cuda9.zip

Regards
Nemo
