### ISSUE TITLE
Error When Adding Miners

### ISSUE THREAD

**Issue by bulldogman75** [aaronsace/MultiPoolMiner#229]
I have stock v2.4.3.5. When I try to add new miner *.ps1 files and run start.bat the cmd windows pops up a bunch of red errors like the following:

"'get algorithm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again"

This happens during benchmarking, but the errors go away and benchmarking is ongoing. Do I need to update/change anything else to do what I am trying to do? (Add Miners?) Just noticed "exavator.exe" in the error as well.

**Comment by aaronsace** [comment]
I think your mixing files from the old and new versions.

**Comment by bulldogman75** [comment]
Sorry, I am new. Didn't know if that would cause a problem. Should I be running v2.4.3.5? Is there any advantage to the pre-release? Do I need to update any files from the master? Thanks for the info.

**Comment by bulldogman75** [comment]
I am figuring it out.  No worries.

**Comment by fonyo** [comment]
I am closing this. Please create a new issue if you are still having problems.
