### ISSUE TITLE
interval for benchmarking

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#23]
There appears to be 1 interval setting, I've changed mine to 20min (1200sec) to even out coin flipping and spending most the time starting up miners and losing profit.
how ever this effect any requirement to re benchmark so ideally a 60sec hard coded benchmark interval with a separate interval for normally mining.

**Comment by aaronsace** [comment]
20 minutes is too high. It will rarely switch often after a few hours of initial running. 

Increasing the interval is to compensate for miners loading speed. Will look at adjusting the process flow and options.

**Comment by aaronsace** [comment]
Fixed a decimal precision issue on the price fluctuation detection which should help. 
Increased the benchmark accuracy so I've also reduced the delta and removed the boost. 

Will upload the code in the evening.
