### ISSUE TITLE
Invalid JSON primitive

### ISSUE THREAD

**Issue by Bazios** [aaronsace/MultiPoolMiner#24]
**********************
Windows PowerShell transcript start
Start time: 20161231114241
Username: COMP1\1
RunAs User: COMP1\1
Machine: COMP1 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Host Application: powershell -noexit -executionpolicy bypass -file .\multipoolminer.ps1 -username bazios -interval 60 -location europe
Process ID: 7084
PSVersion: 5.0.10586.117
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0.10586.117
BuildVersion: 10.0.10586.117
CLRVersion: 4.0.30319.34209
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2016-12-31_11-42-41.txt
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
No Pools!
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."

**Comment by aaronsace** [comment]
You downloaded the release zip file and haven't changed anything, correct? 

What files are in the pools folder?

**Comment by aaronsace** [comment]
If you are still having problems, let me know.

**Comment by Bazios** [comment]
problem solved after reboot
thank you

**Comment by Dangerous-Mind** [comment]
I got this error today on one of my rigs.

And the miner is acting very strangely. It restarts from time to time.
Other rigs are mining Monero as this but after some time it stops and restarts mining Monero.
And since this rig is a bit temperamental to mining restarts it freezes.
Waiting for the platform 2 fix so that I can make a clean install.

After restarting the application the "Invalid JSON primitive" disappeared.

**Comment by Dangerous-Mind** [comment]
The restart its not a problem created by the app.
