### ISSUE TITLE
incorrect version?

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#240]
I'm not sure which is the correct version... the one available for download says version 2.5.1.2, but it's in the folder for version 2.5.3.1.   was there a backtrack to version 2.5.1.2 because the versions after that had a fatal flaw?

**Comment by fonyo** [comment]
I was just about to test the new version and noticed the same. What is the fundamental flaw you are talking about?

**Comment by fonyo** [comment]
Closing this as this has been resolved.
