### ISSUE TITLE
ClaymoreDual with Sia does not terminate at benchmarking

### ISSUE THREAD

**Issue by DrRobotto** [aaronsace/MultiPoolMiner#243]
The program does not terminate the ClaymoreDual benchmarking even after some time.
![claymoredual](https://user-images.githubusercontent.com/20887855/28261712-a39cf388-6ae0-11e7-9912-eb960bb189e5.png)

**Comment by scaras** [comment]
delete the "ClamoreDualxx" files and use the claymore files used now. (ClaymoreSiaxx, ClaymoreDecredxx, ...)

the claymoredualxx is not used now ( no correct coding )

**Comment by DrRobotto** [comment]
So I did a clean install of the multipoolminer and now I haved none of the ClaymoreMiner in spite of they are listed before the benchmark ...

**Comment by aaronsace** [comment]
Sorry but this screenshot is not correct. Please download the latest release and post a screenshot and log file. 

https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.5.3.3/MultiPoolMinerV2.5.3.3.zip

**Comment by fonyo** [comment]
If you are mixing the new miner files with the old ones (and therefore creating duplicate hashrate stat references) this exact issue will happen and you will see benchmarking stats finished for one of the dual mined coins and still "benchmarking" on the other one and benchmarking will be stuck entirely.

**Comment by DrRobotto** [comment]
I tried to download the newest release and did a fresh install. However, I just see ClaymoreDual Decred whereas NicehashLegacy Miner shows all the algorithms and runs on DaggerPascal and DaggerLbry with ClaymoreDual. Nevertheless, I would prefer to mine on multipool. 

All the other algorithms are stuck at the idle section without any benchmark being made.

**Comment by DrRobotto** [comment]
Here is an actual screenshot after a new start, where the other Claymore algorithms disappeared:
![claymoredual](https://user-images.githubusercontent.com/20887855/28306816-1b551dd6-6ba1-11e7-9e0e-324edfe7dbda.png)

**Comment by DrRobotto** [comment]
So after a new clean start
![claymoredualbefor](https://user-images.githubusercontent.com/20887855/28308534-c3c97afc-6ba6-11e7-95c1-4aaae0b7eb3e.png)


and after some benchmarking
![dualbefore](https://user-images.githubusercontent.com/20887855/28308548-cc9e716e-6ba6-11e7-8a7e-81e6879faaa7.png)

and right after all the algorithms disappear
![claymoredual](https://user-images.githubusercontent.com/20887855/28308564-e1fee520-6ba6-11e7-9dc0-cfea7c33a896.png)
