### ISSUE TITLE
Does benchmarking take into account dev fees?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#246]
I'm wondering if the benchmark feature takes into account the 1% or 2% dev fee for claymore or whatever dev fee exists for any other miner. If it doesn't, then its estimated profits report could be improved and it may switch to and from ETH more intelligently.

I'm also wondering if the dev fee days for the multipoolmining program itself is factored in to the estimated daily profits. If not, then the profitability line stating that "multipoolminer is x% more profitable" is not correct.

**Comment by scaras** [comment]
that 1 or 2 % change (and even more) can also happen during confirming the blocks, transfer the coin, what exchange you use, heat/power throthling, ... crypto coins can easely go up or down +20% in a few minutes, so as long as it is not changed to $, €, BTC, ...

**Comment by mjmeans** [comment]
Yes. but those are unknown factors. The 1% dev fee on claymore mining ETH only is known. Known factors should always be applied.

**Comment by aaronsace** [comment]
Fees are small but I will add fees and power costs.

**Comment by mjmeans** [comment]
Thanks. It could be possible for sgminer or some other miner to come close to claymore in the benchmark. If it happens to be within 1%, then the claymore will actually be net worse because if it's fee and the other miner should be used.

I don't think power costs as you will not know, from algo to algo, how much power is being consumed. And because the GPU power usage reported by each card is not a very good indicator of actual power usage for the rig unless you also know the power supply efficiency and mobo power usage. Plus power supply efficiency is also variable with power load and age of the power supply. So power costs factors are problematic at best.

**Comment by aaronsace** [comment]
I understand but it would not normally switch for just 1% better profit; it would have to be a larger difference. 

Power costs are comparable which is all that's required.

**Comment by scaras** [comment]
max powercosts are simple to calculate. just take a look to how powerfull your psu is... 
that would be the max w/h of your TOTAL mining rig (so also power for fans, leds, cpu, keyboard, ...)

**Comment by fonyo** [comment]
It is not ideal to get the power consumption from the size of the psu. Not every PSU is used at 100% power output. If you happen to max out an 1200W gold or titanium PSU, that would actually consume more than 1300W at the wall. There are other cases where people have much larger PSUs than what they actually need. That would also be misleading for the calculation. The best way is manually entering the total consumption from whattomine, however, that is also different for each algo.
