### ISSUE TITLE
New release after 3 months

### ISSUE THREAD

**Issue by m-bosch** [aaronsace/MultiPoolMiner#2467]
Hi @aaronsace,

When will the  new release be launched? Its for 3 months now and the latest version isnt even working. Its time to release a new version. I think many people already switched to alternatives including me, i am still looking to see if there are updates coming to come back to MPM

**Comment by aaronsace** [comment]
Me and Nemos published a working release 7 days ago: 
https://github.com/MultiPoolMiner/MultiPoolMiner/tags
