### ISSUE TITLE
3.5.5.1 benchmarking issues

### ISSUE THREAD

**Issue by m-bosch** [aaronsace/MultiPoolMiner#2468]
I directly downloaded the 3.5.5.1 version after the previous issue, while benchmarking directly the first benchmark gave the following issue:

`2020-02-16 21:04:11 ERROR: Miner (CcminerZenemy-v2.4-3xGeForceGTX10708GB {X16R@ZergPool-Algo}) was stopped because MPM could not retrieve hash rate information from the miner API within 60 seconds. `

`PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "Kan geen verbinding maken omdat de doelcomputer de verbinding actief heeft geweigerd 127.0.0.1:4001""`

**Comment by aaronsace** [comment]
When a miner fails, it goes to the next miner; is that not happening?

**Comment by m-bosch** [comment]
it does, but it fails too, after 30 minutes i aint got a single benchmark succesful

**Comment by aaronsace** [comment]
Are you running everything with the default config? i.e. just clicking 'start.bat'

**Comment by m-bosch** [comment]
No i copied the config from a previous working version.

**Comment by aaronsace** [comment]
Run a fresh release download with the default config and check if it's working. 
If that is working then we can check your configuration.

**Comment by m-bosch** [comment]
{
  "Algorithm": "$Algorithm",
  "API_ID": "$API_ID",
  "API_Key": "$API_Key",
  "CoinName": "$CoinName",
  "CreateMinerInstancePerDeviceModel": "$CreateMinerInstancePerDeviceModel",
  "Currency": ["EUR", "BTC"],
  "Delay": "5",
  "DeviceName": "$DeviceName",
  "SingleAlgoMining": false,
  "Donate": "10",
  "ExcludeAlgorithm": [
  "cuckaroo31",
  "ethash2gb",
  "ethash3gb",
  "sha256",
  "scrypt",
  ],
  "ExcludeCoinName": "$ExcludeCoinName",
  "ExcludeDeviceName": "$ExcludeDeviceName",
  "ExcludeMinerName": [],
  "ExcludeMiningCurrency": "$ExcludeMiningCurrency",
  "ExcludePoolName": [
    "yiimp",
    "zpool",
    "zpoolcoins"
  ],
  "IgnoreFees": false,
  "Interval": "120",
  "MinerName": "$MinerName",
  "MinerStatusKey": "key",
  "MinerStatusUrl": "https://api.brucomining.com/v1.0/workers/reportMPM",
  "MiningCurrency": "$MiningCurrency",
  "NoExcavatorLogs": true,
  "PoolName": [
    "NiceHash",
    "NLPool",
    "BlazePool",
	"MiningPoolHub",
    "MiningPoolHub-Algo",
	"MiningPoolHub-Coin",
	"Blockmasters",
	"Zergpool"
  ],
  "PricePenaltyFactor": "$PricePenaltyFactor",
  "Proxy": "$Proxy",
  "RemoteAPI": "$RemoteAPI",
  "ShowMinerWindow": false,
 
  "SSL": false,
  "SwitchingPrevention": "2",
  "UseDeviceNameForStatsFileNaming": true,
 
  "UserName": "baron1898",
  "Watchdog": "$Watchdog",
  "WorkerName": "miner1",
  "Pools": {
    "NiceHash": {
      "Worker": "miner1",
      "Wallets": {
        "BTC": "btcaddress"
      },
      "IsInternalWallet": true,
	  "PricePenaltyFactor": 0.9
    },
    "NLPool": {
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1"
    },
	 "MiningPoolHub": {
      "API_Key": "key",
      "Username": "baron1898",
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1"
    },
    "MiningPoolHub-Algo": {
      "API_Key": "key",
      "Username": "baron1898",
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1"
    },
	"MiningPoolHub-Coin": {
      "API_Key": "key",
      "Username": "baron1898",
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1"
    },
    "BlazePool": {
      "Wallets": {
        "BTC": "btcaddress"
      },
      "Worker": "miner1"
    },
	"Blockmasters": {
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1",
	  "PricePenaltyFactor": 0.50
	  
    },
	"Zergpool": {
      "Wallets": {
        "LTC": "ltcaddress"
      },
      "Worker": "miner1",
	  "PricePenaltyFactor": 0.85
	  
    }
  },
  "Miners": {},
  "Wallets": {
    "LTC": "ltcaddress",
    "BTC": "btcaddress"
  },
  "PoolBalancesUpdateInterval": "15",
  "MeasurePowerUsage": false,
  "PowerPrices": "$PowerPrices",
  "ShowPowerUsage": "$ShowPowerUsage",
  "BasePowerUsage": "$BasePowerUsage",
  "IgnorePowerCost": true,
  "ProfitabilityThreshold": "$ProfitabilityThreshold",
  "HashRateSamplesPerInterval": "$HashRateSamplesPerInterval",
  "WarmupTime": "$WarmupTime",
  "HWiNFO64_SensorMapping": "$HWiNFO64_SensorMapping",
  "MinPoolWorkers": "$MinPoolWorkers",
  "AllowedBadShareRatio": "$AllowedBadShareRatio",
  "APIPort": "$APIPort",
  "VerboseOutput": "$VerboseOutput",
  "HashRateSamplesPerMinute": "$HashRateSamplesPerMinute",
  "BenchmarkInterval": "$BenchmarkInterval",
  "MinHashRateSamples": "$MinHashRateSamples",
  "MinWorker": "$MinWorker",
  "ShowAllMiners" : false,
  "VersionCompatibility": "3.3.0",
  "Region": "Europe"
}

**Comment by m-bosch** [comment]
Sorry copied the config here, i will recheck tonight with fresh

**Comment by m-bosch** [comment]
just ran with complete new install,  same problem, from 20 to 19 to 18 benchmarks to go, but zero benchmarked in the list, so every benchmark is on the removed list....

**Comment by aaronsace** [comment]
I've just downloaded the release and seems to be running fine; about half way through benchmarking. 

Maybe check that there are no issues on your system. 

Check that you have the latest PowerShell: https://github.com/PowerShell/PowerShell/releases/latest
Check that you have the latest version on Windows 10. 
Make sure that you don't have any 3rd party virus checkers or firewalls installed. 
Make sure that you are you are using an admin account. 
Make sure that you are running from a location that is not protected i.e. `C:\MultiPoolMiner`
Make sure that MultiPoolMiner has added firewall exceptions to Windows Defender. 
Make sure that all the files in the MultiPoolMiner folder were successfully unblocked. 

Plus, if there is anything else you can think of that would effect it...

**Comment by m-bosch** [comment]
Hi Aaron,

Thanks for the response, Is there a guideline for making the firewall exceptions? that part is the only part the i cant answer with "checked and correct"
