### ISSUE TITLE
miningpoolhub job setting?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#248]
Does the miningpoolhub account default job setting or miner job setting need to be specified? i.e. if it is set to ethash, equihash, but MPM is started with "cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia" then what takes precedence?

**Comment by aaronsace** [comment]
MultiPoolMiner has no relation to the MiningPoolHub worker settings; they are completely separate.
