### ISSUE TITLE
Project resurrection

### ISSUE THREAD

**Issue by mwodzynski** [aaronsace/MultiPoolMiner#2483]
This is the time to resurrect this project. After ETH merge you can be very popular again. I hope to see you back at it.

**Comment by grantemsley** [comment]
I don't see that happening. Pretty sure everyone who worked on it has moved on.

There is still [NemosMiner](https://github.com/Minerx117/NemosMiner) which is based on several the same original code but has been getting regular updates and improvements.

**Comment by GoZippy** [comment]
I am sad to see this dead - followed for a long time... I am setting up a new poolfor friends and would like to distribute a multi pool miner with our pools all added by default so it is super easy for people to download and start running
Any ideas on projects I can support that would be a good base for this purpose?

**Comment by Demon4u** [comment]
https://github.com/Demon4u/Nvidia-RTX-LHR-Unlocker
