### ISSUE TITLE
EWBF CUDA Zcash Miner

### ISSUE THREAD

**Issue by snakethejake81** [aaronsace/MultiPoolMiner#25]
I tried adding this miner with a JSON file, but it doesn't have an API to pull stats and doesn't even log to a file to pull the hashing data from.  It only displays in the console window.  Would be nice to integrate this as it give 200 sol/s on a GTX 970 and even more on new cards.  I was thinking it may be possible to capture and parse the console window output, or pipe it out to a file to parse; but I'm not quite up to the task in powershell.

https://bitcointalk.org/index.php?topic=1707546.0

**Comment by aaronsace** [comment]
I have posted on that forum regarding an API but it's full of bull**** rants. 

I'll send you a JSON file to do it manually in a few minutes. 

I will probably have to try and parse it if no API is planned and add it to the next version.

**Comment by aaronsace** [comment]
Just enter your hash rate in this file (it's currently set to zero) then put it in the 'miners' folder. 
[EWBF.txt](https://github.com/aaronsace/MultiPoolMiner/files/680236/EWBF.txt)

**Comment by snakethejake81** [comment]
Excellent, much appreciated.

**Comment by aaronsace** [comment]
Please can you put this file next to 'miner.exe' then right click and run it. 
After 2 minutes, there will be a log called 'test.txt'; please can you send it to me? 
[test.zip](https://github.com/aaronsace/MultiPoolMiner/files/686166/test.zip)

**Comment by snakethejake81** [comment]
I will give it a try tonight and post the results.

**Comment by snakethejake81** [comment]
[test.txt](https://github.com/aaronsace/MultiPoolMiner/files/688925/test.txt)

**Comment by aaronsace** [comment]
It's blank... try this: 
[test2.zip](https://github.com/aaronsace/MultiPoolMiner/files/690800/test2.zip)

**Comment by snakethejake81** [comment]
Turned out the same.  Tried a few different things but it doesn't seem to be outputting via the StandardOutput.

**Comment by aaronsace** [comment]
I'm confused; it works at my end. Is it not launching the miner...? Check task manager.

**Comment by snakethejake81** [comment]
It launched it, but the counter showed a zero then never progressed.  Just hung.  The miner was running.  I can try it again tonight.

Jake Warren

________________________________

**Comment by aaronsace** [comment]
Try this one: 
[test3.zip](https://github.com/aaronsace/MultiPoolMiner/files/692365/test3.zip)

**Comment by aaronsace** [comment]
Please check what I've wrote here is correct: 
https://bitcointalk.org/index.php?topic=1707546.msg17444916#msg17444916

**Comment by lyolyalya** [comment]
that's correct.
where do i need to paste it?

**Comment by aaronsace** [comment]
PowerShell

**Comment by aaronsace** [comment]
I'd appreciate it if you try to get the issue some attention. Thanks.

**Comment by lyolyalya** [comment]
ah=)understood.it is same script or you change something?
i was thinkig about testing on 660 ti, then v0.10.0 maybe.any way wanna capture this for you to understand what's going on.

**Comment by aaronsace** [comment]
I just changed the path to 'c:\ewbf' and typed out how you wrote the commands. 
If could post screenshots on the forum then that may help. 

I found a general fix/hack that may mitigate the issue. Will try implementing it after work if there is no response there.

**Comment by aaronsace** [comment]
Got a response from EWBF. Try adding '--boff' to the command line arguments.

**Comment by lyolyalya** [comment]
damn!=)i'm just done screen capture=)it's working now=)
![image](https://cloud.githubusercontent.com/assets/16507768/21771164/efc8d402-d68e-11e6-9f15-a8409f273617.png)

**Comment by aaronsace** [comment]
Amazing! That's one problem down. 
Thanks for the time that you've put into testing this; worth it in the end. :)

**Comment by lyolyalya** [comment]
be my guest=)

**Comment by aaronsace** [comment]
lyolyalya, is ccminer working on your machine?

**Comment by lyolyalya** [comment]
ccminer is passed all bencmarks in v2 with your help in here - 
https://github.com/aaronsace/MultiPoolMiner/issues/11
now i use v1.3=)
so they need to follow my steps i guess=)i try fresh version today and see what's new=)
