### ISSUE TITLE
TPruvot 2.1 pre TRIBUS algo

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#251]
https://github.com/tpruvot/ccminer/releases/download/v2.1-tpruvot/ccminer-2.1-tribus.7z

**Comment by papampi** [comment]
Tpruvot 2.2 is out now.

**Comment by AcharyaOne** [comment]
Cuda 9!
v2.2.1 Windows CUDA 9 RC "test" binaries
@tpruvot tpruvot released this 2 days ago

Intermediate release with tribus improvements, with a cuda 9 (rc) binary

Require a nvidia driver 384.xx or more recent
