### ISSUE TITLE
BTC/GH/Day * MH/s * s/Day <> reported BTC/Day

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#252]
Example MPM shows:
Speed = 82.07 MH/s
BTC/Day = 0.00202
BTC/GH/Day = 0.02458

There are 84,600 seconds per day. So 82.07 MH/s * 84,600 s/Day / 1,000 MH/GH = 7.090848 GH/Day.

And 7.090848 GH/Day * 0.02458 BTC/GH/Day = 0.1743 BTC/Day.  NOT 0.00202 BTC/Day.

Of course the real BTC/Day earned at 82.07 MH/s is closer to what MPM shows, but the displayed units and values are wrong and the math doesn't work.

**Comment by aaronsace** [comment]
I'm not sure what you are trying to do with that calculation. 

This is the two pieces of information then the calculation: 

Speed = 0.08207 GH/s
BTC/GH/Day = 0.02458
BTC/Day = 0.08207*0.02458 = **0.0020172806**

Here is a base reference: 

This is the two pieces of information then the calculation: 

Speed = 1 GH/s
BTC/GH/Day = 0.02458
BTC/Day = 1*0.02458 = **0.02458**

**Comment by mjmeans** [comment]
No.. Bad math. Check your algebraic units. Multiplying x GH/s times y BTC/GH/Day produces z (MH*BTC)/(GH/Day)*s, which is not equivalent to BTC/Day. Units must be converted.

A rate of 1 MH/s (mega hash per second) is 60 MH/min or 3,600 MH/hour or 86,400 MH/Day. Which is 86.4 GH/Day. Thus:
`    f(x)(GH/Day) = x(MH/s) * 84,600(s/Day) / 1000(MH/GH)`
In the above formula, "s" and "MH" units cancel out, leaving GH/Day.

And to get BTC/Day from MH/s and BTC/GH/Day units you need to:

`    f(x)(GH/Day) = x(MH/s) * 84,600(s/Day) / 1000(MH/GH)`
`    f(y)(BTC/Day) = y(BTC/GH/Day) / f(x)(GH/Day)`

Or to simplify:
`   z = y / (x * 84600 / 1000)`
` where x = MH/s, y = BTC/GH/Day, z = BTC/Day`

The only way your calculation could result in expected BTC/Day is if the reported rate from miningpoolhub of BTC/GH/Day is actually BTC/(GH/s)/Day. Because GH (a quantity) is not equal to GH/s (a rate of change).

**Comment by aaronsace** [comment]
Man, you're way over think this. BTC/GH/Day is simply how much you get paid in a day if you were mining at 1GH/s.

**Comment by mjmeans** [comment]
I see. Then the term "BTC/GH/Day" in common use is really a lie (or at best imprecise) and actually refers to "BTC/(GH/s)/DAY". Is that right?

**Comment by nemosminer** [comment]
mjmeans = NOOB

**Comment by aaronsace** [comment]
@mjmeans Yes, I think you are technically correct about the name but the usage is common and quite obvious.

**Comment by mjmeans** [comment]
@nemosminer FO. An assumption about units of measure caused the Mars Climate Orbiter to crash. In any formula proper units are always specific and important.

**Comment by nemosminer** [comment]
you believe we went to space and sent orbiter to mars.... = NOOB

**Comment by mjmeans** [comment]
plonk
