### ISSUE TITLE
error when downloading nicehash/excvator

### ISSUE THREAD

**Issue by learningplenty** [aaronsace/MultiPoolMiner#254]
continuously notified of error when downloading nicehash excavator.
I guess the path in the powershell script is wrong - but what should the correct path be?
currently it is set as

$Path = ".\Bin\Excavator\excavator.exe"
$Uri = "https://github.com/nicehash/excavator/releases/"

**Comment by aaronsace** [comment]
You have to do it yourself as part of their agreement of usage.
