### ISSUE TITLE
Sometimes creates multiple miner windows

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#255]
Sometimes MPM will create a miner window that fails in some way but doesn't end. (Like when DAG fails to load and the miner just stops without ending). If the miner has the mutex for the GPU then that miner will block all other miners from accessing those GPUs. MPM creates a new miner window which will them automatically fail to access the GPU's the original miner has accessed but may also fail to automatically close.

But I have noticed that sometimes when there is a hang like this, MPM will have opened three or four miner windows, all of the failing to mine anything. To recover, you have to manually close all open miner windows and then MPM will create a new miner window that will start mining.

I have a feeling that this has something to do with releasing the GPU mutex when MPM switches from one miner to another and maybe MPM isn't waiting long enough for the previous miner to completely release it's resources. I haven't tracked from which miner and to which miner this is happening.

This is happening on my test PC with an AMD processor PC with 2 cores, 8GB RAM, 16GB page file, and 2 RX480-8G, 1 RX570-4G.

**Comment by aaronsace** [comment]
I found that was happening with Claymore miners sometimes so I got them to kill themselves if there was an error by using his '-r -1' command line option option. Are there any other miners doing this? I have run it a few times without issue now.

**Comment by mjmeans** [comment]
I'm sorry. I didn't check to see which miners were open or which was the first or which was the previous closed. I'm just not watching it that closely. But I do know that when it is running it beats AwesomeMiner hands down.

**Comment by aaronsace** [comment]
No worries, I'll close it unless you see it happening again. It should be impossible as I store the process ID and check if it is running. AwesomeMiner is a cool idea; I could happily waste months building interfaces in C# and having perfectly formatted classes but it's just not worth it and doesn't add any value.

**Comment by mjmeans** [comment]
The biggest problem with AwesomeMiner is that it doesn't benchmark. So with cards that are mod+OC for max performance on one crypto, you have to manually test and record the performances (a huge PITA)  and dual performance ETH+decred/sia/whatever takes a huge hit. The thing I like about AM is the flexibility to adjust the pools and coins per GPU. But without the benchmarking with real world current difficulties with each crypto, you get terrible performance. They added all this flexibility and forgot the most important factor: your rig's actual performance under live conditions. The benchmarking and periodic updating of the current hash rates is the best part of MPM. I just wish that those cryptos that haven't been mined in a few days to a week would automatically get re-benchmarked since difficulties may have changed, and since the rig owner may have changed the OC slightly but not enough to want to spend time re-benchmark all miners.
