### ISSUE TITLE
Suggestion about benchmarking

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#256]
So here's the scenario: hub.miningpoolhub.com:17020 autoswitch port mines 4 different ethash coins. Each coin is at a different DAG and difficulty, and that affects the hash rate result. Benchmarking on the auto switch port will be done on whichever coin happens to be being mined at the time which may be the worst effective has rate at that time. This can introduce a worst case error on the order of 15-20% in the calculated btc/day for ethash if it happened to benchmark the autoswitching pool when it was mining the lowest hash coin. I think MPM could do much better if it benchmarked each miner<->coin combination, and then mined on the 20xxx ports instead of relying on the 17xxx auto switch ports.

**Comment by aaronsace** [comment]
It supports 20xxx ports by using "-poolname miningpoolhubcoins"

I have added a 2gb variant of Ethash but any more would not currently be feasible. I will need to support something like algorithm sub-names or miner variants to reduce the amount of claymore settings.

**Comment by fonyo** [comment]
Unless there is a significant difference between DAG numbers (eg. 10+), this should not be an issue as the difference will be close to negligible. Difficulty does not count here at all as pool will scale the work difficulty to match the miner's hashrate (of course, unless there is an error on the pool's side such as the way too high diff share issue last week).
