### ISSUE TITLE
No miners! Error

### ISSUE THREAD

**Issue by Nebiforever** [aaronsace/MultiPoolMiner#258]
Hello there, i've been trying for hours to solve this but i think i've gone nuts. Porbably i'm missing a very small point here but what's wrong with my bat file ?

i've also tried with  -command "&.\MultiPoolMiner.ps1 
it gives the same error.

any help is appriciated. thx

> **********************
Windows PowerShell transcript start
Start time: 20170805174008
Username: RIG1\Tahta
RunAs User: RIG1\Tahta
Machine: RIG1 (Microsoft Windows NT 10.0.15063.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command C:\Users\Tahta\Desktop\MPM\MultiPoolMiner.ps1 -username nebiforever -workername 1 -interval 60 -location europe -ssl -type nvidia -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,usd -donate 10
Process ID: 772
PSVersion: 5.1.15063.483
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.483
BuildVersion: 10.0.15063.483
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-08-05_17-40-08.txt
No Miners!

>

**Comment by aaronsace** [comment]
First check if there is anything in the 'Miners' folder. 
Then check if there is anything in the 'Bin' folder. 

Please download if you are missing anything: 
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by Nebiforever** [comment]
Thank you for fast response. Both miners and bin folders are ok. i even deleted some of the unnecessary  algorithms from miners folder. excavator and other dlls are ok too. 

the thing is, the script runs if run it directly and enter my username. benchmarks are running and i even see the coins in my dashboard in miningpoolhub interface. 

but it gives error when i try to run it over the bat file

**Comment by Nebiforever** [comment]
Still need some help pls

**Comment by Nebiforever** [comment]
some more interesting information is, after benchmarks complate, now the script is running normally, doing profit switches etc. 

but it runs in powershell mode (blue screen) and i still need to enter my username everytime i start it.

**Comment by Nebiforever** [comment]
So, no one has any clue of the reoson about this nonsense problem ? :)
interesting. i will continue to manually start the script for now. hope something changes in next update

**Comment by aaronsace** [comment]
Have you tried just downloading the release and double clicking the 'start' file? 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.5.3.4.1/MultiPoolMinerV2.5.3.4.1.zip

**Comment by Nebiforever** [comment]
update !
i started the bat file without touching anything, it started benchmarks with cpu/amd (no nvidia algortims) algoritms. intersting thoughi because if i start the script manually, it tries to benchmark all algoritms (nvidia/amd/cpu)

but my system is nvidia so i deleted the amd and cpu commands from bat file and only left nvidia. 
Bam! , "no miners" error again. when i only leave amd there, batch file starts to work again with amd algortim benchmarks. guess we are getting somewhere :)

**Comment by Nebiforever** [comment]
you know what ? i've found the solution. i needed to write "NVIDIA" not "nvidia" dont know why but i gues it is because of the system language settings (not english). some how the powershell wasnt able to read "nvidia" if it's typed in lower-case letter.

thanks for the support :)

**Comment by aaronsace** [comment]
How strange; I will have a check over that.

**Comment by Nebiforever** [comment]
Yea sounds odd. But i'm happy to resolve it :)
Btw before closing the topic i have another question about miner;

i started the batch fresh and added the algortims one by one to the batch file and made the interval time 120 seconds for the benchmark. Because some of the algoritms takes time to speed up and some times the script tries to start 2 miners at the same time and results zere hash speed or low hash speeds. With this i got accurate benchmarking results.

But some miners refuse to start and i solved the problem with copying the bin files from the previous folders (which is downdloaded when i was manually running the script before i solve the lower-case letter problem). they are all same files (even the file sizes are same to the byte) but when i replace them, the new script can start the miner. Can you think of any reason for this ?

The most important thing about this miner is to have accurate benchmarks to have the most profit.  does the miner do the benchmarks accurate normally ? or is it only me? because whenever i let the miner do the benchmarks on its own, half of the agoritms eighter does not show up (because of zero hash) or show wrong speed.

**Comment by aaronsace** [comment]
Sorry, I'm not getting any problems; I've run it a few times with CPU, AMD and NVidia. 

It can't store inaccurate benchmarks as it takes 6 readings. If they are fluctuating then it will wait another 60 seconds. I've run it a few times with all three (CPU, AMD and NVidia). 

All I can think is that you have a really slow hard drive and/or cpu.

**Comment by Nebiforever** [comment]
you let the script run all the algorithms in one batch with in 60 secs interval time and get the accurate results ? hmm sounds good. maybe you fine tune the ps1 files for which miner will run which algorithm before starting the benchmark and avoid the confusion for the script. 

i am getting used to script and probably after these ps1 file edits i've done (disabled/swapped the miners that have problems with my system) if i reset the benchmark it may complate it accurately in one run.

my rig has an ssd and G4560 cpu, i dont think those are the problems 👍 

any guess for the miners run after coppying files from the previous downloads (complate another folder whcih seperately run the script before) ?

**Comment by aaronsace** [comment]
Is it having problems download and extracting the miners? Is the 'bin' folder you are copping contain the same files?

**Comment by Nebiforever** [comment]
no dowload and extracts are okey. both folders have the same files and all the files are in exact size (even exact byte)

**Comment by aaronsace** [comment]
Sounds like everything is working as it should. I can't think what would be stopping the files running.

**Comment by aaronsace** [comment]
I do run this when the script first runs to unblock files downloaded of the internet but files downloaded by PowerShell shouldn't be effected: 

`Get-ChildItem . -Recurse | Unblock-File`

**Comment by Nebiforever** [comment]
hmmm will keep in mind if i need to run fresh script. 

at least now my batch works and i'm looking against a black background instead of blue :)

your script is piece of art, with all these variations and algoritms running around it's working like charm. Just needs some care and manual edit at the beggining and rest is being handled great. 

again thank you for all support and this miner 👍

**Comment by scaras** [comment]
having dutsh as native lang. and also using amd and nvidia in one system i ran into this problem once now i think about it.
i was just thinking it has to be in uppercase letters so didn't look at it as a bug (cuz CPU and AMD is used)
