### ISSUE TITLE
Only mines on Zpool when donation is active

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#259]
mpm mines on Zpool only when donation is active, otherwise it mines on miningpoolhub only when donation is not active.

**Comment by aaronsace** [comment]
They donation code is very simple and isolated. 

Have you entered your BTC wallet?

**Comment by alucard20724** [comment]
yes...i've entered my wallet.  

but zpool only comes active during donate time.. i.e. "-donate 10" in the startup.bat file

the only work around to keep zpool active is to do "-donate 1440"

**Comment by aaronsace** [comment]
Please post the full command line that you are using.

**Comment by alucard20724** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -command "&.\multipoolminer.ps1 -username myminer -workername myworker -interval 60 -location us -ssl -type amd -poolname miningpoolhub -currency btc,usd -donate 1400"

**Comment by aaronsace** [comment]
You haven't entered your wallet?

**Comment by alucard20724** [comment]
i've entered it in the multipoolminer.ps1

**Comment by alucard20724** [comment]
i'm using version 2.5.3.4.1

**Comment by aaronsace** [comment]
It goes in the command line 

powershell -version 5.0 -noexit -executionpolicy bypass -command "&.\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -username myminer -workername myworker -interval 60 -location us -ssl -type amd -poolname miningpoolhub -currency btc,usd -donate 1400"

**Comment by alucard20724** [comment]
aye... put it in the command line.. now works .. it wasn't in a released version so i wasn't sure... thanks

**Comment by aaronsace** [comment]
No worries.
