### ISSUE TITLE
CPU compatibilty

### ISSUE THREAD

**Issue by PollacoMan** [aaronsace/MultiPoolMiner#26]
I dl and unzipped the multipoolminer v2.2.2 unto windows 7 64-bit.  My CPU is an old 2 core Celeron but i have a GTX750ti gpu.  When i ran the start.bat i got a bunch of red letters stating environment error.  A friend of mine suggested it might be due to the old CPU cuz it all went well in his intel i7.   

So i know the zip works, just not in my computer.  Is there a compatibility issue?  Any plans on fixing it if that is the case?  Thanx for your attention.

**Comment by aaronsace** [comment]
Please can you show me the log file?

**Comment by PollacoMan** [comment]
Sorry but im not exactly sure where can i find that. :(  I looke in all the folders inside Multipoolminer but i dont find any log.txt file

**Comment by aaronsace** [comment]
There should be a folder called 'logs'.

**Comment by PollacoMan** [comment]
i have a screen cap 
![multiminer giving shit](https://cloud.githubusercontent.com/assets/24883206/21597602/ca7475d4-d112-11e6-8a04-f7a7b91ee6e0.JPG)

Hope that is of any help. There is no logs folder :(

**Comment by aaronsace** [comment]
What's in the 'bin' folder?

**Comment by PollacoMan** [comment]
Inside "bin" folder there is a folder named "claymore".  Within that folder 3 more folder: Cryptonight, equihash and ethash

**Comment by aaronsace** [comment]
If there is no 'logs' folder and there is only 'claymore' in the 'bin' folder then your computer is blocking it access.

**Comment by aaronsace** [comment]
Try running this command in PowerShell: 
`Set-ExecutionPolicy -Scope Process Bypass `

**Comment by aaronsace** [comment]
If that doesn't work, check you have PowerShell version 5: 
https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by aaronsace** [comment]
Let me know the outcome either way.

**Comment by PollacoMan** [comment]
i tried the powershell and i was asked yes or no.  i answered yes and retried the program.  Same thing happended.  and still no log folder. Im gonna dowload and install that and recheck

**Comment by PollacoMan** [comment]
is this program compatible with old celeron? i dont understand why am i having this problem and my friend is not.

**Comment by aaronsace** [comment]
Yes, you haven't even started mining yet.

**Comment by PollacoMan** [comment]
yes, correct, i have done nothing but clicking start.bat and gotten problems.  and i dont know why i get those problems.   I will download the Framework 5 and try again.  Thx

**Comment by aaronsace** [comment]
Has your friend got windows 10?

**Comment by PollacoMan** [comment]
yes, correct, just confirmed Win 10 computer.  Im installing and updating the framework right now.

**Comment by PollacoMan** [comment]
It keeps going and periodically showint the ccminer error over and over, but when i click OK. the program keeps going.  Is this benchmarking process going to end eventually?

**Comment by aaronsace** [comment]
My program is working now which is great (I'll add this on to the notes on the release page). 

The issue now is with ccminer, not me ;)
'MSVCR120.ddl' is common in many programs. You are missing the c++ runtime.

**Comment by aaronsace** [comment]
Try this: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

**Comment by PollacoMan** [comment]
yes, your program is working fine now.  I just copy/pasted theMSVCR120.ddl file from my ccminer 1.8.3 into the Nvidia and Nanashi folder inside Binfolder.  Everything seems to be going well now. You can add that trick as well my friend.

**Comment by aaronsace** [comment]
Neat trick! I may add that file so others don't have the same issue. 
Glad you got it sorted!

**Comment by PollacoMan** [comment]
Do you have a readme or a site with futther help?  The program is still going and im not sure what to do now?  Should i wait?

**Comment by aaronsace** [comment]
You can just leave it; it is mining from the start. Once all the miners that say benchmarking have gone from the screen, it will be mining the most profitable. 

You can add more pools and miners; it supports JSON or PS1. Best just copying the files that are there as a reference if you are going to do that. What are you wanting to add by the way?

**Comment by aaronsace** [comment]
Just done a minor release (V2.2.3). It helps the miner selection.
