### ISSUE TITLE
NiceHash pool support? "enhancement"

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#260]
is there a chance of getting NiceHash as one of the pools for mpm?

nicehash is a bunch of jerks, but their profitable coins are based off of user demand and not exchange rate.

**Comment by jakewarren81** [comment]
I've been working on a pool file for it in a separate fork, you can try it out; just drop this file in your Pools folder:

https://github.com/jakewarren81/MultiPoolMiner/blob/master/Pools/Nicehash.ps1

It has some issues recognizing all algos since nicehash names them slightly different.  But the major ones seem to work.

I use it as a backup for zpool for now.

**Comment by alucard20724** [comment]
thanks.. it works.. i just need to fiddle with the miner code now so it doesn't over write my zpool benchmarks.. which it's currently doing.. \(-_-)/

but it works.. thanks

**Comment by alucard20724** [comment]
how do you put it as a backup for zpool?   i just put the nicehash.ps1 file in the pool folder, but it seems to override any algorythms in common with zpool.    anything for miningpoolhub stays untouched.  miningpoolhub.ps1 is what i have in my start.bat file.

**Comment by jakewarren81** [comment]
When I say as a backup I meant its usually lower profit than zpool, but if zpool doesn't connect, nicehash is the only one left in the list.

It doesn't overwrite anything.  If nicehash is a higher calculated profit for a particular algo than the other pools you have enabled, it will show up on the list instead.

**Comment by aaronsace** [comment]
Maybe. 

It's funny, the original script was adapted from work I had done with the NiceHash API.

**Comment by scaras** [comment]
what file do i need to edit for dagger running to nicehash (if more profit)?
i occasionaly use nicehash for hashpower.

**Comment by aaronsace** [comment]
Just a pool in the 'pools' folder.

**Comment by scaras** [comment]
but with just this file it wants to run claymore with ethash.eu.... and not dagger...

**Comment by jakewarren81** [comment]
I'm still working out the bugs with the file between the different naming conventions.  I don't mine dagger since I only run NVIDIA cards; but I will look at it when I get time.

**Comment by aaronsace** [comment]
Algorithms.txt is the list of algorithm name corrections. 

If you check it and finish it (if it's not already) then do a pull request; might as well add it in.

**Comment by alucard20724** [comment]
Nicehash.ps1 in pools seems to have a problem with the location.  it's not accepting the users location from the start.bat file, but instead just appears to be using any random location code listed in Nicehash.ps1 file.... getting  stale shares.

**Comment by aaronsace** [comment]
@alucard20724 I'm overriding the user variable in error.
