### ISSUE TITLE
Freezes during benchmark

### ISSUE THREAD

**Issue by virtakar** [aaronsace/MultiPoolMiner#261]
MultiPoolMiner freezed my computer, I rebooted and it did it again. Here's the last log before freeze:

[2017-08-06_23-24-25.txt](https://github.com/aaronsace/MultiPoolMiner/files/1203465/2017-08-06_23-24-25.txt)

I just copy/pasted Excavator and associated dlls (cudart64_80.dll, msvcp120.dll and msvcr120.dll) before starting the script. Is it because my computer is badly configured (I undervolted and underclocked my GPU but it has been stable on Nicehash for 2 weeks now) and should I disable a miner?

**Comment by aaronsace** [comment]
You must have under-volted too far.

**Comment by virtakar** [comment]
OK I'll try at full power, thanks for the help!

**Comment by aaronsace** [comment]
I recommend leaving all settings as default but increase the max fan speed. 
If you are using an AMD graphics card, just setting state 7 voltage the same as state 6 will do.

**Comment by virtakar** [comment]
Back to default settings:

![gpu_fan](https://user-images.githubusercontent.com/17980657/29007451-d7128a9c-7b03-11e7-8799-c4bccaf663e6.PNG)
![gpu_mv](https://user-images.githubusercontent.com/17980657/29007452-d8064a38-7b03-11e7-8cd9-de6d0a870ad0.PNG)

Not even reducing the voltage of state 7, still freezes.

**Comment by aaronsace** [comment]
Still think it must be a system issue. Reducing the voltage slightly should help mitigate power or heat problems. Try setting state 7 to 1150. 

Also, are your drivers up-to-date?

**Comment by virtakar** [comment]
Drivers are up-to-date. Retried, no luck. I got an error in the miner's window just before freezing though: ZecMiner64 told me GPU 0 hangs when call to OpenGL. Could that be it?

**Comment by aaronsace** [comment]
Definitely a problem with the GPU then. Try just not using the miner, other miners may not push it as hard.

**Comment by virtakar** [comment]
OK I'll try tomorrow with a rested head... Thank you so much for your help!

**Comment by aaronsace** [comment]
No worries.
