### ISSUE TITLE
Why am I mining to your account?

### ISSUE THREAD

**Issue by uvxcoin** [aaronsace/MultiPoolMiner#262]
Bin\Ethash-Claymore\EthDcrMiner64.exe -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal aaronsace.multipoolminer -epsw x -esm 3 -allpools 1 -allcoins  1 -dpool mine.zpool.ca:5744 -dwal 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -dpsw multipoolminer,c=BTC -dcoin dcr -dcri 40

This is my batch -

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username xxx  -workername rig3 -interval 60 -location us -type amd -algorithm ethash,equihash,groestl,neoscrypt,skein -poolname miningpoolhub -currency btc,usd"

I intended on adding back "donate" after testing but I see you are forcing it.

**Comment by aaronsace** [comment]
Sorry but you will need to provide more information.

**Comment by jakewarren81** [comment]
You need the -donate 0 in the command, you can't just remove it as the default is 10 if no value is specified.
