### ISSUE TITLE
Question about switching

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#264]
After watching my rigs run a few hours I noticed that your app doesn't switch when MPH switches.
Please clarify if you are following MPH's algo to switch to or, what I think is happening, you are actually finding the best algo for the rigs.

Just curious. For example watched MPH place Myriad-Groestl | Digibyte-Groestl at the top of their list and all my AMD rigs stayed on Claymore ETH/SIA 

Thank you for a very cool program

**Comment by aaronsace** [comment]
All the profit stats are based off the live pool values but it won't just keep switching for marginal profit increases.

**Comment by Imaminer** [comment]
Thanks!
