### ISSUE TITLE
Not benchmarking AMD,NVIDIA algorithms

### ISSUE THREAD

**Issue by virtakar** [aaronsace/MultiPoolMiner#265]
Scirpt benchmarks AMD only miners, then runs the most profitable one and not benchmarking the AMD,NVIDIA miners. Is it because I'm not patient enough and should I wait?

[2017-08-08_09-05-36.txt](https://github.com/aaronsace/MultiPoolMiner/files/1207163/2017-08-08_09-05-36.txt)

**Comment by aaronsace** [comment]
It's still benchmarking the NVIDIA list at the top. AMD+NVIDIA will benchmark after that.

**Comment by aaronsace** [comment]
BTW, if you don't have an NVIDIA GPU then take it out of the command line.
