### ISSUE TITLE
Profit confision

### ISSUE THREAD

**Issue by Nebiforever** [aaronsace/MultiPoolMiner#267]
is something wrong here ? it says up tp %177 more profitable. if it's correct than i guess i still could not understand this "mpm is more profitable" thing. i was thinking that i've sorted that one out, up to now. 

All benchmarks are correct and they are actual real outputs of the rig.

![ekran alintisi](https://user-images.githubusercontent.com/30752781/29097226-60671468-7ca1-11e7-8c23-4353ffc37dd6.JPG)

**Comment by aaronsace** [comment]
No, run the profit reset file.
