### ISSUE TITLE
Disable Dual Mining

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#268]
Is there an easy way to do this? I have edited all claymore files with -mode 1 on all rigs and then reset benchmarking and started everything back up again. Seems there should be a global switch somewhere to disable.

**Comment by aaronsace** [comment]
You can specify which miners you want to use via command line but it's easier just deleting them from the 'miners' folder.

**Comment by Imaminer** [comment]
I didn't have a miner choice for Claymore without dual mining which is why I edited ClaymoreSia20, 30 and 40. I removed all the others.

**Comment by aaronsace** [comment]
FYI, this is the command line for claymore (non dual) only: 
`-minername claymore`

**Comment by Imaminer** [comment]
Thank you
