### ISSUE TITLE
Disable cpu mining while running specific GPU algorithms

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#269]
can we add a feature to disable CPU mining while running specific GPU algorithms, and then re-enable CPU mining when GPU algorithm has changed to a different algorithm such as claymore dual.    

i've noticed that if cpu is mining, if GPU starts mining on Skein, my GPU will have a 1-2% lower hashrate than if CPU wasn't mining.  I've noticed this on my Nvidia systems.  Haven't noticed it on my AMD GPU systems. All my CPU are intel.  I don't know if this affects AMD CPUs.

don't hate... i like to cpu mine. SUPPORT THE REVOLUTION!!!

**Comment by aaronsace** [comment]
If you are seeing your GPU hashrate then delete FireiceCpu8 and FireiceCpu6. If it's still dropping, delete FireiceCpu4.

**Comment by scaras** [comment]
[http://www.gatwick-fsg.org.uk/affinitymask.aspx?SubMenuItem=hardware](url)
set a mask and leave at least one phisical core free. 
use` --cpu-affinity n` for the jayddee and tpruvot miners.
 n = mask calculated on site for your cpu

**Comment by aaronsace** [comment]
I don't think you need to go to that extreme; the operating system will work out the affinity itself just fine. 

FireiceCpu seems to be the only miner that really pushes the CPU; I think it's the amount of cache it's using on the CPU.

**Comment by scaras** [comment]
when i use the 254 mask (all but physical 0) the UI hangs less often using the pc for normal use (for the wife and kids with facebook games) without losing lots of hashpower.
