### ISSUE TITLE
CPU sia/vanilla 

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#27]
Unknown algo parameter 'sia'
Unknown algo parameter 'vanilla'

Usage: cpuminer-multi [OPTIONS]
Options:
  -a, --algo=ALGO       specify the algorithm to use
                          scrypt       scrypt(1024, 1, 1) (default)
                          scrypt:N     scrypt(N, 1, 1)
                          sha256d      SHA-256d
                          anime        Animecoin
                          axiom        Axiom MemoHash
                          blake        Blake-256 (SFR)
                          blakecoin    Blakecoin
                          blake2s      Blake-2 S
                          bmw          BMW 256
                          c11/flax     C11
                          cryptonight  CryptoNight
                          dmd-gr       Diamond-Groestl
                          drop         Dropcoin
                          fresh        Fresh
                          groestl      GroestlCoin
                          heavy        Heavy
                          keccak       Keccak
                          luffa        Luffa
                          lyra2        Lyra2RE
                          myr-gr       Myriad-Groestl
                          neoscrypt    NeoScrypt(128, 2, 1)
                          nist5        Nist5
                          pluck        Pluck:128 (Supcoin)
                          pentablake   Pentablake
                          quark        Quark
                          qubit        Qubit
                          shavite3     Shavite3
                          skein        Skein+Sha (Skeincoin)
                          skein2       Double Skein (Woodcoin)
                          s3           S3
                          x11          X11
                          x13          X13
                          x14          X14
                          x15          X15
                          zr5          ZR5
                          scryptjane:N

Seems you are trying to mine SIA and vanilla with a miner that does not support it.

Boyise

v2.2.2

**Comment by aaronsace** [comment]
It will detect very quickly that if it's not supported. 
Will check for an alternate miner or just remove them. 

Upgrade to 2.2.3 it's far smoother and bug free.
