### ISSUE TITLE
Don't close miners if zpool front end drops

### ISSUE THREAD

**Issue by scaras** [aaronsace/MultiPoolMiner#270]
is it possible to ceep the miners open when the front end of zpool drops?
(maybe with a check if miner is still hashing)
i've noticed that stratum servers stay online (or reconnect faster if it drops when using -R 5 command).
this is making loss bigger when switching miners.

**Comment by aaronsace** [comment]
Until I implement failure detection I think it switching over to MiningPoolHub is an adequate solution for now. It also switches to Zpool if the MiningPoolHub API is down.

**Comment by scaras** [comment]
if 2% mining fee is to mush different in calculation is enough to shange the scrypt, this deffinitly needs to change cuz it is way more than 2%. i not gonne bother, but just to lazy to realy look into coding this whole scrypt to change it for myself...

**Comment by aaronsace** [comment]
Sorry, I can't figure out what you saying.

**Comment by scaras** [comment]
don't bother... drunk and stoned (i love living close to the netherlands)... but the loss of changing to MPH is bigger then if you use the last known most proffiting miner of zpool for the unknown proffiting miner if you calculate the time between switching miners, swithching to other miner, ...

**Comment by papampi** [comment]
Zpool api gives timeouts from time to time and it makes MPM drop the miner at Zpool and switch to MPH.
if its possible to keep the last benefit files before updating to new one and keep mining if there is no new one it would be great.

**Comment by papampi** [comment]
Since mining pool hub api has problems this is very important when using zpool, 
I removed all MPH algos and tried to use only zpool, it gives no pool and stop mining every time zpool api timeouts.
