### ISSUE TITLE
myriad-groestl on miningpoolhub

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#271]
Sorry for bad my english, when the algorithm works myriadgroestl sometimes I see such a picture GPU #0 waiting for data, my video-cards is MSI 1060 6 Gb, Msi 1060 3 Gb, Asus 1060 3 Gb.
![img_20170810_134544_hdr](https://user-images.githubusercontent.com/30767482/29151192-a94c7398-7dd3-11e7-9227-60edd9e80066.jpg)
How can this be remedied?

**Comment by aaronsace** [comment]
#228 Just delete it from the 'miners' folder.

**Comment by spider703** [comment]
delete miner Nvidia-Klaust ?

**Comment by alucard20724** [comment]
just delete **CcminerKlaust.ps1** from the "**Miners**" folder.     This problem only exist with Klaust.    I just commented out Klaust algorithms.
