### ISSUE TITLE
zpool

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#273]
Whats the batch file for zpool look like?
do I use my BTC for username?
Tried -wallet. It didnt like that.
Thanks

**Comment by aaronsace** [comment]
Check the 'start.bat' file: 
https://github.com/aaronsace/MultiPoolMiner/blob/master/Start.bat

**Comment by Imaminer** [comment]
Need more specific instructions.
This is my bat file
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet mybtcgoeshere -username xxx -workername rig3 -interval 60 -location us -type amd -algorithm ethash,equihash,groestl,neoscrypt,skein,keccak,cryptonight,myrgr,myriadcoingroestl,myriadgroestl,lyra2z,sib -poolname Zpool -currency btc,usd"

This fails. It goes back to MPH instead of zpool

**Comment by aaronsace** [comment]
What are you trying to do?

**Comment by Imaminer** [comment]
Use your program to mine at zpool

**Comment by aaronsace** [comment]
It mines on zpool. You need a MiningPoolHub account aswell.

**Comment by Imaminer** [comment]
Please give an example batch file to do that. I have tried every way I could think of

**Comment by aaronsace** [comment]
It mines on MiningPoolHub and Zpool. 

This prioritizes MiningPoolHub: 
`&.\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm cryptonight,decred,ethash,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,sib -poolname miningpoolhub -currency btc,usd -donate 10`

This prioritizes Zpool: 
`&.\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm cryptonight,decred,ethash,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,sib -poolname zpool -currency btc,usd -donate 10`

This prioritizes neither and will select the most profitable: 
`&.\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm cryptonight,decred,ethash,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,sib -currency btc,usd -donate 10`

**Comment by Imaminer** [comment]
Ok I just tried again and set it to zpool.
Miner goes to MPH
ETH: 08/10/17-15:49:58 - New job from us-east.ethash-hub.miningpoolhub.com:17020

**Comment by aaronsace** [comment]
You do realize Zpool doesn't have Ethereum???

**Comment by Imaminer** [comment]
Hah! No I didnt lol! (smacks self in head)
Ok let me pull eth out and try again to test

**Comment by Imaminer** [comment]
Everything is going to MPH. Should I redo the benchmark? Will it pull stats from zpool AND MPH if I do that?

**Comment by aaronsace** [comment]
Please can you send me the log from the 'logs' folder?
Drag and drop it into the message.

**Comment by Imaminer** [comment]
Sure while I get that I just tried removing all algo except sib. Got no miners message

**Comment by aaronsace** [comment]
Can I just check, you are using this version right? 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.5.3.4.1/MultiPoolMinerV2.5.3.4.1.zip

**Comment by Imaminer** [comment]
I have latest version version.
Ok this test is all algos and poolname zpool
[2017-08-10_16-03-29.txt](https://github.com/aaronsace/MultiPoolMiner/files/1216211/2017-08-10_16-03-29.txt)
Miner went to ETH on MPH.

**Comment by Imaminer** [comment]
This test is removing ETH and poolname still zpool
Miner went to MPH
[2017-08-10_16-08-30.txt](https://github.com/aaronsace/MultiPoolMiner/files/1216220/2017-08-10_16-08-30.txt)

**Comment by aaronsace** [comment]
Monero is not on Zpool.

**Comment by Imaminer** [comment]
Well then the sib test should of worked
Why no miner?

**Comment by Imaminer** [comment]
Wait I might of accidently removed some miners. Let me double check

**Comment by Imaminer** [comment]
Nope all there for AMD. Tried again. No miners for SIB.
Is Sib Nvidia only? Like ccminer?

**Comment by aaronsace** [comment]
I don't I have an AMD sib miner. Zpool looks like it's working fine on your log. You're are just taking all the algorithms out.

**Comment by Imaminer** [comment]
Cool thanks. Should I redo the benchmarks?

**Comment by Imaminer** [comment]
Hey! I am mining on zpool! I just removed -algorithms from batch lol
It decided on Decred

**Comment by aaronsace** [comment]
Your benchmarks are probably fine. 

Run the profit reset file. 
Add the algorithms back into your command line. 
Start mining.

**Comment by Imaminer** [comment]
Thank you. Closing this one out. You have been a great help!

**Comment by Nebiforever** [comment]
you should put these batch examples (and some other tips you post here) into the readme file. that would help alot for new starters
