### ISSUE TITLE
Please consider adding new Ethminer 

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#274]
I just tested and its as fast as Claymore or faster. More stable and NO FEES.
https://github.com/ethereum-mining/ethminer

Launching it is like Genoils -
ethminer -G -SP 0 -S us-east.ethash-hub.miningpoolhub.com:17020 -O UserName.rig3:x
Other params can be added.

My testing is ONLY on AMD / MPH so far. Loving it.

I cant seem to get it right. 
[Ethminer.txt](https://github.com/aaronsace/MultiPoolMiner/files/1219146/Ethminer.txt)

Thanks

**Comment by aaronsace** [comment]
Cheers, I'll definitely get this added.

**Comment by SS2006** [comment]
Just to make sure I get the newest version that includes this new miner, i want to make sure I'm reading your site correctly, is v2.5.3.4.1 the newest version? The reason I ask is it has March 20 next to it, so it seems older. Scrolling down I see 'newer ones' from 23 days ago but the version number is 2.5.3.4, which is clearly an older one. Is it simply that the date of march 20 is just wrong?

**Comment by aaronsace** [comment]
March 20 was when I first uploaded it. I've bumped the version a few times which is why the dates are like that.
