### ISSUE TITLE
Memory leak on powershell.exe - ~4GB per day

### ISSUE THREAD

**Issue by nitrobg** [aaronsace/MultiPoolMiner#276]
The script has a quite serious memory leak and I can reproduce it on 2 different rigs with Windows 10 Pro x64. The powershell.exe process grows in size by about 4GB per day.
I can give you remote access to my rig for tests.

**Comment by aaronsace** [comment]
I have no access to memory in PowerShell so I can't be leaking it but I'm going to check what I'm storing and see if there is anything unnecessary. I've seen the memory increase a little but never to that extreme.

**Comment by papampi** [comment]
I havent seen this on both of my rigs, may be because I set a restart schedule every day at 8:30

**Comment by aaronsace** [comment]
I tend to not run it more than a day either. It would still function on my system even if it had got to 4gb.

**Comment by papampi** [comment]
Both my rigs are up for over 18 hours now and none shows high memory leak, each windows shell has around 150 MB memory.

**Comment by aaronsace** [comment]
I wonder if it's the version, a few people have mentioned it. 

@nitrobg and @papampi 

What does your log show, this is mine: 

> PSVersion: 5.1.15063.483
> PSEdition: Desktop
> PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.483
> BuildVersion: 10.0.15063.483
> CLRVersion: 4.0.30319.42000
> WSManStackVersion: 3.0
> PSRemotingProtocolVersion: 2.3
> SerializationVersion: 1.1.0.1

**Comment by nitrobg** [comment]
That's odd. Since this morning, the process grew up to 7.2GB.

```
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I'm using a snapshot of a 9 Jul repo but I can't see noticeable changes to bother with an update.
I'm getting some error messages on each reload (it works fine anyway).

Rig 1:
```
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: .."
ConvertFrom-Json : Invalid JSON primitive: ..
At C:\1060\Include.ps1:125 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

Rig 2:
`PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (502) Bad Gateway."`

**Comment by papampi** [comment]
This is mine 
'''
Process ID: 8124
PSVersion: 5.1.15063.0
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.0
BuildVersion: 10.0.15063.0
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
'''

**Comment by aaronsace** [comment]
I think there was a lot of fixes since then. 

Can you try this one just in case? 
https://github.com/aaronsace/MultiPoolMiner/archive/308ede1191b80c02316daefcb072ab2b9485f11c.zip

**Comment by nitrobg** [comment]
OK, I'll get back to you later.

**Comment by nitrobg** [comment]
The leak is still there but it seems to be reduced in size. About 20 hours after the initial launch, the process now consumes 1.2GB RAM.

**Comment by aaronsace** [comment]
@nitrobg Thanks for checking.

**Comment by fonyo** [comment]
![powershell-memuse](https://user-images.githubusercontent.com/10072275/30511639-9222d1b6-9ad5-11e7-8cee-de19c0bb75c6.jpg)
Not sure what happened yesterday or overnight but powershell just got a spike in the memory used by it.

**Comment by fonyo** [comment]
So is there a specific version of PS we should be using?
