### ISSUE TITLE
MPM not getting what it shows.

### ISSUE THREAD

**Issue by papampi** [aaronsace/MultiPoolMiner#277]
Hi, I need help with MPM switch, seems like something is not right.
I have been using MPM for the last week
I feel like its not getting what it show in mining from MPH.
So ... here is my setup.
2 rigs, each 6 x 1070, mild OC, (250+ mem, 100+ core, 85% Power, Temp limit 75)
MPM sync time 600 (was 300 for past week , changed to 600 last night)
coins/algos : Ethash,Equihash,Lyra2re2,Neoscrypt, Sia,Groestl,cryptonight,lyra2z,myr-mgr (removed myr-mgr yesterday)
MPM  on each rig says I should get at least 14$ a day without MPM and 19$ a day with MPM 
which makes 2.3$ a day/card at least
What MPH bitcoin dashboard shows for last 4 days is as below which is way less than 2$ a day/card:
[code]
2017-08-15 (UTC)	0.00118331 BTC  
2017-08-14 (UTC)	0.00470864 BTC price was around 4k$   =  18 $
2017-08-13 (UTC)	0.00582330 BTC price was around 3.5k$=  20 $
2017-08-12 (UTC)	0.00549901 BTC price was around 3.2k$ = 17 $
2017-08-11 (UTC)	0.00587651 BTC price was around 3.2k$ = 18 $
[/code]

So ... Is there any thing I need to do or others face the same lower benefit/day ?

**Comment by nemosminer** [comment]
its not PPS...

**Comment by papampi** [comment]
I know its not PPS, But how come its so less than expected in 4 consecutive days? 
I am asking if I can raise the income by changing sync time, adding or removing algos , .... 
Or this is what MPM can get ?

**Comment by aaronsace** [comment]
I'd not focus on dollars as the is simply a currency conversion. Focus on Bitcoin; how much is it say you are getting per day if run 24/7?

**Comment by papampi** [comment]
Both rigs are running 24x7 , 2 rigs GTX-1070 x 6 cards Total 12 cards
Last 4 days based on MPH:
```
2017-08-14 (UTC)	0.00470864 BTC 
2017-08-13 (UTC)	0.00582330 BTC
2017-08-12 (UTC)	0.00549901 BTC
2017-08-11 (UTC)	0.00587651 BTC
```

**Comment by aaronsace** [comment]
Around 0.00548 BTC/Day
What is it saying on MultiPoolMiner?

**Comment by papampi** [comment]
MPM now shows it should get .00268-0.00582 on each rig
Which makes  0.00536 - 0.01164 for 2 rigs
Thats totally in range ... :+1: 
My question is why its in the minimum range. 
Is there any way to change my setup to get that a bit higher ?
Is 600 sync time too much ? 
Is it better to have more algos or less ?
What are the rules of thumbs to use on MPM to get best results?

**Comment by Nebiforever** [comment]
i was testing mpm for last week and i am having the same results. what is the acceptable difference between mpm and mph? 

i want to maximize my income also with mpm. because with these results nicehash gives better dailiy income.

**Comment by aaronsace** [comment]
It's hard to test this as it takes days. I wouldn't change the sync time from the default. 

Maybe this needs changing: 
`$DecayBase = 1 - 0.1`

Try setting it to: 
`$DecayBase = 1 - 0.01`

**Comment by papampi** [comment]
Where should I change that and what does $DecayBase do ?

**Comment by papampi** [comment]
What I say is I expect to get at least 2$ from a 1070, 
MPM shows this :
```

MultiPoolMiner is between 0% and 16% more profitable than the fastest miner:

Miner          BTC                             USD
-----          ---                             ---
MultiPoolMiner 0.00355 ±41 % (0.00253-0.00499) 15.40164 ±41 % (10.95973-21.64382)
EWBF0-Equihash 0.00329 ±40 % (0.00235-0.00461) 14.26844 ±40 % (10.18932-19.98058)```

But what I actually get from MPH much less than 2$ day/card

**Comment by aaronsace** [comment]
It's the percentage that you decrease the switching threshold.

**Comment by papampi** [comment]
Ok, will try that, Thanks.
You said dont change default sync interval , start.bat default is 60 sec, 
Isnt it too much to sync every minute and may be start mining a new coin ?
Usually it takes more than a minute for each miner to get to optimum speed

**Comment by aaronsace** [comment]
It doesn't take 10 minutes though. 
It won't just keep switching.

**Comment by papampi** [comment]
Thats true ... :+1: 
I just set $DecayBase = 1 - 0.01
and lower sync interval to 5 min, 
Will keep eye on the rigs and will post how it goes
Thanks a lot for all the helps.
Will raise the donation time to a coffee a day :)

**Comment by papampi** [comment]
So, I have been using 
$DecayBase = 1 - 0.01 , with 120s sync interval for 2 days. 
Most of the times it seems more stable and not switching too fast.. 
but some times it stick to one coin and wont switch even if the coin drop to rank 10.
Waited for 20 sync cycles for blake2s, and its rank was very low after 5th interval
Only restart MPM cause the new coin to start mining.
