### ISSUE TITLE
Integration of cgminer for Skein-Algorithm

### ISSUE THREAD

**Issue by bandit420** [aaronsace/MultiPoolMiner#28]
Could you consider adding cgminer for Skein-Algorithm? The current sgminer-Implementation is very cpu-intensive (like 100%) and not working correctly as far as I can tell.

That is the link for the latest version of cgminer on miningpoolhub:
https://mega.nz/#!Axx2HY7b!nVio9djtGFmFm1od7vylaKNyxzVJxDp0u4LNNhKwy0s

And the source:
https://github.com/reorder/cgminer_skein

The miner also has the xgminer-API you specified allready in the Include.ps1-Script for sgminer.

**Comment by aaronsace** [comment]
Just a rant. 

It baffles me as to why so many people on GitHub spend loads of time creating something then can't be bothered to mark it as a release and attach a compiled version.

**Comment by bandit420** [comment]
First of all : thank you for considering it.

So because I'm pretty new and kind of in the process and kind of new:
Best would be to fork the repo, build it and send in a pull request? 
Then I could probably do it with my really underdeveloped knowlegde of mingw.

I allready trying to do it locally with a new PS-miner-script, but my knowledge is really in the process of growing and it ended up with nothing.

**Comment by aaronsace** [comment]
Don't worry about trying to fork this. It was the number of cgminer spinoffs with no complied releases that riled me. 

I just don't want to add every miner under the sun especially as there is no direct link to dynamically download. To add it is very simple if the api is the same as sgminer.

**Comment by aaronsace** [comment]
I haven't tested it but put this in the 'miners' folder. Let me know if it works.

**Comment by bandit420** [comment]
The txt-file is working fine, just the hashrate-calculation seems a bit weird (live-hashrate is null).

Although miner is running in API-Mode.

> API running in local read access mode on port 4028

Hashrate with 6*RX480 around 1,45-1,6 Gh/s.

I just packed a few files in there, let me know if you need more info or a translation.

[2017-01-04_02-29-52.txt](https://github.com/aaronsace/MultiPoolMiner/files/683755/2017-01-04_02-29-52.txt)
[Reorder_Skein_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/683756/Reorder_Skein_HashRate.txt)
[Reorder_Keccak_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/683757/Reorder_Keccak_HashRate.txt)

**Comment by bandit420** [comment]
Just rerun the benchmark. Still 0 Hashrate. My uneducated guess is the parsing must be different.

**Comment by aaronsace** [comment]
Done. It had a mh/s variable instead of a kh/s variable. 

Wish everyone just passed h/s in the APIs or at least the multiplier in a separate field.
