### ISSUE TITLE
zpool api add timeoutsec

### ISSUE THREAD

**Issue by papampi** [aaronsace/MultiPoolMiner#280]
I saw some one mentioned in mega miner thread they solved zpool api timeout (No Pool)  issue by adding timeoutsec to Zpool.ps1

from :
    $Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing | ConvertFrom-Json
to :
                            $Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing -timeoutsec 5 | ConvertFrom-Json

**Comment by papampi** [comment]
Tested, not helping

**Comment by aaronsace** [comment]
Ah, genius. Will set the timeout to 5 seconds.

**Comment by aaronsace** [comment]
Ha, well that was short lived. :P

**Comment by aaronsace** [comment]
Mining continues even when there are no pools. It just keeps checking and leaves the miners running.

**Comment by tutulino** [comment]
Aaronsace I hope I can help, I add three tries to Zpool api (usually
problematic), if only one pool is active there is "infinite retries" by
main program loop, but in MM you can run more than one pool same time, if
one of them fail others must work, this is reason of timeout.

$retries=1
do {
try {
$Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status"
-UseBasicParsing -timeoutsec 5 | ConvertFrom-Json
#$Zpool_Request=get-content "..\zpool_request.json" | ConvertFrom-Json
}
catch {}
$retries++
} while ($Zpool_Request -eq $null -and $retries -le 3)
if ($retries -gt 3) {
WRITE-HOST 'ZPOOL API NOT RESPONDING...ABORTING'
EXIT
}

2017-08-16 10:42 GMT+02:00 aaronsace <notifications@github.com>:

**Comment by papampi** [comment]
But if zpool gives time out it will switch to mph ...
and zpool gives so many timeouts ,
I tried to go with only zpool algos + dual eth from mph.
That causes miners switch to eth+sia everytime zpool times out.

**Comment by aaronsace** [comment]
If MiningPoolHub is active then it will continue with just MiningPoolHub and ignore the failed zpool. MegaMiner is just my code. 

Is the problem that invoke-webrequest locks up completely without the timeout?

The retry 3 times idea is good instead of failing after the first attempt.

**Comment by papampi** [comment]
Continue with MPH if Zpool timeouts is the problem I'm talking about.
Zpool timeouts too many times and MPH has wrong rates ... lol
So I say if zpool gave timeout, MPM uses last good or retry till get an answer for shell

**Comment by papampi** [comment]
@tutulino 
I am trying your workaround, is this correct ?
```
  $retries=1
                do {
                        try {
                            $Zpool_Request = Invoke-WebRequest "http://www.zpool.ca/api/status" -UseBasicParsing -timeoutsec 5 | ConvertFrom-Json 
                            #$Zpool_Request=get-content "..\zpool_request.json" | ConvertFrom-Json
                        }
                        catch {}
                        $retries++
                    } while ($Zpool_Request -eq $null -and $retries -le 10)
                
                if ($retries -gt 10) {
                                    WRITE-HOST 'ZPOOL API NOT RESPONDING...ABORTING'
                                    EXIT
                                    }

if (-not $Zpool_Request) {return}
```
or I should remove the 
```
if (-not $Zpool_Request) {return}
```

Sorry if noob question, I'm more of a linux guy than windows!!!

**Comment by papampi** [comment]
Even with 10 retries I get "'ZPOOL API NOT RESPONDING...ABORTING" from time to time ...

**Comment by aaronsace** [comment]
You need to sleep about 10 seconds before retrying.

**Comment by papampi** [comment]
Doesnt "-timeoutsec 5" makes it wait 5 sec till get no response ?
Since I removed the 
```
if (-not $Zpool_Request) {return}
```
I got no " ZPOOL API NOT RESPONDING...ABORTING" yet.
Seems its working fine.

**Comment by aaronsace** [comment]
But you you need to sleep before trying again otherwise the server will block the requests.

**Comment by UselessGuru** [comment]
In case of failed API requests I fail back to a cached request like this:

In 'include.ps1' I added this:
`function Get-Cached-PoolInfo {
    param(
        [Parameter(Mandatory=$true)]
        [String]$Name 
    )
    $Path = "Cache\$Name"
	if(Test-Path $path) {Get-Content $path}
}

function Set-Cached-PoolInfo {
    param(
        [Parameter(Mandatory=$true)]
        [String]$Name, 
        [Parameter(Mandatory=$true)]
        [String]$Value 
    )
	if(-not (Test-Path "Cache")){New-Item "Cache" -ItemType "directory"}
    $Path = "Cache\$Name"
	$Value = $Value.substring(0, $Value.length -1) + ',"timestamp":"' + (Get-Date -Format ("yyyy'-'MM'-'dd' 'HH':'mm':'ss")) + '"}'
	$Value | Set-Content $Path
	
}`

and in each pool file I do this:
`try
{
    $Zpool_Request = (Invoke-WebRequest "http://www.zpool.ca/api/status" -TimeoutSec 5 -UseBasicParsing)
	Set-Cached-PoolInfo "Zpool_Request.txt" $Zpool_Request
}
catch
{
	$StatsTimestamp = " [cached] "
}
$Zpool_Request = (Get-Cached-PoolInfo "Zpool_Request.txt" | ConvertFrom-Json)
if (-not $Zpool_Request) {return}

$StatsTimestamp = $Zpool_Request.timestamp + $StatsTimestamp`
$StatsTimestamp can then be returned to them main routine as part of 
`	        [PSCustomObject]@{
	            Algorithm 		= $Zpool_Algorithm
	            Info 			= $Zpool
		    StatsTimestamp 	= $StatsTimestamp
	            Price 			= $Stat.Live
	            StablePrice 	        = $Stat.Week
	            MarginOfError	= $Stat.Fluctuation
	            Protocol		= "stratum+tcp"
	            Host			= $Zpool_Host
	            Port			= $Zpool_Port
	            User			= $Wallet
                    Pass			= "c=$Currency"
	            Location 		= $Location
	            SSL			= $false
	        }`

**Comment by aaronsace** [comment]
@UselessGuru That is the best idea I've seen.

**Comment by aaronsace** [comment]
@UselessGuru If you have complete code, do a pull request.

**Comment by UselessGuru** [comment]
Feel free to base it off my above snippets. :)

**Comment by aaronsace** [comment]
Cheers @UselessGuru

**Comment by UselessGuru** [comment]
I've updated my code:

```
try
{
    $MiningPoolHub_WebRequest = (Invoke-WebRequest "$URL" -TimeoutSec 5 -UseBasicParsing)
	if ($MiningPoolHub_WebRequest.Content -match ".*{.+}.*") {
        Set-Cached-PoolInfo "MiningPoolHub_WebRequest.txt" $MiningPoolHub_WebRequest
    }
}
catch
{
	$StatsTimestamp = " [cached] "
}
$MiningPoolHub_Request = (Get-Cached-PoolInfo "MiningPoolHub_WebRequest.txt" | ConvertFrom-Json)
if (-not $MiningPoolHub_Request.success) {return}

$StatsSource = $MiningPoolHub_Request.timestamp + $StatsSource
```
That way I am only allowing well-formed web requests to be cached.
E.g. today morning zpool was down and would return an 'empty' (2 bytes, CR/LF) long request. Above code takes care of this.
