### ISSUE TITLE
Remove MPM as default

### ISSUE THREAD

**Issue by papampi** [aaronsace/MultiPoolMiner#282]
Since the problem with MPH api is not solving and no one is answering there, either by mail or twitter, please remove MPH as default pool from MPM and make zpool default. 
Or let the start.bat dictate.

**Comment by jakewarren81** [comment]
Just remove it from your start.bat if you don't want to use it. Currently there is no functionality that sets a "default" or priority of one pool over another.  Its based on profitability.  That might be an interesting enhancement though.

**Comment by aaronsace** [comment]
The 'start.bat' has to be edited to insert a username so the pool can be changed or removed by the user as well.
