### ISSUE TITLE
CleanUp Log folder

### ISSUE THREAD

**Issue by papampi** [aaronsace/MultiPoolMiner#284]
Noticed the log folder gets bigger and bigger for no reason.
Seems like a good idea to add a clean up for logs older than a week.

**Comment by scaras** [comment]
i've found a basic script to do this.

```
#----- define parameters -----#
#----- get current date ----#
$Now = Get-Date
#----- define amount of days ----#
$Days = "1"
#----- define folder where files are located ----#
$TargetFolder = ".\Logs"
#----- define extension ----#
$Extension = "*.txt"
#----- define LastWriteTime parameter based on $Days ---#
$LastWrite = $Now.AddDays(-$Days)

#----- get files based on lastwrite filter and specified folder ---#
$Files = Get-Childitem $TargetFolder -Include $Extension -Recurse | Where {$_.LastWriteTime -le "$LastWrite"}

```
pasting this at the end of the script ( just above```
 #Stop the log
Stop-Transcript 
```seems to work seems to do the job

**Comment by fonyo** [comment]
Closing this as it has been resolved by providing an option to user for cleaning up the Logs folder and removing all log files created by the Claymore miners. https://github.com/aaronsace/MultiPoolMiner/commit/c0f23255779c150ed123f9e664707eca6165e187
