### ISSUE TITLE
miningpoolhub

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#288]
I work on zpool and MPH pools, on the last I look not all algorithms are extracted, but only some, for example skein. How to add these algorithms to the prey on the pool?

**Comment by spider703** [comment]
And the second question is - I took the updated file from the pool folder for miningpoolhub and after changing the MPM does not start. what am I doing wrong?

**Comment by aaronsace** [comment]
Sorry, I'm not following what you are writing.

**Comment by spider703** [comment]
On a pool miningpoolhub.com it is extracted only 5 or 6 algorithms, and how the others to add?

**Comment by aaronsace** [comment]
Oh, I think I understand what you mean; are you use the 'start.bat' file?

Edit it in notepad to change the algorithm list.

**Comment by spider703** [comment]
спасибо за подсказку
