### ISSUE TITLE
cryptonight error

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#29]
Bin\Claymore\Cryptonight\NsGpuCNMiner.exe -o stratum+ssl://europe.cryptonight-hub.miningpoolhub.com:17024 -u boysie.multipoolminer -p x

Main pool is stratum+ssl

╔════════════════════════════════════════════════════════════════╗
║            Claymore CryptoNote GPU Miner  v9.6 Beta            ║
╚════════════════════════════════════════════════════════════════╝
Wrong wallet address boysie.multipoolminer - XMR/QCN/BCN/FCN/Aeon/Duck/Dash/OEC/MCN/ORION addresses are supported only.
Pool stratum+ssl removed from the list
Wrong wallet address boysie.multipoolminer - XMR/QCN/BCN/FCN/Aeon/Duck/Dash/OEC/MCN/ORION addresses are supported only.
Pool mine.moneropool.com removed from the list
Wrong wallet address boysie.multipoolminer - XMR/QCN/BCN/FCN/Aeon/Duck/Dash/OEC/MCN/ORION addresses are supported only.
Pool monero.crypto-pool.fr removed from the list
No pools specified! Specify at least one pool in "pools.txt" file or in "-o" parameter.

**Comment by aaronsace** [comment]
The issue is in the release notes and mentioned on MiningPoolHub. The problem is with Claymore; awaiting an update to the miner to support usernames which he said would be released by now. 
https://bitcointalk.org/index.php?topic=638915.msg17349937#msg17349937

**Comment by aaronsace** [comment]
Claymore has now released the new version. Testing it now, you should be able to just replace it in the bin folder.
