### ISSUE TITLE
Runtime Exception in Chinese Computer

### ISSUE THREAD

**Issue by shtse8** [aaronsace/MultiPoolMiner#290]
```
在设置字符串格式时出错: 输入字符串的格式不正确。。
所在位置 C:\Users\shtse\Downloads\MultiPoolMinerV2.5.3.4.1\MultiPoolMiner.ps1:380 字符: 13
+             $MinerComparisons[0] | Add-Member $_ ("{0:N5} 眥1:P0} ({2: ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({0:N5} 眥1:P0} ({2:N5}-{3:N5}):String) []，RuntimeException
    + FullyQualifiedErrorId : FormatError
```

It seems that https://github.com/aaronsace/MultiPoolMiner/blob/master/MultiPoolMiner.ps1#L385 cannot be decoded properly in Chinese computer. In all my Chinese computers, It displays `{0:N5} 眥1:P0} ({2:N5}-{3:N5})` instead of `{0:N5} ±{1:P0} ({2:N5}-{3:N5})`. May we avoid using this special character for widely supporting in different languages computers?

**Comment by aaronsace** [comment]
Hmm, I set the file encoding to UTF-8 with BOM. Maybe I need to force PowerShell to read it as such as well.

**Comment by aaronsace** [comment]
Could do with some that understands encoding in PowerShell better.

**Comment by shtse8** [comment]
Yes, we should use encoded utf8 as well.

**Comment by aaronsace** [comment]
Do you get this error if you run it in command prompt and PowerShell?

**Comment by aaronsace** [comment]
This commit was after release, did this effect anything? 
https://github.com/aaronsace/MultiPoolMiner/commit/cd885ad190bb5cbc926b243ca4a8db15bbbf58df

**Comment by aaronsace** [comment]
Let me know if that commit and/or `chcp 65001` fixed it.

**Comment by shtse8** [comment]
Sorry, I am not following why the commit can fix that problem. It seems just adding a param and a download list param.
I have tried adding a `chcp 65001`  into the `start.bat` like this:
```
chcp 65001

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username username-workername multipoolminer -interval 60 -location asia -ssl -type cpu -algorithm cryptonight,ethash,equihash,groestl,lyra2z,neoscrypt,pascal,sia -poolname miningpoolhub -currency btc,usd -donate 10"
```
But the error still exists.

I am now trying to run it in powershell and then the `.ps1`.
but the following error occur. I don't know how to fix it.
```
.\MultiPoolMiner.ps1 : 无法加载文件 C:\Users\shtse\Downloads\MultiPoolMinerV2.5.3.4.1\MultiPoolMiner.ps1，因为在此系统上禁止运行脚本。有关详细信息
，请参阅 http://go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ .\MultiPoolMiner.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by shtse8** [comment]
Can we simply use `\u00B1` instead of `±`?

**Comment by shtse8** [comment]
I have tried and now can display the char using `$([char]0x00B1)` instead of `±`

the line is changed to:
```
 $MinerComparisons[0] | Add-Member $_ ("{0:N5} $([char]0x00B1){1:P0} ({2:N5}-{3:N5})" -f ($MinerComparisons_Profit[0] * $Rates.$_), $MinerComparisons_MarginOfError[0], (($MinerComparisons_Profit[0] * $Rates.$_) / (1 + $MinerComparisons_MarginOfError[0])), (($MinerComparisons_Profit[0] * $Rates.$_) * (1 + $MinerComparisons_MarginOfError[0])))
```

**Comment by aaronsace** [comment]
The commit has an invisible encoding identifier at the beginning of the file. 
'Execution_Policies' is because your computer is blocking the file form the internet. You need to do `powershell -executionpolicy bypass`. 

So does `$([char]0x00B1)` work? 
If `chcp 65001` does not work fix it then I will put the char code.

**Comment by shtse8** [comment]
`$([char]0x00B1)` works.

I am now testing the `chcp 65001`.

**Comment by shtse8** [comment]
Tried. Still getting this error if I run it in command prompt (via the '.bat' file) and PowerShell (running the '.ps1' directly).

**Comment by aaronsace** [comment]
Cheers @shtse8 for confirming this. I will commit the change today.
