### ISSUE TITLE
NiceHash Only?

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#291]
I put -poolname nicehash in batch file and when run the program starts benchmarking algos from NH, Miningpool and HR.

Can I just do NH?

**Comment by aaronsace** [comment]
`-poolname nicehash` works. If you selected algorithms that are not available at nicehash then it finds another pool as if it was down.

**Comment by Imaminer** [comment]
Ahh didn't know that. Thanks!

**Comment by Pititul** [comment]
Should I pick one or leave all three poolnames in the batch file just in case?

**Comment by aaronsace** [comment]
@Pititul It's safe to have just one pool. MultiPoolMiner will still use the other pools as backups even if you only select one.
