### ISSUE TITLE
Request for new miner

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#292]
Please implement this for AMD skunk.
https://github.com/semtexzv/Prospector

Nicehash has implemented it so its safe to use.

**Comment by aaronsace** [comment]
Interesting, I'll check it out.

**Comment by Imaminer** [comment]
Thanks. I was skipping it at first as the owner refuses to open source it but since NH implemented it I'm sure its safe to use or they wouldn't do it.
