### ISSUE TITLE
Excavator Equihash Issue AMD

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#300]
This is latest version AFTER the Excavator fix 3 hours ago
The rig I am benchmarking has 3 AMD cards.
Excavator is starting 5 miners. 3 are mining and 2 are TRYING to mine but cannot.
This is causing general slowdown of system and possible incorrect speeds on the 3 real miners.

See pics - 
https://s2.postimg.org/3mku6hbc9/excavator.jpg

https://s2.postimg.org/a1jv35i21/excavator2.jpg

Thanks

**Comment by aaronsace** [comment]
Does exactor work on those cards? Try running Excavator manually.

**Comment by Imaminer** [comment]
Yes it works fine. I might of found the issue. Miners folder had extra miners in it for additional cards. I removed them and am trying again.
It will need admin rights though to run correctly

**Comment by Imaminer** [comment]
Ok of course now it only opens 3 miners. So my mistake  leaving additional miners in folder. Also (I know this is a tough one) Excavator disables Radeon settings when running because it accesses the bios of each card directly. When Excavator completes it restarts Radeon and the box pops up covering the screen. Anyway to auto close or minimize that? Just an annoyance lol

**Comment by aaronsace** [comment]
The AMD part of Excavator is certainly quirky. I may try and just disable the AMD part by default using: '-na'

**Comment by Imaminer** [comment]
I agree. I just removed it. Very unstable and using all the CPU.
Closing this.
