### ISSUE TITLE
Wrapper: Remove unneeded linefeeds

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#306]
To avoid unwanted empty lines in wrapper output change wrapper.ps1: 

`        $Line`
to
`        $Line -Replace '\`t\|\`n\|\`r'`
`$Line -Replace '\`t\|\`n\|\`r'`
(each one sould be backticked, but GH does not display properly...)

**Comment by aaronsace** [comment]
```
$Line -Replace '\`t\|\`n\|\`r'
```

**Comment by aaronsace** [comment]
I wonder if there is a command to write a line without it adding a new line break.

**Comment by UselessGuru** [comment]
> $Line -Replace '\`t\|\`n\|\`r'
That's exactly how I put in GH - but I could not get it to display it properly here :-(. BTW: In PS you do not need to add the backslashes.

**Comment by UselessGuru** [comment]
wrapper.ps1:

`        Write-Host $Line -NoNewline`

Great - works like a charm!
