### ISSUE TITLE
error EthminerNvidia.txt

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#307]
![2017-08-26_002505](https://user-images.githubusercontent.com/30767482/29713986-3221b5b6-89f5-11e7-8517-c08078475d02.jpg)
Incorrect speed display

**Comment by aaronsace** [comment]
Is the live value wrong in the running miners lower down on the screen?

**Comment by aaronsace** [comment]
Can you check if the wrapper text file that is created whist running. Is it updating? What is the value?

**Comment by aaronsace** [comment]
The commas in your language settings also baffle me; never quite sure how it handles them. 

Does this work for you: 

```
$test = [Decimal]"47.19"
$test *= [Math]::Pow(1000, 2)
$test
```

**Output: 47190000.00**

**Comment by scaras** [comment]
same problem here,
it reads the hashrate as one number and not decimals. 
(mining at 39.84MH/s shows 3,98GH/s)

**Comment by aaronsace** [comment]
@scaras what is the output of this on powershell?

$test = [Decimal]"47.19"
$test *= [Math]::Pow(1000, 2)
$test

**Comment by scaras** [comment]
```
PS C:\Users\scaras> $test = [Decimal]"47.19"
$test *= [Math]::Pow(1000, 2)
$test
47190000,00
```

**Comment by aaronsace** [comment]
Can you drop the temp text it creates.

**Comment by scaras** [comment]
don't know what file you need (or where to look for it)
i just spend my free time to learn new things to challenge me (now it is coding ;) )

**Comment by scaras** [comment]
i ran the scrypt in ps ISE and posted the outcome...

**Comment by scaras** [comment]
at my p.o.v. it is the wrapper not looking @ the .  of the hashrate. (but then again, i may have a high iq, coding is relative new to me)

**Comment by spider703** [comment]
but I do not know how to run this command separately and which file to send to you later

**Comment by aaronsace** [comment]
Open powershell and try this: 
```
        $Line = "00:24:49|main  Mining on PoWhash #61df1bd3 : 47.19MH/s"

        if ($Line -like "*total speed:*" -or $Line -like "*accepted:*" -or $Line -like "*mining *:*") {
            $Words = $Line -split " "

            $matches = $null

            if ($Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1))] -match "^((?:\d*\.)?\d+)(.*)$") {
                $HashRate = [Decimal]$matches[1]
                $HashRate_Unit = $matches[2]
            }
            else {
                $HashRate = [Decimal]$Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1)) - 1]
                $HashRate_Unit = $Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1))]
            }

            switch ($HashRate_Unit) {
                "kh/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mh/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "gh/s" {$HashRate *= [Math]::Pow(1000, 3)}
                "th/s" {$HashRate *= [Math]::Pow(1000, 4)}
                "ph/s" {$HashRate *= [Math]::Pow(1000, 5)}
            }

            $HashRate | Out-Host
        }
```

**Comment by spider703** [comment]
47190000,00 that's what he gave out

**Comment by scaras** [comment]
like i posted above... (that was the outcome on the script pane using powershell if that script was tested)

**Comment by spider703** [comment]
So far this has disabled this miner

**Comment by aaronsace** [comment]
So that part of the code is working fine then. It must be a problem with the file or reading it. Post the wrapper text file to GitHub.

**Comment by spider703** [comment]
write the name of the file you need to discard

**Comment by aaronsace** [comment]
It begins with the word wrapper followed by the port number. It it written to continually.

**Comment by spider703** [comment]
removed the programm, instal from scratch, put from those files from the archive that you gave. single added EthminerNvidia.txt From the Miner folder

**Comment by aaronsace** [comment]
No, I mean upload the text file so I can see it.

**Comment by spider703** [comment]
param(
    [Parameter(Mandatory = $true)]
    [Int]$ControllerProcessID, 
    [Parameter(Mandatory = $true)]
    [String]$Id, 
    [Parameter(Mandatory = $true)]
    [String]$FilePath, 
    [Parameter(Mandatory = $false)]
    [String]$ArgumentList = "", 
    [Parameter(Mandatory = $false)]
    [String]$WorkingDirectory = ""
)

Set-Location (Split-Path $script:MyInvocation.MyCommand.Path)

. .\Include.ps1

Remove-Item ".\Wrapper_$Id.txt" -ErrorAction Ignore

$PowerShell = [PowerShell]::Create()
if ($WorkingDirectory -ne "") {$PowerShell.AddScript("Set-Location '$WorkingDirectory'") | Out-Null}
$Command = ". '$FilePath'"
if ($ArgumentList -ne "") {$Command += " $ArgumentList"}
$PowerShell.AddScript("$Command 2>&1 | Write-Verbose -Verbose") | Out-Null
$Result = $PowerShell.BeginInvoke()

Write-Host "MultiPoolMiner Wrapper Started" -BackgroundColor Yellow -ForegroundColor Black

do {
    Start-Sleep 1

    $PowerShell.Streams.Verbose.ReadAll() | ForEach-Object {
        $Line = $_

        if ($Line -like "*total speed:*" -or $Line -like "*accepted:*") {
            $Words = $Line -split " "
            $HashRate = [Decimal]$Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1)) - 1]

            switch ($Words[$Words.IndexOf(($Words -like "*/s" | Select-Object -Last 1))]) {
                "kh/s" {$HashRate *= [Math]::Pow(1000, 1)}
                "mh/s" {$HashRate *= [Math]::Pow(1000, 2)}
                "gh/s" {$HashRate *= [Math]::Pow(1000, 3)}
                "th/s" {$HashRate *= [Math]::Pow(1000, 4)}
                "ph/s" {$HashRate *= [Math]::Pow(1000, 5)}
            }

            $HashRate | Set-Content ".\Wrapper_$Id.txt"
        }

        $Line
    }

    if ((Get-Process | Where-Object Id -EQ $ControllerProcessID) -eq $null) {$PowerShell.Stop() | Out-Null}
}
until($Result.IsCompleted)

Remove-Item ".\Wrapper_$Id.txt" -ErrorAction Ignore

**Comment by scaras** [comment]
[Wrapper_23333.txt](https://github.com/aaronsace/MultiPoolMiner/files/1253618/Wrapper_23333.txt)

**Comment by spider703** [comment]
the program itself refers to an error in the file Include.ps1 line 393

**Comment by spider703** [comment]
Wrapper_23333.txt Does not want to create this file

**Comment by spider703** [comment]
I managed!!!!
in file EthminerNvidia_Ethash_HashRate i delete 00
{
    "Live":  47190000,
    "Minute":  47190000,
    "Minute_Fluctuation":  0,
    "Minute_5":  47190000,
    "Minute_5_Fluctuation":  0,
    "Minute_10":  47190000,
    "Minute_10_Fluctuation":  0,
    "Hour":  47190000,
    "Hour_Fluctuation":  0,
    "Day":  47190000,
    "Day_Fluctuation":  0.13283162658096745,
    "Week":  47190000,
    "Week_Fluctuation":  0.43161865681021072,
    "Updated":  "\/Date(1503750035883)\/"
}

**Comment by spider703** [comment]
now displayed correctly

**Comment by aaronsace** [comment]
Cheers. The file has a comma instead of a dot. I will check this when I get a moment. I think that I should ensure JSON standard.
