### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#308]
Can you release a new version that has the latest updates from the last month?

**Comment by alucard20724** [comment]
Can you release a latest version so i can submit bugs based off that version?... My Nvidia systems no longer updates the "Profit" display so the % number is now pointless.  Doing "profitreset.bat" doesn't solve the problem.  code is all cannabalized(copied) from github, so the version no longer has meaning.

**Comment by aaronsace** [comment]
Just download the full code. I'll mark a release once the last bugs are fixed. Sometime within a week.

**Comment by alucard20724** [comment]
smacks forehead... o_O

**Comment by alucard20724** [comment]
thanks

**Comment by imrecsoka** [comment]
Aaron, is it the best practice to download https://github.com/aaronsace/MultiPoolMiner/archive/master.zip and then run the start.bat or startgb2.bat inside there ?

OR is it better to extract that over an existing old school build like 2.5 the original vanilla version?

**Comment by aaronsace** [comment]
Just run 'start.bat' and it will find the miners online or on your system. If any are missing then check the 'bin' folder.
