### ISSUE TITLE
Can't get nicehash equihash to work

### ISSUE THREAD

**Issue by mikef147** [aaronsace/MultiPoolMiner#309]
MPH benchmarks and shows equihash on a few different miners, but none at all for nicehash.  Other nicehash algos all show up and work fine. The nicehash api looks like it's using the same "equihash" phrase, but I just can't figure out why it's not coming up as an option.  Tried starting a fresh multipoolminer and re-benchmarking but still no go.

**Comment by aaronsace** [comment]
The pools aren't anything to do with the benchmarking. Check your command line options. '-minername' '-wallet'

**Comment by mikef147** [comment]
I think i described it wrong - it doesn't show nicehash as a pool on the list of algos, speeds, profitability for EWBF it only shows MPH. I do see in my history that it did switch to nicehash using EWBF once though.

For example,
EWBF2              Equihash        1.25 KH/s 0.00176 1,407.58088 MiningPoolHubCoins-Zclassic

There is no EWBF line for profitability for NH, since NH profitability should be different than MPH, i thought it would have its own line but may be wrong.
