### ISSUE TITLE
sgminer-gm for cryptonight

### ISSUE THREAD

**Issue by bandit420** [aaronsace/MultiPoolMiner#31]
I have tried to integrate sgminer-gm for the cryptonight algo. It is working via JSON-config. The only downside is the port can not be the autoswitch-port (20580 instead of 17024), for now I just configured it manually.

The next step was the PS-script, but the logic for unzipping and setting the right path is not working in that case. I just copied it from the Sgminer.ps1-script. Could you take a look at it? The download itself and unzipping is working.

The additional parameters just set for my AMD RX480s.

Right now I run a benchmark for all the AMD-algos with the sgminer-gm instead of the sgminer from nicehash to see if its also working.

Theoretically it supports also Equihash and Ethash, but is not as fast as Claymore-Miners.  

[sgminer-gm.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/685725/sgminer-gm.ps1.txt)
[sgminergm.txt](https://github.com/aaronsace/MultiPoolMiner/files/685724/sgminergm.txt)

.

**Comment by aaronsace** [comment]
Interesting, these look nice! I think these will be a great addition. 

This should fix the archive expand: 
`Expand-Archive $FileName (Split-Path (Split-Path $Path))`

Not sure what the issue with the port could be as they both point to the same coin anyway.

**Comment by bandit420** [comment]
The double split was the solution. Thanks!

Yeah should be the same ports, but tried 17024 and 20580 once again. Same results. I think they have only a bitcointalk-thread, but I personally have no account there.

For later use the PS-script:
[sgminergm.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/685866/sgminergm.ps1.txt)

And a log for working algorithms with the sgminergm instead of nicehash-sgminer:
[2017-01-04_09-33-14.txt](https://github.com/aaronsace/MultiPoolMiner/files/685871/2017-01-04_09-33-14.txt)

I have to add: it was tested on Win10 with a 2 core Celeron and 6 RX480, so on a few algos I get like 100% cpu load. Seems to be a general sgminer issue or is maybe connected to the weak CPU.

**Comment by aaronsace** [comment]
Raise an issue on genesis mining and/or let MiningPoolHub know. Must be some sort of connectivity problem as there is only one coin on the port.

**Comment by bandit420** [comment]
Allright, I will raise the issue.

On my working machine there is an i5-6600k running, but still the sgminer is blocking 1 core to the max. I think maybe opening an issue for that, too.
