### ISSUE TITLE
I Launch Multipoolminer or Start and it freezes right away mouse moves super laggy

### ISSUE THREAD

**Issue by bobothemonkey1** [aaronsace/MultiPoolMiner#312]
I'm not sure if it's freezing while it's trying to do the benchmark while also downloading the miners?  I tried editing the start and removing CPU and AMD since im only using nvidia cards but it just seems like it's going super slow.  I left it running after trying to do another fresh install all night woke up it was still lagged out and frozen.  Windows 10 on a gaming PC running 4k graphics on a 1080ti single.  I was planning on moving this software if it worked to all my 6x 1060 mining rigs but i always test on my gaming pc first.  If this sounds like something common plz throw me a line and let me know what im doing wrong.  Thanks either way.

**Comment by bobothemonkey1** [comment]
Are you supposed to launch Start first or Multipoolminer or does it not matter.

**Comment by aaronsace** [comment]
Turn cpu mining off in the command line options. 'start.bat' contains an example command line.

**Comment by bobothemonkey1** [comment]
I am guessing with all the freeze's hard restarted messing with the code a bit I've gone and messed this up so I am going to start again from a fresh install.  Do you recommend opening Start or Multipoolhub when opening it for the first time.  And when you said remove the CPU mining in the command line options which file am I editing or at which point would I get into a command line for this?

**Comment by bobothemonkey1** [comment]
I'm sorry multipoolminer not hub

**Comment by aaronsace** [comment]
You definitely shouldn't get any BSOD. If you have used miners before then you should be able to work it out. MultiPoolMiner miner basically launches the popular miners and switches to the best one. The easiest way to control which miners that you want to use is to go into the folder called 'miners' and delete them.

**Comment by bobothemonkey1** [comment]
Looks like I had a problem download excavator I will try to figure it out before I come back to the thread.

**Comment by aaronsace** [comment]
The link is on the release page.
