### ISSUE TITLE
Understanding the start.bat and startgb.bat 

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#313]
Hi, i have downloaded all your updated files and replaced my old 2.5 version i downloaded here ages ago.
I deleted the stats folder content and i started the Start2gb.bat file.
Took me ages to get the benchmarks through as it was over 1 hour.
I dont really understand the difference between the start.bat and the Start2gb.bat file.
I got a really nice hash rate with the Ether miner for claymore at about 24.5 MH/s
I then also noticed in my console on the miningpoolhub site under balances nothing was really moving?
do i need to wait longer?
Anyway i then thought let me just try the vanilla start.bat as u am used to.... no benchmarks were needed as they were done i guess by the other bat file. I notice now that my EthDcrMiner64.exe is giving me a rubbish MH/s second though:

Setting DAG epoch #145...
21 MH/s

Not sure how this works properly as i see some pools for mining have different EPOCHS.
with the Start2gb.bat run i noticed the Dag thing was like #140 
So i dont understand what the hell is going on.

Please give me suggestions Aaron/anybody, appreciate it

I just want to mine and use what i have to the fullest , i really cant even waste 2-3 MH/s its too precious for me, i am a small fish trying to make a living.

**Comment by imrecsoka** [comment]
Okay wait, forget that what i said about benchmarking, i dont understand this, now all of a sudden for the start,bat it is benchmarking from scratch.
So how do i track the Start2gb   versus the start.bat

**Comment by aaronsace** [comment]
The 'start.bat' is just an example command line.

**Comment by spider703** [comment]
aaronsace I changed your example bat file and use it to start, the first time I ran a benchmark on all the algorithms I selected

**Comment by imrecsoka** [comment]
And what is  Start2gb and why is the  hash rate better by 1 or 2 MH/s for me?
and does it work the same as start.bat ?
I wrote as much information as i could here.... please?
