### ISSUE TITLE
Klaust v8.13 fixes the connection issues - Update your miners until new MPM release is out

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#315]
https://github.com/KlausT/ccminer/releases

**Comment by aaronsace** [comment]
Awesome, will do this sometime this week.

**Comment by imrecsoka** [comment]
1)
Hi, how do you get a new release , i dont really get it.
I download the course code as per Aaron and then i extract and overwrite my existing files.
I do however encounter all sorts of errors when i launch the start.bat , some miners dont work or whatever.
2)
Will Aaron release a complete zipped version like he used to on here?
3)
I am still trying to understand why when ik run startgb2.bat i get better hash rate in claymore's ethereum miner....  by 1 or 2 MH/s
4)
When i run start.bat the rate is worse, how does this work?

Please show me some love here I also donate my machine power and i also want to make this world a better place like micheal jackson.

**Comment by fonyo** [comment]
1. You shouldn't copy over but start fresh to avoid issues/errors.
2. https://github.com/aaronsace/MultiPoolMiner/releases
3. That is for older graphics cards with 2GB or less VRAM. Not all ethash algo coins have reached the 2GB+ DAG files, start2gb.bat will only mine those coins with smaller DAG.
4. The larger the DAG file, the slower your miner will be.
