### ISSUE TITLE
Error when invalid parameters given for miner of type [API=wrapper]

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#317]
An error (file not found) is thrown when an invalid algorithm is selected in a miner of type [API=wrapper].

The error can be suppressed by adding the following line:
```
            if ($_.Process -eq $null -or $_.Process.HasExited -ne $false) {
                $DecayStart = Get-Date
                $_.New = $true
                $_.Activated++
                if ($_.Process -ne $null) {$_.Active += $_.Process.ExitTime - $_.Process.StartTime}
                if ($_.Wrap) {$_.Process = Start-Process -FilePath "PowerShell" -ArgumentList "-executionpolicy bypass -command . '$(Convert-Path ".\Wrapper.ps1")' -ControllerProcessID $PID -Id '$($_.Port)' -FilePath '$($_.Path)' -ArgumentList '$($_.Arguments)' -WorkingDirectory '$(Split-Path $_.Path)'" -PassThru}
                else {$_.Process = Start-SubProcess -FilePath $_.Path -ArgumentList $_.Arguments -WorkingDirectory (Split-Path $_.Path)}
                if ($_.Process -eq $null) {$_.Status = "Failed"}
```
                    elseif ($_.Process.HasExited -eq $true) {$_.Status = "Failed"}

```
                else {$_.Status = "Running"}
            }
```

**Comment by aaronsace** [comment]
Sorry, I don't understand what you have posted. If there is a file missing then you need to get it.

**Comment by aaronsace** [comment]
If it's not just a missing file, please provide more explanation.

**Comment by UselessGuru** [comment]
e.g. CcMinerSP does not support 'hmq1725'

If you were to configure 'CcminerSp-mod.ps1' like 

```
$Commands = [PSCustomObject]@{
    #"bitcore" = "" #Bitcore
    #"blake2s" = "" #Blake2s
    #"blakecoin" = "" #Blakecoin
    #"c11" = "" #C11
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = "" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    "hmq1725" = "" #hmq1725
    #"keccak" = "" #Keccak
    #"lbry" = "" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = "" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    "scrypt-jane" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    #"timetravel" = "" #Timetravel
    #"x11" = "" #X11
    #"x11evo" = "" #X11evo
    #"x17" = "" #X17
    #"yescrypt" = "" #Yescrypt
}
```
CcMinerSP will start briefly and exit immediately because of incorrect parameters, in this case an unsupported algorthm.
Then you will receive an 'file not found error' in 'Get-Stats' because there is no 'Wrapper_$Port.txt' file.

```
            "wrapper" {
                do {
                    $HashRate = Get-Content ".\Wrapper_$Port.txt"
                
                    if ($HashRate -eq $null) {Start-Sleep $Interval; $HashRate = Get-Content ".\Wrapper_$Port.txt"}

                    if ($HashRate -eq $null) {$HashRates = @(); break}

                    $HashRates += [Double]$HashRate

                    if (-not $Safe) {break}

                    Start-Sleep $Interval
                } while ($HashRates.Count -lt 6)
            }
```

**Comment by aaronsace** [comment]
Gotcha.

**Comment by UselessGuru** [comment]
I saw your correction in include.ps1 to suppress the error message.
But what about the failed miner (because of incorrect parameters). Shouldn't it be reported as failed as in my proposed fix?

**Comment by aaronsace** [comment]
The hashrate will be null so the benchmark will fail if it continues to be null. Unless I'm missing something?

**Comment by UselessGuru** [comment]
By marking them as failed I can see that there is a problem with the specific miner config.
Your fix will lead to a null benchmark result -> done.
My proposed fix will make it obvious that the miner is not operational.

**Comment by aaronsace** [comment]
I think what you are proposing goes beyond the wrapper API. I will be implementing a watch dog feature at some point.

**Comment by aaronsace** [comment]
Currently, 'failed' is for if the process has failed and the benchmark (after a few tries) will treat a null hashrate as zero.
