### ISSUE TITLE
startgb2.bat  >> -poolname miningpoolhubcoins

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#318]
Hello, i am not sure still what the start2gb.bat is for as it contains at least one new algorithm and it also has -poolname miningpoolhubcoins

what is this.

Do i still log in to https://miningpoolhub.com to check my balances as per normal ?

**Comment by UselessGuru** [comment]
> Do i still log in to https://miningpoolhub.com to check my balances as per normal ?

Yep
