### ISSUE TITLE
xevan for AMD

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#323]
https://github.com/LIMXTEC/Xevan-GPU-Miner/releases
new!!!

**Comment by aaronsace** [comment]
This is for xevan algorithm?

**Comment by Imaminer** [comment]
Well I'm not Spider703 but I just went and looked and yes its a sgminer fork for xevan.
Im gonna try it out soon.

**Comment by Imaminer** [comment]
Ok added xevan to algo file
Added xevan to start.bat
Made this file sgminerlimextec
File downloaded but did NOT benchmark.
What did I mess up?

. .\Include.ps1

$Path = ".\Bin\sgminerlimxtec\sgminer.exe"
$Uri = "https://github.com/LIMXTEC/Xevan-GPU-Miner/releases/download/1/sgminer-xevan-5.5.0-nicehash-1-windows-amd64.zip"

$Commands = [PSCustomObject]@{
    "xevan" = "--algorithm xevan --text-only -I 12"
    
}

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    [PSCustomObject]@{
        Type = "AMD"
        Path = $Path
        Arguments = "--api-listen -k $_ -o $($Pools.(Get-Algorithm($_)).Protocol)://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_) --gpu-platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | Select-Object -ExpandProperty Vendor), 'Advanced Micro Devices, Inc.'))"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week}
        API = "Xgminer"
        Port = 4028
        Wrap = $false
        URI = $Uri
    }
}

**Comment by Imaminer** [comment]
Working 
![inkedxevan_li](https://user-images.githubusercontent.com/30805282/29886091-e84d334e-8d86-11e7-82d2-3356d8acb794.jpg)

**Comment by aaronsace** [comment]
Nice. Is there any profit in this algorithm?

**Comment by Imaminer** [comment]
Well its new so not yet...but maybe mine with Suprnova and hold coins...
https://bitcointalk.org/index.php?topic=1370307.0
https://bsd.suprnova.cc/
https://bittrex.com/Market/Index?MarketName=BTC-BSD

**Comment by Imaminer** [comment]
Oh and add SuprNova to your list of pools  :P

**Comment by spider703** [comment]
Hi guys. I posted a link yesterday and went to bed, I see you have already figured out for yourself

**Comment by rohitdhaka** [comment]
i don't know how configure start.bat pls full step provide.
sorry for bad eng

**Comment by aaronsace** [comment]
@rohitdhaka  Edit 'start.bat' it in notepad.
