### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#324]
I am getting tired of changing batch files on all the rigs when I want to use a single pool or even change pools.

Instead of -algorithms blah blah blah blah how about remove that completely if you want ALL algo on a pool. Leave as option if you want to be selective.

So if I use -poolname zpool I will get ALL algos on zpool and ONLY mine on zpool
So if I use -poolname miningpoolhub I will get ALL algos on mph and only mine on MPH
So if I use -poolname miningpoolhub,zpool I will get ALL algos on mph AND zpool and only mine on MPH and zpool

No more changing batch files a million times.
Thanks for consideration.

**Comment by aaronsace** [comment]
That's how it works? Is there a bug?

**Comment by aaronsace** [comment]
Just tested now, seems to work.

**Comment by Imaminer** [comment]
Ill try again but in a previous test if I left -algorithm out of batch file and choose a single pool it went to all the other pools anyways.
So testing now no -algo and -poolname zpool
Previous test I got a bunch of mph and HR

**Comment by aaronsace** [comment]
I don't allow people not to exclude MiningPoolHub completely. You can take the wallet out and it won't mine on Zpool but you can't take the username out because I set it to mandatory: 

```
    [Parameter(Mandatory = $true)]
    [String]$UserName, 
```

Feel free to change it to false.

**Comment by Imaminer** [comment]
Understood. I love MPH. I was just gonna throw 100% hash to that new coin on zpool for a while. 
No worries. 
I wish MPH would add new coins faster (or at all)
Closing

**Comment by Imaminer** [comment]
I need to reopen. How do I stop it from mining to NH?
This batch mines to NH, MPH and zpool
I do not want NH

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
timeout 5

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet xxxxxxxxxxxxxxxxxxxxxxx -username xxxxxxxxx -workername Rig2 -interval 60 -region us -type amd -poolname miningpoolhub,zpool -currency btc,usd -donate 60"

**Comment by Imaminer** [comment]
![pools](https://user-images.githubusercontent.com/30805282/29894776-9d00e890-8da4-11e7-8bc8-989ddeb5bf6e.JPG)

**Comment by Imaminer** [comment]
Sometimes the answer is so simple its ridiculous
I just removed the pools I didn't want from the pools folder.

Ok last question. Whats the difference between miningpoolhub and miningpoolhubcoins?

**Comment by aaronsace** [comment]
It's just because Pascal is only found on NiceHash. I would recommend just deleting files as you have done as it's an irregular use case. 

The difference is the ports: 
Simple coin mining (Port 20XXX)
Algo switch mining (Port 17XXX)

**Comment by Imaminer** [comment]
Hub is 17xxxxx
Hubcoins is 20xxxx
? Correct

**Comment by Imaminer** [comment]
Thank you for the fast responses. Have a good one!
