### ISSUE TITLE
Prospector only mining on one GPU

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#325]
toml has all enabled.
here is log

[30_08_17 21;41;33.txt](https://github.com/aaronsace/MultiPoolMiner/files/1265188/30_08_17.21.41.33.txt)

**Comment by aaronsace** [comment]
Have I done something wrong with the toml file?

**Comment by aaronsace** [comment]
Can you delete the toml file then open prospector then post the toml file that prospector creates?

**Comment by aaronsace** [comment]
Never mind, I think I've worked out what I'm doing wrong. I'll fix it tomorrow.

**Comment by spider703** [comment]
i can run 3 my videocard
in the old file changed to and all card working
    [gpus.0-0]
    enabled = true
    [gpus.0-1]
    enabled = true
    [gpus.0-2]
    enabled = true
