### ISSUE TITLE
Re-Open Prospector Issue please

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#326]
Can we re-visit this some more please. I appreciate all your work on this crazy miner lol....
I just tried again with a fresh download of latest code and now Prospector is attempting to start on XMR during bench marking but of course fails because XMR is not supported on GPU's but only on CPU's. 
So this is causing bench marking to take a lot longer as it tries it twice.

And I don't see any code change to fix the only working on one GPU issue for supported algo's.

Thanks again...

**Comment by aaronsace** [comment]
I'll remove xmr if it's not supported yet.
