### ISSUE TITLE
Include code with sgminer

### ISSUE THREAD

**Issue by scrunchds** [aaronsace/MultiPoolMiner#33]
Can you please include the following code before the start of sgminer?

setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_USE_SYNC_OBJECTS 1
timeout /t 4

**Comment by aaronsace** [comment]
Will look into add that somewhere. 
Is there not 4 options that people usually set?

**Comment by Fredar** [comment]
Not sure if every option is great for each algo, but for zec and eth we use these:
```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
```

**Comment by bandit420** [comment]
GPU_FORCE_64BIT_PTR 0
GPU_MAX_HEAP_SIZE 100 is for cards with less then 2GB RAM.

So it would be nice if you can choose 3 cases:

1. only 2GB cards
2. 2GB + 2GB+ on one system
3. only 2GB+ cards

**Comment by bandit420** [comment]
@Fredar 

I have only 8GB cards, can test it later and give some feedback. The worst that can happen is a segmentation fault and the miner does not start.

**Comment by snakethejake81** [comment]
I have an RX 470 8GB rig with six cards, and those five variables Fredar mentioned, are permanently set on it..  I've found no difference in hashing with and without the HEAP SIZE option set.  So I just include it in the bat file i run when starting the MultiPoolMiner script.

Of course sgminer doesn't work at all with these cards on Windows 10 so I don't bother with it at the moment.

**Comment by Fredar** [comment]
I use them on all my rigs with mixed cards and I never had problems.

**Comment by aaronsace** [comment]
Thanks guys, will be added in the next release.

**Comment by scrunchds** [comment]
If you could also add this to eth and zec mining please would be great as well.  Older 2gb cards don't work without it.  The timeout /t 4 command ensures enough time to lock in the settings.  This is due to the fact that once the gpu is accessed the settings are locked in.

**Comment by scrunchds** [comment]
By the way keep up the good work!  It is good to see a good aglo switching program other that nice hash.

**Comment by buntakunfumoffu** [comment]
hi, your program is wonderful.
Maybe you can add an algorithm variable for sgminer ?

**Comment by aaronsace** [comment]
Thanks 😀
Like a filter so it only mines certain algorithms?

**Comment by buntakunfumoffu** [comment]
No for additional command like : rawintensity, worksize, gpu-threads.
example : cryptonight.sgminergm.options = -rawintensity 512 -w 4 -g 2

**Comment by aaronsace** [comment]
Ah, I see. Ye, people have issues adding custom commands. The only way to do it currently is it edit the files in the 'miners' folder but it's not very clear.
