### ISSUE TITLE
Excavator....sigh

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#332]
![phyfail](https://user-images.githubusercontent.com/30805282/29997604-63b20270-8fe5-11e7-9ec6-9286ea12bb21.JPG)

I added phymem to admin group. That didn't work.
So I went ahead and marked Excavator.exe as needed Admin rights.
Now it fired up error free but produced zero hashes.
After about 1 minute of running a second copy of Excavator opened and that crashed the rig.
My gut feeling is this was ONLY written to work with NiceHash as its their tool. I didn't try NH.

So until I see you announce you got it working on AMD rigs to MPH I think I will avoid it lol.
It has great potential but seems proprietary to NH.

Keep trying :)

**Comment by aaronsace** [comment]
It is still in the early stages; I think it's going places so it's definitely worth keeping support.

**Comment by Imaminer** [comment]
Agree. I had it running when i used the NH miner tool and Excavator was faster then Claymore.
