### ISSUE TITLE
Nicehash Wallet

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#333]
Hi, since nicehash pool is being implemented would it be possible to add the it's own wallet to take advantage of the fees.

**Comment by scaras** [comment]
ad these lines at the top (below other $wallet string) of multipoolminer.ps1
```
    [Parameter(Mandatory=$false)]
    [String]$Wallet_Nicehash = "your_nicehash_wallet",
```
and change the next lines in ./pools/Nicehash.ps1
` User          = "$Wallet.$WorkerName"`
to
` User          = "$Wallet_Nicehash.$WorkerName"`

**Comment by AcharyaOne** [comment]
Awesome!
