### ISSUE TITLE
I3-7100t and nvidia 1070

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#335]
I like to let it run all the miners but many cpu miners fail with hanging message, and some gpu miners also fail like gatelessgate and reorder (and some others) , can someone test if it's only me?
(8gb ram with 32gb page file)

**Comment by aaronsace** [comment]
The latest code commits skip past hanging miners. Not all miners will work on your system.

**Comment by aaronsace** [comment]
I'll be updating the release version today so that it matches.

**Comment by AcharyaOne** [comment]
Thanks, I'm using the master branch but I wasn't sure if it was skipping it right
