### ISSUE TITLE
Todays Fix and Claymore missing .dll

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#336]
Fresh install of recent code all rigs fail on claymore missing libcurl.dll
All rigs can run Claymore fine outside of MPM

Strange

![eth](https://user-images.githubusercontent.com/30805282/30004053-475a8fdc-9096-11e7-92eb-60796153b42a.JPG)

**Comment by aaronsace** [comment]
You need to make sure all the files are in the bin folder: 
https://bitcointalk.org/index.php?topic=1433925.0

**Comment by Imaminer** [comment]
ok I'll check it out. I guess I will edit the miner file too and change to new version while I'm at it

**Comment by aaronsace** [comment]
I've set it up for version 10 but I don't include '.exe' files in the source.
