### ISSUE TITLE
No Gateless?

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#338]
What a shame. I will add it back on mine. I like it. Until Excavator works better anyways....

**Comment by aaronsace** [comment]
It was going to be an awesome miner but there is simply nobody developing it. Excavator is great for NVidia and it will be great for AMD once zawawawa fixes BSOD issue when it runs in admin mode. Nothing beats Claymore for AMD anyway.

**Comment by Imaminer** [comment]
Cool. Glad to hear Excavator is making progress
