### ISSUE TITLE
nvidia algorithm suggestions

### ISSUE THREAD

**Issue by Nebiforever** [aaronsace/MultiPoolMiner#339]
i want to mine on only miningpoolhub (no dual mining with another pool or etc) with nvidia based rigs.

when i remove the algorithms command from bat file, it adds all algorithms an all pools automatically.

if i add or remove them manually it takes some time and doesnt look practical.

any algorithm suggestions for nvidia rigs someone can offer me ? (especially profitable for pascal based systems)

**Comment by aaronsace** [comment]
Either specify the algorithms that you want to mine or remove your wallet.

**Comment by Nebiforever** [comment]
ok thanks it needs to be manually than

btw last release connects to wrong region for some algorithms 
example: bat file is europe
scrypt connects to asia for equihash, europe for ethash
