### ISSUE TITLE
Master issues

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#341]
I'm trying running the latest master release but it stays benchmarking excavator forever with no numbers being retrieved. Also fireice wouldn't run on 2 1070 (I'm running 8) so I changed the threads, blocks, bfactor, bsleep to 19, 60, 0, 0, now it works again.  Not sure what is optimal for those gpu.

**Comment by AcharyaOne** [comment]
Not sure if prospector has the same problem on benchmarking forever, I think it has.

**Comment by AcharyaOne** [comment]
Also, the profit isn't being well calculated for multipoolminer, more than double it seems.
Side note: Nanashi, Palgin, Nsgminer don't work on my 1070's, have no idea why.

**Comment by aaronsace** [comment]
Apologies; somehow made a mistake on the temporary excavator pool fix; will push a commit today. 

Just checking now but I think prospector works and it's just Excavator holding up the benchmark. 

Nanashi, Palgin, Nsgminer work on 1080 ti. Do they work if you run those miners manually? Also, are the miner binaries complete (no files missing)?

**Comment by UselessGuru** [comment]
To make testing easier:
```
...
        $ActiveMiners | Where-Object Best -EQ $true | ForEach-Object {
            if ($_.Process -eq $null -or $_.Process.HasExited -ne $false) {
```
Insert the following line to create a cmd file for each executed miner combo:

```
                "$(Split-Path $_.Path -leaf) $($_.Arguments)" | Set-Content ((Split-Path $_.Path) + "\" + $_.Name + "_" + ($($_.Algorithm | ForEach-Object { ($Pools.$_.Name + "_" + ($_))}) -join "-") + ".cmd")
```

```
                $DecayStart = Get-Date
                $_.New = $true
                $_.Activated++
                if ($_.Process -ne $null) {$_.Active += $_.Process.ExitTime - $_.Process.StartTime}
                if ($_.Wrap) {$_.Process = Start-Process -FilePath "PowerShell" -ArgumentList "-executionpolicy bypass -command . '$(Convert-Path ".\Wrapper.ps1")' -ControllerProcessID $PID -Id '$($_.Port)' -FilePath '$($_.Path)' -ArgumentList '$($_.Arguments)' -WorkingDirectory '$(Split-Path $_.Path)'" -PassThru}
                else {$_.Process = Start-SubProcess -FilePath $_.Path -ArgumentList $_.Arguments -WorkingDirectory (Split-Path $_.Path)}
                if ($_.Process -eq $null) {$_.Status = "Failed"}
                elseif ($_.Process.HasExited -eq $true) {$_.Status = "Failed"}
                else {$_.Status = "Running"}
            }
...
```

**Comment by AcharyaOne** [comment]
Don't apologize, you've put a lot of work into this, thanks uselessguru, will try that.

**Comment by AcharyaOne** [comment]
Just tried this one yet
![image](https://user-images.githubusercontent.com/31579891/30038459-b7aea1f2-91bc-11e7-93ca-e52b4766596f.png)
I am using the integrated graphics as primary display and with cuda 8 and it's patch installed, have no idea how to solve this. I've googled and it seems some people have the same problem.

**Comment by aaronsace** [comment]
If TPruvot works, maybe you should submit an issue with each effected miner on GitHub?

**Comment by AcharyaOne** [comment]
ok, I will, and pheraps will try disabling the integrated graphics, I suspect it could be that.

**Comment by AcharyaOne** [comment]
Should I have cuda installed? I think I will try latest drivers as I was using 382.53

**Comment by aaronsace** [comment]
I think I'm just using the drivers from windows update: 384.76

**Comment by AcharyaOne** [comment]
Good news, palgin and nanashi now work with latest driver of nvidia 385.41, I didn't install cuda this time.
But Nsgminer gives this message
![image](https://user-images.githubusercontent.com/31579891/30056392-6c4bc30c-922a-11e7-97f3-ae8be0f166b3.png)
Maybe the problem is just my rig.
The profit displayed is still more than double, could you check that?

**Comment by aaronsace** [comment]
That's great. 

I wouldn't worry too much about nsgminer. 

What's wrong with the profit though?

**Comment by AcharyaOne** [comment]
The section in the bottom which gives the information about what multipoolminer is making more in profit it says 52€ and the actual miners less than 20€

**Comment by AcharyaOne** [comment]
![image](https://user-images.githubusercontent.com/31579891/30062753-2a9c3e36-9244-11e7-8ff1-bafd8c205aa4.png)
this appears time to time, when it refreshes it goes away, can this error be ignored?

**Comment by aaronsace** [comment]
Odd, I thought error action would hide that: 
https://github.com/aaronsace/MultiPoolMiner/blob/74583e982f9263b2768102e1f5766fa9f74f3037/Miners/Prospector.ps1#L48

**Comment by aaronsace** [comment]
@AcharyaOne Are you comparing against your earnings on http://MiningPoolHub.com? I applied a temporary fix so you should be having any problems. 

I'm going to push a different update that should help with Zpool.

**Comment by AcharyaOne** [comment]
It's just what it shows in the console of multipoolminer, can you point me to the file fix maybe I'm missing something.

**Comment by UselessGuru** [comment]
> The section in the bottom which gives the information about what multipoolminer is making more in profit it says 52€ and the actual miners less than 20€

This may happen if something goes wrong with 'Get-Hashrate' when there is a problem with mixed up port numbers.
I suggest you delete the profit files and re-benchmark.

**Comment by AcharyaOne** [comment]
I deleted all stats and started again, tx

**Comment by AcharyaOne** [comment]
It seems the stats for claymore/sia are broken

**Comment by AcharyaOne** [comment]
Could you check it please?

**Comment by AcharyaOne** [comment]
The latest include.ps1 you updated fixed it :)

**Comment by AcharyaOne** [comment]
Seems not all stats are working, like claymore_sianicehash and ewbf

**Comment by AcharyaOne** [comment]
Using latest changes in master:
![image](https://user-images.githubusercontent.com/31579891/30513429-e3ff832e-9afa-11e7-8f01-475e57d92490.png)
It seems all the txt miner files don't work, maybe I'm doing something wrong, I'm not sure,
