### ISSUE TITLE
Changes Questions

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#342]
Lots of changes fast. Thats great!
I'm trying to keep up lol.
I assume by reading the code Excavator is right now for NiceHash and maybe Zpool?
Also I see you changed to MPHcoins in bat instead of MPH.
Why?
And lastly I see new algo's in bat that are not in algo file. Are these specific to NH and Excavator?

Generally I dislike NH but when the coin profit gets this low they often are the highest paying. So just trying to understand changes before trying.
Thanks

**Comment by aaronsace** [comment]
I've had to hack the pool files a bit because of this breaking bug: 
https://github.com/nicehash/excavator/issues/51

Regarding MPHcoins: Ethash2gb is a lot faster on AMD cards and you should see it's actually more profitable than mining Ethereum!

NiceHash pools have lower profit but you can milk their buyers on the low times.

**Comment by AcharyaOne** [comment]
Sorry but does it mean that nvidia users should keep MPH instead of MPHcoins?

**Comment by Imaminer** [comment]
Trying all the new stuff now on AMD. But I dont want any NH so just remove those algos and pool?
Makes sense to me....

**Comment by aaronsace** [comment]
You can keep your command line that you were using in the previous versions. I don't think I have made any breaking changes except rename 'location' to 'region'.

**Comment by Imaminer** [comment]
I dont understand Ethash2gb. Its not in the algorithm file, not in the pool file but yet its listed in the start.bat as an algo. Confused

**Comment by aaronsace** [comment]
The algorithm.txt file is just a thesaurus; it's not actually used to control anything.

**Comment by Imaminer** [comment]
I did not understand that! Thanks
