### ISSUE TITLE
CPU Miner TPruvot Lyra2RE2

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#346]
The argument the miner takes to mine this algo is lyra2v2 which is the same parameter at zpool but at miningpoolhub the algo parameter is lyra2re2, I don't know how to adapt the miner script for this difference.

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    [PSCustomObject]@{
        Type = "CPU"
        Path = $Path
        Arguments = "-a $_ -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week}
        API = "Ccminer"
        Port = 4048
        Wrap = $false
        URI = $Uri
    }

**Comment by aaronsace** [comment]
Use: 
`Get-Algorithm "lyra2v2"`

**Comment by aaronsace** [comment]
Just copy 'CpuminerTpruvotAvx2.ps1'

**Comment by AcharyaOne** [comment]
After some testing I realized I brought up a false issue, sorry, my bad but thanks for the tip.
