### ISSUE TITLE
New Miner Alert

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#349]
https://bitcointalk.org/index.php?topic=2146605.0

I will try it later today

**Comment by jjziets** [comment]
why would one even bother to run this. surely this will just steel hash-rate. no source to check that I can see.

**Comment by fonyo** [comment]
Apparently it is slower than Claymore. Posted by newbie account.

**Comment by Imaminer** [comment]
I had some success with the new version released this morning. For my AMD cards it matched Claymore v.10 speeds.
Many are testing the fee thing and if its stealing shares. 
Might end being a good alternative to Claymore. Competition is good.
Dual mining is also being discussed. Now that would be interesting!

**Comment by UselessGuru** [comment]
For those who want to try:

[eminer061rc2.txt](https://github.com/aaronsace/MultiPoolMiner/files/1320883/eminer061rc2.txt)

It also requires an enhancement to function 'Get-HashRate' in 'include.ps1':
```
...
            "eminer" {
                do {
                    $Request = Invoke-WebRequest "http://$($Server):$Port/api/v1/stats" -UseBasicParsing -TimeoutSec $Timeout
                    
                    $Data = $Request | ConvertFrom-Json
                    
                    $HashRate = $Data.total_hashrate_mean

                    if ($HashRate -eq $null) {$HashRates = @(); break}

                    $HashRates += [Double]($HashRate | Measure-Object -Sum | Select-Object -ExpandProperty Sum)
                
                    if (-not $Safe) {break}

                    Start-Sleep $Interval
                } while ($HashRates.Count -lt 6)
            }
...
```

**Comment by aaronsace** [comment]
@UselessGuru Your name should be useful guru. 

https://github.com/aaronsace/MultiPoolMiner/invitations
