### ISSUE TITLE
problem in new version on cpu miner

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#353]
The CPU does not switch to a more profitable algorithm. for example, the cryptonight is extracted, the yescript became more profitable, and the switchover did not happen until manually closing the miner

**Comment by aaronsace** [comment]
That's add to see anything more profitable than Cryptonight. It was most likely not above the switching threshold.

**Comment by aaronsace** [comment]
I'll be pushing an update to the stats as soon as I've finished that should help with all the miners.

**Comment by spider703** [comment]
the difference between 0.00008 and 0.00052 I think it's essential to switch to it, but the miner switched in five minutes only

**Comment by aaronsace** [comment]
That is a large difference. 
Can you drop the log file(s) onto GitHub?

**Comment by spider703** [comment]
I turned off the log files. I'll see how it works for a couple of days, if it's the same, then I'll turn on the log files for you

**Comment by spider703** [comment]
log files 
[2017-09-08_20-34-16.txt](https://github.com/aaronsace/MultiPoolMiner/files/1287311/2017-09-08_20-34-16.txt)
and what he want from me, what dns-name in Excavator should be
![2017-09-08_205005](https://user-images.githubusercontent.com/30767482/30204218-b5f43088-94d8-11e7-902f-7ba83be49601.jpg)
