### ISSUE TITLE
Change yiimp to http://yiimp.eu/

### ISSUE THREAD

**Issue by rhadamants** [aaronsace/MultiPoolMiner#354]
Change yiimp to http://yiimp.eu/

**Comment by AcharyaOne** [comment]
<WALLET_ADDRESS> should be valid for the currency you mine. DO NOT USE a BTC address here, the auto exchange is disabled!
As optional password, you can use -p c=<SYMBOL> if yiimp does not set the currency correctly on the Wallet page.

**Comment by aaronsace** [comment]
@rhadamants If you want to add Yiimp; just copy the zpool file and edit from there. As @AcharyaOne said though, you can't use BTC so you'll need a load of wallets from an exchange.
