### ISSUE TITLE
Powershell CPU usage high

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#355]
After a while it starts mining it gets like this:
![image](https://user-images.githubusercontent.com/31579891/30189991-3309e2de-942f-11e7-9a8b-dd633536ce4b.png)
is it possible to decrease cpu usage from powershell?

**Comment by aaronsace** [comment]
Speed improvement will come in the next update. 

Please not though that it is doing nothing for 60 seconds so that CPU usage will go up and down.

**Comment by fonyo** [comment]
I have been monitoring MPM's performance and I believe there is also a memory leak. I am consistently getting the following results. 2 days after launch, powershell reports over 1.5GB of memory used. This increases to over 3GB after 4 to 5 days. The reason I have not noticed this before is that my mining rigs are set to reboot once every day. My standard workstation with 3 AMD cards, however, that is often left running for months without a reboot, has made me realise there are issues with high memory usage while MPM is left running for longer periods such as weeks. I am testing now how high it will go and post my results.

**Comment by aaronsace** [comment]
'.net' performs garbage collection itself; I don't believe that MultiPoolMiner is creating any unmanaged objects. If anyone knows as to what is using all this memory then please post your findings.

**Comment by fonyo** [comment]
Just within the 3 hours since I posted, PowerShell has gained 0.5GB in memory usage. Win7 64bit. CPU usage is moderate, it takes a core away for a few seconds per minute before memory usage increases by roughly 10-15 megs. 

Still ways to go before it eats up all my 16gigs. I wish I could help more with this one but I can only post findings.

**Comment by aaronsace** [comment]
Possible memory problem that may be prevent the memory being released once the function closes (it also could be nothing to do with it): 

```
$Client = New-Object System.Net.Sockets.TcpClient $server, $port
$Writer = New-Object System.IO.StreamWriter $Client.GetStream()
$Reader = New-Object System.IO.StreamReader $Client.GetStream()
#do something
```

This would be better: 
```
$Client = New-Object System.Net.Sockets.TcpClient $server, $port
$Stream = $Client.GetStream()
$Writer = New-Object System.IO.StreamWriter $Stream
$Reader = New-Object System.IO.StreamReader $Stream
#do something
$Stream.Close()
$Client.Close()
```

**Comment by fonyo** [comment]
Sorry, just noticed I was quite off-topic when we have this one:
https://github.com/aaronsace/MultiPoolMiner/issues/276

**Comment by fonyo** [comment]
Let's just stick to original title for the records.
