### ISSUE TITLE
As I figured it was on my end.  I got it working 1 other question about multi gpu unit

### ISSUE THREAD

**Issue by bobothemonkey1** [aaronsace/MultiPoolMiner#358]
So I got it up and running once I wiped windows and got rid of whatever the problem was you were right it takes a long time!  Do you see a socket 1150 celleron 2.8 with 4gb unbuffered ddr3 pushing 6x 1060's being able to handle this program I'm guessing there is alot of memory being thrown around while its all downloading and benchmarking but I wouldn't know.  I got it work on my 4k gaming PC which I always use as a tester.  If you think there will be any issues moving it onto that platform could you please let me know.  Also  I am a bit confused about the -wallet line since this is mining poolhub shouldnt the username be sufficient or is that for another coin not on hub if so please explain.  Thanks so much I will definately send you a tip do you have a eth address?

**Comment by aaronsace** [comment]
It should work on any system. It is setup to handle 6 GPUs and a CPU but you may get better performance disabling the CPU in the command line. All the backup pools require a bitcoin wallet; I recommend you enter one. To set MiningPoolHub as the main pool, remove the other pools from the command line. 

Appreciate anything, it takes a considerable amount of my time. 
My eth address: 0xB87CBE890Ac8cB236852cbAF5F86A0e6f93f5B90

**Comment by bobothemonkey1** [comment]
Rock on man your a legend. Eth incoming

**Comment by bobothemonkey1** [comment]
It's about half way thru benching on the first gpu unit with no issues!  So your answer made me think I was misunderstanding this a bit.  Do you offer the use of different pools because those pools might support different coins than the others?  So I would have to goto those pools and register the same credentials for the username workernames?  Or is it like a failsafe system in case one of them goes down?

**Comment by bobothemonkey1** [comment]
Oh and also since your dealing with multiple algorithms any recommendations on the overclock/powertarget settings.  I was set up for eth running them all at 0/+650 with a 70%target power.  Ideal for Eth but maybe will impact the other coins, what do you think?

**Comment by aaronsace** [comment]
All the pools offer varying coins that also overlap to provide a failsafe. 
Not done any clocking on NVidia but on AMD just lowering the voltage slightly (reduces production of heat) and upping the speed limit on the fan (increase removal of heat) is all that's needed. As long as your cards are 100% stable then your settings will be fine.
