### ISSUE TITLE
Nanashi miner lyra2z

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#359]
So I was looking at the dashboard of miningpoolhub and noticed that hashrate never goes beyond 9mh/s when nanashi miner shows 14mh/s and as such the profit is very low of what was to be expected, anyone with same situation?
![image](https://user-images.githubusercontent.com/31579891/30245465-658c126e-95d2-11e7-825d-2f695ddaa79e.png)
![image](https://user-images.githubusercontent.com/31579891/30245469-7a3cad5e-95d2-11e7-950e-703b20770947.png)
![image](https://user-images.githubusercontent.com/31579891/30245472-963b116c-95d2-11e7-90c3-8fe31a77f64f.png)

**Comment by aaronsace** [comment]
On the screen that you are on, the pool is measuring your share submissions over 5 minutes and the share difficulties are variable. Check the daily graphs at MiningPoolHub; it will give you a longer running picture of the speed.

**Comment by AcharyaOne** [comment]
Thanks for your reply, I can not longer check the graph of 2 days ago but the max profit was 0.88 zcoin in 24h which I bit more than half than it should be when mining at 14mhs. But I'll keep that graph in mind next time to make sure of the hash rate.

**Comment by AcharyaOne** [comment]
I've been watching the graph and I never goes above 9mhs despite Nana shipping reporting 14. I disabled it and the next miner reports 10 and and graph doesn't go above 5. Something is not right with miningpoolhub

**Comment by aaronsace** [comment]
I recommend reporting it to the miner developer and the pool as it's not something I would be able to help with.

**Comment by AcharyaOne** [comment]
I understand that, I was just trying to share my results have somebody confirm it. Is there a way to force lyra2z mining on zpool to test it?

**Comment by fonyo** [comment]
Let's just stick to original title for the records.

**Comment by AcharyaOne** [comment]
I deleted it because after being ignored I got even trolled, I won't bother posting again.

**Comment by aaronsace** [comment]
@AcharyaOne Nobody has trolled you on the issue here but anyway best not deleting posts as it's confusing when looking back at this.

**Comment by fonyo** [comment]
Can you please elaborate on the trolling issue further and explain what we can do to help you or what is expected of us?

**Comment by aaronsace** [comment]
@fonyo They didn't get an answer they wanted in time so they overacted and deleted all the posts. 
@AcharyaOne Post a new issue to report a bug or request a feature. Everyone is being as helpful as possible. 

This is not a forum; it's an issues tracking page.
