### ISSUE TITLE
Doubled Hashrate on Cryptonite while reading via xgminer

### ISSUE THREAD

**Issue by bandit420** [aaronsace/MultiPoolMiner#36]
While reading the hashrate of sgminer on cryptonite the value is doubled (average per 5s and average is added up it seems).

![1](https://cloud.githubusercontent.com/assets/24902401/21729933/9743701e-d44d-11e6-8f0f-5f4ebdb5daaf.PNG)

So there is a hashrate of 8 Kh instead of 4Kh.

Thats the script I used to test it:
[sgminergm.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/690631/sgminergm.ps1.txt)

Btw port-issue is fixed, so sgminer is also working on port 17024, it was a poolside issue.

Sgminer is also crashing on cryptonight when parameters are not speciefied (rawintensity, worksize).

**Comment by d-rays** [comment]
Apparently the hashrate is doubled on all algorithms with Sgminer, not only with Cryptonight.
At least it is definitely doubled on Neoscrypt, Ethash and Equihash for sure.

**Comment by aaronsace** [comment]
I confirm you are correct, there was an error between builds. (It's adding MH and KH by mistake in the include.ps1 file)
I'm rewriting this code anyway. Thank you for reporting the bug.

**Comment by aaronsace** [comment]
I've pushed a fix on the code. Download the 'include.ps1' file.

**Comment by bandit420** [comment]
In 2.2.3 with the new include there is the following error-message:

+ $AllPools = if(Test-Path "Pools"){Get-ChildItemContent "Pools" |  ...
+ CategoryInfo          : ObjectNotFound: (Get-ChildItemContent:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

Tried it with the current master-branch:

+ CategoryInfo          : ObjectNotFound: (C:\Users\user\...\ZecMiner64.exe:String) [Convert-Path], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ConvertPathCommand

But anyway, keep up the good work and let me know if you need further infos.

**Comment by aaronsace** [comment]
Sorry, just got onto my machine to test; it seems to be fine. 
I've updated the release to 2.3.1 and attached a new zip file; it seems to be working (I only changed 1 line).
