### ISSUE TITLE
which btc address should I use

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#362]
I see the new 2.6 has a bitcoin address. I assume this is the address used by zpool and nicehash for the payouts?

I have 6 rigs so the payout should be frequently and as the btc network charge is high i would like to avoid that.

Am I right that using nicehash address is recommended? I see they have a zero charge for deposits and one can see the pending balance. 

The alternative is using an exchange address.

**Comment by jjziets** [comment]
would be nice if the readme was updated

**Comment by aaronsace** [comment]
You can put any Bitcoin address you want to or not enter one; it's up to you.
