### ISSUE TITLE
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#365]
I get a lot of red rolling text, See below. how do I fix this? with 2.6.0.2 and Nvidai 1070 rigs

```
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
At C:\MultiPoolMinerV2.6.0.2\MultiPoolMiner.ps1:211 char:29
+             (Compare-Object $_.Algorithm ($Miner.HashRates | Get-Memb ...
+                             ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

**Comment by aaronsace** [comment]
I can't think as to why Algorithm would be null. 

Are you using an intact files? Please try downloading it from scratch and run 'start.bat'.

**Comment by jjziets** [comment]
could it be my start string? 

Tested the zip. it is fine. also downloaded just.for. still the same

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -username Etherion -workername wk1 -ssl -region europe -currency btc,usd,eur -type nvidia -poolname miningpoolhubcoins,zpool,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sib,Lyra2RE2,MyriadGroestl,skein -donate 10"

**Comment by aaronsace** [comment]
I can't reproduce this error. How often are you getting it? 

I downloaded the release from GitHub and launched with your exact command line. It went through the whole benchmark and is running without error.

**Comment by jjziets** [comment]
O this is frustrating.

It is doing this on all my rigs and I have run out of options.

I have even gone so far as to re install windows 10. Most of m,my rings run 10 but one runs 7.

The 7 in another location. 
Windows 7. Fiber network (Different ISP than a farm) and using AMD cards. Downloaded the zip and then I updated all the MSV files. updated power shell. Same problem. 

windows 10 with 6 Nvidia card. ASDL network.
deleted the folder and downloaded your miner again. 
Made the folder short. 
set the path. 

used your standard script.

here is a log file https://www.dropbox.com/s/11jp2qddbxf91dx/2017-09-12_22-30-44.txt?dl=0

 


```
C:\MultiPoolMiner>powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -username Etherion -workername wk2 -ssl -region europe -currency btc,usd -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sib,Lyra2RE2,MyriadGroestl,skein -donate 1"
Transcript started, output file is .\Logs\2017-09-15_12-13-06.txt
ConvertFrom-Json : Invalid JSON primitive: .
At C:\MultiPoolMiner\Include.ps1:127 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

**Comment by jjziets** [comment]
I see it everytime the script updates.

**Comment by aaronsace** [comment]
In the folders called 'miners'; delete all the files accept for one miner and see if the error stops.

**Comment by aaronsace** [comment]
Just got access to a computer; your log has miner files that aren't part of the release. 

Definitely try remove files like I said on the post above as I think there is something wrong with some of them files loading.

**Comment by jjziets** [comment]
a simple thing as extracting the zip and overwriting the folder vs delete folder and extract new...  way to much time wasted. 

thanks for the good work :-)

**Comment by aaronsace** [comment]
Ah, that would be it.
