### ISSUE TITLE
massive variance between identical miners - causing diffrent coins to be mined.

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#37]
each miner has same 4 GPU as same speed/spec/setup
actual speed is 1.1GH but you seems to round to whole numbers for some odd reason.

Rig1
   Type: AMD

Miner    Algorithm      Speed BTC/Day  BTC/GH/Day Pool
-----    ---------      ----- -------  ---------- ----
Reorder  Skein         1 GH/s 0.00730     0.00582 MiningPoolHub

Rig2
   Type: AMD

Miner    Algorithm      Speed BTC/Day  BTC/GH/Day Pool
-----    ---------      ----- -------  ---------- ----
Reorder  Skein         1 GH/s 0.00405     0.00363 MiningPoolHub

Both are same hardware 

Both have been running v2.3 for same time.

It seems to be the BTC/GH/DAY throwing it out, removing the reorder hash rate file didn't help I had to remove the profit file.

Now they both have the same fig in BTC/GH/DAY

Reorder  Skein         1 GH/s 0.00565     0.00505 MiningPoolHub
Reorder  Skein         1 GH/s 0.00564     0.00505 MiningPoolHub

**Comment by boysie123** [comment]
its possible while they have both been running from the same time that they were up at different times, eg one failed and missed updating from some data, it looks like you build the profit file based on polled data points and apply math to it to try and normalise the probable profit over time. how ever this seems to suggest that this can cause lrg different between rigs that poll at different times or amt of times depending on if they are up or failed for any reason.

So this would mean you need either the pool side to provide the data on each poll or for a (hosted web service) ref point to provide the collected data points/math calc externally of the miner which can be thrown out by missing data points while down.

eak

**Comment by aaronsace** [comment]
It's based on the current live figure and a 24 hour average. It's not just chasing fleeting profits but sustainable coins to mine. 

Low fluctuating prices are mostly based on the live figure. 
High fluctuating prices are based more on the average figure. 

I'm currently fixing the weighting issue that is applied to new data after a rig has been down.

**Comment by boysie123** [comment]
awesome glad you know what you are doing :)
