### ISSUE TITLE
mpm shows mining one aglo but running anotehr

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#371]
so at this moment lyra2z  is most profibile but  NVIDIA-TPruvot\ccminer-x64.exe is running. but yet the status sows CcminerKlaust-MyriadGroestl

![image](https://user-images.githubusercontent.com/19214485/30509851-d4a968ae-9ab9-11e7-950b-239a52eaa47e.png)

2.6.0.2

**Comment by aaronsace** [comment]
You're miss reading it; the bottom stats are averages over 1 week. You have probably made changes to the configure so you need to run the profitreset.bat if you want that last table to show a comparison.

**Comment by jjziets** [comment]
AAA. Ok I thought it was average top currency bottom5
