### ISSUE TITLE
Resolve-DnsName, lots of errors when starting fresh

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#372]
[2017-09-16_13-49-36.txt](https://github.com/aaronsace/MultiPoolMiner/files/1308334/2017-09-16_13-49-36.txt)

**Comment by fonyo** [comment]
I deleted the Excavator miner file btw

**Comment by fonyo** [comment]
Closing this as I realised what the problem was.

**Comment by winnal** [comment]
What was the problem?... I'm getting the same thing.

**Comment by fonyo** [comment]
Excavator needs to be downloaded. Or the miner files deleted.
