### ISSUE TITLE
how can selling to nicehash be more profitable than mining direct.

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#374]
between zpool and miningpoolhub you have most if not all the coins that is listed on nicehash. But for some reason my miners keep on mining to nicehash

NeoScrypt
Equihash
Lbry

just a few examples. 

I would understand that for a short time some a buyer on nicheash will pay more than what he will get mining the a coin but that is not going to be true for long.

for example Equihash can not be more profitable to mine on nicehash than mining the coins directly.

Nicehash takes 3% on the buyers side and 3% on the sellers side. Then the buyer still needs to make profit. I have used nicehash to buy hashpower so it should be between 5-10% less profitable to sell to nicehash than mining the same coin directly. 

Are you sure you are the calculating the value of hashrate right from nicehash?

Also mining to nicehash you the worker does not get the max one can get, ever worker get what the order is willing to pay. which can be a lot lower than the average. assuming your working on the average then 50% will be getting less and 50% get more.

**Comment by scaras** [comment]
not all people like to spend all there time to check the markets, make all the wallets (or keep there coins on poloniex, bitrex, ...) this is a easy way to autoexchange to bitcoin. you can always delete the nicehash pool file if you don't want to mine to them. (but if you have a nicehash wallet, it is a way to get some btc to rent hashpower from them)

**Comment by aaronsace** [comment]
This is staying as is. Buyers do at times pay nonsensical amounts and is their loss. NiceHash is great for noobs and as a backup. I recommend just taking NiceHash out of the command line if you want to avoid using them.

**Comment by jjziets** [comment]
I have not a problem getting more than what it's worth, but I am just pointing out something illogical.

![image](https://user-images.githubusercontent.com/19214485/30524405-702e3e82-9bf3-11e7-8619-e37375580805.png)
In the imaged Equihash it linked to nicehash. Will the pool change if it is more profitable to mine on zpool/mph?

![image](https://user-images.githubusercontent.com/19214485/30524425-bd3198f0-9bf3-11e7-910f-a2814c234c30.png)

This really does not make sens.

**Comment by fonyo** [comment]
Everything seems to be fine on the screenshots. BTC/GH/day is normalised data which is needed for calculation and to compare profitability. Every algorithm hashes differently. You would get little to none with a few gigahash when mining BTC (SHA-256), where a few gigahash would earn you more than a living when mining ie. Vertcoin (Lyra2 Reduced Efficiency 2).
