### ISSUE TITLE
FireIce Question

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#375]
Why is FireIce running a different thread per GPU?
I have 5 cards per rig so FireIce is taking 1% per card.
Can't it be configured to run like every other miner in the world?
Just wondering....

**Comment by fonyo** [comment]
If you ran one instance for five cards or five instances for each of the the five cards, that is still the same 1% donation NOT ~~5x1%~~.

**Comment by aaronsace** [comment]
OMG

**Comment by Imaminer** [comment]
Dont sound right to me.

**Comment by fonyo** [comment]
You can safely delete the FireIce config files from the \Miners folder if you don't agree.

**Comment by fonyo** [comment]
To be added to FAQ
