### ISSUE TITLE
fall back for miners such a ccminersp

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#379]
ccminersp seems to be faster on skein but i does not connect well to mph. Would be great if there can be someway to have zpool as fall back. ccminer does not support fallback i know it should be in the powershell. 

![image](https://user-images.githubusercontent.com/19214485/30531634-ee121920-9c4f-11e7-9236-1a8d428fff02.png)

![image](https://user-images.githubusercontent.com/19214485/30531942-b2866efe-9c51-11e7-89eb-5ed5a7c05547.png)

**Comment by aaronsace** [comment]
Watchdog Timer coming in the next code commit.

**Comment by fonyo** [comment]
It might be suffering from the the same connection issue as klaust's ccminer. I suggest raising this on ccminersp's Issues page, where this could be looked at.

**Comment by jjziets** [comment]
How to i prevent mpm to mine to miningpoolhub for this miner? It seems to sometime mine to zpool and other times to mph. I don't want another miner to be affected though.

**Comment by fonyo** [comment]
The root cause should be eliminated by opening an issue on the miner's issues page. This is not in scope for MPM.

**Comment by fonyo** [comment]
However to answer your question, you could edit the miner file and add zpool as a static address in the config. Not sure it will have the perfect behaviour on display but then it will only mine on zpool.
