### ISSUE TITLE
NVIDIA 1070 not pass benchmark

### ISSUE THREAD

**Issue by gorilza** [aaronsace/MultiPoolMiner#38]
Nvidia 1070 does not pass speed test on ccminer (miner works at any one algorithm for 30-40 minutes), the claymore miner all goes well. What could be the problem ? Win7, 376.19.
[Logs.nvidia.1070.zip](https://github.com/aaronsace/MultiPoolMiner/files/694712/Logs.nvidia.1070.zip)

**Comment by aaronsace** [comment]
Thank you, please can you send the 'stats' folder as well?

**Comment by gorilza** [comment]
[Stats.nvidia.1070.zip](https://github.com/aaronsace/MultiPoolMiner/files/694724/Stats.nvidia.1070.zip)

**Comment by gorilza** [comment]
Version 2.3 had the same problem. On AMD everything works well.

**Comment by aaronsace** [comment]
Please can you try using this include file then send me the log. 
[Include.zip](https://github.com/aaronsace/MultiPoolMiner/files/694929/Include.zip)

**Comment by lyolyalya** [comment]
try to reproduce this if you haven't AMD cards - https://github.com/aaronsace/MultiPoolMiner/issues/11
i will try new version little later.

**Comment by lyolyalya** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/11

**Comment by gorilza** [comment]
C the new include is either the departure or the driver miner throws error.
[Stats.logs.nvidia.1070.zip](https://github.com/aaronsace/MultiPoolMiner/files/695533/Stats.logs.nvidia.1070.zip)

**Comment by aaronsace** [comment]
Thank you, I will release a fix later today.

**Comment by lyolyalya** [comment]
nanashi ccminer in your pack is not working
![image](https://cloud.githubusercontent.com/assets/16507768/21800852/15c6b202-d728-11e6-85b5-797bd02410c4.png)

**Comment by aaronsace** [comment]
Does the rest work? I uploaded a fix to the api on include. Please can you try it: 

[Include.zip](https://github.com/aaronsace/MultiPoolMiner/files/695716/Include.zip)

**Comment by lyolyalya** [comment]
keccak is benchmarking again and again...but after i replaced include.ps1 it just skipped it.groest fine.myr-groest - fine..looks like skipping is working fine.need to understand why it benchmarking all over again...
screenshot in a few minutes...

**Comment by lyolyalya** [comment]
aaand it crashes...
[2017-01-10_12-08-59.txt](https://github.com/aaronsace/MultiPoolMiner/files/695845/2017-01-10_12-08-59.txt)

**Comment by lyolyalya** [comment]
can i suggest you 100% stable ccminers for apropriate algos?

**Comment by aaronsace** [comment]
If there is a lot a algorithms not working then I could manually skip them in the code. 
As it seems to be working now though; I'll mark this as a release.

**Comment by aaronsace** [comment]
Would you be able to provide a definitive list of algorithms that work for each ccminer then I will update it in v2.4 once I have finally finished it?

**Comment by lyolyalya** [comment]
that's what i\m talking about=)
lyra2 - nanashi miner for nicehash by tpruvot(just copied it from nicehash bin folder and placed in my google drive - https://drive.google.com/open?id=0BzIjrFYeA7rtakdIQlU1ZVplYTQ
neoscrypt - https://github.com/KlausT/ccminer/releases
skein - https://github.com/sp-hash/ccminer/releases/
cryptonight - https://github.com/KlausT/ccminer-cryptonight/releases
all other algos not interesting as for me but if you want to then try - https://github.com/tpruvot/ccminer/releases
they all working with yours v1.3 24/7 about two weeks without any issue(gpu - 2075\mem - 9000)

**Comment by lyolyalya** [comment]
place them if you can right i mentioned and then i will test.scaring do it by myself now=)your code grow very fast and i think i can't do all right=)

**Comment by aaronsace** [comment]
Cheers lyolyalya. All will be included in v2.4.

**Comment by lyolyalya** [comment]
you're welcome=)waiting for release.
