### ISSUE TITLE
Mining on Nicehash when Nicehash is not added as a pool

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#380]
So I thought I would do some more testing and check out zpool and the other coins MPH still does not have. I have been mining on MPH for years (since Simplemining.net/SimpleCryptoGroup closed its doors) so this is all new to me. I added my BTC address after -wallet and zpool after miningpoolhub, miningpoolhubcoins.

I immediately noticed Pascal being benchmarked as a ClaymoreDual secondary coin but mined on Nicehash (alongside MPH-Ethereum). I did not add Nicehash as a pool and I would really like to stay away from it.

I have had pascal added to the algorithm list before but mining only kicked in when I added a wallet address and zpool to the list.

Is this normal behaviour for MPM? I can see there is no Pascal mined on Zpool but is there an option to exclude all the nicehash stuff regardless?

**Comment by fonyo** [comment]
Also, DecredNicehash gives rejected shares only. (Nicehash is still not added to the list of pools in the start.bat)

**Comment by aaronsace** [comment]
Check out 'Start-MiningPoolHub.bat'

**Comment by Imaminer** [comment]
Or just remove Nicehash from the pools folder

**Comment by aaronsace** [comment]
That's an option too but that removes your backup pool. 

The only algorithms that MiningPoolHub and Zpool don't cover is Pascal; bit of a non-issue.

**Comment by fonyo** [comment]
So how does one achieve to mine ethash on MPH and Lbry or Decred as a the secondary coin on Zpool?

**Comment by aaronsace** [comment]
If you only put MiningPoolHub and Zpool in the command line then it wont mine on NiceHash unless they are down.
