### ISSUE TITLE
Some cpu miners benchmarks not populating

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#381]
![image](https://user-images.githubusercontent.com/31579891/30565432-25e44bdc-9cc0-11e7-91c3-82ac8c593421.png)
This is an example, the second one was present but the first one wouldn't populate with benchmark values, even after deleting the respective stat file and restarting the batch file. To make it work, I had to manually introduce values on the stats file.
There are some others cpu miners that have the same problem.

**Comment by aaronsace** [comment]
The CPU miner APIs are a bit sill as it only reports a speed when a block is found. If the CPU miner never finds anything then it benchmarks as zero. It does wait a few minutes though. 

Is this the issue that you are having?

**Comment by AcharyaOne** [comment]
I don't think is that because it appears accepted shares very often.
![image](https://user-images.githubusercontent.com/31579891/30568902-a5860d58-9ccf-11e7-9fdc-196e7f76dd4c.png)
I have noticed this issue before but I just erased all the stats of cpu and tried again, maybe it could be related with some naming issue, it seems it gets confused because there is various Jaydee versions (and Tpruvot). Also could this be related somehow to the issue of txt file miners disappearing of benchmark at master release?

**Comment by jjziets** [comment]
I get the same,

only Lyra2z and CryptoNight works most of the time.

**Comment by jjziets** [comment]
![image](https://user-images.githubusercontent.com/19214485/30638118-a77739a8-9dfa-11e7-8a15-a3c44860fd9f.png)
running but does not get added

**Comment by jjziets** [comment]
could be that it never found a share?

**Comment by aaronsace** [comment]
It's not found one yet on that screenshot.
