### ISSUE TITLE
New crazy error

### ISSUE THREAD

**Issue by Imaminer** [aaronsace/MultiPoolMiner#382]
This is a all Nvidia rig. Just did a reboot and when I re-started MpM I get this .
Any help is appreciated. I removed sgminerskein and still get same error minus the sgminer part

Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not
be found. (Exception from HRESULT: 0x8007007E)"
At C:\MPM_9.17.17)old\Miners\SgminerSkein.ps1:16 char:258
+ ... -platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DllNotFoundException

Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not
be found. (Exception from HRESULT: 0x8007007E)"
At line:1 char:253
+ ... -platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DllNotFoundException

Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not
be found. (Exception from HRESULT: 0x8007007E)"
At line:1 char:222
+ ... -platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DllNotFoundException

Exception calling "GetPlatformIDs" with "0" argument(s): "Unable to load DLL 'opencl.dll': The specified module could not
be found. (Exception from HRESULT: 0x8007007E)"
At line:1 char:183
+ ... -platform $([array]::IndexOf(([OpenCl.Platform]::GetPlatformIDs() | S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DllNotFoundException

**Comment by aaronsace** [comment]
You're missing opencl.

**Comment by Imaminer** [comment]
I think Windows 10 did some update and screwed up my Nvidia drivers. Re-installing now

**Comment by aaronsace** [comment]
I think it's included in the driver package install: 

![capture](https://user-images.githubusercontent.com/21113644/30616644-d240f126-9d8a-11e7-939e-5cbfd5c4b7f4.PNG)

**Comment by Imaminer** [comment]
Looks like Win update did overwrite the Nvidia drivers. Finished install and now testing MPM

**Comment by Imaminer** [comment]
Yup that was it. Gee thanks Windows...
