### ISSUE TITLE
ccminer Klaust 8.13 stops sending shares

### ISSUE THREAD

**Issue by mlsad3** [aaronsace/MultiPoolMiner#383]
I have 2 different rigs showing the same issue, one with just a single graphics card, and the other with 6.
After a few minutes, it stops submitting shares. Even after 30 minutes, no new shares have been sent.

![image](https://user-images.githubusercontent.com/15711477/30676834-62b36512-9e45-11e7-9cc1-12bf4e625dbd.png)

**Comment by mlsad3** [comment]
I see we have had issues with KlausT before: https://github.com/aaronsace/MultiPoolMiner/issues/228, I submitted this at https://github.com/KlausT/ccminer/issues/57 just in case it doesn't already exist

**Comment by alucard20724** [comment]
does hashrefinery confirm that they haven't received shares?

**Comment by mlsad3** [comment]
I'm not sure exactly when this happened, it was somewhere in the red box. Then I deleted the miner.
By the way, there is no key for what the lines mean in the chart. Blue is probably the reported hash rate, I'm guessing the yellow is based on shares submitted, and I have no idea what the little green/yellow line is at the very bottom. Could you please enlighten me?
![image](https://user-images.githubusercontent.com/15711477/30679712-95bf1cea-9e58-11e7-9d2e-80d021d901f7.png)

**Comment by aaronsace** [comment]
I can look at adding a check for share submissions in coming watchdog timer feature but other than that I think that this issue is beyond the scope of MultiPoolMiner.

**Comment by mlsad3** [comment]
That's fine with me. Thanks

**Comment by fonyo** [comment]
Klaust is working fine on my end since v8.13. Are you sure it is not a pool-side issue?

**Comment by aaronsace** [comment]
I would recommending sticking to just using HashRefinery as a backup and not a main pool. Zpool is a lot bigger.

**Comment by mlsad3** [comment]
Thanks for the suggestions
