### ISSUE TITLE
Other currency

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#385]
Is there a way to add Thai Baht?

**Comment by UselessGuru** [comment]
This requires changes to MultiPoolMiner.ps1, as mentioned here:
[https://github.com/aaronsace/MultiPoolMiner/issues/328](url)

**Comment by Pititul** [comment]
Thank you.

**Comment by fonyo** [comment]
Closing this issue. Please submit a new ticket if additional help is required.
