### ISSUE TITLE
Other Currency then BTC

### ISSUE THREAD

**Issue by Laago** [aaronsace/MultiPoolMiner#386]
Is it possible to change payoutcoin from btc to something else when the miner is switching to zpool?

for instance, the c=BTC command is applied every time i connect to zpool.
Is there a way to change the c=btc command to c=*insert desired currency* ?

**Comment by UselessGuru** [comment]
Payout currency should be a per pool setting. You add the currency setting to each pool file.
More on this here: https://github.com/aaronsace/MultiPoolMiner/issues/345

**Comment by aaronsace** [comment]
I wouldn't recommend getting paid out in an alternative currency; the pool doesn't work the same as MiningPoolHub.

**Comment by fonyo** [comment]
Note to self. Should be added to FAQ.

**Comment by fonyo** [comment]
Added to FAQ, closing this issue.
