### ISSUE TITLE
EWBF keeps disappearing

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#387]
I have been seeing EWBF disappearing on many occasions today. Tested on 2 NVIDIA rigs. I think pool is not sending work (however, I am not 100% sure hence this post) as EWBF stops showing messages right after displaying solver. If I load a backup (including stats) those EWBF instances will also keep degrading in speed then disappear. Could it be MPH being overloaded/responding slowly or something else? Has anyone else experienced the same?

**Comment by aaronsace** [comment]
Is the speed showing next to the miner in the 'running' section on MultiPoolMiner correct? If it is zero then it will cause the stat to lower to zero over time. 

Watchdog Timer will help with this; once I turn the stat check on then it should ensure that only valid readings are kept and continuous invalid readings would cause the miner to be kicked.

**Comment by AcharyaOne** [comment]
What release are you using? On master release all txt miners disappear on me

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/tree/master/Miners

**Comment by AcharyaOne** [comment]
What I mean is that txt filetype miners have all hashrates disappear and will not be mined. They are benchmarked and then disappear and never touched again. I tried to explain the problem at the master issues thread.

**Comment by fonyo** [comment]
How does moving "--eexit 1" help with EWBF disappearing? I am not sure I understand why this works as the order of parameters should not matter.

**Comment by AcharyaOne** [comment]
@aaronsace When I have been alerting for over 2 weeks of the benchmark disappearing on TXT file miners and being ignored and then on the thread of EWBF keeps disappearing I join in and alert again you post a link to the miners, what is that supposed to be? a joke?

**Comment by aaronsace** [comment]
@AcharyaOne Please don't spam the issues. Thanks.
