### ISSUE TITLE
Gatelessgate miner missing from the master:  neoscrypt for AMD cards

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#388]
gatelessgate is missing from the miners.. it supports Neoscrypt which is twice as fast as current neoscrypt miners for AMD

**Comment by aaronsace** [comment]
Gatelessgate development is dead. Do you know of any others?

**Comment by alucard20724** [comment]
well that sucks... the current version for Neoscrypt for AMD is twice as fast as any other Neoscrypt available.    I don't know of any others.  it may be dead, but the dead miner for Neoscrypt for AMD cards is twice as fast as anything alive.  I reran the benchmark on a couple of my systems to verify.  GatelessGate Neoscrypt for AMD is at least twice as fast as any other Neoscrypt for AMD that is supported by mpm at least for the 4xx/5xx cards... only about 50% faster for my Vega64

**Comment by aaronsace** [comment]
You can still use the configuration file for Gatelessgate but I'm not including it in the release. If someone picks up the development then it will be added back.

**Comment by alucard20724** [comment]
ok... that's what i did

**Comment by mjmeans** [comment]
How do you do this? Just copy the txt file from the miners folder from a previous version?

**Comment by aaronsace** [comment]
Yes, it is just a JSON text file.

**Comment by aaronsace** [comment]
Keep an eye on this: 
https://github.com/zawawawa/GatelessGateSharp
