### ISSUE TITLE
JSON from whattomine?

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#39]
hey, again.i was thinking...is it possible to work with JSON from whattomine to choose profitable coin?
want to mine some coins that not listed on miningpoolhub now.just asking=)

**Comment by aaronsace** [comment]
I have the code for a couple of other pools but not whattomine. I'm not going to add other pools until version 3.

**Comment by lyolyalya** [comment]
i see...but i'm not talking about pools, i'm talking about coins.now nvidia can have profit from sibcoin for example...i was dreaming about program that gets data from whattomine and shows results like yours multipoolminer, and then i'm just put my miner to desired pool and coin=)ahh...this dreams=)ok.i get it.wait and see...

**Comment by aaronsace** [comment]
It will come. :)
