### ISSUE TITLE
Making less profit when compared

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#391]
It used to say MPM is between % more... now it's like this. Did I do something wrong? It is using the same miner as in the comparison (ccminerTruvot). 

Miner                 BTC                             USD
-----                 ---                             ---
MultiPoolMiner        0.00223 ±54 % (0.00145-0.00344) 8.27720 ±54 % (5.36774-12.76367)
CcminerTpruvot-Lyra2z 0.00923 ±47 % (0.00626-0.01362) 34.28386 ±47 % (23.24599-50.56283)

**Comment by Pititul** [comment]
Not really complaining, USD 8.27720 per day is more that NiceHash. Just wondering since MPM is using the same miner why does not it make USD 34.

**Comment by aaronsace** [comment]
Run the 'ResetProfit.bat' file.

**Comment by Pititul** [comment]
Thank you!
