### ISSUE TITLE
Hashrate recording off by 1000x

### ISSUE THREAD

**Issue by mlsad3** [aaronsace/MultiPoolMiner#392]
Every now and then (well it's only happened twice), I've noticed that the system is running with some extreme differences between actual and recorded speeds.
Here's an example. Instead of realizing I would only make 0.0003 BTC/day, it thought I should be making 0.8 BTC/day due to something bad that was recorded:
![image](https://user-images.githubusercontent.com/15711477/30784263-708971aa-a10f-11e7-9dd9-e0e37eaee8f4.png)

After deleting profits and running benchmark:
![image](https://user-images.githubusercontent.com/15711477/30784260-63e837a6-a10f-11e7-893f-bf84221e672b.png)

I think what happened originally is the ccminer started hitting an exception and was printing a bunch of red text to the screen. And so maybe it recorded bad values. That said, I thought we only grab statistics from the web api's, so this shouldn't have caused an issue.

Anyway, regardless, it would be great if there was a faster recovery from the bad statistics. In my case, it would take days (weeks?) before the bad statistics averaged back down again. If instead we noticed several magnitudes of difference for a sustained period of time, maybe we would delete the profits and re-benchmark? (not sure if the works in my mind came out in a way that makes sense)

**Comment by aaronsace** [comment]
Coming in the next commit.

**Comment by mlsad3** [comment]
Awesome, thanks!

**Comment by mlsad3** [comment]
Just for tracking purposes, here's a picture of the incorrect stats (from API, I guess) while the miner specifically shows a much smaller number:
![image](https://user-images.githubusercontent.com/15711477/30786148-d3c34db2-a12e-11e7-8cd4-4a911d27d013.png)
