### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#395]
whether it is possible to make that at mining on the currency processor kryptonight still to override cpuminer-aes-avx.exe with the parameter -t 2 on the following after kryptonight in the list algorithm or m7m algo?

**Comment by aaronsace** [comment]
I can't seem to make sense of what you are saying...

**Comment by spider703** [comment]
my processor work on algo Cryptonight on 2 cores of eight, I want to work together with him algo m7m on 2 or 3 cores

**Comment by aaronsace** [comment]
So you want to dual mine on a CPU?

**Comment by spider703** [comment]
yes, I separately start m7m when Cryptonight works, while the speed of Cryptonight does not drop. how can this be realized?

**Comment by aaronsace** [comment]
Create two files in the folder called 'miners'. On one miner, specify 'index' 0, 1, 2 and 3. Then on the other miner specify 'index' 4, 5, 6 and 7.

**Comment by spider703** [comment]
you can write an example of a file with different indexes, I can not run them simultaneously

**Comment by aaronsace** [comment]
```
[
	{ 
		"Type":  "CPU", 
		"Path":  ".\\Bin\\CPU-JayDDee\\cpuminer-aes-avx.exe", 
		"Arguments":  "some arguments", 
		"HashRates":  {"algo":  "hashrate"}, 
		"API":  "Ccminer", 
		"Port":  "different port", 
		"Wrap":  false, 
		"Index":  [0,1,2,3] 
	} 
]
```

**Comment by spider703** [comment]
and the file name is what to set FireiceCpu2.ps1?

**Comment by aaronsace** [comment]
Just name it like, 'CPUMiner1.txt' and 'CPUMiner2.txt'.

**Comment by spider703** [comment]
but can not somehow be merged into one file with FireiceCpu2.ps1? MPM starts fireiceCpu2 and with him starts cpuminer-aes-avx.exe with param -a m7m -o stratum+tcp://m7m.mine.zpool.ca:6033

**Comment by aaronsace** [comment]
If the indexes are different then a different file name is needed as for the stat files not to conflict.

**Comment by spider703** [comment]
created file1.txt
[
	{ 
		"Type":  "CPU", 
		"Path":  ".\\Bin\\Cryptonight-CPU2\\xmr-stak-cpu.exe", 
		"Arguments":  "", 
		"HashRates":  {"Cryptonight":  "0,13721"}, 
		"API":  "FireIce", 
		"Port":  "3334", 
		"Wrap":  false, 
		"Index":  [0,1,2,3] 
	} 
]
created file2.txt
[
	{ 
		"Type":  "CPU", 
		"Path":  ".\\Bin\\CPU-JayDDee\\cpuminer-aes-avx.exe", 
		"Arguments":  "-a m7m -o stratum+tcp://m7m.us.hashrefinery.com:6033 -u 1J6ERS9LjhRhXkifkVfdpbP56aY7TLqEoe -p x -t 3", 
		"HashRates":  {"m7m":  "70"}, 
		"API":  "Ccminer", 
		"Port":  "4048", 
		"Wrap":  false, 
		"Index":  [4,5,6,7] 
	} 
]
file1 is runing, file2 not runing

**Comment by aaronsace** [comment]
Without testing, I'm not quite sure but back slashes should be doubled and numbers shouldn't contain commas.

**Comment by fonyo** [comment]
Closing this, please post here is more help is required.
