### ISSUE TITLE
Just after log starts:

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#396]
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (522) Origin Connection Time-out."

**Comment by fonyo** [comment]
I thought MPH had cloudflare caching turned on. Why would it fail to load the API?

**Comment by aaronsace** [comment]
Still could be cloud flare. Maybe the cloud flare caching is off?

**Comment by aaronsace** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out

**Comment by aaronsace** [comment]
I would rather the API dropped out than provided old information. Next update will continue running when the API is down.

**Comment by fonyo** [comment]
But if you are caching and using outdated API data, are you not technically doing the same?

**Comment by aaronsace** [comment]
I have a timeout as well. 

But the issue with MiningPoolHub was that it was always sending cached data even when the server wasn't down.

**Comment by fonyo** [comment]
Reminds me I need to chase MPH whether he found a solution for a fully live API.
