### ISSUE TITLE
Initial Setup: "No Pools!" error

### ISSUE THREAD

**Issue by slavkosky** [aaronsace/MultiPoolMiner#397]
While running initial setup (running MultiPoolMiner.ps1 in Powershell) using downloaded MultipoolMiner version 2.6.0.2 I get a message over and over again "No Pools!" instead of it asking for my miningpoolhub login to commence miner download and benchmarking.

Log Below:
**********************
Windows PowerShell transcript start
Start time: 20170928120500
Username: Kenobe-IV\Kenobe
RunAs User: Kenobe-IV\Kenobe
Machine: KENOBE-IV (Microsoft Windows NT 10.0.15063.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'F:\Crypto\MultiPoolMinerV2.6.0.2\MultiPoolMiner.ps1'
Process ID: 15760
PSVersion: 5.1.15063.608
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.608
BuildVersion: 10.0.15063.608
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-09-28_12-05-00.txt
No Pools!
No Pools!

**Comment by aaronsace** [comment]
Use the start.bat file example.
