### ISSUE TITLE
Unable to Download EthDecredClaymore?

### ISSUE THREAD

**Issue by zaptrem** [aaronsace/MultiPoolMiner#398]
With a clean run of the latest commit I'm being told that it is unable to download this exe and is searching for it. As the program has already moved on to do something else I'm unable to get the exact log message. In addition, I was getting the following red error:

The property 'PriorityClass' cannot be found on this object. Verify that the property exists and can be set.
At D:\MultiPoolMiner-master\Include.ps1:548 char:5
+     $Process.PriorityClass = $PriorityNames.$Priority
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

My full log is here: 
[2017-09-29_09-37-22.txt](https://github.com/aaronsace/MultiPoolMiner/files/1344524/2017-09-29_09-37-22.txt)

**Comment by aaronsace** [comment]
I can't download claymore's miners as they are on megadrive. Get the bin folder from the release zip.

**Comment by zaptrem** [comment]
Is the priority Class error related?

**Comment by aaronsace** [comment]
Maybe. Your log just has everything failing though, bit odd.

**Comment by zaptrem** [comment]
Can you give some more details? I've seen all kinds of red errors everywhere I use this script.

**Comment by aaronsace** [comment]
Get the bin folder from the release first. 

https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.6.0.2/MultiPoolMinerV2.6.0.2.zip
