### ISSUE TITLE
Claymore Cryptonight 10.1 just released. Doesn't work with current mpm.

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#399]
Claymore GPU Cryptonight version 10.1 released.  not supported by current version of mpm.
some of the parameters were changed... -xpool now instead of -o
... and others too... you git the jist of it.

Current version: 10.1 BETA:
- v10.1 - fixed some critical bugs.
- now miner uses the latest framework which is used for dual and zec miners. Therefore several new options are available.
- new assembler GPU kernels are used.
- added "-dmem" options that can improve performance in many cases. Note that twice more GPU memory is used in this mode.
- some old options were removed, some were renamed, please read Readme for detailed information and samples.
- reduced devfee, it's 1% now if you use secure SSL/TLS connection, 1.5% for unsecure connection.
- devfee mining is executed every hour, similar to dual and zec miners.
- a lot of minor improvements.

**Comment by aaronsace** [comment]
If anyone has updated the configuration file for Claymore Cryptonight Miner then feel free to do a pull request.
