### ISSUE TITLE
Disable algo on certain pool

### ISSUE THREAD

**Issue by FabianGabor** [aaronsace/MultiPoolMiner#400]
Since Yiimp.eu is very similar to Zpool I did set it up. The only issue I'm having is that on Yiimp certain algos (for example blake2s) don't have certain coins but on Zpool it does. It would be nice to have a parameter for enabled algos for each pool.

**Comment by UselessGuru** [comment]
See issue #345 section 2

**Comment by aaronsace** [comment]
I'm not 100% clear as to what you are trying to achieve but I'll explain the options: 

'-PoolName' is to specify which pools take **preference** (all pools are still available to the miners)
'-Algorithm' is to specify the only algorithms that you wish to use (all other algorithms are excluded completely)

Check this example: 
https://github.com/aaronsace/MultiPoolMiner/blob/master/Start-Zpool.bat

**Comment by FabianGabor** [comment]
As @UselessGuru said. 

For example Yiimp doesn't support mining certain coins with multi algos but Zpool does. One particular coin is Verge (XVG) that supports 5 different algos (Scrypt, x17, groestl, blake2s, and lyra2rev2). Zpool does support all of those but Yiimp only supports x17 so if you try to mine on Yiimp with an unsupported algo you can't connect.

**Comment by aaronsace** [comment]
I think it maybe the way you have setup Yiimp. It's not possible to mine on a pool that's not supported.

**Comment by FabianGabor** [comment]
I copied the Zpool.ps1 but the issue is not with the file. Yiimp supports the algos in question but can't mine certain coins with that algo. For example Zpool supports blake2s and x17 for XVG but Yiimp only supports x17. So if I launch with `-poolname zpool,yiimp -algorithm blake2s,x17` then it will try to mine XVG with blake2s on Yiimp because blake2s is more profitable. But the pool will refuse the connection because of `-p c=XVG` is not available for blake2s.

**Comment by aaronsace** [comment]
I think you have identified the problem. You need to set the passwords correctly in the Yiimp ps1 file.

**Comment by FabianGabor** [comment]
The password is fine when using x17 on Yiimp. The issue is that when using blake2s Yiimp will refuse to connect because with that algo they don't support XVG like Zpool does and they won't convert the available coins for blake2s for XVG. This issue might not be present (haven't tested) if I'd try to mine for BTC.

**Comment by FabianGabor** [comment]
I added the modification #345 suggested by @UselessGuru and it seems to be working:

# In case some algos are not working properly
$DisabledAlgorithms = @("blake2s","equihash","neoscrypt","sib")

$Yiimp_Regions | ForEach-Object {
	$Yiimp_Region = $_
	$Yiimp_Region_Norm = Get-Region $Yiimp_Region
	
	# Do only for selected algorithms, creates a smaller pool list
	if ($DisabledAlgorithms -inotcontains $Yiimp_Algorithm -and ($Algorithm -eq $null -or $Algorithm -icontains $Yiimp_Algorithm)) {
		if ($Wallet) {
				[PSCustomObject]@{
					...
				}
		}
	}
}

**Comment by aaronsace** [comment]
This is how you are supposed to setup the Yiimp pool: 

`switch ($Yiimp_Algorithm_Norm) {
    "blake2s" {$Yiimp_User = "enter wallet"}
    "x17" {$Yiimp_User = "enter wallet"}
}

switch ($Yiimp_Algorithm_Norm) {
    "blake2s" {$Yiimp_Pass = "enter coin"}
    "x17" {$Yiimp_Pass = "enter coin"}
}

...

[PSCustomObject]@{
    Algorithm     = $Yiimp_Algorithm_Norm
    Info          = $Yiimp_Coin
    Price         = $Stat.Live
    StablePrice   = $Stat.Week
    MarginOfError = $Stat.Week_Fluctuation
    Protocol      = "stratum+tcp"
    Host          = "$Yiimp_Algorithm.$Yiimp_Host"
    Port          = $Yiimp_Port
    User          = $Wallet
    Pass          = "$WorkerName,c=BTC"
    Region        = $Yiimp_Region_Norm
    SSL           = $false
    Updated       = $Stat.Updated
}`

**Comment by aaronsace** [comment]
The issue simple stems from you entering the wrong credentials. You don't need to disable anything if you don't provide MultiPoolMiner with wrong pool information.

**Comment by FabianGabor** [comment]
That setup is nice when you want to receive BTC but I want to mine XVG directly on all pools and all algos that are available on that pool and that coin.

**Comment by aaronsace** [comment]
Yiimp does not support BTC. You have to enter the wallet and coin for each pool. 

You just change "if ($Wallet)" to "if ($Yiimp_User)"

**Comment by FabianGabor** [comment]
I solved it by adding this to Yiimp.ps1 before ForEach-Object loop:
```
$Yiimp_Request.blake2s.estimate_current = 0
$Yiimp_Request.blake2s.estimate_last24h = 0
```
