### ISSUE TITLE
Add an option for # of CPU threads

### ISSUE THREAD

**Issue by FruitFace** [aaronsace/MultiPoolMiner#401]
Would it be possible to add scripting to tell all CPU miners to use only X threads?  I had to change all the miners configs manually to add --threads=3 (I have a 4 core CPU), except for the ones where the thread # was part of the config.

The reason I did this, is I've read that hashrates can be affected negatively if there is not enough CPU resource available for them.  Also, I use my PC for other things while mining, so I like to have a core set aside.

Thanks

**Comment by aaronsace** [comment]
I fixed the resource problem a different way. CPU miners now have a lower priority than the GPU miners. 

https://github.com/aaronsace/MultiPoolMiner/commit/e196cdf30ee82f2fa46722654c02b1137b2477e3

**Comment by FruitFace** [comment]
Good to know, thanks for the quick response!  Would there be a valid use
case to have options for either solution?
