### ISSUE TITLE
-region not honored

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#403]
I'm just trying this again. I put "-region usa" in and for some reason it is connecting to asia or Europe miningpoolhub.com ports. So it's not honoring the region parameter.

For reference, the poolname parameter is left at default and set to miningpoolhubcoins,zpool,nicehash.

**Comment by aaronsace** [comment]
I used 'US not 'USA'.

**Comment by mjmeans** [comment]
Duh. Sorry.

Side note: As you know, Europe and Asia are continents and US is not. For consistency sake shouldn't US be changed to America (also a continent), or perhaps North America and South America for those in brazil, et.al.?

**Comment by aaronsace** [comment]
Maybe, I just copied what MiningPoolHub referenced them as: 
https://ethereum.miningpoolhub.com/

I'll run the name correction files on the input parameters. Will help with Algorithm parameter as well.
