### ISSUE TITLE
Having a weird "DNS Name Resolve" issue

### ISSUE THREAD

**Issue by slavkosky** [aaronsace/MultiPoolMiner#404]
I'm having an odd issue I've never encountered before, I've attached a screenshot of what's happening:

![tseckzl - imgur](https://user-images.githubusercontent.com/21113644/31060227-aa0b513e-a707-11e7-873a-3eec76e44599.jpg)

**Comment by jechol** [comment]
Same here.

**Comment by TheSkynet1337** [comment]
I have the same issue. $Pools appears to be null in this case. It only happens for the Nvidia Excavator 2 and 4 files for me. Mining does still proceed properly though. I have however yet to be switched to excavator so I can't say if that would lead to problems.

[2017-10-08_22-56-47.txt](https://github.com/aaronsace/MultiPoolMiner/files/1367297/2017-10-08_22-56-47.txt)
[2017-10-09_01-09-15.txt](https://github.com/aaronsace/MultiPoolMiner/files/1367296/2017-10-09_01-09-15.txt)

**Comment by TheSkynet1337** [comment]
This actually appears to already be fixed.
To get the fix just use the clone or download button to download a zip of the newer version instead of using the newest version from the releases tab.
