### ISSUE TITLE
High reject rate with CCMiner-Alexis\Keccak

### ISSUE THREAD

**Issue by FruitFace** [aaronsace/MultiPoolMiner#405]
I'm seeing a very high rejection rate for submitted shares.  Reject reason is low diffculty shares.  How do I fix this?

Thanks
[ccminer alexis.docx](https://github.com/aaronsace/MultiPoolMiner/files/1347715/ccminer.alexis.docx)

**Comment by nemosminer** [comment]
trying setting the difficultly manually eg:

-p d=256 

some pools are better than others Alexis plays nice on Nicehash Keccak auto difficulty.. yimmp clones need d=256 even then still not perfect... haven't tested others...

**Comment by FruitFace** [comment]
Thanks for the quick response.  I'll try it out tonight and will update.

Cheers

**Comment by FruitFace** [comment]
So I looked at the Miners folder, hoping there was a .txt for the miner\coin combo, but I only found the CcminerPalgin.ps1 file.  

Without learning scripting, I don't see how I can add the difficulty setting for just that one coin.  Am I missing something?

**Comment by nemosminer** [comment]
like this:      eg:

    #"bitcore" = "" #Bitcore
    "blake2s" = "" #Blake2s
    #"blakecoin" = "" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"cryptonight" = "" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    #"hmq1725" = "" #hmq1725
    "keccak" = "d=1024 -i 29" #Keccak
    "lbry" = "" #Lbry
    "lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = " -i 15" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = " -i 21" #Sib
    #"X11Gost" = " -i 21" #X11Gost
    #"skein" = "" #Skein
    #"timetravel" = "" #Timetravel
    "c11" = "" #C11
    #"x11evo" = "" #X11evo
    #"x17" = " -i 21" #X17
    #"yescrypt" = "" #Yescrypt

note: (1070 setup intensities)

**Comment by FruitFace** [comment]
Thanks for the lead.  So it turns out the switch is -m , for a difficulty multiplier.  Then I ran the miner manually, and found anything less than 2 would lead to the issue I was having.

As far as inserting  "-m 2" to the script, I had to add a space in front of it, like so " -m 2" or it would append directly to the end of the currency choice for zpool.

Afterward, I deleted the hashrate file for palginmod-keccac and let it run.

It all worked out!  Thanks for the help.

**Comment by nemosminer** [comment]
nice -m 2 fixes it! can use auto difficulty : )

**Comment by spider703** [comment]
"keccak" = " -m 2" #Keccak
So the line will look like?

**Comment by FruitFace** [comment]
This is the actual line from the CcminerPalgin.ps1 file:

 "keccak" = " -m 2" #Keccak

**Comment by FruitFace** [comment]
That's right.  If you delete the hashrate file from the stats folder, afterward, you'll see it run it's benchmark, and you'll see if appended to the end of the command, and you can see it run in the command window.

**Comment by spider703** [comment]
if add this parametr in end in Arguments = "-a $_ -o ..... ($Commands.$_) -m 2" to all algo?

**Comment by UselessGuru** [comment]
> if add this parameter in end in Arguments = "-a $_ -o ..... ($Commands.$_) -m 2" to all algo?

This would double difficulty for all algos for this pool. 
I would not recommend this - just change it for the problematic algo unless you see the same diff level problems with all algos..

**Comment by nemosminer** [comment]
yes only use this for keccak-paligin/Alexis78 

"keccak" = " -m 2" #Keccak

solves this issue can now be closed
