### ISSUE TITLE
2gb algos?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#407]
Is there any reason to use 2gb algos when all gpu's are 4gb or larger?

Is there any logical reason why a 2gb algo should run faster than a normal algo on a 4gb/8gb card?

If not, then benchmarking would not have to go through all the normal and all the 2gb algos, and the MPM profit table will be shorter.

**Comment by aaronsace** [comment]
Can be faster and some people may not have 4gb. Just take it out of the command line if you wish to skip it.
