### ISSUE TITLE
Switching miners

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#408]
I'm just wondering... do I pay 2% dev fee everytime I switch to a miner even to the very same miner for the second time?

**Comment by aaronsace** [comment]
There is no dev fee for MultiPoolMiner. How the dev fees are taken the other miners depends on how they implemented it.

**Comment by Pititul** [comment]
I meant dev fee from ccminers, claymore etc... if I keep switching to different algo, do I pay the fee each time I run Tpurovot? I asked because I was thinking of increasing the interval so it doesn't switch so much.

**Comment by aaronsace** [comment]
I don't believe any of the mine the dev fee first.
