### ISSUE TITLE
nicehash support

### ISSUE THREAD

**Issue by snakethejake81** [aaronsace/MultiPoolMiner#41]
Any thoughts on adding nicehash support?

One area that would be nice is the additional algorithm support like LBRY, which miningpoolhub doesn't have.  Dual mining ETH with LBRY would be much more profitable than ETH and SIA.  They have a JSON api available as well, which should make it a bit simpler.

Thanks.

**Comment by lyolyalya** [comment]
why need nicehash?you don't mine with nice hash - you sell them your hashpower.and you will allways earn less with nicehash compared direct mining...and they already have an autoswitch.don't see any reason to support them...

**Comment by snakethejake81** [comment]
I convert anything I mine on miningpoolhub to bitcoin or ethereum as it is.  They support algorithms that MiningPoolHub doesn't support, some of which can have higher profitability.  LBRY is a good example of that.  It was more profitable than ZEC and Ethereum recently.  Just looking for more ways to optimize profit.

**Comment by lyolyalya** [comment]
but they have't skein or sibcoin=)and again - nicehash - it's not mining - it's hashpower seller=less profits.miningpoolhub tells that he planning lbry to add, so wait a bit=)better ask lbry support on miningpoolhub too for faster implementation=)many miners want lbry on miningpoolhub=)

**Comment by snakethejake81** [comment]
Makes sense.  I just need to be more patient, hah.
