### ISSUE TITLE
lyra2z miner not working with Rx560 on windows 7 services park1

### ISSUE THREAD

**Issue by somidax** [aaronsace/MultiPoolMiner#410]
Hello,

I have tried running this but it just keep going off as would appreciate if one
[2017-10-05_12-31-08.txt](https://github.com/aaronsace/MultiPoolMiner/files/1359115/2017-10-05_12-31-08.txt)
 can get any better miner for zcoin.

thanks

**Comment by aaronsace** [comment]
If there is a better one then I will add it but it's not profitable on AMD anyway; I wouldn't worry.

**Comment by somidax** [comment]
ok. thanks for will get nvidia cards and build on it. FX6100 amd cpu when
tried works best. will build the nvidia around it.

appreciate and God bless
