### ISSUE TITLE
benchmark extremely decreases over time

### ISSUE THREAD

**Issue by Piarb** [aaronsace/MultiPoolMiner#411]
Hi! 
I'm trying to use MPM about one week. And for now I encountered a problem. After first benchmark mining starts perfectly. But during mining on each miner benchmark decreases over time. Although hashrate is stable. As result few hours/days later I see benchmarks of most profitable algos is down to 10-90% of real. Can somebody tell me what Im doing wrong or where I must look for the problem? 
Thanx for advance. 
(Sorry for bad english)

**Comment by aaronsace** [comment]
Can you upload the log file and stats folder? 
Also, what version are you using?

**Comment by Piarb** [comment]
For example current log. As I can see in log: After rebenching of claymore-dual it works normal about 53 minutes. And then falling from 140,40 MH/s to 83,00 MH/s. 
[2017-10-05_16-09-37.zip](https://github.com/aaronsace/MultiPoolMiner/files/1359808/2017-10-05_16-09-37.zip)
Unfortunately I don't see a version. I'm simply downloaded ZIP from "code" page like on screenshot. Is this a wrong way? )
http://clip2net.com/clip/m534343/e737d-clip-67kb.png

**Comment by Piarb** [comment]
The only way I was able to find to resolve my problem. A made all hashrate-files read only after benchmark (
It's not right. But what can I do else?

**Comment by aaronsace** [comment]
Try the release build instead of the code: 
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by aaronsace** [comment]
Also, try setting the '-interval' setting to 120.

**Comment by aaronsace** [comment]
Claymore is reporting no speed: 

> 
> {
>     "Live":  0,
>     "Minute":  0,
>     "Minute_Fluctuation":  1,
>     "Minute_5":  0,
>     "Minute_5_Fluctuation":  1,
>     "Minute_10":  0,
>     "Minute_10_Fluctuation":  1,
>     "Hour":  0,
>     "Hour_Fluctuation":  1,
>     "Day":  115604094.394069,
>     "Day_Fluctuation":  0.18484264819824672,
>     "Week":  115604094.394069,
>     "Week_Fluctuation":  0.18484264819824672,
>     "Duration":  "11:36:52.2452119",
>     "Updated":  "\/Date(1507213236525)\/"
> }
>
