### ISSUE TITLE
hash to coins?

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#412]
Is https://hash-to-coins.com/ a reasonable multi-pool to add to MPM?

**Comment by aaronsace** [comment]
Does it have an API to access the information on the homepage?

**Comment by UselessGuru** [comment]
It does have an API, but needs registration and API key:

[https://bitcointalk.org/index.php?topic=721712.msg20463891#msg20463891](https://bitcointalk.org/index.php?topic=721712.msg20463891#msg20463891)

Pricing information is mentioned here:

[https://bitcointalk.org/index.php?topic=721712.msg20824554#msg20824554](https://bitcointalk.org/index.php?topic=721712.msg20824554#msg20824554)
