### ISSUE TITLE
worth using ccminer form SP mod for LBRY?

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#413]
https://github.com/sp-hash/ccminer/releases/tag/LBRYSP6

**Comment by UselessGuru** [comment]
Not for me. I am mining with a single GTX 1080i and get about 490MH/s, whereas I can get 496MH/s with Excavator. Not much faster, but every bit counts!

**Comment by aaronsace** [comment]
I was using it but someone pointed out that it takes the dev fee when you open it so I got rid of it.

**Comment by nemosminer** [comment]
worth using ccminer form SP mod for LBRY? = no
