### ISSUE TITLE
djm34/ccminer-msvc2015 

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#414]
New release https://github.com/djm34/ccminer-msvc2015/releases/

**Comment by jjziets** [comment]
I'm getting 2MHs on 1070

**Comment by UselessGuru** [comment]
> I'm getting 2MHs on 1070

Do you see many **stratum Connection interruption** messages with this miner?

**Comment by jjziets** [comment]
No. None.
