### ISSUE TITLE
add support for Xevan?  ccminer-xevan

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#416]
it's available on both zpool and hashrefinery

https://github.com/krnlx/ccminer-xevan

**Comment by alucard20724** [comment]
palgin has a windows build here for cuda 9.0
https://bitcointalk.org/index.php?topic=2237852.msg22643615#msg22643615

i'm messing with it now.

**Comment by Piarb** [comment]
You can try unzip this ps1 into miners folder: 
[CcminerXevan.zip](https://github.com/aaronsace/MultiPoolMiner/files/1363810/CcminerXevan.zip)
Just replace executable if you need CUDA9

**Comment by nemosminer** [comment]
cuda 9.0 x86 is fastest version so far ive tested it and haev it running 

https://github.com/nemosminer/NemosMiner-v2.2/blob/master/Miners/CcminerXevan.ps1

**Comment by imrecsoka** [comment]
And this is also going to be integrated for those AMD  miner out there?

**Comment by aaronsace** [comment]
@nemosminer It would be great if you could keep the miners up-to-date over here. 
https://github.com/aaronsace/MultiPoolMiner/invitations

If anyone out there is using Xevan, please can you do a pull request?

**Comment by imrecsoka** [comment]
I wish i understood half of this, so please help me guys:

-what do you mean a pull request?  We are not FTPing a file here are we? no i really dont understand, please explain it to me.
-also , how do you plug in new coins in to multipoolminer...
Even XMRIG should be put in to this suite to replace or be an addition to XMR-STAK-CPU, it out performs it by a few to 10 hashes in my case.

**Comment by UselessGuru** [comment]
Ccminer-Xevan added:
https://github.com/aaronsace/MultiPoolMiner/commit/11773731a917d2f0239377025c889e9f96515a28
