### ISSUE TITLE
XMRig Cryptonight (and cryptonight-lite) Nvidia and CPU 

### ISSUE THREAD

**Issue by AcharyaOne** [aaronsace/MultiPoolMiner#417]
https://github.com/xmrig/xmrig-nvidia
https://github.com/xmrig/xmrig

**Comment by spider703** [comment]
need for him miner.ps1
in file json i put donate 1 and speed on this miner 94 h against 70.5 h on FireIceCpu

**Comment by UselessGuru** [comment]
I cannot find a way to retrieve it's hashrate... there is no API, and running it as 'Wrap=$true' causes an 'out of memory' error.
If anyone wants to try my unfinished miner file (you will have to add the hash rate file manually):
[XMRig-NVIDIA0.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/1367056/XMRig-NVIDIA0.ps1.txt)

**Comment by spider703** [comment]
This is for CPU miner

**Comment by UselessGuru** [comment]
> for CPU miner?

For NVIDIA.

**Comment by spider703** [comment]
I'm trying to make a miner for cpu
. .\Include.ps1

$Path = ".\Bin\xmrig-2.4.0\start.cmd"
$Uri = "https://github.com/xmrig/xmrig/releases"

$Commands = [PSCustomObject]@{
    #"bitcore" = "" #Bitcore
    #"blake2s" = "" #Blake2s
    #"blakecoin" = "" #Blakecoin
    #"vanilla" = "" #BlakeVanilla
    #"c11" = "" #C11
    "cryptonight" = "" #Cryptonight
    #"decred" = "" #Decred
    #"equihash" = "" #Equihash
    #"ethash" = "" #Ethash
    #"groestl" = "" #Groestl
    #"hmq1725" = "" #HMQ1725
    #"jha" = "" #JHA
    #"keccak" = "" #Keccak
    #"lbry" = "" #Lbry
    #"lyra2v2" = "" #Lyra2RE2
    #"lyra2z" = "" #Lyra2z
    #"m7m" = "" #M7M
	#"myr-gr" = "" #MyriadGroestl
    #"neoscrypt" = "" #NeoScrypt
    #"nist5" = "" #Nist5
    #"pascal" = "" #Pascal
    #"quark" = "" #Quark
    #"qubit" = "" #Qubit
    #"scrypt" = "" #Scrypt
    #"sia" = "" #Sia
    #"sib" = "" #Sib
    #"skein" = "" #Skein
    #"skunk" = "" #Skunk
    #"timetravel" = "" #Timetravel
    #"tribus" = "" #Tribus
    #"veltor" = "" #Veltor
    #"xevan" = "" #Xevan
	#"x11" = "" #X11
    #"x11evo" = "" #X11evo
    #"x17" = "" #X17
    #"yescrypt" = "" #Yescrypt
}

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | ForEach-Object {
    [PSCustomObject]@{
        Type = "CPU"
        Path = $Path
        Arguments = "-a $_ -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_)"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week}
        API = "Ccminer"
        Port = 4048
        Wrap = $false
        URI = $Uri
    }
}
speed values are not written to the file XMRCpu_CryptoNight_HashRate.txt

**Comment by AcharyaOne** [comment]
https://github.com/xmrig/xmrig/releases/tag/v2.4.0
API has been added on cpu version
