### ISSUE TITLE
"-poolname nicehash" mines on miningpoolhub

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#419]
Using MPMv2.6.0.2.

So I wanted to test mining on nicehash only. I changed the poolname parameter to only show nicehash and restarted MPM. MPM still mines MPH.

**Comment by aaronsace** [comment]
Check this example: 
https://github.com/aaronsace/MultiPoolMiner/blob/master/Start-NiceHash.bat
