### ISSUE TITLE
ConvertFrom-Json : Invalid JSON primitive: .

### ISSUE THREAD

**Issue by theeddie** [aaronsace/MultiPoolMiner#420]
ConvertFrom-Json : Invalid JSON primitive: .
At C:\\MultiPoolMinerV2.6.0.2\Include.ps1:127 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~

any ideas

**Comment by aaronsace** [comment]
The file(s) is not valid JSON. Please get a fresh download.

**Comment by FabianGabor** [comment]
I have the same issue. Using only Zpool. http://www.zpool.ca/api/status should be JSON but still getting an error. Stats show up and work however.
