### ISSUE TITLE
Currently mining with upto 6 GPUs is fully supported. Where required advanced users can create additional miner files to support mining with more than 6 graphics cards.

### ISSUE THREAD

**Issue by theeddie** [aaronsace/MultiPoolMiner#421]
What needs to be done to get past this

**Comment by aaronsace** [comment]
The files in the folder called 'miners' are editable.

**Comment by fonyo** [comment]
How many cards are you using and what algorithms are you planning to mine?

**Comment by mavlevypaul** [comment]
Hey there,

Id like to mine lyra2z,equihash,groestle,ethash,lyra2rev2,neoscrypt

I have 8 GPUS 

Is there any way that you could give me some guidence on what settings in the miners files to change?
