### ISSUE TITLE
Error if '$NewPools' contains only one algorithm

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#426]
If $NewPools can only read one pool file which results in exactly one supported algorithm, then:

Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Program Files\CryptoMining\MultiPoolMinerV2.6\MultiPoolMiner.ps1:101 char:105
+ ...  -Unique) @($AllPools | Select-Object -ExpandProperty Name -Unique) | ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by aaronsace** [comment]
Is this correct now?

**Comment by UselessGuru** [comment]
Yes. Thanks!
