### ISSUE TITLE
Multiple instances of same algo in same pool cripple stats (hash-to-coins)

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#428]
When developing a pool file for #412 'hash-to-coins' (just for the sake of it) I noticed that there is an issue that could lead to crippled stats.

Note: I am aware that mining with 'hash-to-coins' is not a very valid scenario for MPM, but the data structure provided by the API demonstrates a possible design flaw in MPM.

Hash-to-coins is special because it supports mining with the scrypt algorithm only.
The API lists different coins and prices. But for all coins the algo is 'scrypt'.

-> When MPM iterates through the web_request it updates the stats with very inconsistent princing information (same algo, but different price for each iteration).
In MPM all pool records for 'hash-to-coins' would be of type 'algorithm=scrypt' and use the same url & port. (not useful in MPM)

When you mine with 'hash-to-coins' the scrypt hashes are somehow auto-converted and payout is in various alt coins depending on your 'hash-to-coins' worker config (no payout conversion in BTC)

See attached web request file:
[HashToCoins.txt](https://github.com/aaronsace/MultiPoolMiner/files/1377421/HashToCoins.txt)

For those who want to dig deeper here is my non-working pool file:
[HashToCoins_PoolFile.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/1377472/HashToCoins_PoolFile.ps1.txt)

**Comment by aaronsace** [comment]
Use the bit that says 'auto now' at the top of the webpage then tick 'auto switch' in the workers page.

**Comment by aaronsace** [comment]
If you don't want it to be automatic then maybe this could set it manually: 
https://hash-to-coins.com/index.php?page=api&action=setworkercurrency&api_key=_USER_API_KEY_&worker=_WORKER_NAME_&coin=_COIN_TAG_
