### ISSUE TITLE
new algo in zpool

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#429]
two new alo "hsr" and "phi" add to the zpool. i am add miner in folder BIN, add file.ps1 in folder miners and miner does not work

**Comment by UselessGuru** [comment]
@spider703 

You must be doing something wrong. You only need a proper miner file.

[ccminer-2.2.2.ps1.txt](https://github.com/aaronsace/MultiPoolMiner/files/1382785/ccminer-2.2.2.ps1.txt)

**Comment by Pititul** [comment]
You need to add these names in the Algorithm.txt too.

**Comment by aaronsace** [comment]
@Pititul you shouldn't _have_ to, maybe it's a bug.

**Comment by spider703** [comment]
you're right
