### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by Voror** [aaronsace/MultiPoolMiner#43]
Errors in benchmarking under Windows 7 in spite of Windows installer 5.  Install WebPlatformInstaller and reboot.  Reboot prevents Fail to bind port 4048 from previous run.  Benchmarking going much smoother now.

**Comment by aaronsace** [comment]
Can anybody confirm this issue or have some detail as to what's actually the cause?

**Comment by lyolyalya** [comment]
sorry,not using win7 for a long time already...

**Comment by D0ssis** [comment]
Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

Stop-Process : The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HA
NDLE))
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Stop-Process], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Micr
   osoft.PowerShell.Commands.StopProcessCommand

Process has exited, so the requested information is not available.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\MultiPoolMiner.ps1:102 char:1
7
+                 Stop-Process $_.Process
+                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], InvalidOperationExcept
   ion
    + FullyQualifiedErrorId : System.InvalidOperationException

New-Object : A constructor was not found. Cannot find an appropriate constructo
r for type System.IO.StreamReader.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\Include.ps1:191 char:23
+             $Reader = New-Object System.IO.StreamReader $Stream
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentExce
   ption
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.C
   ommands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Users\dossis\Downloads\MultiPoolMinerV2.3.2\Include.ps1:193 char:13
+             $Request = $Reader.ReadToEnd()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull




Alot of this kind of errors while doing benchmark on Windows 7 Ultimate 64bit.

**Comment by aaronsace** [comment]
Those errors are because the miner is not open so it can't read the hash rate. Please can you attach the log file?
Can you confirm that you have updated to PowerShell 5: https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by D0ssis** [comment]
I have updated to PowerShell 5. Heres the full log file because of maximum 65536 characters and maximum file limit on pastebin is too small for this:

http://uploadboy.me/urehog95u8q3/2017-01-19_04-45-41.txt.html

**Comment by D0ssis** [comment]
I restared Multipoolminer and I dont get those errors anymore so they were appearing only in Benchmark stage.

Thanks anyways. I hope that log file helps to detect where the problem is so it can be fixed for the rest of users who might crash in to it.

**Comment by aaronsace** [comment]
It may have just been blocking the miners from running when you first ran them. I will look at the log later to check it's working right. 
(BTW you can drag and drop files onto github posts. )

**Comment by D0ssis** [comment]
Ah ok, thanks for the heads up! :)
