### ISSUE TITLE
Hash rates vs accepted share

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#431]
Hash rates or accepted share, which is more profitable? I have 2 ccminers (newest Nanashi and Alexis) on the same algo, one is 96 MHs and the other one is 83 MHs but the later gets more "yes!." I'm keeping both for now. 

Maybe this should take into account when benchmarking.

**Comment by aaronsace** [comment]
My first thought is that the difficulty of the stratum connection is probably different because it is variable.

**Comment by Pititul** [comment]
Alright, thx man.
