### ISSUE TITLE
Changing poolname doesn't work as expected

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#433]
This is related to https://github.com/aaronsace/MultiPoolMiner/issues/419.

MPM should only mine on the specified pools no matter what algos are specified. And MPM should only mine on the specified algos, no matter what pools are specified.

Put it another way:
1. MPM should never mine or benchmark on a pool that is not specified.
2. MPM should never mine or benchmark on an algo that is not specified.
3. Previous existing benchmark and/or profitability data should not override #1 and #2.
4. If a pool/algo combination is not valid, it should silently ignore that combination and never try to benchmark or mine it.

I just finished several days mining in NiceHash using their GUI miner to document how well it did. Next, I want to use MPM to mine exclusively on MPH for several days. Then I will have MPM mine exclusively on ZPool or NiceHash. Whenever I switch from pool to pool, I don't want to have to examine which algos are currently supported by which pools. MPM should know which are available through the API of the pool.

**Comment by aaronsace** [comment]
The pools have loads of algorithms that are no use; you have to specify which algorithms that you wish to mine on. 

Please check the three start.bat varirnts

**Comment by aaronsace** [comment]
Which pool you mine on has little relevance. 

For your tests, I recommend removing the Bitcoin address from the bat file or deleting the pool files.

**Comment by aaronsace** [comment]
The reason '-poolname' is a preference only and doesn't remove pools is not only for safety but also so that you can do things like this: 

`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -workername multipoolminer -poolname zpool -algorithm ethash,decred,equihash,groestl,lbry,neoscrypt,sib"`

Only Ethash will mine on NiceHash in this command line; all others will use Zpool.

**Comment by mjmeans** [comment]
What will happen in your case if ethash on Zpool is never the most profitable is that you will waste mining resources benchmarking ethash on ZPool and never be able to accumulate enough coin even after a year and multiple benchmarks to transfer to your external wallet. It will be lost rewards.

The way you are going, with new multi-mining pools coming up ever few months, you will end up with splitting your mining rewards between more pools giving you lower balances per pool. And with each pool having minimum payout rules and different payout fees, tracking your profits will get geometrically more difficult. And mining rewards a pool that happens to be more profitable for a few days (or even for just the few minutes while benchmarking) will be lost rewards if that pool never becomes profitable again.

I then suggest a different way. Make poolname and algos follow the rules I suggest above (which would mean that in your example command NiceHash would never be mined because it was "enabled"). Or allow a more declarative command that enables specific algos per pool i.e. "-poolname zpool(decred,equihash,groestl,lbry,neoscrypt,sib),nicehash(ethash),zpool ". In this example zpool would be used for all available algos, so ethash would mine on NiceHash and could mine on zpool if zpool supports it.

**Comment by aaronsace** [comment]
You're overthinking this. 

All you need to do is specify one pool that you want to be the default then specify some algorithms. There is no better way to ensure you send your resources to the least number of pools. 

The algorithms that you pick are more important than sticking to one pool.

**Comment by aaronsace** [comment]
There are ways to achieve this with the existing standard command line options so I'm closing this.

**Comment by aaronsace** [comment]
@fonyo If you get chance, can you update the help files to make to clear the '-poolname' is to specify the **default** pool(s) and is not a filter? 

'-Algorithm' is a filter and is the key to configuring MultiPoolMiner.

**Comment by mjmeans** [comment]
Well, I agree that not mining on an available algo is something most people will never want to do, but I disagree about the pool choices. If I want to mine only on pools (x and y) and I don't want 1% of my mining capacity spent on pool (z) and end up with such low balances on that pool that it takes months to even have enough to meet their minimum to transfer to an external wallet. All such minor amount are wasted income. There is a time value of money. If 1% goes to each of 4 pools and the remaining 96% goes to the default pool, then you have an effective additional 4% loss (over fees) in the time value of money since it is money you can't use for anything at all until you reach the payout limits of those pools.

**Comment by fonyo** [comment]
I agree it is not feasible to have earnings spread out to many pools BUT this is not a one-click-miner and its current scope and feature set would not allow for such implementation required to resolve this in a fashion that satisfies the needs of everyone. As simple as we want this to be, users do need to know what they are doing in order to avoid such anomalies of wasted cents and mining power. 

Updated README and clarified functionality. I may just add a warning as well.
