### ISSUE TITLE
watchdog option

### ISSUE THREAD

**Issue by gemini100** [aaronsace/MultiPoolMiner#434]
hi arronsace 
first of all, very big work, thank s a lot, it could pass nicehash software
i v got proble with watchdog,
on start.bat in the front code page here in git it's written  -watchdog at the end
in version 2.6.0.2 (start.bat no option -watchdog is written ) no problem

what are files concerned by this option too download and be sure that all work fine????
2/ if there is something i could help just write me and ask; it would be a pleasure

**Comment by aaronsace** [comment]
I recommend downloading everything then just copy the 'bin' and 'stats' folder from the old version.

**Comment by gemini100** [comment]
thank you aaronsace
if you need some help, like translating, collecting datas, just ask about it, try i will be on my best skills for the job
