### ISSUE TITLE
MPM profitibility vs actual down 40% today

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#438]
It looks like MPM is reporting the same profitability per day today as it did yesterday. even after resetting profit calculations. However, actual profits appearing at MPH plus other pools totals about 20% lower. Could this be caused by the recent Ethereum hard fork and maybe the profitability services that MPM uses hasn't adjusted yet?

**Comment by aaronsace** [comment]
If you look in the profit text files then it has a breakdown of time periods. You will be able to see if it has dropped from the week average.

**Comment by jjziets** [comment]
I also see this. $ per card reports at $2.3 but I got $1.9 over 24h period.

**Comment by aaronsace** [comment]
I doubt this is a problem with MultiPoolMiner. The stats are the average over the week and should be used as a guide.

**Comment by mjmeans** [comment]
I used reset-profits.bat so it shouldn't be counting anything from the previous week.

**Comment by aaronsace** [comment]
@mjmeans Then that's the average profit since you reset it.

**Comment by mjmeans** [comment]
And that means it's way wrong. Now looking like 40% off.
