### ISSUE TITLE
Resolve Dns_name

### ISSUE THREAD

**Issue by tatsumakisen** [aaronsace/MultiPoolMiner#439]
![multipoolminer issue](https://user-images.githubusercontent.com/32253596/31746567-15f22ba8-b436-11e7-8a16-14b92f359486.jpg)

Resolve-DnsName : us-east.equihash-hub.miningpoolhub.com : Se devolvió esta operación porque se agotó el tiempo de espera
En C:\Users\jegg\Desktop\MultiPoolMiner-master ACTUAL 18-10-2017\Miners\Excavator2.ps1: 25 Carácter: 127
+ ... @("$_", "$((Resolve-DnsName $Pools.$(Get-Algorithm $_).Host -ErrorAct ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (us-east.equihash-hub.miningpoolhub.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : ERROR_TIMEOUT,Microsoft.DnsClient.Commands.ResolveDnsName

**Comment by aaronsace** [comment]
us-east.equihash-hub.miningpoolhub.com is down?

**Comment by tatsumakisen** [comment]
No, everything seems to be working fine right now

**Comment by aaronsace** [comment]
If it's working now then I'll close the issue.
