### ISSUE TITLE
edit time for benchmark

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#440]
how i can reduce time for bechmark in your programm?

**Comment by aaronsace** [comment]
Limit the algorithms and lower the interval.

**Comment by spider703** [comment]
limit in file MultiPoolMiner.ps1?

**Comment by aaronsace** [comment]
No, the bat file.

**Comment by spider703** [comment]
--benchmak 1 
???

**Comment by aaronsace** [comment]
No, it's literally called interval. Check the readme.
