### ISSUE TITLE
Prospector is not Connecting to the Pool

### ISSUE THREAD

**Issue by leetlezee** [aaronsace/MultiPoolMiner#441]
[2017-10-19_00-32-56.txt](https://github.com/aaronsace/MultiPoolMiner/files/1398917/2017-10-19_00-32-56.txt)
Prospector keeps having errors connecting to the pool, but MultiPoolMiner doesn't recognize the issue and keeps running Prospector even though it's not actually mining.

**Comment by aaronsace** [comment]
Try the new watch dog feature.
