### ISSUE TITLE
try convert .ps1 to .exe

### ISSUE THREAD

**Issue by gemini100** [aaronsace/MultiPoolMiner#442]
i notice that powershell consume a little bit ressourcess more than an exe classic monitoring software that s  why there not enough ressources in a little cpu like my g4400 and cause, i think,  claymore dual to crash on my two principals rig,
when i add a cpuminer on 1 thread my cpu goes to 100% 
because powershell 5 need between 48 and 70% ressources of cpu....

i was trying to convert multipoolminer.ps1 to multipoolminer.exe it seems to work, i convert now include too.... i will tell you guys about my little experience,
i m conscient that it would be more complicated and huge pain to ass, but it's a begining like always

**Comment by aaronsace** [comment]
I would just recommend turning CPU mining off as it wouldn't be worth it anyway. 

It's wrote in PowerShell for flexibility; I could have done it in C# or C++ and compiled it. There are plenty of improvements to be made including optimizing but it's to remain as plain PowerShell.

**Comment by gemini100** [comment]
thanks arronsace, yes i turn off cpu mining
but on my two 6 gpu rigs, it crash when doing claymore dual, i think, not sure,
MPM is very clever like that, it turn very well on two small little rig one and two gpu, for 6, it keep crashing when mining with claymore i think

and i try nicehash legacy, no crash, and the good minercontrol of Kbomba originally, no crash....
i m very disapointed cause i ll planning work with MPM ... for all rigs
here is the last lines of my log file: it tell that crash for ccminer-x64.exe -a sib but claymore was running or shutting down may be


### 

   


   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a sib -o
                                               stratum+tcp://sib.mine.zpool.ca:5033 -u
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd -p worker2,c=BTC


   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
1.77 KH/s 00 Days 00 Hours 01 Minutes Once     Bin\Equihash-EWBF\miner.exe --eexit 1 --api --server
                                               equihash.eu.nicehash.com --user
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd.worker2 --pass x --port 3357
                                               --solver 0
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20535 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 20 -platform 2
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a equihash -o
                                               stratum+tcp://equihash.eu.nicehash.com:3357 -u
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnC3Pc5RN.worker2 -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFBEGwVm3cuoQUwXNrfwVEwC3Pc5RN
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 30 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFBEGwVm3cuoQUwXNrfwVEwC3Pc5RN
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 40 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\NVIDIA-KlausT\ccminer.exe -a groestl -o
                                               stratum+tcp://europe.hub.miningpoolhub.com:20486 -u
                                               geminiwhitehat.worker2 -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               lbry.eu.nicehash.com:3356 -dwal
                                               33t3PFBEGwVm3cuoQUwXNrfwVEwC3Pc5RN.worker2 -dpsw x -dcoin lbc -dcri 40
                         Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a sib -o
                                               stratum+tcp://sib.mine.zpool.ca:5033 -u
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd -p worker2,c=BTC


   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
1.77 KH/s 00 Days 00 Hours 01 Minutes Once     Bin\Equihash-EWBF\miner.exe --eexit 1 --api --server
                                               equihash.eu.nicehash.com --user
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd.worker2 --pass x --port 3357
                                               --solver 0
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20535 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins 1 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 20 -platform 2
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a equihash -o
                                               stratum+tcp://equihash.eu.nicehash.com:3357 -u
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnC3Pc5RN.worker2 -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 30 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               decred.mine.zpool.ca:5744 -dwal 33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd
                                               -dpsw worker2,c=BTC -dcoin dcr -dcri 40 -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\NVIDIA-KlausT\ccminer.exe -a groestl -o
                                               stratum+tcp://europe.hub.miningpoolhub.com:20486 -u
                                               geminiwhitehat.worker2 -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               lbry.eu.nicehash.com:3356 -dwal
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd.worker2 -dpsw x -dcoin lbc -dcri 40
                                               -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               lbry.eu.nicehash.com:3356 -dwal
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd.worker2 -dpsw x -dcoin lbc -dcri 30
                                               -platform 2
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a lbry -o
                                               stratum+tcp://lbry.mine.zpool.ca:3334 -u
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd -p worker2,c=BTC
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool
                                               europe.ethash-hub.miningpoolhub.com:20565 -ewal geminiwhitehat.worker2
                                               -epsw x -esm 3 -allpools 1 -allcoins exp -dpool
                                               pascal.eu.nicehash.com:3358 -dwal
                                               33t3PFhfgdhss55f4ddsxfqmskxdjcnB26fgd.worker2 -dpsw x -dcoin pasc -dcri 20
                                               -platform 2

**Comment by gemini100** [comment]
it actually going on an old mobo of 2007 with e2200 cpu 2 gb of DDR2; and two 1060 gpu without display, accessing by remote management... so, for more than 3 days

**Comment by UselessGuru** [comment]
"Compiling" PowerShell is probably not giving better performance or reduce memory consumption, since it is not really compiled.
Instead a 'wrapper' will be put around your script that makes it directly executable. However PowerShell must still be present on your system, and the actual code executed will still be in PowerShell script.
Compiling PS makes primarily sense if you want to obfuscate your code, or if you want to prevent accidental code modifications.

**Comment by aaronsace** [comment]
Delete any miners that are not working on your system from the folder called 'miners'.

**Comment by gemini100** [comment]
thank you Arronsace, have a discussion with you make me stronger, really
in what you offer for the network, for the community, i do my best each day
to understand what you offer to us, and when i could, i will participate to
your big picture with financial support

**Comment by AcharyaOne** [comment]
Not sure if it is related but I have a similar problem when mining neoscrypt with klaust or alexis at default settings which run forever with no errors outside of multipoolminer but when using multipoolminer it exits with a cpu inline memory (or something like that) error. Any idea of what could be causing this problem?

**Comment by aaronsace** [comment]
@AcharyaOne There is no way MultiPoolMiner could cause a the miner to fail. The command line that you use to run it manually may not exactly match the command line shown on MutiPoolMiner; double check and see if there is a difference.

**Comment by gemini100** [comment]
like arron says, cpu mining isn't very very important for a little cpu
i notice that powershell use sometjhing 50% of cpu ressources, sometimes
more, that s not sufficient for at least one thread mining....
don ' t forget that our cpu and ddr works hard with the gpu, even for gpu
mining too

**Comment by AcharyaOne** [comment]
@aaronsace  I know it's weird but it does, it's exactly the same command, as suggested somewhere by uselessguru the command line for each miner is saved in it's folder.

@gemini100 @aaronsace 
I tried changing neoscrypt miner cpu priority (to 4), disabling cpu mining but I still have the same issue, I mine with 8 gpu, maybe the problem is some weird combination of resources used at same time by powershell and neoscrypt miner. (i3-7100t, 8gb ddr2400, 60gb pagefile)

**Comment by AcharyaOne** [comment]
@aaronsace  I know it's weird but it does, it's exactly the same command, as suggested somewhere by uselessguru the command line for each miner is saved in it's folder.

@gemini100 @aaronsace 
I tried changing neoscrypt miner cpu priority (to 4), disabling cpu mining but I still have the same issue, I mine with 8 gpu, maybe the problem is some weird combination of resources used at same time by powershell and neoscrypt miner. (i3-7100t, 8gb ddr2400, 60gb pagefile)

**Comment by gemini100** [comment]
yes acharya it's ressources problem at certain moment , just when you are
outside, think about loosing work of 8 GPU s for one day,because of of cpu
mining,
like you i try, i try, but after i realise, that my cpu is much much
important than cpu mining, i advice you, too stop, it dosen't , i don't
know how to say in english,
your cpu have a noble mission that drive all the big picture so let it work
at his own

**Comment by fonyo** [comment]
I overloaded and basically burnt down an extension lead due to CPU mining (while testing m7m). I can post photos if anyone wants to see it. While everything was fine mining with GPUs, I did not account for the extra power going through with CPU mining. While m7m was relatively profitable, it wasn't profitable enough to have such downtime caused by the melted plug (it shut down two rigs).

Be careful, guys. Luckily, there was no fire and I witnessed it in person.

**Comment by gemini100** [comment]
really sorry for you man
i try to turn your attention from cpu mining, much than a time
very sorry, i hope you turn on your rigs easilly
and always cpu mine with one thread, the most important is to keep it on

**Comment by gemini100** [comment]
sheet, for burning.... that a bad news

**Comment by fonyo** [comment]
It is all OK, every single plug, socket, extension cord etc. tend to have 13A fuses fitted in them in the UK. This prevents bad things from happening but can be very annoying when the quality of the installed fuse is rubbish and cuts way under 13A. When I calculated the consumption after the meltdown, I realised I was pulling way above 13A, so in this case at least it was a good fuse... :)

**Comment by gemini100** [comment]
ok fonyo happy for you
turn off cpu mining,, you think that it doe s nothing but cpu is in the
heart of the system
keep it clean, safe, under work

**Comment by fonyo** [comment]
I meant it's not worth blowing up fuses and killing CPUs for a few cents a day.

**Comment by gemini100** [comment]
that's what i call good approach

**Comment by AcharyaOne** [comment]
The miner exits with an error like this:
![image](https://user-images.githubusercontent.com/31579891/32689592-90e525c0-c6df-11e7-8e23-7d2f83fb20ae.png)

It seems powershell cpu affinity is linked with all the miners it calls, I think that is the reason for the error, could an overclock cause this?
Anyway I can run with no problems multipoolminer with cpu mining only and neoscrypt miner outside of multipoolminer at same time.
![image](https://user-images.githubusercontent.com/31579891/32689688-931b95bc-c6e0-11e7-898d-8545c70b53cc.png)

ccminer.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.ahashpool.com:4233 -u 3Jxu5ULZKZfsiLxNA8rn5FrQ5B2NiqXKki -p multipoolminer,c=BTC -i 17.6 --cpu-affinity 0x3 --cpu-priority 5

**Comment by fonyo** [comment]
From my experience all cuda errors are caused by too much OC. This doesn't mean it can't be a miner issue but there is less than 1% chance for that and if so or to make sure, you should post this to the Github repository of that particular miner.

**Comment by fonyo** [comment]
Also, please be careful with CPU mining. I strongly advise against it.

**Comment by gemini100** [comment]
me too
max on one thread,
if you have 4 core, 2 thread
always let much than egnough power or ressources for the work
