### ISSUE TITLE
dstm’s ZCash Nvidia Miner v0.5.2 for Windows

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#443]
[http://cryptomining-blog.com/9208-dstms-zcash-nvidia-miner-v0-5-2-available-for-windows-now/](http://cryptomining-blog.com/9208-dstms-zcash-nvidia-miner-v0-5-2-available-for-windows-now/)

To include the miner:
1. Download and extract the miner manually to 'Bin\NVIDIA-DSTM'
2. Extend  include.ps1 / get-hashrates:

```
            "dstm" {
                $Message = @{id = 1; method = "getstat"} | ConvertTo-Json -Compress

                $Client = New-Object System.Net.Sockets.TcpClient $server, $port
                $Writer = New-Object System.IO.StreamWriter $Client.GetStream()
                $Reader = New-Object System.IO.StreamReader $Client.GetStream()
                $client.SendTimeout = $Timeout * 1000
                $client.ReceiveTimeout = $Timeout * 1000
                $Writer.AutoFlush = $true

                do {
                    $Writer.WriteLine($Message)
                    $Request = $Reader.ReadLine()

                    $Data = $Request | ConvertFrom-Json
                
                    $HashRate = $Data.result.avg_sol_ps

                    if ($HashRate -eq $null) {$HashRates = @(); break}

                    $HashRates += [Double]($HashRate | Measure-Object -Sum).Sum

                    if (-not $Safe) {break}

                    Start-Sleep $Interval
                } while ($HashRates.Count -lt 6)
            }
```
3. Copy the attached miner file to the miner folder
[DSTM.txt](https://github.com/aaronsace/MultiPoolMiner/files/1401121/DSTM.txt)

**Comment by UselessGuru** [comment]
EBWF, Nicehash, NicehashEquihash and DSTM all report their hashrate the same way, just the attribute name is different. e.g. EWBF = 'result.speed_sps' vs. DSTN = "avg_sol_ps"

You could possible reduce the number of API's (from 4 make 1):

How about adding the attribute name to the miner file (extra parameter, eg. "Hashrate_AttName" = "avg_sol_ps" for DSTN)

Then retrieve the hashrate in Get-Hashrates using the extra parameter instead of having 4 different miner API types.

**Comment by aaronsace** [comment]
Something definitely needs doing with the APIs. 

May move the APIs into separate files in a folder called 'APIs' then have an some sort of in/out message command option.

**Comment by alucard20724** [comment]
is there a working api for this yet?...  currently i can't get it to save the hashrate in the stat file... just keeps recording "0"

**Comment by aaronsace** [comment]
Nope, the APIs will be updated soon; should be done by the weekend. 

I'll then aim to mark a release before moving on.
