### ISSUE TITLE
pre-releaze this Watchdog Timer

### ISSUE THREAD

**Issue by spider703** [aaronsace/MultiPoolMiner#445]
postpone please prerelease with watchdog or attach here, the thing is very necessary

**Comment by aaronsace** [comment]
You can just download the code without the 'bin' folder: https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

I will try and get a pre-release up tomorrow.

**Comment by aaronsace** [comment]
Sorry about the delays; there were too many issues and not enough time. 

Just a few issues on GitHub to close and then I will mark a release.
