### ISSUE TITLE
ZecMiner issue

### ISSUE THREAD

**Issue by mjmeans** [aaronsace/MultiPoolMiner#449]
ZEC - Total Speed: 0.000 H/s, Total Shares: 0(0+0+0+0+0+0), Rejected: 0, Time: 00:01
ZEC: GPU0 0.000 H/s, GPU1 0.000 H/s, GPU2 0.000 H/s, GPU3 0.000 H/s, GPU4 0.000 H/s, GPU5 0.000 H/s
Pool switches: ZEC - 1
GPU0 t=46C fan=28%, GPU1 t=50C fan=0%, GPU2 t=41C fan=28%, GPU3 t=45C fan=28%, GPU4 t=48C fan=27%, GPU5 t=54C fan=26%

GPU0 t=45C fan=27%, GPU1 t=50C fan=0%, GPU2 t=40C fan=26%, GPU3 t=45C fan=26%, GPU4 t=47C fan=25%, GPU5 t=53C fan=25%
ZEC: Stratum - connecting to 'equihash.usa.nicehash.com' <169.45.93.83> port 3357 (SSL/TLS)
Cannot establish SSL/TLS connection
ZEC: Stratum - Cannot connect to equihash.usa.nicehash.com:3357
ZEC: Stratum - Failed to connect, retry in 20 sec...
ZEC: Stratum - connecting to 'equihash.usa.nicehash.com' <169.45.93.83> port 3357 (SSL/TLS)
Cannot establish SSL/TLS connection
ZEC: Stratum - Cannot connect to equihash.usa.nicehash.com:3357
ZEC: Stratum - Failed to connect, retry in 20 sec...

**Comment by kiLLeen** [comment]
I don't understand what makes you think that is related to MPM. This is a log of a miner not able to connect to Nicehash.

**Comment by aaronsace** [comment]
The new watchdog timer will pickup this failure.
