### ISSUE TITLE
Switching very often

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#450]
I think my mpm setting switches pool and algo too often. One algo launched 19 times for the total of 1 hour. Is this ok? Should it stay on one algo longer in order to get the share? I'm making only 0.0005 a day on zpool (according to zpool page). 

I gonna try running on Nicehash+MPH now. Maybe zpool isn't as profitable as many people claim. 

Or is it because I have too many algos so it switches ll thr time?

3 x 1070

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -Noninteractive -command "&.\multipoolminer.ps1 -wallet 358nQ1UpueNaw3118AmwA1PriTwRU9qbzM -username Meeh -workername Alpha -ssl -region asia -interval 300 -currency thb,btc,usd -type nvidia -poolname zpool, nicehash -algorithm bitcore,blake2s,blakecoin,c11,cryptonight,decrednicehash,ethash,equihash,groestl,hmq1725,hsr,jha,keccak,lbry,lyra2re2,lyra2z,myriadgroestl,neoscrypt,nist5,pascal,phi,quark,qubit,sia,sianicehash,sib,skunk,skein,tribus,timetravel,xevan,x11,x11evo,x17,veltor -donate 15 -watchdog"

**Comment by aaronsace** [comment]
Get rid of any dodgy algorithms.

**Comment by Pititul** [comment]
Thank you very much. I'll try this tomorrow. Right now I want to see how much MPH+NH running for 24hrs make.

**Comment by fonyo** [comment]
I agree you have way too many algorithms selected. For 1070 cards I recommend these.
-poolname miningpoolhub,miningpoolhubcoins -algorithm cryptonight,decred,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,siaclaymore,myr-gr,lyra2re2,lyra2,lyra2rev2,lyra2v2 

The best way to test is to try them out separately. Try MPH for 24 hours, then do the same with Nicehash. However, there are some algorithms/coins either of them won't support.

Good luck, I am sure you will see improvements!

**Comment by Pititul** [comment]
@fonyo which pool are you currently mining on?

**Comment by fonyo** [comment]
The config above is from my 1070 rig, so I am mining mostly on MPH but after fine-tuning Claymore Dual (created over 100 extra miner files for Sia, Decred, LBRY for both normal and 2gb versions), I figured it is worth the effort to include zpool when mining lbry and Decred for 10-15% extra profit occasionally.

Check out my fork if you are interested. I also have a batch file that only adds extra miners that are relevant to 1070 rigs to save time with benchmarking. My fork is based on the latest release (2.6.0.2) so if you are using the latest MPM master with the watchdog feature, you can just download the Plugins folder only and place it to MPM root and it will work.

**Comment by FruitFace** [comment]
I have 3x 1070's and 1x 1080ti.  Would you say that you branch would work well, even with the 1080ti?

**Comment by fonyo** [comment]
Sure, if it was a normal 1080, that would be a different case due to the gddr5x memory but you should be good. It takes a while to bench but the benefit is great.

**Comment by Pititul** [comment]
I did the Claymore dcri fine-tune... following your lead, but with ahashpool, it still switches like crazy (lyra2z, lyra2re2 and myr-gr, 10-15 minutes each). MPH doesn't switch as often tho but it also make less than zpool does when comparing 24hrs. These yiimp clones seem to switch all the time.

I'll try MPH+zpool as you suggested today.

**Comment by Pititul** [comment]
I think I'll set the interval to 15 mins since most coin's estimate average time per block is around 10 mins.

**Comment by Pititul** [comment]
Lbry in Zpool hasn't paid for a while now, so I added LbryNiceHash, now it's up top. Also Decred isn't paying in Zpool and Sia doesn't work in MPH... only NiceHash.

**Comment by fonyo** [comment]
Setting the interval that high is not the best idea as you will limit the update frequency of MPM.

**Comment by FruitFace** [comment]
I suppose the question (which may have no good answer) is how much switching is too much?  I configured my start based of the info from this thread, and used Fonyo's 1070 to flavor the config, as well.

Here's a snapshot from today:

![switches](https://user-images.githubusercontent.com/26655630/32033264-e51b9d64-b9c8-11e7-9c45-5fb69017ea85.JPG)

That's with the following start.bat:
-type nvidia -poolname zpool, miningpoolhub, miningpoolhubcoins -algorithm cryptonight,decred,ethash,equihash,groestl,lbry,siaclaymore,myr-gr,lyra2re2,lyra2,lyra2rev2,lyra2v2,lyra2z,Sia,Sib -donate 1 -watchdog

**Comment by Pititul** [comment]
@FruitFace it's the PPLNS that I am concerning.

I agree, best support ever and an ingenious piece of work.

**Comment by fonyo** [comment]
Well, it should get better and switch less the more you use it as your average hash for each algo becomes more accurate. I am just doing this for fun, happy to help. ;)

**Comment by fonyo** [comment]
Closing this now, please post a new thread if you have any more queries.
