### ISSUE TITLE
No Pools available

### ISSUE THREAD

**Issue by TheSkynet1337** [aaronsace/MultiPoolMiner#457]
I continuously get a string of error messages followed by No pools available. If I manually go to https://miningpoolhub.com/index.php?page=api&action=getautoswitchingandprofitsstatistics however, the site seems to be operating normally.
 It is also preventing initial setup of the new build, MPM never switches to benchmarking.
This is on a clone from 1h ago(26/10/17 18:31CEST).
[2017-10-26_18-28-26.txt](https://github.com/aaronsace/MultiPoolMiner/files/1419206/2017-10-26_18-28-26.txt)
[2017-10-26_18-29-46.txt](https://github.com/aaronsace/MultiPoolMiner/files/1419207/2017-10-26_18-29-46.txt)

**Comment by aaronsace** [comment]
Please use the release.

**Comment by tatsumakisen** [comment]
The same here, No pools available,,   Include.ps1  -> Include.psm1

**Comment by aaronsace** [comment]
Please use the release.
