### ISSUE TITLE
Is fees takine in to the prof calc? 

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#458]
I noticed that mining with neoscrypt that zpool(2%) nicehash(3%) is prefer over miningpoolhub(0.9%)

![image](https://user-images.githubusercontent.com/19214485/32072668-b3461d8e-ba93-11e7-8938-ddfdd30e2924.png)

is fees part of the profit calc?

**Comment by jjziets** [comment]
![image](https://user-images.githubusercontent.com/19214485/32072746-01f0df00-ba94-11e7-83ef-9ce89c96c753.png)

![image](https://user-images.githubusercontent.com/19214485/32072765-17a756d0-ba94-11e7-9aef-c13c575fae01.png)

![image](https://user-images.githubusercontent.com/19214485/32072784-2e809470-ba94-11e7-9750-76b526d461ff.png)
![image](https://user-images.githubusercontent.com/19214485/32072793-390b782e-ba94-11e7-929c-ea7e2644c8e4.png)

**Comment by jjziets** [comment]
this is with the same start.bat

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3FNSyKaq388KuzSEz2E7aRETn5tnpowF95 -username Etherion -workername wk4 -ssl -region europe -currency btc,usd -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool,nicehash -algorithm neoscrypt -donate 10"

**Comment by aaronsace** [comment]
No, pick wish pools you want to pay for.
