### ISSUE TITLE
zpool

### ISSUE THREAD

**Issue by theeddie** [aaronsace/MultiPoolMiner#459]
Is anyone else having problem with the zpool side of this script?  seems zpool is not reporting any profits

**Comment by Pititul** [comment]
Not for me.

**Comment by aaronsace** [comment]
Zpool drops out sometimes. New release coming this weekend with many improvements.

**Comment by fonyo** [comment]
When do you exactly plan to do the new release, I want to make sure I fix the encoding issues by then and maybe update the README with a few more things so there are less handholding in the future (maybe a step-by-step guide would be useful for entry level users?). Please let me know.
