### ISSUE TITLE
Cannot run latest code (using module .\Include.psm1)

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#460]
I cannot run the latest code (using module .\Include.psm1). In any case I get the following errors:
```
Set-Stat : Cannot process argument transformation on parameter 'Duration'. Cannot convert null to type "System.TimeSpan".
At C:\Program Files\CryptoMining\MultiPoolMiner-master\Pools\MiningPoolHub.ps1:27 char:127
+ ... it" -Value ([Double]$_.profit / $Divisor) -Duration $StatSpan -Change ...
```
[2017-10-27_08-04-50.txt](https://github.com/aaronsace/MultiPoolMiner/files/1420940/2017-10-27_08-04-50.txt)

I tried to fix it by changing $StatTime to a global variable):
>     $Global:StatSpan = New-TimeSpan $StatStart $StatEnd
This modified code can then be run but it finds no pools (because the wallet value is missing).

[2017-10-27_08-07-11.txt](https://github.com/aaronsace/MultiPoolMiner/files/1420941/2017-10-27_08-07-11.txt)

I now added the wallet directly to the main code:
```
using module .\Include.psm1

param(
    [Parameter(Mandatory = $false)]
    [String]$Wallet="1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb", 
    [Parameter(Mandatory = $false)]
```
Still no pools found!
However I can run the same code in a debug environment (PowerGUI or Visual Studio Code)

**Comment by aaronsace** [comment]
Confirmed.

**Comment by aaronsace** [comment]
Pools complete: 
https://github.com/aaronsace/MultiPoolMiner/commit/a711203028b0ca1ce9023fd6d7d8a3b5ea89eeab

I'll amend the miners tonight.

**Comment by UselessGuru** [comment]
All fixed now! Great! I really appreciate your effort. Your code makes very good study material - at least for me 👍
