### ISSUE TITLE
Benchmarking use back default username/workername

### ISSUE THREAD

**Issue by joeyoon80** [aaronsace/MultiPoolMiner#462]
Found an issue where during benchmarking the miner uses back the default username.working name which is aaronsace.multipoolminer instead of my username.workername defined in the start.bat file.

![image](https://user-images.githubusercontent.com/32901879/32140932-fd40be60-bcac-11e7-96d7-8ad06647824d.png)

**Comment by fonyo** [comment]
Are you using the latest release or latest master?

**Comment by joeyoon80** [comment]
Latest release V2.6.0.2. Also Lyra2Rev2 Miningpoolhub  benchmark using ccminer didn’t work, it kept saying waiting for another 30secs, but not sure if that’s the server issue.

Sent from Mail for Windows 10

**Comment by fonyo** [comment]
I was unable to reproduce this. Can you confirm you are launching the same batch file you edited with your details?

**Comment by joeyoon80** [comment]
Yes confirmed few times that the batch file had my details only. I just re-ran the benchmark after clearing previous benchmark. Some of the benchmarking were done with your account instead.

![capture1](https://user-images.githubusercontent.com/32901879/32175278-6eaf784e-bdbf-11e7-8dff-b3e8c101e495.JPG)
![capture2](https://user-images.githubusercontent.com/32901879/32175279-6eed8404-bdbf-11e7-8b36-fdfd7fc944b3.JPG)
![capture3](https://user-images.githubusercontent.com/32901879/32175281-6f24bb4a-bdbf-11e7-9455-a0f6f7c4e439.JPG)
![capture4](https://user-images.githubusercontent.com/32901879/32175282-6f5c693c-bdbf-11e7-9e3f-6c9aecbb567a.JPG)
![capture5](https://user-images.githubusercontent.com/32901879/32175283-6f8f65ee-bdbf-11e7-8207-7dff304e7139.JPG)
![capture6](https://user-images.githubusercontent.com/32901879/32175285-700278f4-bdbf-11e7-9109-9c7e76ba269f.JPG)
