### ISSUE TITLE
Invalid Job IDs when mining to Zpool using DJM34\ccminer lyra2z

### ISSUE THREAD

**Issue by FruitFace** [aaronsace/MultiPoolMiner#464]
Not an issue with MPM, but wanted to see if anybody is seeing a large amount of Invalid JobIDs with lyra2z when mining to Zpool using djm34/ccminer-msvc2015?

I already posted a q in Github for the miner, but there doesn't seem to be much activity there...

It's not consistent, but there are times where near 80% of my submissions show the error.
It happens with both the Cuda9 and non-cuda9 versions.

![lyra2z](https://user-images.githubusercontent.com/26655630/32146120-7274f62a-bc98-11e7-880c-860437ff9065.jpg)

**Comment by fonyo** [comment]
This has started happening yesterday. Periodically zpool just rejects everything it receives for a few seconds (it happens on all my rigs at the same time). I believe it is an issue with the pool and not ccminer.

**Comment by FruitFace** [comment]
@fonyo  Thanks for confirming it's not just me.  I was going to post something in Zpool's bitcointalk forum, but I don't have permissions to do so.

**Comment by fonyo** [comment]
I noticed the same behaviour with optiminer while testing the m7m algo (XMG). I also dual mine ethereum on MPH and lbry on zpool. Ethereum works flawlessly (0 rejects) while lbry and m7m would go down at the same time on all rigs for a few seconds. It is definitely a pool-side issue. Zpool also went down for a little while yesterday.

**Comment by FruitFace** [comment]
Here's the response I received:
"It happens when a block is found on the network between when you received the work and when you miners sent back the work. A new block would have a new ID is all so your old work was invalid."

Doesn't sound like your situation though.

**Comment by fonyo** [comment]
That should happen only occasionally due to bad luck. When a new block is found, pool sends you message to drop the current work and gives you the new work to prevent this from happening. The fact this happens on multiple algos and rigs at the same time makes me have a conclusion of pool being either slow or having some other stratum issue. Also, m7m pool went down and even disappeared from the list on their site. That also makes me think they are experiencing some serious stratum issues they may not want to admit just yet.

**Comment by FruitFace** [comment]
Wonder if you'll get a different answer if you out in a ticket...

**Comment by fonyo** [comment]
It is not worth it for me to get involved with zpool and its shady stuff so I will have to kindly refuse your suggestion. I am merely testing things out. We will have to accept their response as a conclusion of this post (well, I am done with this for sure) and hope we were either unlucky and/or they are going to fix their pools at some point.

**Comment by FruitFace** [comment]
No worries.  Yah, I've read the threads with regarding the Zpool controversy.  I'm not sure how I feel about it tbh.  

Many sources suggest that despite the questions surrounding it, the payouts end up being better than MPH.

Really, the only 2 pools I mine to are Zpool and MPH anyway, as Nicehash's fees are too high, imo.  Also, I very much like the autoexchange feature for MPH and Zpool, which keeps me away from any other multipool.

Have you had any personal experiences that guided you away from Zpool?

I'll be closing this issue.

**Comment by fonyo** [comment]
No, I have been using MPH since the SimpleCrypto Group closed its doors. If I were in that situation and know everything was true and legit, I would pull together and publish all the logs and do everything I can to prove that my pool is not stealing. I did not see counter-proof anywhere. For me, that is enough and I just stay away (apart from trying out and testing a few things here and there).

**Comment by FruitFace** [comment]
Thanks for the detail.  One last question, what do you think of
hashrefinery?

**Comment by fonyo** [comment]
I don't have sufficient information of that pool but it has been around some time. Currently it integrates into MPM as a failover pool. I feel MPH could be the ultimate pool if the owner had more help with making improvements and more importantly doing so in a much quicker fashion. He is really taking MPOS to the limits with owning over 10-20% of network hash of multiple larger coins. He scaled up the servers multiple times on his own this year and with only really minor hiccups. Impressive. Honest and frequent comms on bitcointalk. These facts would win me over from any pool any time.

**Comment by FruitFace** [comment]
Yes, I've looked over their bitcointalk thread, and I have seen good things about MPH.  I've had my miner pointing to just MPH for 24hrs, and it's certainly much more stable as far as algo profitability.  Lyra2z ran most of the time.  Thanks for the background info.  I'll donate a bit of my profits to the pool and see how things go.  Thanks!
