### ISSUE TITLE
Couple of issues starting latest master-multipoolminer on AMD

### ISSUE THREAD

**Issue by podlbo** [aaronsace/MultiPoolMiner#465]
Hy. Im new to minnig community :) I did start couple of latest releses with no problem. But latest master file give me folloving issues.
You cannot call a method on a null-valued expression.
At C:\MultiPoolMiner-master\Pools\MiningPoolHub.ps1:17 char:5
+     $MiningPoolHub_Hosts = $_.all_host_list.split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression.
At C:\MultiPoolMiner-master\Pools\MiningPoolHub.ps1:17 char:5
+     $MiningPoolHub_Hosts = $_.all_host_list.split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

>> TerminatingError(Get-Algorithm): "Cannot bind argument to parameter 'Algorithm' because it is an empty string."
Get-Algorithm : Cannot bind argument to parameter 'Algorithm' because it is an empty string.
At C:\MultiPoolMiner-master\Pools\MiningPoolHub.ps1:20 char:51
+ ... MiningPoolHub_Algorithm_Norm = Get-Algorithm $MiningPoolHub_Algorithm
+                                                  ~~~~~~~~~~~~~~~~~~~~~~~~

and last one
PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At C:\MultiPoolMiner-master\MultiPoolMiner.ps1:115 char:77

I do not know how to repair this to work on my computer...

**Comment by aaronsace** [comment]
Please use the release.

**Comment by podlbo** [comment]
So latest relese is MultiPoolMinerV2.6.0.2 :) Thanks, i will revert back.
