### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SaintPistachio** [aaronsace/MultiPoolMiner#467]
I am running the master.zip from Commits on Oct 30, 2017

PS>TerminatingError(Set-Stat): "Cannot process argument transformation on parameter 'Value'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Double"."
Set-Stat : Cannot process argument transformation on parameter 'Value'. Cannot convert the "System.Object[]" value of 
type "System.Object[]" to type "System.Double".
At C:\CC\MultiPoolMiner-master\MultiPoolMiner.ps1:502 char:115
+ ... HashRate" -Value ($Miner_HashRates | Select-Object -Index $i) -Durati ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-Stat], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-Stat
Set-Stat : Cannot process argument transformation on parameter 'Value'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Double".
At C:\CC\MultiPoolMiner-master\MultiPoolMiner.ps1:502 char:115
+ ... HashRate" -Value ($Miner_HashRates | Select-Object -Index $i) -Durati ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-Stat], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-Stat

**Comment by UselessGuru** [comment]
Me too.
Happens when Get_Hashrate returns crappy values.
I fixed it by changing
```
            $Miner_HashRates = $_.GetHashRate($_.New -and $_.Benchmarked -lt 3)
            $_.Speed_Live = $Miner_HashRates | Select-Object -First $_.Algorithm.Count

            if ($Miner_HashRates.Count -ge $_.Algorithm.Count) {
                for ($i = 0; $i -lt $_.Algorithm.Count; $i++) {
                    $Stat = Set-Stat -Name "$($_.Name)_$($_.Algorithm | Select-Object -Index $i)_HashRate" -Value ($Miner_HashRates | Select-Object -Index $i) -Duration $StatSpan -FaultDetection $true

                    #Update watchdog timer
                    $Miner_Name = $_.Name
                    $Miner_Algorithm = $_.Algorithm | Select-Object -Index $i
                    $WatchdogTimer = $WatchdogTimers | Where-Object {$_.MinerName -eq $Miner_Name -and $_.PoolName -eq $Pools.$Miner_Algorithm.Name -and $_.Algorithm -eq $Miner_Algorithm}
                    if ($Stat -and $WatchdogTimer -and $Stat.Updated -gt $WatchdogTimer.Kicked) {
                        $WatchdogTimer.Kicked = $Stat.Updated
                    }
                }

                $_.New = $false
            }
```
to
```
            $Miner_HashRates = $_.GetHashRate($_.New -and $_.Benchmarked -lt 3)
            if ($Miner_HashRates.Count -ge $_.Algorithm.Count) {
                if ($Miner_HashRates | Select-Object -Index 1) { #Hashrate value present
                    $_.Speed_Live = $Miner_HashRates | Select-Object -First $_.Algorithm.Count
                    for ($i = 0; $i -lt $_.Algorithm.Count; $i++) {
                        $Stat = Set-Stat -Name "$($_.Name)_$($_.Algorithm | Select-Object -Index $i)_HashRate" -Value ($Miner_HashRates | Select-Object -Index $i) -Duration $StatSpan -FaultDetection $true
                        #Update watchdog timer
                        $Miner_Name = $_.Name
                        $Miner_Algorithm = $_.Algorithm | Select-Object -Index $i
                        $WatchdogTimer = $WatchdogTimers | Where-Object {$_.MinerName -eq $Miner_Name -and $_.PoolName -eq $Pools.$Miner_Algorithm.Name -and $_.Algorithm -eq $Miner_Algorithm}
                        if ($Stat -and $WatchdogTimer -and $Stat.Updated -gt $WatchdogTimer.Kicked) {
                            $WatchdogTimer.Kicked = $Stat.Updated
                        }
                    }
                    $_.New = $false
                }
            }

```

**Comment by aaronsace** [comment]
Master branch is not finished. Use the latest release instead.

**Comment by fonyo** [comment]
@UselessGuru is on fire again. :) Would you like to participate in writing some of the Version 3 features for MPM? Not sure what @aaronsace's plans are regarding to timelines but surely it could be kicked off soon?
