### ISSUE TITLE
How do I setup multialgo multiminer for respective algo? E.g. use excavator for lyra2rev2 and ewbf for equihash

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#469]
I want to mine with the excavator when using lyra2rev2 algo and ewbf when using equihash algo, these two miners are the best for me when it comes to each algo. Excavator doesn't get as fast rates using equihash as ewbf does, and excavator is the best lyra2rev2 miner I have used with the highest rates for me.

Once I figure out how to switch algo/miner together then I can start trying to have multipool settings too. I'm new so I'm working with Nicehash atm, but eventually I'll try miningpoolhub and others. Just a hassle setting up accounts on every pool.

Please help?

This is my start.bat:
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3Lx1F4pGpsQ8HCj2BnU1BWkqJKFZDHmuPX -username winnal -workername multipoolminer -region usa -currency btc,usd -type nvidia -poolname nicehash -algorithm equihash,groestl,lyra2re2 -donate 30"

Will that work?

**Comment by aaronsace** [comment]
Try this: 

`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3Lx1F4pGpsQ8HCj2BnU1BWkqJKFZDHmuPX -workername multipoolminer -location usa -currency btc,usd -type nvidia -poolname nicehash -minername ewbf0,ewbf1,ewbf2,excavator2,excavator3 -algorithm equihash,groestl,lyra2re2 -donate 30"`

**Comment by winnal** [comment]
Thanks, I made a few changes:
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3Lx1F4pGpsQ8HCj2BnU1BWkqJKFZDHmuPX -region us -currency btc,usd -type nvidia -poolname nicehash -minername ewbf0,ewbf1,ewbf2,excavator2,excavator3,ExcavatorNvidia2,ExcavatorNvidia4 -algorithm equihash,groestl,lyra2re2 -donate 0"

I noticed that there are Nvidia excavators and I use Nvidia GPU, so I added those. But still a problem, when I run it, it doesn't list excavator2 or 3, only excavatornvidia2 and 4, and it gives me a bunch of errors like this, and it never benchmarks:

Resolve-DnsName : The term 'Resolve-DnsName' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\Winnal\Downloads\MultiPoolMinerV2.6.0.2\Miners\ExcavatorNvidia2.ps1
:24 char:123
+ ... ethod = "algorithm.add"; params = @("$_", "$((Resolve-DnsName $Pools. ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Resolve-DnsName:String) [], Com
   mandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by winnal** [comment]
OK I fixed the problem by downloading the zip of the master file instead of releases.

Now I'm getting this when excavator tries to run:
[12:08:00][0x00001a44][error] core | Failed to open command file: NiceHash_Equih
ash_3.json

**Comment by winnal** [comment]
OK, fixed that as well, I must've been missing username in the start.bat.

**Comment by Incarnation** [comment]
is it working? how is the full working command looks like?
