### ISSUE TITLE
V2.4 testing.

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#47]
Hey.looks like big testing is coming=)
have some questions before i start.
ccminerklaust and ccminernanashi for example.
looks like both would be benchmarking all the algos with default settings.
so if i want klaust to benchmark only neoscrypt and nanashi only lyra then i need to delete from this ps1 files all the algos exept neoscrypt and lyra.right?

**Comment by aaronsace** [comment]
Yes, just delete or comment out the line(s). 
I'd be interested if there is any difference though; check the stats file. 

I will remove a lot of them if they are just the same in order to speed up the benchmarking. It should pick itself the miners that you suggested for each ago once benchmarked.

**Comment by lyolyalya** [comment]
i wrote that=)
klaust only for neoscrypt, groestl, myr-groestl.
nanashi - lyra.
sp - skein.
tpruvot - just an option.
i already tested them by myself so i knew the results=)
if i don't use cpu mining ang sgminer - same thing?delete ps files?
seems like another things i already know.

**Comment by aaronsace** [comment]
Right, I will set tpruvot for all algos and limit the other miners to those specific ones. 
Is there any settings needed or is defaults fine? 

You can just take CPU out of the start.bat file. Or delete miners like you said.

**Comment by lyolyalya** [comment]
ok...ewbf got new options..
Added option --solver to manual solver selection.(0-3, 0 seems faster for 1070)
Added option --eexit to exit when the miner fails, it will allow you to use a script to automatically restart or perform other actions(1 - worker fail,2 - connection fail, 3 - both)
Added option --log logging to a file.
everything else looks normal.i\s just use -i 26-27 in skein for intensity.

**Comment by lyolyalya** [comment]
seems like ewbf benchmarking issue.
[2017-01-20_01-25-54.txt](https://github.com/aaronsace/MultiPoolMiner/files/719262/2017-01-20_01-25-54.txt)

**Comment by gorilza** [comment]
Skein has been already tested for 16 minutes and not be interrupted Sobieraj, a return to issue #37 ?

**Comment by aaronsace** [comment]
@lyolyalya, I made a typo on the wrapper hash rate reading. 
Try this amendment: 
[Include.zip](https://github.com/aaronsace/MultiPoolMiner/files/719341/Include.zip)

**Comment by aaronsace** [comment]
@gorilza, I think your correct; if the miner doesn't close then it's not marking it as failed. Will send you fix to test in a second.

**Comment by lyolyalya** [comment]
emmm.strange...ewbf passed but with red alerts=)
stuck on skein=)
[2017-01-20_02-35-17.txt](https://github.com/aaronsace/MultiPoolMiner/files/719393/2017-01-20_02-35-17.txt)

**Comment by aaronsace** [comment]
It can't connect to "127.0.0.1:4068"; is that the port for ccminer? Has the miner failed?

**Comment by lyolyalya** [comment]
no.miner works fine=)maybe sp closed the port...
yepp...i chance skein ccminer with klaust and it passed normally,
but always red alerts with new include file=)

**Comment by aaronsace** [comment]
Yep, it's the same bug then.

**Comment by lyolyalya** [comment]
ccminer cryptonight also can't 4068...

**Comment by lyolyalya** [comment]
but sps help tells us...
![image](https://cloud.githubusercontent.com/assets/16507768/22150526/170838a0-df22-11e6-93e3-196071793fa7.png)

**Comment by lyolyalya** [comment]
klaust ccminer cryptonight has no api port at all...
E:\miners\ccminer-cryptonight-103-x64-cuda80>ccminer-cryptonight -h
    *** ccminer-cryptonight 1.03 (64 bit) for nVidia GPUs by tsiv and KlausT
    *** Built with Visual Studio 2013 using the Nvidia CUDA Toolkit 8.0

 tsiv's BTC donation address:   1JHDKp59t1RhHFXsTw2UQpR3F9BBz3R3cs
 KlausT's BTC donation address: 1QHH2dibyYL5iyMDk3UN4PVvFVtrWD8QKp
 for more donation addresses please read the README.txt
-----------------------------------------------------------------
Usage: minerd [OPTIONS]
        Options:
          -d, --devices         takes a comma separated list of CUDA devices to use.
                          Device IDs start counting from 0! Alternatively takes
                                string names of your cards like gtx780ti or gt640#2
                                (matching 2nd gt640 in the PC)
    -f, --diff            Divide difficulty by this factor (std is 1)
          -l, --launch=CONFIG   launch config for the Cryptonight kernel.
                          a comma separated list of values in form of
                                AxB where A is the number of threads to run in
                                each thread block and B is the number of thread
                                blocks to launch. If less values than devices in use
                          are provided, the last value will be used for
                          the remaining devices. If you don't need to vary the
                                value between devices, you can just enter a single value
                                and it will be used for all devices. (default: 8x40)
                    --bfactor=X       Enables running the Cryptonight kernel in smaller pieces.
                                The kernel will be run in 2^X parts according to bfactor,
                          with a small pause between parts, specified by --bsleep.
                          This is a per-device setting like the launch config.
                                (default: 0 (no splitting) on Linux, 6 (64 parts) on Windows)
              --bsleep=X        Insert a delay of X microseconds between kernel launches.
                          Use in combination with --bfactor to mitigate the lag
                                when running on your primary GPU.
                          This is a per-device setting like the launch config.
          -m, --trust-pool      trust the max block reward vote (maxvote) sent by the pool
          -o, --url=URL         URL of mining server
    -O, --userpass=U:P    username:password pair for mining server
          -u, --user=USERNAME   username for mining server
          -p, --pass=PASSWORD   password for mining server
        --cert=FILE       certificate for mining server using SSL
          -x, --proxy=[PROTOCOL://]HOST[:PORT]  connect through a proxy
    -k, --keepalive       send keepalive requests to avoid a stratum timeout
    -t, --threads=N       number of miner threads (default: number of nVidia GPUs)
          -r, --retries=N       number of times to retry if a network call fails
                          (default: retry indefinitely)
          -R, --retry-pause=N   time to pause between retries, in seconds (default: 30)
        --timeout=N       network timeout, in seconds (default: 270)
          -s, --scantime=N      upper bound on time spent scanning current work when
                          long polling is unavailable, in seconds (default: 5)
              --no-longpoll     disable X-Long-Polling support
              --no-stratum      disable X-Stratum support
          -q, --quiet           disable per-thread hashmeter output
          -D, --debug           enable debug output
          -P, --protocol-dump   verbose dump of protocol-level activities
              --benchmark       run in offline benchmark mode
          -c, --config=FILE     load a JSON-format configuration file
          -V, --version         display version information and exit
          -h, --help            display this help text and exit

E:\miners\ccminer-cryptonight-103-x64-cuda80>pause
Для продолжения нажмите любую клавишу . . .

**Comment by lyolyalya** [comment]
cryptonight...nicehash - same as klausT...can we avoid 4068 from using somehow like in old versions of multipoolminer?

**Comment by aaronsace** [comment]
So, there is no api? We can wrap it instead. On the miner, set the api name to 'wrapper' and set wrap to 'true'.

**Comment by gorilza** [comment]
After the new update, it became worse. The miners do not start.
[Stats.zip](https://github.com/aaronsace/MultiPoolMiner/files/719612/Stats.zip)

**Comment by lyolyalya** [comment]
i opened an issue on klausT miner cryptonight.
sp - hasn't option issues at all=)
will try wrapper.

**Comment by lyolyalya** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/16507768/22153267/4595c734-df2f-11e6-8393-8abd3b5a59b7.png)
if so - then - 
![image](https://cloud.githubusercontent.com/assets/16507768/22153282/5e7652b4-df2f-11e6-8fd0-f5db1833d656.png)
seems like it searching wrapper_4068...
![image](https://cloud.githubusercontent.com/assets/16507768/22153319/8a54cea6-df2f-11e6-9792-0fe7c81b4952.png)

**Comment by aaronsace** [comment]
I don't think every miner can be wrapped because some miners don't flush the text out to the correct stream (not sure if the is a work around). It works with cpuminer but not claymore etc.

**Comment by lyolyalya** [comment]
i don't know anything about it=)check my changes.are they correct?

**Comment by lyolyalya** [comment]
can i just specify my hashrates in a problem miners manually for now?

**Comment by lyolyalya** [comment]
emmm...maybe...just maybe...
in wrapper.ps1
![image](https://cloud.githubusercontent.com/assets/16507768/22156589/a2ace8a0-df3c-11e6-95b5-52fea13525a1.png)
in include - 
![image](https://cloud.githubusercontent.com/assets/16507768/22156617/c19fa130-df3c-11e6-9d65-f2ec62b3a793.png)

i've changed in include "ps1" to "txt" and red alerts are gone for ewbf miner...
![image](https://cloud.githubusercontent.com/assets/16507768/22156654/f4b7f702-df3c-11e6-98c7-460bfdb408b6.png)

**Comment by aaronsace** [comment]
That's the amend that I sent you, right?

**Comment by lyolyalya** [comment]
no.i got it from release again.

**Comment by lyolyalya** [comment]
what delta you are using by default?

**Comment by aaronsace** [comment]
10% but it has a 1% decay.

**Comment by lyolyalya** [comment]
what is decay in this case?=)

**Comment by lyolyalya** [comment]
just got answer about sp ccminer.need to specify -b 127.0.0.1:4068 manually to activate it.
it's working now.

**Comment by aaronsace** [comment]
Nice one. 

The delta is takes 1% off the delta every minute so, if I remember correctly, it will be 5% after an hour. It decreases slower and slower so it would takes ages for the delta to reach 0%.

**Comment by lyolyalya** [comment]
i see...but why?=)i mean...i'm not so bad in math, but can't understand it=)as i can see i can just ignore decay,right?

**Comment by aaronsace** [comment]
It makes the switching work well. Switching loses you profit so it has to be able to make it back. The loss in which a switch will cost you percentage wise decreases as does the delta.

**Comment by lyolyalya** [comment]
that's right=)i just don't understand that math=)well.if you sad so...
if i need to lower delta to 5% i need to change this to 0.05?
![image](https://cloud.githubusercontent.com/assets/16507768/22161107/917430d8-df51-11e6-8c26-d9658426f50c.png)

**Comment by aaronsace** [comment]
Oh, a decimal percentage is the percentage divided by 100. 
So, yes.

**Comment by aaronsace** [comment]
Ha, I only fixed one '.ps1' error; I fixed the other now. Will work through these fixes now the push it.

**Comment by lyolyalya** [comment]
ok...well...summary...for nvidia only.
skein with sp ccminer - manually -b 127.0.0.1:4068
cryptonight by klaust- waiting for answer(not so critical for nvidia now)
ewbf - --eexit 1 --solver 0 (for me) and i've changed in include wrapper "ps1" to "txt".
removing sgminer, nheqminer, 
manually set skein only in sp-ccminer, 
manually myr-groestl, groestl, neoscrypt in klaust miner, 
manually lyra only in nanashi.
manually disarmed tpruvot miner=)
and finally walked through all benchmarking without any issue or warning of powershell=)




manually entered hashrate

**Comment by lyolyalya** [comment]
emmm...why it switched?=)
![image](https://cloud.githubusercontent.com/assets/16507768/22161952/2950dd04-df55-11e6-9098-483e5cd0c1f5.png)

**Comment by gorilza** [comment]
забавно, вот вопрос не слишком мало алгоритмов оставил для работы? может еще парочку каких включить ? qubit например ?

**Comment by lyolyalya** [comment]
реально переключаются всего 2-3.гроестлы - для тестирования.монеро - абы телепалось.в основном,это скейн,неоскрипт и зкеш.

**Comment by aaronsace** [comment]
It's very close, maybe the profit changed afterward. What's the log show?

**Comment by lyolyalya** [comment]
[2017-01-20_08-54-12.txt](https://github.com/aaronsace/MultiPoolMiner/files/720334/2017-01-20_08-54-12.txt)

**Comment by aaronsace** [comment]
I'll run through the logic. Night.

**Comment by gorilza** [comment]
С асиками тягаться смысла нет конечно. Но вот либры нехватает, но тут вопрос к хозяину пула уже :)

**Comment by lyolyalya** [comment]
если разобраться - тут много чего не хватает=)я бы и аврору скеин добавил и либру и червонец и есть еще, наверное, много неизведанных монеток...либру обещает, но ее профит сейчас не выше зека,потому не критично...да и не о том в этой теме речь=)речб о том,чтобы создать программу-аналог найсхеша, но при этом не сдавать в аренду мощностя а майнить этими мощностями самому=)со временем это можно будет делать на любом пуле=)просто этот - наиболее пригодный для тестирования.

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/22172034/f5ffcbf8-dfa5-11e6-9793-857a2b0af14a.png)
well...it WAS good night=)seems like everything is working well=)

**Comment by lyolyalya** [comment]
emm...just little confusion of active time...can you set this for summarising or something for each miner?example - ewbf acive time 5 hours(5 times), spccminer - 7 hours(7 times) and so on...

**Comment by gorilza** [comment]
2.4.3.1 Test EWBF always starts with solver 2, and for example to 1070 you need to choose a solver 0.

EWBF                       Equihash         2,11 KH/s      0,00901 4 264,23260
EWBF                       Equihash         2,11 KH/s      0,00901 4 264,23260
EWBF                       Equihash         2,11 KH/s      0,00901 4 264,23260

solver
0	2270-2300
1	2170
2	2110

**Comment by lyolyalya** [comment]
да=)это ужа каждый по карточке смотрит=)разраб говорил,что 1-3 это для более старых карт.ручным путем подбирается.

**Comment by gorilza** [comment]
Так тут то все три теста проходят с одним и тем же солвером ( 2 ), что бессмысленно

**Comment by aaronsace** [comment]
@lyolyalya That looks a like nicer way of writing it. I'll change it.

**Comment by aaronsace** [comment]
@gorilza It benchmarks all three solvers, what do you mean?

**Comment by gorilza** [comment]
@aaronsace The logs all 3 bench with solver #2. Although it was supposed to be 0, 1, 2. it is not critical. But not quite a valid test result.

**Comment by aaronsace** [comment]
Oh, thanks! I'll split it.

**Comment by gorilza** [comment]
Can't pass the test ccminer-80-x64.exe -a yescrypt.
Trying to constantly run. Does not switch to a different algorithm.
![default](https://cloud.githubusercontent.com/assets/25017700/22176564/f705af5a-e026-11e6-979e-6ed9d1e232c5.png)

**Comment by lyolyalya** [comment]
tpruvot ccminer doesn't work with yescrypt.

**Comment by gorilza** [comment]
![000](https://cloud.githubusercontent.com/assets/25017700/22177261/d3e297a6-e033-11e6-97ce-900571909e78.png)

**Comment by lyolyalya** [comment]
hmm...strange...it worked...i'm not at home now.will check tomorrow...but again...this is the same myraid coin.skein or groestl will give much better results...there is no optimised yescrypt miner yet, as i know.

**Comment by lyolyalya** [comment]
you can try this if you want.
https://github.com/djm34/ccminer-tpsp

**Comment by gorilza** [comment]
This is very old, at 1070 makes no sense to use it.

**Comment by lyolyalya** [comment]
no interest to yescrypt makes no miners=)again, i'll check klaust tomorow and let you know.

**Comment by lyolyalya** [comment]
yeah.you are right.no one  from ccminers i have doesn't work with yescrypt=)only djm...sooo.on your decision...if there is no miners - why mine yescrypt at all?=)

**Comment by gorilza** [comment]
To run Bin\Cryptonight-KlausT needed to add a library cudart64_80.dll.

**Comment by aaronsace** [comment]
Does it not come with the NVidia drivers? Where did you get it from?

**Comment by gorilza** [comment]
From \Bin\Ethash-Claymore\cudart64_80.dll

**Comment by lyolyalya** [comment]
nope=)win10 not telling me this=)no more cudaart=)

**Comment by lyolyalya** [comment]
just got the aswer from klausT ccminer cryptonight dev...
https://github.com/KlausT/ccminer-cryptonight/issues/15#issuecomment-274411403
seems like no api port for this miner in the near future...
so will need to set monero hashrate manually i gues for nvidia users...or set djm ccminer by default but it so slow...on your decision...

**Comment by aaronsace** [comment]
Does this do anything?  
[Miners.zip](https://github.com/aaronsace/MultiPoolMiner/files/724897/Miners.zip)

**Comment by lyolyalya** [comment]
what you mean?klaust ccminer cryptonight is working but need to enter hashrate manually cause there is no api port now.
today it switched once.
klaust ccminer mines neoscrypt, groestl and myraid groestl in my case.
is that what are you asking for?=)

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/22222143/6bafb880-e1be-11e6-8d84-37ea5ab44e88.png)

**Comment by aaronsace** [comment]
Does it output anything when using the wrapper. I'll probably just have to use the slower miner but want to check that it doesn't output anything on the wrapper.

**Comment by lyolyalya** [comment]
klausT ccminer - does...
klaustT ccminer-cryptonight - no.

**Comment by gorilza** [comment]
@lyolyalya выложи плиз свой настроеный, чет у меня толи powershell мозга компостирует, толи видюхи вразнос пошли...

**Comment by aaronsace** [comment]
How odd. Sure it will get integrated at some point; worth a shot.

**Comment by lyolyalya** [comment]
@aaronsace you see the answer=)suggested tpruvot...not so fast i guess=)

**Comment by lyolyalya** [comment]
@gorilza в смысле вразнос?=)
емм...сюда он не влазит=(

**Comment by lyolyalya** [comment]
@gorilza https://drive.google.com/open?id=0BzIjrFYeA7rtUmJuZVMzZnRGVHM

**Comment by lyolyalya** [comment]
ток же ж статистику мою убери и монеру руками если что подправь хешрейт.

**Comment by twod85** [comment]
Reaches benchmark EWBF miner opens a window and immediately closes. Bugs do not have, but the benchmark fails. Windovs 10 Aniversari, GTX1070*4.

**Comment by aaronsace** [comment]
Does EWBF0, EWBF1 and EWBF2 all fail?

**Comment by aaronsace** [comment]
Open command prompt and run this: 

```
cd "[enter path to the miner here]\Bin\Equihash-EWBF\"
miner.exe --boff --server europe.equihash-hub.miningpoolhub.com --user aaronsace.multipoolminer --pass x --port 17023 --eexit 1 --solver 2
```

Does it work?

**Comment by twod85** [comment]
![ewbf1](https://cloud.githubusercontent.com/assets/6468647/22248186/75eab0bc-e24e-11e6-9895-d3dfe8daddf8.png)![ewbf1_cmd](https://cloud.githubusercontent.com/assets/6468647/22248189/79de4bc0-e24e-11e6-85f2-77ad318eb865.png)
cmd working

**Comment by twod85** [comment]
![ewbf1](https://cloud.githubusercontent.com/assets/6468647/22248300/fec48084-e24e-11e6-862f-1e3a91c44026.png)
![ewbf1_cmd](https://cloud.githubusercontent.com/assets/6468647/22248305/0196d280-e24f-11e6-8d16-bf4720f3301b.png)
cmd working

**Comment by aaronsace** [comment]
I will see if I can come up with some tests after work.

**Comment by twod85** [comment]
It shortens the way you've written. 'c:\multipoolminer' It works. Thank you.

**Comment by aaronsace** [comment]
Ah, I think it's missing quotes in the wrapper file so it won't work on paths with invalid characters. I will check later and issue a fix. Thanks.
