### ISSUE TITLE
Picture and question. 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#473]
I swear to God I'm not trying to bug you guys. I want to post a picture with some Benchmarks marked in yellow and also red. From my understanding, the MultipoolMiner will pick (should pick) the fastest miner for a particular algo. Right? 

For example: in my screenshot,(Highlighted in Yellow) the 
CCminerPalgin for Lyra2RE2 is the fastest @ 188.70 MH/s, 
Next fastest is CcminerLyra2RE2 for Lyra2RE2 @ 179.38 MH/s. 
And last was CcminerTpruvot for Lyra2RE2 @ 153 MH/s.

As for "Lyra2z" (compared in red) I show:
CcminerNanashi for Lyra2z @ 7.02 MH/s
Next fastest is CcminerTpruvot for Lyra2z @ 5.37 MH/s

Here is my question: If I have "repeatedly" done these benchmarks on my system, and the results are the same - showing a clear "fastest" miner for a particular algo, can I go into the miners folder and delete the slower miners? The ONLY reason I think this would come in handy is if I adjust the overclock settings and want to re-benchmark, with the slower miners deleted, the benchmarking process would take less time. Right? 

I have come to this theory based on the ASSUMPTION that several miners that can mine a certain algo are provided because everyone's mining rigs are different, and someone else might show a completely different result. The other theory I have is that I am completely wrong in my assumption, and I should NOT delete any of those "slower" miners because they may be designed / coded / to mine a different coin, but it's still using the over all master algo. IE: Lyra2RE2 or Lyra2z 

Also, regarding the FAQ, I think I have found 2 errors. Using the "ResetBenchmark.bat" run as admin or not, does not delete the contents of the "Stats" folder. Also, the "RemoveLogs.bat" mentioned in the FAQ does not appear to be included in the zip package. 
![capture](https://user-images.githubusercontent.com/23691069/32310722-cc370d54-bf6a-11e7-8824-1009235d547c.PNG)

**Comment by UselessGuru** [comment]
Don't delete the miner. Instead comment out (add # in front of the algo in question) the slower algorithms in the miner file(s).

**Comment by aaronsace** [comment]
Either leave the miners or edit them in notepad as @UselessGuru is suggesting. 

Not all the stats are for the benchmark. Remove logs may have been added later; just delete the logs folder instead.

**Comment by cmbconcretefire** [comment]
I think I understand what both of you are essentially saying. But can you show me where I should go to rename these miners? Is it (for example) the Bin folder? The Miner folder? 

@UselessGuru said > Don't delete the miner file. Instead comment out (add # in front of the algo in question) the slower algorithms in the miner file(s). And @aaronsace  said > or edit them in notepad as @UselessGuru is suggesting.

So I go into which folder and actually open / edit the files in notepad and just simply place a # symbol in front of any other character? (The first character I assume?)  I really do understand what you're both saying, I just want to make sure I go to the correct folder and am editing the correct files. Also @aaronsace said this > Not all the stats are for the benchmark. < Are you suggesting I leave the miners alone and not edit them.......or, are you suggesting that the GUI (for lack of better term) (the CMD window) shows stats other than just benchmark stats? Because if that's what you're suggesting, then yes, I understand that. 

Thanks for the help guys. Really appreciate it. I want to tweak this miner just right. One last thing, and I hate to bring it up but Windows defender is giving me a virus warning of Win64/BCoinMine.....but oddly, it only shows up in AMD folders. It's odd because I only use NVIDIA cards. I know all about the false positives of miners, but a little knowledge of this coming from you guys would make me feel better.

**Comment by aaronsace** [comment]
The miner configurations are in the folder called 'miners'; hack at them as much as you want. 

'#' means the line is a comment and is ignored; it's the same as deleting the line but it's easier to it add back. 

There can be many virus warnings; just allow them all.

**Comment by fonyo** [comment]
Maybe it is easier for you to create a new folder called 'miner backups' or any name you want and move (not copy) the unwanted miner files there.
