### ISSUE TITLE
Dual Mining

### ISSUE THREAD

**Issue by oakmaster** [aaronsace/MultiPoolMiner#474]
How do I stop dual mining by deleting siaclaymore in start.bat and does siaclaymore mean sia, dcr, lbry and pascal thank you

**Comment by aaronsace** [comment]
The miners are located in the folder called 'miners'. Delete any Claymore ones that you wish to remove.

**Comment by fonyo** [comment]
Siaclaymore means Sia mined in dual mode (MPH only supports that method), there is a separate Sia parameter (nicehash), Decred (nicehash and zpool), pascal (nicehash), lbry (nicehash and zpool).
