### ISSUE TITLE
Increase intensity -i # with ccminer using multipoolminer

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#475]
How do I add the command for intensity to ccminer when multipoolminer runs it's commandline? I can manually add it by writing a .bat file, but I don't know where to edit/add it through multipoolminer.

**Comment by winnal** [comment]
I'm trying to add it here in the miner .ps1 file:
Arguments = "-a $_ -o stratum+tcp://$($Pools.(Get-Algorithm $_).Host):$($Pools.(Get-Algorithm $_).Port) -u $($Pools.(Get-Algorithm $_).User) -p $($Pools.(Get-Algorithm $_).Pass)$($Commands.$_) -i ##"

But it won't run when I add that.

**Comment by aaronsace** [comment]
Add it to the commands above. That's what's it's for; they are all currently blank.

**Comment by winnal** [comment]
I got it to work thanks, sorry posted a bit early, just moved -i in front of -a
