### ISSUE TITLE
How to setup multipooling to only use certain miners

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#476]
So I want to run excavator lyra2rev2 when mining nicehash pool and then everything else ewbf, ccminer mining equihash and groestl through miningpoolhub.

How can I make it only run excavator with nicehash?

I'm trying something like this but I doubt it'll work:
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 3Lx1F4pGpsQ8HCj2BnU1BWkqJKFZDHmuPX -username winnal -workername multipoolminer -ssl -region us -currency btc,usd -type nvidia -poolname nicehash,miningpoolhub,miningpoolhubcoins -minername excavator3,excavatornvidia3,ewbf2,ccminerpalgin,ccminernanashi,CcminerTpruvot -algorithm lyra2re2,equihash,groestl -donate 33 -watchdog"

**Comment by aaronsace** [comment]
There is no reason to do that; wouldn't make any sense as pools don't effect miners. It picks the top (most profitable) pool or you manually specify the default pool.

**Comment by winnal** [comment]
Right, but excavator doesn't work with any other pool so I'm trying to avoid it crashing/stopping when trying to mine another pool with excavator.

**Comment by aaronsace** [comment]
Does it not?

**Comment by aaronsace** [comment]
Just tested, the IP address trick works still.

**Comment by winnal** [comment]
Oh yeah I never tried that again after I got it to work with nice hash. I'll uses it'll work then. I'll report back when I try it. Thanks!
