### ISSUE TITLE
Anyway to setup an auto restarter for miner

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#478]
I keep getting illegal mem lol 👾

**Comment by fonyo** [comment]
More info and/or logs please.

**Comment by winnal** [comment]
I do. It's the OC but I just want it to restart lol cuz I can slowly tune it but I just need it to stay up if I miss it.

**Comment by fonyo** [comment]
It's not worth it as you will literally burn down your cards. That's for one. Also the tiny bit of extra you think you are getting is actually lost due to the constant restarts.

**Comment by fonyo** [comment]
One of my mates have a 1070 that caught on fire for a sec. Don't ask me how that happened as it sounds impossible but it did...

**Comment by winnal** [comment]
I believe you and I'm trying to lower it but sometimes it's the temps that get too low when it's cold in winter and actually gets too fast. So yeah I'm trying not to restart but it's just for convenience and insurance in case I'm not around. But eventually I'll tune it to be permanently stable. I'm still doing long runs of testing to insure stability, but sometimes I can't watch it all day so.

**Comment by fonyo** [comment]
You are not putting your rigs outside in the minuses, are you?!

To ensure stability, find the OC that it can run with for 24 hours, then lower the clocks a little more. That works like a charm every time!
