### ISSUE TITLE
claymore cryptonight 10.2 wrong port on nicehash?

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#479]
claymore cryptonight on nicehash seems to be pulling up the wrong port from nicehash for stratum+ssl.  the port it tries to use is 3355, and gets no connection on nicehash.  the port it should be trying to use is 33355.

i did a quick workaround by replacing the ssl with tcp in the nicehash.ps1 pool file.

**Comment by imrecsoka** [comment]
I have issues with cryptonote miner claymore version 10.2 beta it seems to timeout and then it connects and then i notice gpu2 is like running at half speed. and gpu0 for example is fine at like 600 hashes, very very weird. The old 9.7 version is hundreds.
I dont know if this is port related

**Comment by aaronsace** [comment]
@alucard20724 Where have you got port 33355 from? 

It says port 3355 here: 
https://api.nicehash.com/api?method=simplemultialgo.info

**Comment by aaronsace** [comment]
Found news pages; added manual override on pool file.
