### ISSUE TITLE
2.4 Testing - Reorder CGminer download

### ISSUE THREAD

**Issue by n3cr0cr0w** [aaronsace/MultiPoolMiner#48]
Do we need to compile our own version of Reorder CGminer or is there a trusted location for the build?

**Comment by aaronsace** [comment]
Did I not include it in the release? It should be in the 'bin' folder.

**Comment by aaronsace** [comment]
Now uploaded v2.4.1

**Comment by n3cr0cr0w** [comment]
That is what I get for cloning straight from GitHUB and not checking out the releases.

**Comment by aaronsace** [comment]
Ah, ye, don't want to clutter the source with claymore miners and what not.

**Comment by lyolyalya** [comment]
2.4.3.1 - i missed so much for 8 hours=)do i need to download it or my manually fixed 2.4 will look the same?=)
