### ISSUE TITLE
need help setting up multipool miner

### ISSUE THREAD

**Issue by fusation** [aaronsace/MultiPoolMiner#480]
Hi
Can someone help me set up this multipool miner I can't get it to work for 3weeks now I tried almost everything that was posted up here but still does not work and the ones that I didn't do was because I couldn't understand it.
So far what I have now is that in the multipool miner folder, I right clicked "start.bat" and clicked "edit"
then changed my walled number, username, worker name, region, type, pool name to"miningpoolhub,miningpoolhubcoins,zpool,nicehash"
and left everything else the same including the currency it's still "btc,usd,eur", clicked save. 
went out and right click "run as administrator" waited and let it do it's thing 2mins later it stops and says "no miner" so I closed this.

Then I went to "multipoolminer.ps1" right click "edit' and changed,
wallet, username, worker name, api id, api key, region, type to "NVIDIA", algorithm to the same as what was on the "start.bat" file, miner name, pool name to"miningpoolhub,miningpoolhubcoins,zpool,nicehash",
and left everything the same. Then I clicked run with powershell waited 2mins later it stopped and it says "no miner".

Please help I can't figure out what is wrong with this program. I have downloaded the 
excavator and moved it in the "multipoolminerv2.6.0.2" folder because I don't know what to do with it.

Can someone tell me what I am doing wrong. Thanks

![multipoolminer](https://user-images.githubusercontent.com/25115191/32401393-4d74eed2-c172-11e7-854a-ee14e331e02d.JPG)
![multipoolminer1](https://user-images.githubusercontent.com/25115191/32401452-9baac576-c173-11e7-8aca-6c13081562db.JPG)

**Comment by fonyo** [comment]
You should not be editing the PS files if you don't know what you are doing.
Download the latest release (2.6.0.2) and not the latest master.
It is recommended to use a single pool, amend the relevant start file with your details. You need to register on MiningPoolHub if you are using that pool. Providing a wallet address is only required when mining on zpool or nicehash.

There are lots of useful information in the README. Please do go through it a few times.
https://github.com/aaronsace/MultiPoolMiner/blob/master/README.txt

**Comment by fusation** [comment]
thanks for the help, but if you look at the second picture that is what I did first and that is everything that the README file said and still I get a "no miner" message I spent a long time trying to find out what I typed or did wrong on the second picture which was the "start.bat" file but I can't seem to get it to work. I have already registered to the mining pool hub and got a wallet address. 
So I still don't under stand what's wrong. I need help. Thanks

**Comment by fonyo** [comment]
Please start from scratch by downloading the latest **release**
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.6.0.2/MultiPoolMinerV2.6.0.2.zip
As mentioned, try a single pool first such as MPH
`-poolname miningpoolhub,miningpoolhubcoins `
Try to include fewer algos:
`-algorithm ethash,ethash2gb,siaclaymore,equihash,lyra2rev2,lyra2re2,lyra2v2`

**Comment by fusation** [comment]
Thanks that works a lot better, but I'll see how long that last till it crashes. Because I remembered it said it was missing a file called "lrl." something like that I can't remember.
When these yellow message pop up should I be concerned? 

Also the MultiPoolMinerv2.6.02 their is only one file there so how can I download it wrong? 
" https://github.com/aaronsace/MultiPoolMiner/releases "

![multipoolminer2](https://user-images.githubusercontent.com/25115191/32402681-93fe1786-c18e-11e7-8d32-f3132f3a4076.JPG)

**Comment by fonyo** [comment]
No, that is good sign! You will see that green bar pop up every minute, sometimes for less than a second. It means MPM does what it needs to. After benchmarking is done, it will mean it is downloading the coin data and profitability stats etc.

Not sure why prospector is not downloading. If you have any issues with any of the miners, take a not of the miner name, head to the Miners folder, locate and simply remove them (it is recommended not to delete them, you could just move them out of that folder). Or really just delete them, you can always use the zip file to restore the content of the Miners folder.

**Comment by fusation** [comment]
Ok, so far I'm up to here now who do I get pass this point?
![multipoolminer3](https://user-images.githubusercontent.com/25115191/32403010-d5517df2-c195-11e7-937b-c3cfe12c637c.JPG)

**Comment by fusation** [comment]
also please don't close this off just yet as I also need help later on to figure out how to setup an asic unit with my graphics card once the asic arrive

**Comment by fonyo** [comment]
Some of the miners don't quite work out for everyone (I have the same problem with that miner on one of my rigs but works well on another). As stated, just remove the problematic miners.

**Comment by fusation** [comment]
I know that you might no like me asking this, but how do I configure my MultiPoolMiner to pool mine because solo mining is taking too long and not much profit as my power bill is going up the longer I leave it on I'm only making $0.05 per day.

Thanks

**Comment by aaronsace** [comment]
@fusation Hu? This is already a pool miner has hinted by the name (MultiPoolMiner); it's not solo mining.

**Comment by fusation** [comment]
sorry must of read it wrong from what fonyo said, just trying to figure out why I'm mining so slow, which was the same speed as a solo mining I had.

**Comment by aaronsace** [comment]
Solo mining and pool mining has no effect on speed; all it effects is where you send your calculated hashes to. MultiPoolMiner cannot increase the speed; all it can do is select the best algorithm for your machine.

**Comment by imrecsoka** [comment]
Hi, i was asking before but i dont think i was clear enough so it was not really a question.
What is "miningpoolhubcoins" ? i know of normal "miningpoolhub", "nicehash", and "zpool"
but i dont understand what "miningpoolhubcoins" is

**Comment by imrecsoka** [comment]
I also seem to get alot of socket or connection errors when i mine , what a bloody pain, is this just something we have to deal with or can the weather be better like it is in London everyday - hot and sunny?

**Comment by aaronsace** [comment]
miningpoolhubcoins just uses the ports that connect to individual coins; pool is better at switching so use the normal miningpoolhub. 

> Simple coin mining (Port 20XXX)
> Select any coin and check its port number. Just start mining with appropriate miner and algo right away.
> Algo switch mining (Port 17XXX)
> We provide auto switching port for each algo. These ports switch coins time to time to mine the most profitable coin. Best for Rental, ASIC, FPGA miners.

Delete any miners that are not working in the folder called 'miners'.

**Comment by imrecsoka** [comment]
Everything Nvidia and Excavator i deleted.
I also dont seem to have luck for Neoscrypt, it seems to be a real bloody pain to deal with.
I was getting like 50 kh/s on 2 graphics cards it doesnt seem right.

**Comment by fonyo** [comment]
@aaronsace There seem to be many questions around miningpoolhub versus miningpoolhubcoins so I am going to add an explanation to the FAQ.

**Comment by fusation** [comment]
Hi 
I finally go my asic miner and wanted to know how to set it up or could you tell me the mining pool hub stratum address a general one so my miner and auto switch through them all. thaks

**Comment by aaronsace** [comment]
@fusation Divert your hash to hub.miningpoolhub.com:12XXX then set you hub worker https://miningpoolhub.com/?page=account&action=hubworkers

**Comment by fonyo** [comment]
@fusation what asic have you got?

**Comment by fusation** [comment]
@fonyo I have an antminer l3+

**Comment by fonyo** [comment]
That's a script ASIC, right? Can't you just point it to port 17001 on MPH?

**Comment by fusation** [comment]
It's a type of asic machine not sure if I can point it that's why I'm asking, because I know that you need the word "stratum" in front of the the pool location I think.

**Comment by fonyo** [comment]
No, you can just omit that for MPH.
Send me a screenshot of the config interface and I will try my best to tell you what to put in and where.

**Comment by fusation** [comment]
Here you go as you can see I cannot set the MPH to 17001 as it max out at 650.

So need help setting it up.

Thanks

![capture 6](https://user-images.githubusercontent.com/25115191/33817475-aa793b34-dea4-11e7-9cd3-011f454a3c6e.PNG)
![capture 5](https://user-images.githubusercontent.com/25115191/33817482-af736a74-dea4-11e7-8157-ae73337ca6f7.PNG)
![capture 2](https://user-images.githubusercontent.com/25115191/33817487-b4456296-dea4-11e7-8046-272c3169bb4c.PNG)
![capture 3](https://user-images.githubusercontent.com/25115191/33817489-b70e6428-dea4-11e7-9a9b-7309fce82e17.PNG)
![capture 4](https://user-images.githubusercontent.com/25115191/33817492-b923d95a-dea4-11e7-8f8d-607f68d7ed38.PNG)

**Comment by fonyo** [comment]
Frequency is the overclock, I guess. You did set port 17001 correctly by including it in the first field (in the URL) on screenshot number 3. You should be good to go.

**Comment by fusation** [comment]
I have a question. the url that I have been using stopped working "stratum+tcp://hub.miningpoolhub.com:17001" I can no longer get into mining pool for my antminer l3+ miner can you help? Thanks

**Comment by fusation** [comment]
never-mind I figured it out
