### ISSUE TITLE
New picture / new problems? 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#481]
I've installed MultipoolMiner about 5 times now, on each of my rigs. So about 10 total. Here are my steps:
1) Download Fresh version of MPM. 
2) Download Fresh version of "prospector" miner --- because I always, always get a warning saying it could not be downloaded. I just create a folder > "Prospector" in with the others and put the prospector.exe in there. 
3) I delete all references to Excavator, because it apparently is not that great anyway. 
4) I edit my bat file, remove the bitcoin addy, I only mine on MPH and MPCH > I delete zpool and nicehashpool from bat. I'm only running Nvidia, so I remove AMD and CPU from type. And I tried fonyo's literal advice of only mining these algos > cryptonight,ethash,ethash2gb,equihash,groestl,lyra2z,neoscrypt,siaclaymore,lyra2re2,lyra2,lyra2rev2,lyra2v2

5) I run the start.bat and it downloads a bunch of stuff, sometimes throws  up red writing but I let it keep going and it seems to sort itself out and goes through the benchmarks seemingly ok. 

6) And here's where I have concerns > Looking at the CMD window I see: 
Miner> MultiPoolMiner > CcminerTpruvot-Lyra2z AND THE PROBLEM FOR ME IS.....about every 60 seconds the screen will flicker and scroll down on it's own and show the EXACT SAME THING, ALL DAY. 
The flickering is it checking in with MPH, I assume this is normal. But it never, ever changes to any thing other than what you see in the screenshot. No lyra2re2, no equihash, etc. Always stuck on Lyra2z. 

Furthermore, checking the "balances" page, I can see that it is indeed mining a multitude of coins. (maybe 6 to 8) which is good......but when I got out and check their "list" of the most profitable algos or coins, it doesn't match (AT ALL) the 6 to 8 coins it does seem to be collecting. Help? 
![capture](https://user-images.githubusercontent.com/23691069/32402294-1584d42c-c0f7-11e7-9a0b-e6863a88b198.PNG)

**Comment by fonyo** [comment]
Just remove lyra2z from the list of algos if you think it is causing you trouble. If you look at MPH, it is quite far down the profitability list and has been for a while without any meaningful movement. Which means, if you are mining lyra2z, you are probably not getting the most out of your rigs. Let me know how it goes.

**Comment by fonyo** [comment]
With your nvidia rigs you should be mining equihash, lyra2rev2, ethash and occasionally the odd neoscrypt and groestl but if you really want to see better earnings, I would only include the following algos:
`-algorithm ethash,ethash2gb,siaclaymore,equihash,lyra2rev2,lyra2re2,lyra2v2`
