### ISSUE TITLE
Fonyo, new pic for review. (or anyone who can help) 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#483]
Hello Fonyo, 

As you can see from the pic, I followed your advice and set the algo's to "really see a difference." 
Anyway, I checked on my rig today only to find this error......and of course the miner had stopped working. 

1) What can I add to the bat file to = "retry if falied.....etc." I know I've seen bat files start with :loop (insert all info) end bat with > goto loop. Is there something similar for multipool miner that you can recommend? 
2) Sorry for being lazy but is there a way to get "Alerts" on my phone (android) if the miner stops working at MPH? 
3) I think you've asked this on the forum, but when you are switching algos - as we are - is there a way to see a traditional type graph for your workers / rigs on MPH? 

Thanks again. It's getting smoother. I'm learning. 
![capture](https://user-images.githubusercontent.com/23691069/32477885-75b0d3c8-c34f-11e7-8b2e-2c27a71de365.PNG)

**Comment by cmbconcretefire** [comment]
Oh yes, one more thing. (sorry) In my pics you can see the miner is always working in the "traditional" cmd window. Is there a simple way to force the miner to run in the powershell window instead? Something I can add to the bat file to force running in powershell? Or something similar?

**Comment by aaronsace** [comment]
I'm highly concerned by that error. When did that error appear and why does it have a dollar symbol on the worker name?

**Comment by fonyo** [comment]
If I think of it, it should be possible to set up SMS notifications by creating a recipe on IFTTT. The method is not quick but very dirty. At least this could be useful until MPH creates a proper rig overview which might take _a very long time_...

1. (And this one will be repetitive) Go to each coin's Workers page YOU CURRENTLY ENABLED MPM TO MINE on MPH and turn on monitoring for all your workers (ie. drog1.multipoolminer and please do remove the $ symbol). There are two equihash coins, few ethash, sia and 2 lyra2rev2 coins. You have to do it for each one of them. This way, if your rigs disappears you can check whether they switched or went down as MPH will send you emails.
2. Add the SMS channel on IFTTT.
3. Create a recipe, connect your email account and set up a filter for the MPH emails.
It should look something like this:
IF (email received from MPH [specific subject title?]) THEN send (SMS OR OS notification)

I could toy around with this today to see if there are any limitations.
One isssue with this is obvious from the start. MPH only sends emails about your worker being down of a pool. But this is also the case when it switches to another coin or algorithm completely but as I mentioned MPH needs to quit being "lazy" and get on with implementing these important changes and interfaces or he will slowly lose his users.

**Comment by fonyo** [comment]
Yeah, it is pretty simple once you have monitoring turned on for each worker and on all coins.
I use Gmail so filtering is very easy.
IF (GMAIL, search for [from: info@miningpoolhub.com subject: IDLE Worker]) THEN (SMS, send to you mobile)
Done.

**Comment by fonyo** [comment]
I have just tested this and can confirm, it works like a charm.
I will try to share the recipe here.
![ebdd25d4-fcb7-4375-bce2-44bcb50601ec](https://user-images.githubusercontent.com/10072275/32489055-a154872a-c3a6-11e7-986f-66d103a7e4a8.jpeg)

**Comment by cmbconcretefire** [comment]
@aaronsace , the reason for the $ symbol is because I put it there. I was following your .bat file but I wanted to differentiate it from yours a little bit so I just put the $ at the end. I am ridiculously , insanely paranoid about my crypto stuff. My point being, my rigs are my rigs. Period. I don't use them to surf the net, or even download files. I always download all files to my main PC and test everything out and then I copy and paste (via EITHER Teamviewer or Remote Desktop Manager - depending on my mood) whatever I have tested over to my rigs. 

That way once it's moved on to my rigs, I can literally fire them up right away. No one can guarantee anything, but I can come pretty darn close in promising you everything is fine on my end. I haven't been hacked, I'm not missing coins. I don't know.....I just logged in to my rig and there was that error. 

Also - and I don't mean this in a rude way - but I've installed and re-installed the MultipoolMiner about 10 times on each rig trying to get through the 'setup' process without any errors but I've not been able to do that. Not by following the directions anyway. Every single time (on different days even) upon setup it refuses to download the 'prospector.exe' so I have to go and fetch that one myself. 

And I don't want to drag this out but I would like to post 2 more photos in consecutive order so you can see what I'm talking about. I really, really, REALLY want to use and like this miner and I have been and you and Fonyo have been great with support but frankly, I still have NO IDEA if this thing is working correctly. Between MPH not having the proper graphs , the auto switching seemingly taking forever , not knowing how much $$ I'm actually making and finally (the pictures) not understanding from top to bottom what any of that means.......I might have to switch miners. And that sucks, because I don't really want to switch miners. In the pictures I know up at the top it shows the benchmarks and then underneath that it shows the amount of time the miner has been running.....but beyond that, I'm completely lost. In the screenshots it goes from "running" to "idle" and then the next picture is a continuation of the first. I don't know what it means and look at the very bottom under "BTC" it always shows "0.00000" AND to top everything else off, I honestly don't know if the miner is actually switching coins or algos. What do the pictures say to you? 
![capture](https://user-images.githubusercontent.com/23691069/32530698-9e7019e0-c40d-11e7-8465-cdba7bbd195b.PNG)
![capture2](https://user-images.githubusercontent.com/23691069/32530704-aa1b7ba4-c40d-11e7-8b52-88946744c28f.PNG)

**Comment by cmbconcretefire** [comment]
And A little off topic but I thought you guys would get a laugh out of this: Last night I actually watched a youtube vid on how to setup "Awesome Miner." I thought I'd at least give it a try you know? I installed it, it appears to be working, and approximately 18hrs later........ it's telling me I'm mining $5,000 USD per day on my six GTX 1060's cards. Lol. It's comical at this point.

**Comment by spider703** [comment]
in an "awesome miner" this often happens, in it I just keep track of online statistics and sometimes sometimes, the mostly profitable Algo in both programs coincides.
my files for wachdog - rebut system if card dead 
[Mining Listener.txt](https://github.com/aaronsace/MultiPoolMiner/files/1452768/Mining.Listener.txt)

**Comment by fonyo** [comment]
Try to ONLY use alphanumeric characters as your workername such as **rig1** or **miner1** or **worker1** but do not use illegal characters as we are not sure where it would cause problems (might break the software or it could be ignored on the pool-side). You can be creative with it, my rigs are named after planets in the solar system (was thinking about giving them girl names just so I could say something like "Sara was misbehaving all night" etc). :)

Looking at the screenshots, it looks like everything is working fine. You can verify this by checking your Balances page on MPH. You can also use the Auto-exchange feature to convert your earnings to eg. Bitcoin then transfer that to your wallet periodically.

**Comment by fonyo** [comment]
Also, please run once the ResetProfit.bat file. That might resolve the issue of your BTC estimate being zero.

**Comment by fonyo** [comment]
@spider703 where did you get that batch file from? Do you have a source please?

**Comment by spider703** [comment]
@fonyo https://www.youtube.com/watch?v=Hg1UTTFQyRY&vl=ru downloaded from here

**Comment by Pititul** [comment]
I use SpeedFan to monitor gpus temperature. If one is below... then it runs a shutdown batch file.

**Comment by cmbconcretefire** [comment]
ok @fonyo , I'll rename the worker in the bat file. Removing the $. I understand. Will reset profits, and possibly run the benches again just for good measure. Then I'll restart and give it another try. 

FYI, I understand auto exchange. I have it set up to exchange everything to LTC. And I even turned Sia Coin > OFF, as I figure I can afford to keep collecting them. @spider703 , thanks, I'll take a look tomorrow. Got to sleep now. Don't close this yet please. I will report back.

**Comment by fonyo** [comment]
I hope you understand, symbols can cause issues and most likely do. Just do a resetprofit first and see how it goes before attempting to rebenchmark everything.

**Comment by cmbconcretefire** [comment]
I think everything is working okay, although I still find it hard to verify the amount of money the miner is telling me I'm making, compared to what MPH is paying me. Between the lack of real time graphs and the auto exchange delay, it's hard to say for sure. 

I'm going to try Nemo's miner and Zpool (but currently cannot get it to connect) 
Anyway, that's not anything negative about MultipoolMiner or you guys ....... but rather just my continuation of experimenting and learning about mining. 
Thanks for the help and suggestions @aaronsace , @fonyo  @spider703 , etc. Oh @fonyo , thanks for the suggestion about adjusting the cmd window. That wasn't the problem though. Since I only use my rigs for mining, I had the resolution set too low. :) I'll check back to see if you guys have anything else to add and you can close this now if you want.

**Comment by fonyo** [comment]
Good luck.
