### ISSUE TITLE
any idea to calculate a profit from MPOS pool (like suprnova)

### ISSUE THREAD

**Issue by dvwzj** [aaronsace/MultiPoolMiner#485]
seem like the other MPOS's pool that do not have api "getautoswitchingandprofitsstatistics" and "getminingandprofitsstatistics" then how to manipulate/recreate these api manually.

or any idea to calculate a profit from hashrate/esttime that I can get from api.

thank you,
ps. sorry for my bad english.

**Comment by aaronsace** [comment]
use whattomine api.

**Comment by spider703** [comment]
dvwzj ты смог добавить супернову в МПМ?
