### ISSUE TITLE
CPU miners

### ISSUE THREAD

**Issue by chabgood** [aaronsace/MultiPoolMiner#489]
I am getting this quite a bit in the CPU miners, TPruvot:

 stratum_recv_line failed
[2017-11-10 08:54:10] Stratum connection interrupted

**Comment by UselessGuru** [comment]
This is a miner problem and indicates a network connection problem.
MPM has nothing to do with the error.

**Comment by chabgood** [comment]
I never get this when GPU mining.

**Comment by fonyo** [comment]
It's an ancient bug in the miner. You should report this error on their Github page.
