### ISSUE TITLE
ccminer Klaust

### ISSUE THREAD

**Issue by snakethejake81** [aaronsace/MultiPoolMiner#49]
FYI, ccminer-klaust requires Visual C++ Redist 2015.  Otherwise it throws a VCRUNTIME140.DLL missing error.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by lyolyalya** [comment]
i install all the visual c++ libs (2005-2015) right after i install windows=)so yeah.it may be=)but i haven't this problems in the future=)

**Comment by aaronsace** [comment]
Updated the release notes.
