### ISSUE TITLE
support for c=<currency> on zpool

### ISSUE THREAD

**Issue by gazm** [aaronsace/MultiPoolMiner#491]
Is there a way to choose the currency for conversion from the batch file? Especially now with BTC switch a real possibility

**Comment by aaronsace** [comment]
The BTC network will still exist if people are still using it. Have to let stuff like this playout and follow the trend; I can only support what the pools choose to support.

**Comment by UselessGuru** [comment]
> Is there a way to choose the currency for conversion from the batch file? Especially now with BTC switch a real possibility

It is not available through parameters in the batch file, but you can edit the pool file 'zpool.ps1':

Pass = "$WorkerName,c=BTC" -> Pass = "$WorkerName,c=**[your currency]**"

**Comment by gazm** [comment]
@UselessGuru thanks

**Comment by fonyo** [comment]
Please be aware that setting anything else than BTC can cause your payout to be delayed or lost completely if insufficient coins are available to complete your transfers. Please read the guide on zpool's home page and analyse the interest of the required coin on the pool before making a decision for going anything else than BTC as your payout currency.
