### ISSUE TITLE
caught in non mining loop

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#492]
when EWBF has an issue connecting to the pool

it shows:

+-------------------------------------------------+
|         EWBF's Zcash CUDA miner. 0.3.4b         |
+-------------------------------------------------+
INFO: Current pool: equihash.eu.nicehash.com:33357
INFO: Selected pools: 1
INFO: Solver: User defined.
INFO: Devices: All.
INFO: Temperature limit: 90
INFO: Api: Listen on 127.0.0.1:42000
---------------------------------------------------
Temp:

Total speed: 0 Sol/s
ERROR: Stratum subscribe timeout

It closes off

Then the MultipoolMiner just starts it again, looping with out any mining taking place...I caught it at 77 restarts. so guess it will go forever.

Boysie

**Comment by aaronsace** [comment]
The new watchdog feature will catch this. 

https://github.com/aaronsace/MultiPoolMiner/commit/920ceae4bb4fa7d40c9105e2edc064b56285051e
