### ISSUE TITLE
Change the checking interval.  

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#496]
It use to be possible to increase the time between checking the different network/pools for profitability. But how do i do this now with 2.6.0.2?

-interval is for benchmarks or is that for all?

**Comment by aaronsace** [comment]
Yes, it's a universal timer for the whole script.

**Comment by fonyo** [comment]
I am adding clarification in the relevant section of the README.

**Comment by fonyo** [comment]
Sent commit.
