### ISSUE TITLE
balance stop updating on mining pool hub

### ISSUE THREAD

**Issue by fusation** [aaronsace/MultiPoolMiner#497]
for some reason my mining pool hub balance has stopped updating my mining progress and the balance has been the same for a few days now. could it be that I setting up my miner wrong but it was mining few days ago now I checked and nothing/

help

**Comment by aaronsace** [comment]
Few days? You can see if it's working straight away; login and check the hashrate on the pool.

**Comment by fusation** [comment]
thank, i think it started to work now I can see some transaction, it just took a long time show something I was worried that I was getting nothing or doing something wrong.
