### ISSUE TITLE
Excavator & Ccminer benchmarking not working with *Nicehash algorithms

### ISSUE THREAD

**Issue by UselessGuru** [aaronsace/MultiPoolMiner#499]
`if ($HashRate_Name -and ($Algorithm -like (Get-Algorithm $HashRate_Name)).Count -eq 1) {`
will not match because $Algorithm can also be Sia**Nicehash** or Decred**Nicehash**
and results in 0 hashrate

this problem was introduced with change https://github.com/aaronsace/MultiPoolMiner/commit/e505d85e86507a132f47cfee6005968a68d3c082#diff-7d92df6946c177b936bf0872246918d5

**Comment by alucard20724** [comment]
try using the latest excavator... it think it's 1.3.6a
they just released 1.3.7 14 hours ago

**Comment by UselessGuru** [comment]
> they just released 1.3.7 14 hours ago

The problem is the same.  The API has not changed, its an MPM issue.

**Comment by UselessGuru** [comment]
The same problem exists in Ccminer.
I fixed the issue like this:
```
if ($HashRate_Name -and ((($Algorithm -like (Get-Algorithm $HashRate_Name)).Count -eq 1) -or ($Algorithm -like "$(Get-Algorithm $HashRate_Name)NiceHash").Count -eq 1)) {
    $HashRate | Add-Member @{(Get-Algorithm $HashRate_Name) = [Int64]$HashRate_Value}
}
```

**Comment by aaronsace** [comment]
What an annoying oversight; the NiceHash extension was only ever meant to be temporary. 

I bet "2gb" causes issues as well.

**Comment by aaronsace** [comment]
Need a some compatibility options for NiceHash, SSL and 2gb but will have to wait for another time.
