### ISSUE TITLE
Benchark hanging in loop

### ISSUE THREAD

**Issue by Tinua** [aaronsace/MultiPoolMiner#50]
Hello
My system is Win10 Pro
Have the new Multipoolminer V2.4.3.1 installed.
Now I can not finish the benchmark.
It seems like hanging in an endless loop through "Bin \ AMD-GenesisMining \ sgminer.exe --api-listen -k myriadcoin-groestl -o stratum + tcp: //hub.miningpoolhub.com: 17005 -u Dumbo.multipoolminer - Px --gpu-threads 2 --worksize 64 --intensity d "
Up to now activated over 30 times.
Restart not help
[2017-01-21_02-47-45.txt](https://github.com/aaronsace/MultiPoolMiner/files/721191/2017-01-21_02-47-45.txt)

**Comment by aaronsace** [comment]
Apologies, kept try everyway to skip past errors in benchmarking but the all ended up having some sort of issue. It now counts the benchmarks itself and should now be fixed. 
https://github.com/aaronsace/MultiPoolMiner/releases
