### ISSUE TITLE
Sorry to log this as issue

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#501]
Hello Fonyo Aaron and all, what is the latest version i should use.
I asked and Fonyo told me about holding off as there was something i should get , 
Please assist and guide me here, i would like to contribute and donate.
I downloaded this MultiPoolMinerPlugins-v2.6.0.2c-Win, But Fonyo told me to disregard and hold off for something else...

**Comment by aaronsace** [comment]
This is very close now; I will put a version number to it this weekend: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

**Comment by imrecsoka** [comment]
Not sure which is the best bat file to run , but i run the multipoolminer one and then it says in yellow, no miners available

**Comment by aaronsace** [comment]
Just wait a couple of minutes, it's downloading them dynamically.

**Comment by imrecsoka** [comment]
i ran all the reset, log, benchmark files and then restarted the zpool.bat file 
i edited all batch files and put my btc wallet in them and my munimingpool username and worker name.
hope thats it

**Comment by aaronsace** [comment]
Yep that should be it. 

Check back tomorrow and I should have cleared all the remaining reported bugs and marked a release.

**Comment by imrecsoka** [comment]
;-)
