### ISSUE TITLE
Dstm doesn't start. Bug with 'ssl://'

### ISSUE THREAD

**Issue by seropaski** [aaronsace/MultiPoolMiner#502]
DSTM miner doesn't start. Your config do same this `--server ssl://equihash.usa.nicehash.com`. 
For working you must fix this as `--server equihash.usa.nicehash.com`. Without `ssl://`.

**Comment by aaronsace** [comment]
It says in the readme to put 'ssl://' in front of the server if you are on an encrypted port...

I can't see any issue and both ssl and non-ssl are working.
