### ISSUE TITLE
how do you add more then one grapics 

### ISSUE THREAD

**Issue by fusation** [aaronsace/MultiPoolMiner#503]
How do you add more graphics card to mining pool miner because I have 2 graphics card and it looks like on the mining screen it shows one? 
or is there a way for me to see how many graphics card it is using?

Thanks
![multipoolminer3](https://user-images.githubusercontent.com/25115191/32984694-271e0ecc-cd10-11e7-8782-1cd3b8446ee2.JPG)

**Comment by aaronsace** [comment]
It mines on them all. If your other card is NVidia then you need to fix your drivers.

**Comment by fusation** [comment]
ok thanks, but it does not look like there is anything wrong with my drive, since nicehash miner detects them both. so when I restart my pc and try running it again it keeps crashing, it shouts all my monitors then turns them back on, then loads the mining pool miner then shows error when it starts to mine. After awhile it switches to 1 graphics card?

**Comment by aaronsace** [comment]
Not much I can suggest. If you can't find what the issue is then delete the miner from the folder called 'miners'.
