### ISSUE TITLE
neoscrypt cc miner reliablity

### ISSUE THREAD

**Issue by Steality** [aaronsace/MultiPoolMiner#505]
Hi, 
So ccminer klaust vs tpruvot and klaust is winner for neoscrypt, but how about stability?
Fonyo mentioned klaust is unreliable in this post, https://github.com/aaronsace/MultiPoolMiner/issues/244
is that means it is not stable?

**Comment by aaronsace** [comment]
I think there has been updates since then; I recommend trying it and see if you have any issues. 

Also, enabling the new watchdog on MultiPoolMiner should help mitigate any problems.
