### ISSUE TITLE
Zpool Failing over to Hashrefinery and NiceHash?

### ISSUE THREAD

**Issue by Splitter9980** [aaronsace/MultiPoolMiner#509]
I noticed today that my machines were running on HashRefinery, which I had never heard of. I found then in the algorithm list that Zpool had disappeared and all of those algorithms replaced with Hashrefinery and NiceHash after the software reported the following error:

PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (502) Bad Gateway."

Looks like Zpool was down and so to keep profits up it's switched to another pool. The problem is that because it's only a failover at the current rate I would never receive a payout (min 0.025BTC) within 60 days so forfeit all work submitted to that pool. Same for NiceHash.

How do I prevent this, I would prefer just continue mining on MiningPoolHub as configured? A search through this site shows nothing about Hashrefinery and I couldn't find it in the code either, but perhaps I didn't look hard enough?

Example, top 3 algo's for 2 consecutive reports:
Miner                  Algorithm                            Speed            BTC/Day         BTC/GH/Day Pool
-----                  ---------                            -----            -------         ---------- ----
CcminerKlaust          NeoScrypt                        1.16 MH/s            0.00052            0.44982 Zpool
CcminerTpruvot         NeoScrypt                        1.10 MH/s            0.00049            0.44982 Zpool
CcminerNanashi         NeoScrypt                        1.01 MH/s            0.00045            0.44982 Zpool

PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (502) Bad Gateway."

Miner                  Algorithm                            Speed            BTC/Day         BTC/GH/Day Pool
-----                  ---------                            -----            -------         ---------- ----
CcminerTpruvot         Bitcore                         17.64 MH/s            0.00045            0.02570 Hashrefinery
CcminerPalgin          X17                             11.43 MH/s            0.00039            0.03416 Hashrefinery
CcminerTpruvot         X17                             10.10 MH/s            0.00035            0.03416 Hashrefinery

**Comment by aaronsace** [comment]
The backup pools are in the folder called 'pools'.

**Comment by Splitter9980** [comment]
Of course they are. Thanks!
