### ISSUE TITLE
"profit" not being shown with version 2.7

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#510]
the profit isn't being shown with latest release version 2.7

maybe i missed it an enablement or something.

**Comment by aaronsace** [comment]
Has the benchmark finished?

**Comment by alucard20724** [comment]
this was after the benchmarks have finished... just shows the watchdog time at the bottom, but no profit display

**Comment by alucard20724** [comment]
doing it without "-watchdog" does not appear to make a difference, there is still no profit displayed.

**Comment by tatsumakisen** [comment]
Hi, the same here

**Comment by Snafu7** [comment]
` -and -not (Get-Job -State Running)`  on:
https://github.com/aaronsace/MultiPoolMiner/blob/b013ffc355f8e554a48ce5f2d1c759f134ec4ce3/MultiPoolMiner.ps1#L475
seems to be what causes the missing profit.

**Comment by lukiifaz** [comment]
Hi , im use old code. 

`if (($BestMiners_Combo | Where-Object Profit -EQ $null | Measure-Object).Count -eq 0) {`  Now is ok

**Comment by aaronsace** [comment]
Cheers, I'll check this tonight.
