### ISSUE TITLE
Multipoolminer get also Nicehash poll instead only the other ones

### ISSUE THREAD

**Issue by Niduin** [aaronsace/MultiPoolMiner#512]
I set "Miningpoolhub,Miningpoolhubcoins ans Zpool" in the Start.bat file but it bench and run also on Nicehash.

**Comment by aaronsace** [comment]
Please attach log.

**Comment by Niduin** [comment]
[2017-11-20_19-04-09.txt](https://github.com/aaronsace/MultiPoolMiner/files/1488856/2017-11-20_19-04-09.txt)

**Comment by aaronsace** [comment]
You need to remove these algorithms: 
Pascal
SiaNicehash

**Comment by Niduin** [comment]
Ah - now it works - thanks ;-)

**Comment by ebbbang** [comment]
Happens to me also ...
algorithms in my bat file are : cryptonight, ethash, equihash, groestl, lyra2z, neoscrypt, sia, siaclaymore

**Comment by aaronsace** [comment]
@ebbbang remove siaclaymore and make sure you have zpool in the mix.
