### ISSUE TITLE
nicehash EWBF goes to multipoolhub and not nicehash.

### ISSUE THREAD

**Issue by chabgood** [aaronsace/MultiPoolMiner#513]
This command is run:
Bin\Equihash-EWBF\miner.exe --eexit 1 --api --server europe.equihash-hub.miningpoolhub.com --port 17023 --user aaronsace.multipoolminer --pass x --fee 0 --intensity 64

Why is it going there and not to nicehash?

**Comment by aaronsace** [comment]
Have you specifically told it to go to NiceHash? 

What command line are you using?

**Comment by chabgood** [comment]
I edit the start.bat file and only use the nicehash pool.

**Comment by chabgood** [comment]
I also downloaded 2.7 and launched the nicehash.bat which does the same thing and it still goes to the hubpool for a few even though they are on NH.

**Comment by aaronsace** [comment]
Please can you post the command-line and log file?

**Comment by chabgood** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 1HKBx8AX8vkrKzTcEQh7GQJ1qrNaoWDHjj -username aaronsace -workername multipoolminer -region europe -currency btc,usd,eur -type nvidia,cpu -poolname nicehash -algorithm cryptonight,decrednicehash,ethash,equihash,lbry,neoscrypt,pascal,sianicehash,sib -donate 24 -watchdog"

[2017-11-20_17-18-28.txt](https://github.com/aaronsace/MultiPoolMiner/files/1489546/2017-11-20_17-18-28.txt)

**Comment by aaronsace** [comment]
I think I have fixed this. Watchdog was interfering with the benchmark.

**Comment by chabgood** [comment]
Is this on master or another branch?

**Comment by aaronsace** [comment]
On the master.
