### ISSUE TITLE
Readme is inaccurate

### ISSUE THREAD

**Issue by tboy1337** [aaronsace/MultiPoolMiner#514]
The readme says that only:
Bitcore, Blakecoin, Blake2s, BlakeVanilla, C11, CryptoNight, Ethash, X11, Decred, Equihash, Groestl, HMQ1725, JHA, Keccak, Lbry, Lyra2RE2, Lyra2z, MyriadGroestl, NeoScrypt, Nist5, Pascal, Quark, Qubit, Scrypt, SHA256, Sia, Sib, Skunk, Skein, Timetravel, Tribus, BlakeVanilla, Veltor, X11, X11evo, X17, Yescrypt 
are supported but in the sample usage it adds decrednicehash,ethash2gb,siaclaymore,sianicehash.  So does that mean that without the extra flags the miner wont duel mine with ethash properly?  Also does that mean you need to add decredclaymore,pascalclaymore,lbryclaymore and also the same with nicehash e.g. pascalnicehash,lbrynicehash?  What is the need in adding nicehash to flag?  Can you please properly document the flags thanks.

**Comment by aaronsace** [comment]
NiceHash stratum connections sometimes aren't compatible. 

As a work around, Sia and Decred have been split.

**Comment by tboy1337** [comment]
Ok that explains the sianicehash and decrednicehash, what about the other
questions?

**Comment by aaronsace** [comment]
As I said, the flags at the end are to do with stratum compatibility; there not for dual mining.

**Comment by fonyo** [comment]
Good point, the list was created solely based on the enlisted items in the algorithms.txt

Will fix that for release. Thanks for catching this one.

**Comment by fonyo** [comment]
With regards to the need of eg. sianicehash, Sia can be mined through different protocols. Miningpoolhub only supports sia mining in conjuction with ethash algos via claymore dual mining. As I understand, Sia solo mining (as a single coin) uses a different mining method which is only supported by Nicehash (from MPM's current pool portfolio). Decred is a similar case.

**Comment by tboy1337** [comment]
Ahh i was wondering how to actually mine sia without claymores, ty for info.  Maybe change flag to siasolonicehash lol,  also ethash2gb isnt well documented either.

**Comment by fonyo** [comment]
Oh, that makes sense. Sia is a weird one, it has at least 4-5 mining protocols/methods that I have heard of. Cool, will add that. I included ethash2gb but I could have sworn I had done it before. Maybe that was explanation on BTCtalk?

**Comment by fonyo** [comment]
All done. Closing this.
