### ISSUE TITLE
Claymore disappeared 2.7

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#515]
Claymore dual working fine during benchmark... but when it's done, it disappeared from the main screen. Not mining. However, Claymore mode 1 works fine.

**Comment by aaronsace** [comment]
Not sure what you mean but I'm releasing a new version so if you are still having issues then reopen.

**Comment by fonyo** [comment]
Are we still having the miners disappearing from the list issue?
