### ISSUE TITLE
Local currency

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#516]
@UselessGuru How do I get this #327 to work in 2.7?

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/510

**Comment by Pititul** [comment]
Nope. This is what I'm talking about. 

@aaronsace please add this in your future update.Thanks.

![img_20171122_012734](https://user-images.githubusercontent.com/31348011/33089857-899a0e14-cf24-11e7-87c6-68498a66705b.png)

**Comment by aaronsace** [comment]
That's not where the profit is displayed.

**Comment by Pititul** [comment]
Yea I know, but it's cool to see it in local money.

**Comment by aaronsace** [comment]
@pitihul The feature that you seem to be suggesting is coming in a later release.

**Comment by UselessGuru** [comment]
Implemented in https://github.com/MultiPoolMiner/MultiPoolMiner/commit/2deeccf9b91f9555e7a052211c010699a41b0236
