### ISSUE TITLE
WARNING: Stat file (CpuminerJayddeeAesavx2_Lyra2z_HashRate) was not updated because the value (424020) is outside fault tolerance.

### ISSUE THREAD

**Issue by lukiifaz** [aaronsace/MultiPoolMiner#517]
WARNING: Stat file (CpuminerJayddeeAesavx2_Lyra2z_HashRate) was not updated because the value (424020) is outside fault tolerance. After update to 2.7.

**Comment by aaronsace** [comment]
The new version detects erroneous values as to not corrupt the statistics.

**Comment by lukiifaz** [comment]
Ok i understood, but after 2 hours with this  i have next problem:
```
 WARNING: Pool API (MiningPoolHub) has failed.
You cannot call a method on a null-valued expression.
At C:\Users\Łukasz\Desktop\ethminer\multi\Pools\MiningPoolHub.ps1:17 char:5
+     $MiningPoolHub_Hosts = $_.all_host_list.split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

WARNING: Pool API (NiceHash) has failed.
```

**Comment by tboy1337** [comment]
Yea im also getting WARNING: Stat file (XXX) was not updated because the value (XXX) is outside fault tolerance. After update to 2.7.  Mostly on my rig mining with cpu and one R9 280.

**Comment by aaronsace** [comment]
@tboy1337 That's normal operation. The bug is the RuntimeException exception not being hidden.
