### ISSUE TITLE
Cpuminer/Minerd

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#518]
Hi, no offense to the Developers, but these miners are just too slow  when you compare the performance of the 2 XMR miners that are out.
But i think main thing here, is that when i run benchmrking, after running start.bat, most of them fail to connect to the stratum / host server.
Even previous versions of MPM are doing this, not sure what we are doing with these checks.

**Comment by aaronsace** [comment]
Both XMRig and FireIce are included. 

All failed miners will be skipped. There will be lots of failed miners to find ones that work.

**Comment by fonyo** [comment]
Suggest going through the README as a refresher course.

**Comment by aaronsace** [comment]
@imrecsoka Check the new version released today; has the latest version of FireIce: 
https://github.com/aaronsace/MultiPoolMiner/releases
