### ISSUE TITLE
2.4.3.5 56commits

### ISSUE THREAD

**Issue by gorilza** [aaronsace/MultiPoolMiner#52]
All the algorithms so
Transcript started, output file is .\Logs\2017-01-25_06-42-33.txt
Add-Member : Cannot add a member with the name "Cryptonight" because a member with that name already exists. To overwrit
e the member anyway, add the Force parameter to your command.
At C:\MultiPoolMinerV2.4.3.5\MultiPoolMiner.ps1:54 char:62
+ ... h {$Pools | Add-Member $_ ($AllPools | Where Algorithm -EQ $_ | Sort  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Cryptonight=;...rypt=; SHA256=}:PSObject) [Add-Member], InvalidOperat
ionException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand
Add-Member : Cannot add a member with the name "Cryptonight" because a member w
ith that name already exists. To overwrite the member anyway, add the Force par
ameter to your command.
At C:\MultiPoolMinerV2.4.3.5\MultiPoolMiner.ps1:54 char:62
+ ... h {$Pools | Add-Member $_ ($AllPools | Where Algorithm -EQ $_ | Sort  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Cryptonight=;...rypt=; SHA2
   56=}:PSObject) [Add-Member], InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Command
   s.AddMemberCommand

**Comment by aaronsace** [comment]
Oops sorry, I'll be a bit more careful before pressing commit from now on. 
Glad to see people are testing as I commit the changes. Thanks!
