### ISSUE TITLE
Please add to release

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#523]
@aaronsace

In order to cut down on questions, time spent on support and make users aware, can you please add to release description and where you see fit:

> Please see README.txt for further instructions, sample usage and command line options.

Or suggest replacing:

> Please submit bugs and feature requests in the 'issues' section.
Logs and Stats are produced in text format; use them when submitting issues.

With:
> Please see README.txt for further instructions, sample usage, command line options and check FAQ before submitting bugs and feature requests in the 'issues' section on Github.
Logs and Stats are produced in text format; use them when submitting issues.

(and maybe important bits of the text in bold or so)

I could amend it myself but I don't want to touch these things. It's your project.

**Comment by aaronsace** [comment]
Good idea. 

I should cut you into the donations. If you have a bitcoin address and username then I will add you.

**Comment by fonyo** [comment]
That is very kind of you ;)
BTC: 1Fonyo1sgJQjEzqp1AxgbHhGkCuNrFt6v9
My username tend to be "fonyo" everywhere on the web and it is on MPH if you are asking for that.

**Comment by aaronsace** [comment]
08117ceff8bb8654799e130c302b2a6a6ae30273

**Comment by fonyo** [comment]
Awesome, thank you! :)

**Comment by fonyo** [comment]
Really not being picky here, and forgive me, I spent way too much time than I should have figuring out how to reword the main features list and ended up with the below to prevent the double use of the word "support" in the same sentence (even though the first one is used as a verb and the second one as a noun). So as per readme:

> Supports benchmarking and multiple platforms (AMD, NVIDIA and CPU)

Also, maybe there should be a short summary of changes included somewhere in the description such as newly added features and miners, key bug fixes.

That also gives me an idea of enlisting all miners currently used by MPM in the README.

Let me know what you think. I could create a draft release description and post it here to review. Maybe keep this thread closed as well.

**Comment by aaronsace** [comment]
The release notes need to be more concise; I just keep adding to it. 

Maybe have description/improvements then fixes/changes then dependencies/steps then warnings/advice. Or whatever you think is best. 

If you can do a rewrite; go for it.

**Comment by fonyo** [comment]
I know now it advises users to seek guidance from the README but I feel if there is too much information there, people might think the description is all they need to get up-and-running. But when I look at it from a different perspective (yours, the method and amount of content there has been so far) I also agree there are things that need to be highlighted as users are generally lazy to read instructions then blame the sw (microaggression and stereotypes here we go). 

I'll see what I can come up with. Maybe if I could reword the whole thing to look less to read? That should satisfy both needs and PoVs.

BTW, I've just read your recent _conversation_ on the MPH ANN. A good example to use to analyse hidden issues when reviewing instructions such as this. I will only consider it as an input and not a requirement, though. ;)

**Comment by fonyo** [comment]
### OLD

Supports benchmarking, has multi-chip support (AMD, NVIDIA and CPU) and includes built-in watchdog timer.

The 'start.bat' files are examples of how you may run the script (and are editable in notepad).
Advanced users can add more miners in the ‘miners’ folder either as JSON or PS1.

Please see readme for further instructions, sample usage, command line options and check FAQ before submitting bugs and feature requests in the 'issues' section on Github.
Logs and Stats are produced in text format; use them when submitting issues.

Any bitcoin donations are greatly appreciated: 1MsrCoAt8qM53HUMsUxvy9gMj3QVbHLazH

Notes

You will need 'excavator.exe' if you don't already have it:
https://github.com/nicehash/excavator/releases
It is not recommended but to upgrade from a previous version of MultiPoolMiner, you may simply copy the 'stats' folder.
If you have Windows 7, please update PowerShell:
https://www.microsoft.com/en-us/download/details.aspx?id=50395
CCMiner may need 'MSVCR120.dll' if you don't already have it:
https://www.microsoft.com/en-gb/download/details.aspx?id=40784
CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it:
https://www.microsoft.com/en-us/download/details.aspx?id=48145
WARNING: DO NOT COPY/DOWNLOAD DLL FILES. USE THE MICROSOFT LINKS!

**Comment by fonyo** [comment]
@aaronsace 

This should be more compact and organised. All the previous data is still there with many more additions But it does not look so scary anymore. Please let me know what you think and if you could add a few key fixes/additions, that would be great.
