### ISSUE TITLE
mpm ver 2.7.0.1-FireiceAMD trying to run each time Claymore2gbLbry running

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#527]
I don't know if this is intended or not, but everytime Claymore2gbLbry runs, 3 instances for FireiceAMD pops up and tries to run also... sometime successful, sometimes not.  this is on my test system with a Vega64 with the blockchain drivers for window10.

**Comment by aaronsace** [comment]
Please can you post the log?

**Comment by aaronsace** [comment]
I can't reproduce this. 

If you are still having problems in 2.7.0.2 then please post the log.

**Comment by alucard20724** [comment]
I'm not seeing the problem with 2.7.0.2
