### ISSUE TITLE
Failed to connect to miner (CcminerTpruvot).

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#529]
Failed to connect to miner (CcminerTpruvot). Can't finish the benchmark.

**Comment by Pititul** [comment]
added stratum+tcp:// in the arguments.

**Comment by Lagarinhos** [comment]
How did u fix it? Im getting loads of this message.. my benchmark goes well, I get shares and so. But at the end, the algo just disappears from the list and stay as idle permanently. :(
