### ISSUE TITLE
Last Build - no miners in bin

### ISSUE THREAD

**Issue by gorilza** [aaronsace/MultiPoolMiner#53]
The next problem, no miners in bin.
[2017-01-26_12-17-42.txt](https://github.com/aaronsace/MultiPoolMiner/files/730848/2017-01-26_12-17-42.txt)
Folder in \BIN
AMD-GenesisMining
CPU-TPruvot
Cryptonight-NiceHash
Equihash-NiceHash
NVIDIA-KlausT
NVIDIA-Nanashi
NVIDIA-SP
NVIDIA-TPruvot

**Comment by aaronsace** [comment]
They can't be included. That's release only builds only.

**Comment by gorilza** [comment]
Ok.
