### ISSUE TITLE
BTG pool is now open on MPH

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#532]
U.S.     :   us-east.equihash-hub.miningpoolhub.com:20595
Europe :   europe.equihash-hub.miningpoolhub.com:20595
Asia     :   asia.equihash-hub.miningpoolhub.com:20595
And added to port 17023 as well.

**Comment by imrecsoka** [comment]
Hi Fonyo, is BTG in MultiPoolMinerV2.7.0.2, or should i wait for a next release.

**Comment by alucard20724** [comment]
Yes... BTG is available with mpm 2.7.0.2... as long as you have equihash capabilities, you have BTG capabilities.

**Comment by aaronsace** [comment]
MultiPoolMiner automatically started mining BTG when it came out.

**Comment by imrecsoka** [comment]
And to check, obviously if it is profitable it will mine it ?
Aaron, you will be pleased to know i completed the benchmarks on MultiPoolMinerV2.7.0.2 and now mining with it.
I got a few errors ,but i ignored it and let it carry on.
I notice though, the predicted/estimated profit at the bottom right that used to be there, seldom comes up/ displayed. I take it this is the new look?

**Comment by fonyo** [comment]
Bitcoin Gold is using equihash, so if you have equihash listed in the batch file then BTG will also be mined on MPH when most profitable. With RX cards, you should be mining ethash coins, though, to get the most profit. Check it on whattomine or just list both ethash and equihash in the batch file and let MPM decide the most profitable algo for you (the latter is probably a better idea).

**Comment by imrecsoka** [comment]
I tried to mine the BTG directly using Zecminer but it seems to be flakey.
It shows speed and stuff but i get no share accepted messages, very weird.
I get very few when it starts to mine, but after a minute or so i get nothing.

In the batch file i have specified equihash also, if i mine that way (most common).
I just wanted to try direct BTG and hold a little bit with no auto exchanging
