### ISSUE TITLE
Install Prerequisites

### ISSUE THREAD

**Issue by aaronsace** [aaronsace/MultiPoolMiner#533]
Check the registry for installed Visual C++ Runtimes then, if not present, download and silently install. 
Maybe include PowerShell 6 also.

**Comment by fonyo** [comment]
Are you planning to achieve the V3 complete feature set by working towards it through v2.x.x in an incremental fashion?

**Comment by aaronsace** [comment]
I need to prioritize the usability for new people before moving on and this is one of them. Once it's click on run with no issues then I will setup a dev branch to allow minor updates to be made on the master when they are needed.

**Comment by zaptrem** [comment]
@fonyo What are these *events* you speak of?

**Comment by fonyo** [comment]
Nothing serious or significant, it was just an unhappy user. I may not want to drag more attention to it by pointing fingers. I hope that is OK. The important thing that comes from it is that we have a single input now that will be considered to clarify docs and improve user experience and usability. All bad things have a good side.
