### ISSUE TITLE
Running on one gpu?

### ISSUE THREAD

**Issue by DJAGER47** [aaronsace/MultiPoolMiner#535]
How to run on one video card? In the computer two graphics cards, one for work. On the other I want to run the miner.

**Comment by aaronsace** [comment]
With difficulty; each miner has it's own settings in the folder called 'miners'.

**Comment by fonyo** [comment]
Restricting mining to certain GPUs is a feature that will come in a future release. In the meantime, advanced users can modify miner files (various config files in the /Miners folder) to achieve the same. First, please go through the README, then run a full benchmark. If you are running the same two cards, once benchmarking is done, you will be able to evaluate what the most profitable coins/algos are for your card or you can also check the stats on whattomine. Once you have this information, you will need to reduce the MPM -algorithm list to those algos and amend the relevant miners with the desired settings. Unfortunately, as MPM is not responsible for the development of the miner software used, you will need to check the README files for each miner to learn what command line options can be used to achieve this.

**Comment by DJAGER47** [comment]
Thank you. Get the idea. You need to try. Claymore I only need to change :)

**Comment by aaronsace** [comment]
Hopefully this feature will be added to MultiPoolMiner at some point.
