### ISSUE TITLE
Add hashrefinery?

### ISSUE THREAD

**Issue by tboy1337** [aaronsace/MultiPoolMiner#539]
Add http://pool.hashrefinery.com mutipool support?

**Comment by aaronsace** [comment]
It's in the 'pools' folder already.

**Comment by tboy1337** [comment]
Add hash refinery to documentation, dont think its been mentioned that its added.

**Comment by fonyo** [comment]
Yes, but that is because it was used as a failover pool and pool file was not complete, either.

**Comment by fonyo** [comment]
Note to self, to be added to README. Please don't close this.

**Comment by fonyo** [comment]
Added to README, closing this.
