### ISSUE TITLE
NiceHash Equihash

### ISSUE THREAD

**Issue by n3cr0cr0w** [aaronsace/MultiPoolMiner#54]
nheqminer.exe is trying to execute every minute in the background on my setup. I'm only running -type AMD on my system. nheqminer.exe doesn't even support AMD mining and should not be trying to run in the background without any notification.

I tried removing the Equihash-NiceHash folder and it just re-downloaded the software. I'm now removing it from the miners folder and then deleting the bin files.

**Comment by aaronsace** [comment]
Sounds like it is trying to mine NVidia or cpu still. 

Is this the command that you are running? 
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username aaronsace -workername multipoolminer -interval 60 -location europe -ssl -type amd"`

**Comment by lyolyalya** [comment]
nheqminer can do opencl. -od parameter.so if you don't want it - delete it.

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/22373179/5023fd40-e4a9-11e6-95eb-b7f629896be1.png)

**Comment by aaronsace** [comment]
I actually already took nheqminer-AMD out of the latest release which is why I think they may not be using the latest version.

**Comment by aaronsace** [comment]
I've actually spotted a bug which isn't related. The nheqminer-NVidia has 'od' on the command line instead of 'cd'.

**Comment by aaronsace** [comment]
I think OpenCL support was dropped so it just means nheqminer won't work on NVidia at the moment. EWBF is faster anyway but will issue a fix anyway tonight. 

**I've convoluted the initial issue a bit. @n3cr0cr0w do let me know if the first solution I posted worked. Cheers.**

**Comment by n3cr0cr0w** [comment]
This is what I'm running `powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username N3Cr0Cr0W -workername multipoolminer -interval 60 -location us -ssl -type amd"`

The only reason I knew it was running was from my Event Log telling me it was crashing every minute, it never showed on the main screen that it was running it or benchmarking it.

I was also running the latest code from last night (US CST) merged with the latest release. (I check for updates every day).

**Comment by n3cr0cr0w** [comment]
Also, the logs never mentioned it, it was trying to run silently which sounds like a bug. Is there a debug mode that I can run to make the logs more complete for testing purposes?

**Comment by n3cr0cr0w** [comment]
As soon as I replace the Nheqminer files in the miner folder (without restarting) it downloads the miner and runs it, nothing is in the MultiPoll Miner log but then I get this in my Event Log.

`Faulting application name: nheqminer.exe, version: 0.0.0.0, time stamp: 0x5877ebda
Faulting module name: MSVCR120.dll, version: 12.0.40660.0, time stamp: 0x577e0cc7
Exception code: 0xc0000409
Fault offset: 0x0000000000074890
Faulting process id: 0x278
Faulting application start time: 0x01d278c8520c59be
Faulting application path: D:\MultiPoolMiner\Bin\Equihash-NiceHash\nheqminer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCR120.dll
Report Id: 4af3b5a1-ede7-4174-836d-5594ea9b65bb
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by aaronsace** [comment]
Ah, sorry, it's because that particular miner doesn't detect the cards on launch. To detect cards, it has to run a command then use the output for the mining settings. I could look at an alternative solution. Will post a suggestion on their issues page as well.

**Comment by newmzy** [comment]
I just tried Multipool miner for the first time tonight, I had another issue which I will open seperately - but I also noticed that very often I got a message something like "Nheqminer has crashed". I am on an all AMD rig.

**Comment by lyolyalya** [comment]
so why nheqminer on amd?use claymore zcash miner.
