### ISSUE TITLE
Can't add any wallet

### ISSUE THREAD

**Issue by Fraydenz** [aaronsace/MultiPoolMiner#541]
Hi, I know this has been asked but it didn't work for me. I have 0 wallets on MPH and am unable to add any for any of the coins I tried. I've stopped mining there for now obviously, but want to mine there. I have auto-switch On currently to pay bitcoin. When I go to the wallet page for btc, or any coin, there is no box to put the wallet in, just a slightly yellow rectangle where the window/box should be.

I've tried many times over a few days on different PCs. I am able to put my pin in and change the payout amount, but that's it. I'm asking because I have .009 btc on there, which is not nothing. I know, I should have tried the wallet 1st.

I'd appreciate any help.

**Comment by aaronsace** [comment]
@Fraydenz Sorry but this is MultiPoolMiner not MiningPoolHub.

**Comment by Fraydenz** [comment]
Oops, sorry!
