### ISSUE TITLE
CRITICAL BUG: mines for 20% on donate wallet....  -donate 0  does not work in version 2.7.0.2

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#542]
-donate 0 does not work

I would consider this a critical bug for version 2.7.0.2

Miner is mining for 20% on donate wallet regardless of -donate flag

**Comment by aaronsace** [comment]
It's measured in minutes. The minimum is 10 minutes (0.7%). 

Where have you got 20% from?

**Comment by alucard20724** [comment]
ok... it's mining 10-12 minutes every hour

**Comment by aaronsace** [comment]
Yep, not every hour in the day! Seeing as it is working as intended then I will close the issue.
