### ISSUE TITLE
CcminerLyra2z ccminer_cuda9.exe invalid shares

### ISSUE THREAD

**Issue by SaintPistachio** [aaronsace/MultiPoolMiner#548]
This miner seems to produce a lot of invalid shares. Maybe only 1/4 are valid. This was running on zpool. v2.7.0.2

**Comment by UselessGuru** [comment]
This is a known problem with the miner itself and has nothing to do with MPM.
[https://github.com/djm34/ccminer-msvc2015/issues/23](https://github.com/djm34/ccminer-msvc2015/issues/23)
I suggest to use another miner, e.g Ccminer 2.2.2.

**Comment by SaintPistachio** [comment]
Perhaps it should be removed until it is fixed? I removed the miner file for now. Thanks
