### ISSUE TITLE
Prospector runs on all cards in mixed amd/nv system with only amd is selected

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#551]
I have a couple of mixed system of amd and nvidia cards that i use for testing.

when only amd card is chosen in the startup scrypt, both cards will still run.  i haven't checked it the other way around.

mpm was downloaded from the master 12/1/2017 about 8pm CST

**Comment by lee-aaron** [comment]
#537 I think what you're describing is like this issue? prospector can run on both cards I believe.

**Comment by alucard20724** [comment]
i don't want it to run on both cards... that's the problem.

**Comment by alucard20724** [comment]
i don't want it  to run on both cards... that's the problem.  If my AMD card is running xmr that is most profitable, i don't want it trying to run Prospector(any prospector algo) also that might be profitable for nVidia. that might be profitable for Nvidia at the time but not AMD.

**Comment by aaronsace** [comment]
This is not support as of yet. You will have to edit the file in the folder called 'miners' and enter your GPU numbers.
