### ISSUE TITLE
About the switch miners

### ISSUE THREAD

**Issue by czjlj** [aaronsace/MultiPoolMiner#552]
I want to switch miner every 10 mins.Because if  switch miner in 60 sec there was wasted some sec for algorithms begun and some times the miner have not yet begun to end.So how can I change it to 10 mins?

**Comment by aaronsace** [comment]
It's not switching every 60 seconds. Please can you post the log if it is?

**Comment by fonyo** [comment]
_(Just_ commenting on this to be added to my watchlist)_
