### ISSUE TITLE
Page Not Working

### ISSUE THREAD

**Issue by aaronsace** [aaronsace/MultiPoolMiner#555]
Readme.md or Index.md needs adding for the page to work: 
https://aaronsace.github.io/MultiPoolMiner/

**Comment by fonyo** [comment]
Cool, once I reviewed the README and added a few newly arisen questions, I will create a markdown version.

**Comment by fonyo** [comment]
Quick update, I am working on the updates we discussed (been very busy the last week or so), currently going through all issues so I can update the README.txt as a master prior to creating the MD version and reviewing, drafting the new release info and a draft process what it should contain going forward.

**Comment by fonyo** [comment]
Page is working now. Please have a look at the the markdown version either on your github.io page or by looking at the .md file itself. Let me know if any issues.
