### ISSUE TITLE
Blake2s and Groestl not working

### ISSUE THREAD

**Issue by Pititul** [aaronsace/MultiPoolMiner#558]
These algos used to work but now they are disabled. Tried benchmark a few times. The miner screen were mining normally during the benchmarks, mining result also showed in the pool page.

Is it due to the pool itself (ahashpool) or I broke something in MPM?

```
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4069""
PS>TerminatingError(Get-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Users\Alpha\Desktop\MultiPoolMiner-master\Stats\CcminerPalgin-x86_Blake2s_HashRate.txt' because it does not exist."
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
```

**Comment by aaronsace** [comment]
'CcminerPalgin-x86' has died; it cannot connect to '127.0.0.1:4069'. Check '4069' is the correct port and/or what errors are being thrown by 'CcminerPalgin-x86'.
