### ISSUE TITLE
Start mining

### ISSUE THREAD

**Issue by wishxy** [aaronsace/MultiPoolMiner#56]
I have problem to start mining with MPM. Please help.
Here is my bat and log file:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username wishxy -workername Z1 -interval 60 -location europe -ssl -type amd"

[2017-01-30_10-45-54.txt](https://github.com/aaronsace/MultiPoolMiner/files/740922/2017-01-30_10-45-54.txt)

**Comment by n3cr0cr0w** [comment]
Some miners do not have official downloads anymore and are packed here in the release zips. Download from release section and copy the bin folder to where you downloaded your current copy.

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
