### ISSUE TITLE
Not switching to different pool when pool goes offline (master version dated dec 02 2017)

### ISSUE THREAD

**Issue by alucard20724** [aaronsace/MultiPoolMiner#560]
when Nicehash went offline today, mpm did not switch to a working pool.  mpm stayed on the non-functioning pool and miners stayed idle.

I'm working with the master downloaded on dec 2, 2017.  works really well except for what just happened.  Not sure if it's fixed/updated since saturday that fixes this problem.  haven't looked at the "three strikes"

p.s. i don't have the watchdog turned on because it keeps removing good miners from my available miners

**Comment by aaronsace** [comment]
If the NiceHash stratum is down then only watchdog will detect the problem.
