### ISSUE TITLE
Help starting the latest version

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#561]
Looks like nicehash might've gotten hacked. Heading to miningpoolhub. Trying to run the newest miner and I get:

Index was out of range. Must be non-negative and less than the size of the
collection.
Parameter name: index
At line:1 char:118
+ ... 64.msi -qn; & .\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentOutOfRangeExce
   ption
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException

**Comment by aaronsace** [comment]
https://www.nicehash.com/

**Comment by aaronsace** [comment]
Just maintenance.

**Comment by winnal** [comment]
No, people on reddit are saying it might have been hacked it's been under maintenance for over 10 hours.

But either way, while it's down I want to mine miningpoolhub again, I'd like to use this miner, could you please look at the error?

**Comment by aaronsace** [comment]
Just ignore the error.

**Comment by winnal** [comment]
What do you mean? The miner won't start.

**Comment by aaronsace** [comment]
I'm confused; is your error report related to NiceHash going down or are you testing the latest build?

**Comment by winnal** [comment]
No, the error is posted when I try and run the miner.

**Comment by winnal** [comment]
Index was out of range. Must be non-negative and less than the size of the
collection.
Parameter name: index
At line:1 char:118

    ... 64.msi -qn; & .\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7 ...

                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        CategoryInfo : OperationStopped: (:) [], ArgumentOutOfRangeExce
        ption
        FullyQualifiedErrorId : System.ArgumentOutOfRangeException

**Comment by aaronsace** [comment]
Cheers, I'll have a look into it. In the meantime use the latest stable release.

**Comment by winnal** [comment]
Great, thanks.

**Comment by winnal** [comment]
Now I'm trying to run the latest release and I get this:

C:\Users\Winnal\Downloads\MultiPoolMinerV2.7.0.2\MultiPoolMiner.ps1 : Cannot
process argument transformation on parameter 'API_ID'. Cannot convert value
"nvidia" to type "System.Int32". Error: "Input string was not in a correct
format."
At line:1 char:144
+ ... rname multipoolminer -region us -currency btc,usd-type nvidia -poolna ...
+                                                            ~~~~~~
    + CategoryInfo          : InvalidData: (:) [MultiPoolMiner.ps1], Parameter
   BindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,MultiPoolMi
   ner.ps1
