### ISSUE TITLE
Help starting multipoolminer

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#562]
Trying to run the newest miner and I get:

Index was out of range. Must be non-negative and less than the size of the
collection.
Parameter name: index
At line:1 char:118

    ... 64.msi -qn; & .\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7 ...

                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        CategoryInfo : OperationStopped: (:) [], ArgumentOutOfRangeExce
        ption
        FullyQualifiedErrorId : System.ArgumentOutOfRangeException

**Comment by fonyo** [comment]
Are you using 2.7.0.2 or the latest master? Please use the release instead of just downloading master.

**Comment by aaronsace** [comment]
Correct link: https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip

**Comment by aaronsace** [comment]
@SHOBU007 https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/v2.7.1.4/MultiPoolMinerV2.7.1.4.zip

**Comment by Freshbrewed** [comment]
Here is a simple solution for your problem. It worked for me after I've tried everything & everything I could find.

Step 1. Press **Windows**-button, then type "**pwsh**". If nothing happens or the window disappears right after, then you are _missing packages needed to run PowerShell 6.0/6.0.1_ correctly.

Step 2. Supposedly you don't have Windows 7 Service Pack 2 installed. Go install it here:
https://answers.microsoft.com/en-us/windows/forum/windows_7-update/how-to-obtain-and-install-windows-7-sp2/c2c7009f-3a10-4199-9c89-48e1e883051e?auth=1

Follow instructions in there. You need **KB3020369** and **Convenience Update (SP2)** which are listed in the aforementioned site.  First, apply KB3020369 and then Convenience Update (SP2).

3. Restart computer. Press _Windows -key_ and type "**pwsh**". If a window opens and stays open, the missed packages were installed succesfully by Windows Updates. Now everythings working as expected!
