### ISSUE TITLE
Are these rates real?

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#563]
It’s been officially stated nicehash has been hacked.

But now, using the multipoolminer it’s giving me a rate of .0045 a day~$60 per day. Is this for real? Obviously due to the downtime of nicehash.

Sorry if it’s not a real programming issue but I’m wondering if these rates are real that’s given in the ‘stats’ folder.

**Comment by aaronsace** [comment]
You'll have to post move information if you think there is something wring. There is a 'logs' folder.

**Comment by winnal** [comment]
Sorry I totally forgot to include the rate of the pool of vertcoin. Miningpoolhub is currently .032 btc/gh/day. Is this correct? I mean it must be by all accounts it’s taking it from Coinbase and miningpoolhub right?

**Comment by aaronsace** [comment]
Sorry, I will need the log.

**Comment by FruitFace** [comment]
I also saw some crazy prices.  I wish my rig could make 31USD/day.  Typical is somewhere beween 8-11USD   Here'a copy of my log.
[2017-12-06_00-31-02.txt](https://github.com/aaronsace/MultiPoolMiner/files/1537739/2017-12-06_00-31-02.txt)

**Comment by Lagarinhos** [comment]
VTC is showing crasy values indeed since yesterday

**Comment by fonyo** [comment]
The rates are seem to be real indeed. If in doubt, you can always launch the ResetProfit.bat even when MPM is running and it will be corrected in the next loop (within a minute by default).
