### ISSUE TITLE
Imposiible to start the miner - tested on 3 pcs

### ISSUE THREAD

**Issue by izacs** [aaronsace/MultiPoolMiner#564]
i try on 3 defrent pcs and 2 windows 2008 and 2012 
keep gitting these error
![bug](https://user-images.githubusercontent.com/34320294/33686901-0ab5da26-dadf-11e7-86f9-d5edd6677f78.png)

**Comment by izacs** [comment]
mm if you install powershell 6 manually and try it works normally

**Comment by izacs** [comment]
but with these errors 
![errors](https://user-images.githubusercontent.com/34320294/33687578-3e66c23e-dae1-11e7-84ad-8b0df5505d2f.png)

**Comment by izacs** [comment]
using only cpu mine btw 
![no miners](https://user-images.githubusercontent.com/34320294/33687710-9b66568e-dae1-11e7-8db0-414ec84206d9.png)

**Comment by aaronsace** [comment]
Please use the latest stable release.

**Comment by izacs** [comment]
give me link please

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by pzacheo** [comment]
I also cannot start it, tested in 2 PCs, one with Win7 another with Win10. Same errors:

C:\MultiPoolMinerV2.7.0.2>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\MultiPoolMinerV2.7.0.2>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\MultiPoolMinerV2.7.0.2>powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet #CONFIDENTIAL# -username xxxxx -workername MINER1 -region europe -currency btc,usd,eur -type amd,nvidia,cpu -poolname miningpoolhub,miningpoolhubcoins,zpool,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib -donate 1 -watchdog"
Get-Algorithm : The term 'Get-Algorithm' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and
try again.
At C:\MultiPoolMinerV2.7.0.2\MultiPoolMiner.ps1:48 char:43
+ $Algorithm = $Algorithm | ForEach-Object {Get-Algorithm $_}
+                                           ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Algorithm:String) [], Co
   mmandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-Algorithm : The term 'Get-Algorithm' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and
try again.
At C:\MultiPoolMinerV2.7.0.2\MultiPoolMiner.ps1:48 char:43
+ $Algorithm = $Algorithm | ForEach-Object {Get-Algorithm $_}
+                                           ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Algorithm:String) [], Co
   mmandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-Algorithm : The term 'Get-Algorithm' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and
try again.
At C:\MultiPoolMinerV2.7.0.2\MultiPoolMiner.ps1:48 char:43
+ $Algorithm = $Algorithm | ForEach-Object {Get-Algorithm $_}
+

**Comment by aaronsace** [comment]
@pzacheo Your issue is not related. 

Get-Algorithm is in this file: Include.psm1
Check that file is accessible.

**Comment by pzacheo** [comment]
Thank you but is not applicable for Windows 10. I tried all in the list. None of them will install for this OS. My 2 Miners are Windows 10 based.

Also the files were not locked. So it's probable something else.

**Comment by aaronsace** [comment]
You don't install it. You simply extract then run. Maybe you need admin for 'c' drive; try putting it on your desktop instead. 

I'm a bit confused as there are are loads of people using it and I have run it from scratch many times.

**Comment by pzacheo** [comment]
Thank you, when you say extract and run, to which file you refer for Win10, this one:
Win8.1AndW2K12R2-KB3191564-x64.msu
This file I can only run it and gives out an error, not for this OS.

I'm a bit desperated because I used Nicehash and have 11 GPUs in 3 different PCs. And I'm still paying for the rigs. Now using Minergate but paying very few money.

**Comment by deviousdevin** [comment]
I had the exact same issue where it couldn't find MultiPoolMiner.ps1, but eventually found a fix.  

I'm not sure which did it, but I made a couple changes to the script.  Current theory that I don't feel like testing cause I'm still researching a lot of this stuff is that I had it stored in a folder that had a space in the name and not something that was a single word.  When I switched to C:\MultiPoolMiner\ it worked.

Here's what I used in the script:

> powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "C:\MultiPoolMiner\multipoolminer.ps1 -wallet ##NOPE## -username MYUSERNAME -workername notemultipoolminer -region us -currency btc,usd,eur -type nvidia,cpu -poolname miningpoolhubcoins -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2z,neoscrypt,sia,siaclaymore,
