### ISSUE TITLE
not work excavator 17018 miningpoolhub

### ISSUE THREAD

**Issue by caxep23** [aaronsace/MultiPoolMiner#565]
when mining vertcoin by excavator miner on the miningpoohub pool, the speed is 0. in dashboard

**Comment by fonyo** [comment]
It works perfectly, please post the content of your start.bat and ensure you are using 2.7.0.2 and NOT the latest master.

**Comment by AmINick** [comment]
Hi, I have the same issue while mining to Miningpoolhub. Although Excavator shows a greater hashrate locally. On miningpoolhub, it is either 0 (not detecting it), or a very low hashrate. I have to manually switch to ccminer-palgin and this way things seem to be correct. However ccminig-pagin shows a lower hashrate locally compare to excavator and it just drop a little over time(at least on my rigs). I am using 2.7.0.2 and used a simply modified miningpoolhub.bat

**Comment by fonyo** [comment]
It works for me, could not reproduce this issue. Can you see hashrate on the Graphs page of either Vertcoin or Monacoin?

**Comment by fonyo** [comment]
There is an issue with the dashboard and the graphs shown on MPH. Your hashrates are safe and accounted for but not visible atm.

**Comment by AmINick** [comment]
saw a new issue saying that win7 doesnt have dns resolve, but I am using win10, am I effected by that bug?

**Comment by caxep23** [comment]
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 1LjWtLA4TCqzHNZXmGBQLqcsBAYXYPYsB9 -username mineralnov23 -workername 1060dom3 -region europe -currency btc,usd,eur -type nvidia -poolname zpool,miningpoolhub,miningpoolhubcoins -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,pascal,siaclaymore,sianicehash,sib,skunk,lyra2re2,phi,myriadgroestl,skein,xevan,neoscrypt,x17,c11,veltor,blakecoin,keccak,x11evo,timetravel,hsr,tribus,Polytimos -donate 0 -watchdog"

**Comment by caxep23** [comment]
проблема сохраняется по порту 17018 не отображается скорость

**Comment by fonyo** [comment]
What is the problem with port 17018? I did learn some Russian for fun when I was a teenager but it is mostly faded away now. Please try to keep the conversation language in English so we can all tuck in (however, we don't mind if you post questions and responses in multiple languages at the same time).

**Comment by aaronsace** [comment]
NiceHash block the host name so the IP address is used instead. 

It works on Windows 10; will be making it backward compatible.
