### ISSUE TITLE
Mining VTC with OCM?

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#566]
I heard it’s faster to mine VTC with OCM? Or is MiningPoolHub faster?

**Comment by aaronsace** [comment]
Sorry, not sure what OCM is. 

MiningPoolHub is a pool not a miner.

**Comment by fonyo** [comment]
One-click-miner for Vertcoin that uses a modified tpruvot lyra2rev2 miner and includes a 2% fee.
Klaust and excavator are faster.

**Comment by fonyo** [comment]
The miner used in OCM has the gigahash bug due to improper fail detection. It also does not like 1070 cards, no matter what I do with the intensities.

**Comment by fonyo** [comment]
@winnal Answering the question you meant to ask: MPM (MultiPoolMiner) can earn you more than OCM even if you use it just to mine lyra2rev2 coins.
