### ISSUE TITLE
Cpu-TPruvot stratum_subscribe send failed error

### ISSUE THREAD

**Issue by Jacobknight** [aaronsace/MultiPoolMiner#567]
Hi, I am constantly getting this error with the latest multipoolminer. Please help.

<a href="https://gyazo.com/8826dc267465828ab2ee93cf1bc356c0"><img src="https://i.gyazo.com/8826dc267465828ab2ee93cf1bc356c0.png" alt="https://gyazo.com/8826dc267465828ab2ee93cf1bc356c0" width="1847"/></a>

My start.bat file [here](https://pastebin.com/Dmx7GmCf)

**Comment by aaronsace** [comment]
Wouldn't worry to much as it's still benchmarking.

**Comment by fonyo** [comment]
Please be careful with CPU mining, 99% of the time it's not worth it even if you have Ryzen 17xx or 18xx processors. You can remove the CPU mining functionality by amending you start.bat and removing the "cpu" parameter after the -type command.

**Comment by Jacobknight** [comment]
Oh. Ya I do have some ryzens. Ya I agree with you. Just mining some ETN atm seems to be doing good.

**Comment by fonyo** [comment]
That's cool, just watch the temps so they also stay cool. ;)
