### ISSUE TITLE
USE RELEASE 2.7.0.2 AND NOT THE LATEST MASTER PLEASE!

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#568]
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip

**Comment by alucard20724** [comment]
why?

**Comment by aaronsace** [comment]
@alucard20724 The master is for testing and people are getting mixed up.

**Comment by alucard20724** [comment]
ok... well... i'm testing. :)

**Comment by crazybrker** [comment]
We want the bleeding edge new scripts! Don't you want more testers?

**Comment by fonyo** [comment]
Whoever is questioning this post should already know, they can use the master. The post was meant to inform the newcomers on what to use, if they don't know what to do! You are welcome to use the master as usual.

**Comment by FabianGabor** [comment]
Maybe have the stable code in the master branch and have a testing / alpha / beta branch for regular updates then merge those into the master when ready. That way you will avoid lots of similar talks.

**Comment by aaronsace** [comment]
@FabianGabor The only issue was that people didn't get that GitHub had a release page so they clicked the first download button. You do have to use the release as the code is missing binary files. 

Think it's safe to close this now.
