### ISSUE TITLE
Location of file MiningPoolHub_Equihash_3.json

### ISSUE THREAD

**Issue by txr13** [aaronsace/MultiPoolMiner#569]
I've downloaded the 2.7.0.2 release (and downloaded excavator separately, as directed). When launching, I receive a message that excavator cannot find the command file "MiningPoolHub_Equihash_3.json".

I haven't been able to locate this file at all. What am I missing? :)

**Comment by aaronsace** [comment]
That file should be located at "Bin/Excavator3/MiningPoolHub_Equihash_3.json"

Are there any '.json' files in 'Bin/Excavator3/'?

**Comment by txr13** [comment]
There is no folder within Bin named "Excavator3"...

**Comment by fonyo** [comment]
Just **Bin/Excavator/* without the ***3***.

**Comment by txr13** [comment]
I have placed the files from the excavator release into Bin/Excavator/. There is no "MiningPoolHub_Equihash_3.json" file in that directory, though.

**Comment by aaronsace** [comment]
Are there any .json files?

**Comment by winfij** [comment]
I'm having the same problem - missing json files, so I thought I'd chime in and answer the pending question.
In my case at least there are only the two sample json files which are in the excavator download package - nothing is being added by mpm.

**Comment by fonyo** [comment]
I've heard this from someone else in another thread, something is wrong. Let's try to narrow this down.

@txr13 @winfij Are you guys using excavator v1.3.8 alpha? If not, can you please try with that version instead? https://github.com/nicehash/excavator/releases

**Comment by winnal** [comment]
Though this issue is partially mine, even when I manually put the .json file in it gives me 0 MHs when mining on miningpoolhub with excavator.

**Comment by winfij** [comment]
Yep - I'm using 1.3.8a downloaded fresh last night.

I don't think the problem is in running excavator though - presumably mpm is supposed to generate that json config file and copy it into the excavator dir?

**Comment by fonyo** [comment]
Yes, but for some reason, it doesn't do it for any of you and I can't reproduce the issue.

**Comment by winfij** [comment]
Is there any extra debug logging we can dial up in mpm to help find the problem?

**Comment by txr13** [comment]
@aaronsace @fonyo Like @winfij, I downloaded excavator 1.3.8a fresh last night. There are two .json files in the directory: command_file_example_1.json and default_command_file.json. No other .json files have been generated.

**Comment by fonyo** [comment]
I have got quite a few in there.
![552cdfc0-2445-41c3-b363-fb7c8040cedb](https://user-images.githubusercontent.com/10072275/33745675-32f9e550-dbb0-11e7-8c8d-666c03626f9f.png)

**Comment by UselessGuru** [comment]
The json files are generated dynamically by the miner file and put in the directory where excavator is. This is defined defined by the following line:
$Path = ".\Bin\Excavator\excavator.exe"
Make sure the user running MPM has write access to this folder.

**Comment by winfij** [comment]
I tried this on another machine and it worked fine, no real idea why.
The first machine was W7, the recent one W10.

**Comment by txr13** [comment]
I haven't tried this on another machine, but I will confirm that I do have write access to the entire folder tree (and therefore MPM does as well), and I am experiencing this issue on W7.

**Comment by fonyo** [comment]
So we are kind of narrowed it down to issues with Win7. @aaronsace can you help confirm? I don't have a Win7 rig anymore :(

**Comment by a6848418** [comment]
Having an exact same issue on Win7. No .json files get generated in \Bin\Excavator\. No excavator mining therefore. looking forward to fixing the issue

**Comment by aaronsace** [comment]
aee83cc2852343be3d8e159f4dcd5f5380aafb08
