### ISSUE TITLE
Check if DNS is able to resolve before executing miner

### ISSUE THREAD

**Issue by n3cr0cr0w** [aaronsace/MultiPoolMiner#57]
US and Europe URLs are not working for some coins. Could you add a DNS lookup before executing the miner to have it skip that miner setup. There maybe more URLs that don't work, I didn't have time to check them all.

http://europe.feathercoin.miningpoolhub.com/
http://europe.ethash-hub.miningpoolhub.com/
http://europe.digibyte-groestl.miningpoolhub.com/
http://europe.gamecredits.miningpoolhub.com/
http://europe.maxcoin.miningpoolhub.com/
http://europe.groestlcoin.miningpoolhub.com/
http://europe.vcash.miningpoolhub.com/
http://europe.maxcoin.miningpoolhub.com/
http://europe.digibyte-skein.miningpoolhub.com/

**Comment by aaronsace** [comment]
They are read from MiningPoolHub's API. Are you sure they don't work? Maybe the Europe server is down?

**Comment by aaronsace** [comment]
Not really sure on how the servers work. I will check if they work when I get home. Maybe report it on the MiningPoolHub forum?

**Comment by n3cr0cr0w** [comment]
Sounds like a good idea, but I didn't find that, where is it?

**Comment by aaronsace** [comment]
The forum? 
https://bitcointalk.org/index.php?topic=472510.0

**Comment by n3cr0cr0w** [comment]
No response from anyone on the forums. Hope it isn't just me that is having trouble.

**Comment by snakethejake81** [comment]
I'm having the same issue with feathercoin, neither the Europe or us servers resolve in DNS so it leaves my miner just hung since feathercoin was the most profitable.

![image](https://cloud.githubusercontent.com/assets/12677849/22597076/0328accc-e9e3-11e6-861b-9671f8d04f1a.png)

**Comment by aaronsace** [comment]
Sorry, I haven't had time to do anything at the moment. Gonna be very busy for the next couple of the weeks. 

MiningPoolHub needs to remove them from the API if they no longer work. I recommend manually editing the pool address to hub.miningpoolhub.com for now.
