### ISSUE TITLE
multipoolminer.ps1 not found, and virus flags from windows

### ISSUE THREAD

**Issue by sangdrax8** [aaronsace/MultiPoolMiner#571]
I am new and was trying to get this to run.  My first problem appears to be the the start.bat example file (from the current stable) has &.\multipoolminer.ps1  My machine fails to find that, so I moved the folder with all the files to the C: and and put it in a folder C:\mpm, then edited the script to run it from there.  That works, but it seems people are indicating you should just be able to add a few variables and start it.  So it feels like I am doing something wrong there?

Once I do get it started, I have windows 10 constantly marking and removing "virus" files, which appear to be the miners that are being downloaded to the windows/system32/bin folder.  I see there is a miners folder in the zip, but apparently it is still downloading these as well?  I eventually end up getting an "WARNING: No miners available" and it appears to re-download the miners. to system32 folder again.  Is there something I need to be doing different to tell it to download to and run miners from the miners folder provided by the zip?

**Comment by aaronsace** [comment]
Extract it onto your desktop then click 'start.bat'. Don't move anything out of the folder. 

https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip
