### ISSUE TITLE
Detect incompatible GPU

### ISSUE THREAD

**Issue by Vxrl** [aaronsace/MultiPoolMiner#572]
![https://i.imgur.com/8unYsjA.png](https://i.imgur.com/8unYsjA.png)

According to https://www.reddit.com/r/gpumining/comments/78jikk/no_kernel_image_is_available_for_execution_on_the/, I'm getting this error message because ccminer is too new to support my GTX 680.

Is it possible for MultiPoolMiner to detect this and respond by either downgrading ccminer or by disabling CcminerLyra2z-Lyra2z?

**Comment by fonyo** [comment]
Are you specifically looking to mine Lyra2z coins?

**Comment by Vxrl** [comment]
No. Disabling lyra2z fixes this, but I fear that I would miss out on other miners that use that algorithm.

**Comment by fonyo** [comment]
You won't be missing out on much as the Lyra2z algo has not been profitable for months, did not even get close to top 3 for ages.

**Comment by Vxrl** [comment]
Fortunately it's possible to remove miners from the Miners folder, so this is no longer a problem for me.

Why do you say this is out of scope? Couldn't MultiPoolMiner use ccminer's API or simply read its standard output to detect this issue and automatically disable this miner?

**Comment by aaronsace** [comment]
It's reporting a speed. If this issue is during the benchmark then it's impossible to detect. The developer of the miner should throw an error and have no 0 hashrate or close.

**Comment by fonyo** [comment]
Oh so you meant to exclude that miner? It does that automatically if the miner fails or not working properly. My understanding was based on the above, to include more miners (as in previous versions of specific miners). That is why I said it was out of scope. Benchmarking can already take too long which would become even worse by including miners that will not contribute much to better MPM.

**Comment by aaronsace** [comment]
GPU detection beyond scope at the moment. 

The developer of that miner should fix the error handling and not report a spoof hash rate.
