### ISSUE TITLE
errors with xmr and prospector

### ISSUE THREAD

**Issue by drewcoins** [aaronsace/MultiPoolMiner#573]
Hi, new guy here coming over from the NH fiasco... this is my second day running the MPM with multipoolhub.

Seems to work well, until it trys to run prospector or xmr . Prospector works for about 3 or 4 shares excepted and then errors out and keeps repeated 0 shares and 0mh/s. Also it has very high cpu lag and causes whole system to be very slow.

I get about the same scenario with xmr.

Everything else works good as far as I can tell. My rig is 1gtx1080ti, 2gtx 1070. windows10. ram16gb, virtualram 16gb.

What should I do ? thanks!

**Comment by fonyo** [comment]
Post your start batch file please. And a log file of when the issue happened.

**Comment by drewcoins** [comment]
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -wallet 1AnXHpacei1zn6YNtuYx7SaNdWWyzH2Dse -username ApolloSpeed -workername hubwire -region us -currency btc,usd -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool -algorithm cryptonight,decred,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,sia,siaclaymore,sib -donate 5 -watchdog"

**Comment by drewcoins** [comment]
[2017-12-07_10-38-53.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540206/2017-12-07_10-38-53.txt)
[2017-12-07_11-07-06.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540207/2017-12-07_11-07-06.txt)
[2017-12-07_11-25-43.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540208/2017-12-07_11-25-43.txt)

**Comment by fonyo** [comment]
Not sure, maybe @aaronsace can help.

**Comment by aaronsace** [comment]
As far as I can tell, MultiPoolMiner is working fine. If there are any miners that are not working very well on your system then you are safe to delete them from the folder called 'miners'.

**Comment by aaronsace** [comment]
@drewcoins You haven't downloaded Excavator though: https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by drewcoins** [comment]
so download that, and put in the main MPM folder ? and then delete the three xmrig .txt files ?

**Comment by aaronsace** [comment]
Files should go in 'Bin\Excavator\'.

**Comment by UselessGuru** [comment]
@drewcoins: Are you overclocking?

Especially high memory OC might cause this. 
Note: some algos are more prone to crashes than other with high mem OC. For me a good test is DSTM. High mem OC causes the DAGbuild to fail.
