### ISSUE TITLE
vertminer support?

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#574]
https://github.com/vertcoin/vertminer-nvidia

Anyone tried it? Could you add support for it?

**Comment by fonyo** [comment]
Same miner as the one used in OCM for Vertcoin. There are better and more stable miners already  included with MPM with no fees. That version has 2% fee.

**Comment by fonyo** [comment]
Don't worry, it is on my watch list. If it ever gets better, It may be included in the future.

**Comment by winnal** [comment]
No worries I just tested it palgins still best.

**Comment by fonyo** [comment]
Excavator is even better, matey, try that one.
