### ISSUE TITLE
Mining vtc with excavator on miningpoolhub

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#575]
Anyone show me how to set that up? I could never get it to connect properly whenever I mined with it I got 0 mhs. I saw someone else with a similar issue I think but I can’t find that post anymore.

**Comment by fonyo** [comment]
It's working for me and like a charm. Miningpoolhub is having issues again showing hashrate for some users. Fine at my end.

**Comment by fonyo** [comment]
Excavator got much better in the last couple of months.

**Comment by winnal** [comment]
It’s not on the miningpoolhub dash. I mean on the excavator console itself it’ll say 0mhs. I’ll give it another shot today and see what I can figure out.

**Comment by winnal** [comment]
Yes, I know I’ve been using them exclusively on nicehash until they got hacked.

**Comment by fonyo** [comment]
Are you using v1.3.8 alpha?

**Comment by winnal** [comment]
I haven’t been using it to mine on miningpoolhub for months now since I was using the nicehash miner, I’ll give it a shot with the new updated version today.

**Comment by fonyo** [comment]
https://github.com/nicehash/excavator/releases

**Comment by winnal** [comment]
What does your command file look like?
MiningPoolHubCoins_Lyra2RE2_3_Nvidia.json

**Comment by fonyo** [comment]
Why do you need that? It would be the same as yours, I haven't touched anything with 2.7, I am running MPM-vanilla. I haven't even had time to update MPMPlugins yet.

**Comment by winnal** [comment]
That's the issue with my miner/computer, it doesn't seem to create the file on its own. When I run excavator I get
[13:01:17][0x000000cc][error] core | Failed to open command file: MiningPoolHubC
oins_Lyra2RE2_3_Nvidia.json

**Comment by fonyo** [comment]
[MiningPoolHubCoins_Lyra2RE2_3_Nvidia.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540591/MiningPoolHubCoins_Lyra2RE2_3_Nvidia.txt)

**Comment by fonyo** [comment]
I logged on to the rig to send it to you. 6x1070 (maybe 5x1070 as one of the risers is misbehaving on that rig and the new one hasn't arrived yet)

**Comment by winnal** [comment]
And what do you put for the IP param? us-east.hub.miningpoolhub.com:20507 without the 'stratum+tcp://'?

**Comment by fonyo** [comment]
I don't do any of that, MPM handles the region and selection. Europe BTW.

**Comment by fonyo** [comment]
I know MPH does not need the stratum stuff specified, you can go without it...

**Comment by fonyo** [comment]
Also try 17018

**Comment by winnal** [comment]
So I'm using this command file
[
    {
        "time":  0,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.add",
                             "params":  [
                                            "lyra2rev2",
											"us-east.hub.miningpoolhub.com:20507",
											"winnal.multipoolminer"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "0"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "1"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "2"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "3"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "4"
                                        ]
                         }
                     ]
    },
    {
        "time":  3,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         },
                         {
                             "id":  1,
                             "method":  "worker.add",
                             "params":  [
                                            "0",
                                            "5"
                                        ]
                         }
                     ]
    },
    {
        "time":  10,
        "loop":  10,
        "commands":  [
                         {
                             "id":  1,
                             "method":  "algorithm.print.speeds",
                             "params":  [
                                            "0"
                                        ]
                         }
                     ]
    }
]
and I just get
[13:17:37][0x00001eb4][info] core | Algorithm 'lyra2rev2' total speed: 0.000000
H/s

**Comment by winnal** [comment]
And in the end I get 211-212 MHs with palgin and 213-214 with excavator anyway so it’s not a huge difference.

**Comment by winnal** [comment]
Excavator is just great at mining many algos now including neoscrypt but I just can’t get it to work with miningpoolhub for whatever reason.

Perhaps I should try MPM vanilla as well?

**Comment by fonyo** [comment]
Sorry, this doesn't make sense to me at all. The config you sent (and I sent), you said it is showing 0 hashrate. I thought that was excavator lyra2rev2.

Then you mentioned you are getting 213-214 with excavator lyra2rev2...

So what is going on here? Can you please clarify?

**Comment by winnal** [comment]
I was getting 213-214 when I was using nicehash miner mining on nicehash. Now I get 211-212 with palgin mining on miningpoolhub.

**Comment by fonyo** [comment]
Oh OK, that makes sense now. :)
Honestly, I don't know but there is another thread revolving around this issue: #569. I am closing this but please join us there so we can get to the bottom of this, and quickly. Cheers.
