### ISSUE TITLE
Lyra2rev2 and equihash algos crash the system to reboot

### ISSUE THREAD

**Issue by lirik666** [aaronsace/MultiPoolMiner#577]
Hi aaronsace, 
Many thanks for your time and work.

I have started to use your software recently, great thing but came across with one big problem. During the benchmarking the pc was suddenly crashing and rebooting. After a few tests i found that crash happens only on Lyra2rev2 and Equihash benchmark. These algos are profitable indeed, thus may be any clues how can I resolve the issue?

I am using 1080 and 1080Ti for my rig. Also, had no any technical problems with mining solo Zcash on EWBF miner in the past.

**Comment by fonyo** [comment]
Can you please post logs?

**Comment by lirik666** [comment]
[2017-12-07_21-39-28.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540723/2017-12-07_21-39-28.txt)
[2017-12-07_21-35-00.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540724/2017-12-07_21-35-00.txt)

**Comment by fonyo** [comment]
I've had trouble with the palgin fork before. Please try to exclude it (README has instructions in the FAQ section on how to remove config files thus excluding miners completely). You could use excavator for both equihash and lyra2rev2 mining. Please follow instructions in the README on how to download and install it. It's very simple to do so.

https://github.com/aaronsace/MultiPoolMiner/blob/master/README.md
