### ISSUE TITLE
Trouble starting miner (and benchmarking)

### ISSUE THREAD

**Issue by huangyihe** [aaronsace/MultiPoolMiner#579]
I just recently switched to MultiPoolMiner (well, because of NiceHash...) and I keep having this problem: basically in the log it keeps saying that it fails to remove a job. At first it appears not to cause any problems, but eventually the script starts to go wild... Here is the log file

[2017-12-07_15-48-18.txt](https://github.com/aaronsace/MultiPoolMiner/files/1540558/2017-12-07_15-48-18.txt)

I have Windows 10 and I have both NVIDIA and AMD cards on my system. Not sure if it's gonna be an issue. The following are the commands used to run the miner:

```text
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username huangyihe -workername miner1 -region usa -currency usd -type AMD,NVIDIA -poolname miningpoolhub,miningpoolhubcoins -algorithm cryptonight,ethash,equihash,lbry,lyra2z,lyra2re2,groestl -donate 5 -watchdog"
```

**Comment by jayntguru** [comment]
Similar problem here (I think). Windows 10. Amd only. Similar errors. except I don't get timeouts.

Benchmarked OK. Gives this error and is flipping coins back and forth.

[2017-12-09_02-46-10.txt](https://github.com/aaronsace/MultiPoolMiner/files/1544485/2017-12-09_02-46-10.txt)

**Comment by aaronsace** [comment]
Remove-Job bug won't cause any problems and has been fixed on the latest master branch.
