### ISSUE TITLE
Need help with a couple errors.

### ISSUE THREAD

**Issue by raked** [aaronsace/MultiPoolMiner#58]
I downloaded your program, ran the multipoolminer powershell file, entered my username, and it started. Unfortunately, I was faced with a problem I'm not sure how to fix. For cgminer, I keep getting "Error -11: Building Program (clBuildProgram)" when it attempts to start a benchmark with the rest of the programs. The rest of the programs give me the error "Stratum extranonce answer id was not correct!" and does not continue. I'm running windows 10 with a GTX 1080. I'd love to use your program, so if you could help me, I would love some assistance!
Log file:
[2017-02-16_10-12-50.txt](https://github.com/aaronsace/MultiPoolMiner/files/782205/2017-02-16_10-12-50.txt)

**Comment by aaronsace** [comment]
Please let the benchmark run through to completion. Any miners or algorithms that do not work on your system will be detected.

**Comment by raked** [comment]
Okay now that's its run through all the errors and stuff it works well, thanks.
