### ISSUE TITLE
Cryptonight - XMRIG  AMD  Miner speed poor

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#580]
Hello Aaron, 

Please have a look at my hashrate with XMRIG AMD:

![image](https://user-images.githubusercontent.com/25494601/33738960-e7c43600-dba3-11e7-8c75-2de7179de868.png)

I am getting a lazy hash rate and i have noticed this on the new version of Claymore Cryptonote miner version 10.2

If SGMiner OR Cryptonote 9.7 miner  is used then the hash rate is good and ALL GPUs get about 633  hashes a second , in total about 19xx odd hashes/second for Crypto.

What can I do to enforce using NsGPUMiner for Claymore or SGMiner ?

I have tried to look at the ps1 files and txt files in the miners folder but it is a little more complicated than i thought.
Thanks

**Comment by station384** [comment]
Not sure if this will help you,  but with xmrig, I've noticed it picks some dumb threading options at times.   AMD seems to like 2 threads.  so this is my solution.

edit file Bin\CryptoNight-AMD\config.json.   set the threading options to what you want.  in my case I have an old pitcairn I run this on, so I changed the threading options to
{
            "index": 0,
            "intensity": 480,
            "worksize": 8,
            "affine_to_cpu": false
        },
		        {
            "index": 0,
            "intensity": 480,
            "worksize": 8,
            "affine_to_cpu": false
        }

then I modified the file Miners\XmrigAmd.txt
I added the command option -c config.json to the end of the command line template.

this works because any options passed in on the command line take precedent over the options in the config file,  but you cannot pass threading options on the command line, so this hybrid solution.   

This is kinda a munged together work around.   

The fix would be to generate the config file, and have to options as configurable parameters set my MultiMinerPool.  But I'm still looking thru the code and havn't decided yet if I want to write a patch yet.

**Comment by station384** [comment]
Oh and to get rid of XMRIG completely would be to add junk to  the launching command line,   so it errors when launching.   It looks like after 3 tries MPM will mark it as bad and move onto the next most profitable miner.  I would also delete the associated hash stats file from the stats directory.   MPM will try and test the has rate again,  it will fail and remove it from rotation.

**Comment by aaronsace** [comment]
It's fully customizable; you can even add older miner versions. 

The solution that @station384 provided sounds like it would work. 

Best reporting incorrect defaults to the respective miner developers.

**Comment by carlo0000** [comment]
hello
can you explain a bit more
i had this in my old config file for xmr-stak-amd
 but it doesn't work in CryptoNight-FireIce  need to make a new config file

and what exactly need to change in the worker file FireiceAmd.ps1

"gpu_thread_num" : 10,

/*
 * GPU configuration. You should play around with intensity and worksize as the fastest settings will vary.
 *      index    - GPU index number usually starts from 0
 *  intensity    - Number of parallel GPU threads (nothing to do with CPU threads)
 *   worksize    - Number of local GPU threads (nothing to do with CPU threads)
 * affine_to_cpu - This will affine the thread to a CPU. This can make a GPU miner play along nicer with a CPU miner.
 */
"gpu_threads_conf" : [
    { "index" : 0, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 0, "intensity" : 900, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 1, "intensity" : 900, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 1, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 2, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 2, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 3, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 3, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 4, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },
    { "index" : 4, "intensity" : 912, "worksize" : 8, "affine_to_cpu" : false },

**Comment by imrecsoka** [comment]
I still need to have a look at this, because XMRIG AMD and the new CLAYMORE 10.2 dont perform properly for me, i am getting robbed of my speed.

**Comment by imrecsoka** [comment]
"Best reporting incorrect defaults to the respective miner developers." not sure the best place for this? how do you locate them?
Thanks for replying nevertheless. I  am looking forward to more future days with Miningpoolhub and Aaron and everybody;'s company.
I will have a look in readme files if there is contact details. I have tried forums before but then the threads get hijacked by an unrelated comment so you then lose your voice which is crap.

**Comment by carlo0000** [comment]
i notice with the new miner you need to run it first than it create an conf file what you can edit
and an aditional amd or nvidia file  and cpu

i testing it on my vega
