### ISSUE TITLE
0 MHs when mining on miningpoolhub with excavator

### ISSUE THREAD

**Issue by winnal** [aaronsace/MultiPoolMiner#581]
I've had this issue for months ever since I started using MPM and haven't been able to figure it out. I've settled with using palgin, but I'm being told it should work. I don't know what's wrong. I input the address either hub.miningpoolhub 17xxx or us-east.hub.miningpoolhub 20xxx and I always get a connection but get 0 MHs.

**Comment by aaronsace** [comment]
@winnal It has to be the IP address not the host name. 'miningpoolhub.com' is blocked be NiceHash.

**Comment by winnal** [comment]
Well, the .json file is not creating itself so I'm having to manually create it that's why. I had a feeling as well. What is the converted ip address?

**Comment by aaronsace** [comment]
What operating system are you using?

**Comment by winnal** [comment]
7

**Comment by aaronsace** [comment]
Windows 7 doesn't have "Resolve-DnsName". I'll push a fix.

**Comment by winnal** [comment]
I see. That makes sense now.

**Comment by AmINick** [comment]
How about a same situation in win 10?

**Comment by aaronsace** [comment]
aee83cc2852343be3d8e159f4dcd5f5380aafb08
