### ISSUE TITLE
Request: please add TLS/SSL connection for Claymore-Equihash-AMD

### ISSUE THREAD

**Issue by lmlim** [aaronsace/MultiPoolMiner#582]
Hi Aaronsace,

current connection of claymore-equihash for AMD is non TLS/SSL which resulted to higher devfee of 2.5%.
i would like to request to use TLS/SSL connection so that devfee is 2%.

or is there a way to alter any config file for this? 

thanks.

**Comment by aaronsace** [comment]
Put "-ssl" in the bat file.

**Comment by fonyo** [comment]
I have noticed this has been removed from the sample batch files since 2.6.0.2. Is there any particular reason for this I should be aware?

**Comment by aaronsace** [comment]
Yes, not all the miners support ssl yet so you get 0.5% reduced fee for Claymore but less miners to chose from.
