### ISSUE TITLE
The pipeline has been stopped

### ISSUE THREAD

**Issue by feernandobraga** [aaronsace/MultiPoolMiner#583]
Hi, I've been mining since yesterday and everything looks fine to me.
However, sometimes the miner appears to crash (I'm not sure because all I can see is that it closes itself) and after that, the multipool miner restarts itself and opens another miner. When I go to the log, the reason for restarting is: "The pipeline has been stooped".
I'm not sure if it's the miner problem or what. At the moment I'm mining with lyra2rev2 with 4 gtx 1070 g1. 
Is there a way to check, or to see the message that the miner leaves before quitting itself?
I hope that I explained the issue quite well, but if you need more information I'm happy to give you the log file.
Thanks heaps and I have to say... What a nice tool you've built here.

**Comment by lee-aaron** [comment]
Well the log file should show if the miner had an error and crashed. Would be helpful to attach :)

**Comment by feernandobraga** [comment]
Thanks for getting back.
I've attached the log file from one of the times that the error appeared.
Also, I would like to ask you a question about how the multipool miner works.
So, I was mining with Lyra2REv2 at the hub.miningpoolhub.com
For the first time, it switched to the sib algorithm and was using the sib.mine.zpool.ca.
My question is: Do I have to create an account at the zpool so I can get paid, or the MultiPoolMiner
will credit my miningpoolhub account?
It's not clear to me how I should set up the miner for multi mining.

Thanks and if you need anything else in regards the error, please let me know.


[feernandobragalog.txt](https://github.com/aaronsace/MultiPoolMiner/files/1541791/feernandobragalog.txt)

**Comment by lee-aaron** [comment]
Regarding your question, you don't have to create an account. You just need to supply your bitcoin wallet address and when you meet the minimum amount to withdraw on zpool, it will automatically deposit the equivalent BTC in your wallet. The other contributors can correct me if I'm wrong but I'm pretty sure this is how it works. Your log also displays some Job errors. I'm not sure if they have been solved already or not but I'll leave this issue open for now.

**Comment by feernandobraga** [comment]
Thank you for answering my question.
In regards the job errors, they still there. But I have no idea on how to fix it.

**Comment by aaronsace** [comment]
@feernandobraga The job errors were a mistake in the release; don't worry about them.

**Comment by feernandobraga** [comment]
Thank you @aaronsace. Also, a weird thing just happened with the MPM. I went to sleep yesterday and it was dual mining Ethereum and something else. I woke up and it was still mining the same thing. I thought that would be strange because usually, it's not the most profitable algo for me (at least not enough to keep running for more than 8 hours).
So I've checked the MPM and it was frozen. Not like a non-responding windows program, but it wasn't updating every 60 seconds. So I pressed enter twice and I got a message saying: "Prices are out of sync" and a few seconds later it started the auto-refresh thing again.

**Comment by aaronsace** [comment]
I think you are describing a feature in the operating system. If you click on the window then it pauses.

**Comment by feernandobraga** [comment]
hahaha... you were right. Just tested it.
In regards the pipeline being stopped. Any idea on how to fix that?

**Comment by aaronsace** [comment]
Not sure TBH, there is probably some way to change it...
