### ISSUE TITLE
Profitability

### ISSUE THREAD

**Issue by dekkyy1111** [aaronsace/MultiPoolMiner#586]
Is that profitability for day, week or month?
And which profitability should i watch? The 11eur or 5eur?

Miner          Pool               Algorithm Watchdog Timer
-----          ----               --------- --------------
CcminerNanashi Zpool              NeoScrypt      1 Seconds
ClaymoreAmd    MiningPoolHubCoins Equihash      63 Seconds

MultiPoolMiner is between 87% and 150% more profitable than the fastest miner:

Miner                                            BTC                             EUR
-----                                            ---                             ---
MultiPoolMiner                                   0.00087 ±55 % (0.00056-0.00134) 11.56019 ±55 % (7.46589-17.89981)
{CcminerNanashi-NeoScrypt, ClaymoreAmd-Equihash} 0.00040 ±8 % (0.00037-0.00043)  5.29957 ±8 % (4.90227-5.72906)

**Comment by Vxrl** [comment]
That is the profitability per day.

See Q5 on https://github.com/aaronsace/MultiPoolMiner.

> Q5. MultiPoolMiner is XX% more profitable. What does this mean?
>
> A5. It is showing you the stat for MultiPoolMiner vs the one miner. It means that the calculated earnings of MultiPoolMiner switching to different algorithms would be that much more profitable than if it had just mined that one particular algorithm the whole time. The number is still only an estimate of your earnings on the pool and may not directly reflect what you actually get paid. On MiningPoolHub and other multiple algorithm pools, coins have fluctuating values and MultiPoolMiner switches to the one that is the most profitable at that time. Because each pool has different delays in exchange and payout, the amount you actually earn my be very different. If there is a significant difference in percentage, you might want to reset the profitability stats by running the ResetProfit.bat file. Your actual (but still estimated) earning is shown in the second row.
