### ISSUE TITLE
Profit comparison isn't displayed when $Downloader.State is "Running"

### ISSUE THREAD

**Issue by Vxrl** [aaronsace/MultiPoolMiner#588]
Over half of the time, when MultiPoolMiner is at the part in its loop where it should print out the profit comparison, the script doesn't because `$Downloader.State` is `"Running"`.

This happened so often that I had to remove the `-and $Downloader.State -ne "Running"` check from the `if` statement (around line 479 of MultiPoolMiner.ps1). I edited the code slightly so that I get a message instead when `$Downloader.State` is still `"Running"` at this point in the loop. The profit comparison prints without issue. Here is a screenshot of what it looks like:

![https://i.imgur.com/U1urIrq.png](https://i.imgur.com/U1urIrq.png)

This is only an issue on this Windows 7 computer. I assume this happens because the computer is slower than my other computer, and the Job started around line 228
`if ($Downloader.State -ne "Running") {
        $Downloader = Start-Job -InitializationScript ([scriptblock]::Create("Set-Location('$(Get-Location)')")) -ArgumentList ($AllMiners | Select-Object URI, Path, @{name = "Searchable"; expression = {$Miner = $_; ($AllMiners | Where-Object {(Split-Path $_.Path -Leaf) -eq (Split-Path $Miner.Path -Leaf) -and $_.URI -ne $Miner.URI}).Count -eq 0}} -Unique) -FilePath .\Downloader.ps1
    }`
isn't finished by the time it's time to print the profit comparison.

I don't understand why a running `$Downloader` Job should prevent the script from printing the profit comparison. Perhaps that check should be removed from the official code?

**Comment by mic4rd** [comment]
Same issue here (Windows 10), thanks for posting this. I also removed the `-and $Downloader.State -ne "Running"` check in line 479 and now correctly shows the Profitability :)

**Comment by aaronsace** [comment]
You don't want it to start displaying and recording profits whilst half the miners a missing. 

The downloader shouldn't be running; you are most likely missing miner binaries and it's searching for them.

**Comment by Vxrl** [comment]
@aaronsace My computer has been running MultiPoolMiner for days, and the downloader is still always running. Disabling the check is the only way to see the profits. If there are missing binaries, the script is failing to download them, yet the script has no problems mining. So there must be a flaw in the script. If there is more information I can provide to help identify and fix the flaw, let me know.

**Comment by aaronsace** [comment]
Does it say that it's trying to download something when you open it? 

Excavator is a common one that people forget to download. Also, JayDDee's CPU can get deleted.

**Comment by Vxrl** [comment]
@aaronsace There is no message that indicates that the script is downloading anything. The only way I even determined that that was the problem is by debugging the source code.

How can I see what it's trying to download?

When I run `Write-Host ($Downloader | Format-Table | Out-String)` before it prints the profit comparison, I get this message:
![https://i.imgur.com/QeDJPYs.png](https://i.imgur.com/QeDJPYs.png)

**Comment by aaronsace** [comment]
It should output a progress bar and/or error when running 'Receive-Job $Downloader'. 

Maybe check the source of the problem '$Downloader = Start-Job' as an empty array should be sent to it which would take no time then complete.

**Comment by mic4rd** [comment]
Using the debug suggested by Vxrl i also get this regularly:
![image](https://user-images.githubusercontent.com/13984586/33828612-189494f2-de6d-11e7-850a-0cbd9ea84992.png)
I downloaded Excavator and it's being used correctly. Also Jayddee CPU miners are all there and being used.

**Comment by aaronsace** [comment]
Try the new release: https://github.com/aaronsace/MultiPoolMiner/releases
