### ISSUE TITLE
OpenCL Error

### ISSUE THREAD

**Issue by Atlx** [aaronsace/MultiPoolMiner#589]
Fresh download 2.7.0.2, unzipped, installed Cuda package, nvidia drivers, https://www.microsoft.com/en-us/download/details.aspx?id=50395, https://www.microsoft.com/en-gb/download/details.aspx?id=40784, https://www.microsoft.com/en-us/download/details.aspx?id=48145. Ran from elevated command prompt. Right click run-as admin, same thing. Attempted to run start.bat with my parameters, same error. Attempted to run start.bat as provided with same result. "Unblocked" all files via powershell gci -Recurse | unblock-file. 

![capture](https://user-images.githubusercontent.com/34379033/33776393-3e108520-dc0f-11e7-82b8-e62888536075.JPG)

**Comment by Vxrl** [comment]
According to https://msdn.microsoft.com/en-us/library/dn261466(v=vs.110).aspx, the Marshal.SizeOf<T> method is only supported in .NET Framework version 4.5.1 and up. This suggests that you need to install an updated version of the .NET Framework.

[Microsoft .NET Framework 4.5.1 (Web Installer)](https://www.microsoft.com/en-us/download/details.aspx?id=40773)

**Comment by Atlx** [comment]
That definitely was it. I appreciate it!

**Comment by aaronsace** [comment]
@Vxrl Thank you! I'll update the prerequisites.

**Comment by Vxrl** [comment]
@aaronsace You might want to link to the newest version of the .NET Framework in the documentation:
https://www.microsoft.com/net/download/windows

**Comment by fonyo** [comment]
Will add it as soon as I can.

**Comment by fonyo** [comment]
added
