### ISSUE TITLE
Suitable driver for Windows 7 x64 using MultipoolMiner

### ISSUE THREAD

**Issue by newmzy** [aaronsace/MultiPoolMiner#59]
I have a couple of rigs which have mostly AMD R9 290s on them, also a 390 and 2 380s.

I have used Ethos (linux mining distro based on Ubuntu)  on both of them to mine ethereum until difficulty and high electricity cost made me swap them to Win7 x64 so I could use Claymore to mine ZEC and then XMR as the ZEC price dropped and dropped.

Claymore has always recommended using the v15.12 AMD drivers with R9 cards for stability with his software. 

I use Miningpoolhub.com quite a bit - for their monero pool and also because I also have a Baikal ASIC which has a great auto-switching hub on miningpoolhub. That is where I heard about Multipoolminer.

Anyway - In the past I have tried to use various miners including different versions of sgminer, sgminer-gm, etc and on my machines they never seem to work very well.  This seems to include when I try to run MultipoolMiner: whenever it tries to run sgminer it seems to just hang and get nowhere.

I suspect that it's the old drivers (15.12) so I was wondering which drivers would you recommend for using MultipoolMiner in Win7 x64? I did the upgrades you recemmonded to the newer powershell, etc. I wish I had upgraded them to Win10 when I had the chance but at that point I was still using Ethos.

**Comment by lyolyalya** [comment]
multipoolminer is an utility to grab all miners together, benchmark them, choose most profitable coin and mine it.it uses miners on your decision.so if you want stability - you need to reorganize your miners.and if nedeed - replace multipoolminer default miners with yours.

**Comment by newmzy** [comment]
OK, that's interesting - but my main question was about which driver to use? You guys who build this obviously use it - which AMD drivers do you use in Windows when you test it? In which OS? I would be willing to build a linux rig if MultipollMiner is more stable in linux.

**Comment by lyolyalya** [comment]
aw...i use nvidia.have no problems at all.sorry.nothing to say about amd drivers.years ago was dissapointed by amd gpu and drivers so not even dream about them=)
aaand again - use same miner and same driver which give you most stable system on a certain algo.multipoolminer can't resolve problems of  miners or os, or driver unstability. if you are mining for a while you must know that parameters for yourself.

**Comment by aaronsace** [comment]
It works with AMD 290 and 480 on windows 10. I believe it's working fine on windows 7 as well for other people. Just get the latest drivers; it will only use the miners that work. 

If you are having issues with the miners that come with it then I recommend swapping out the bin files for ones that work on your system.
