### ISSUE TITLE
ccminer-Palgin report "the launch timed out and was terminated" 

### ISSUE THREAD

**Issue by AmINick** [aaronsace/MultiPoolMiner#590]
Hi,
while excavator fails to report hashrate/shares consistently, my ccminer-palgin ran into issues where it reports "the launch timed out and was terminated" after running for a certain period of time (20min to 1 hour). Is this issue experienced by anyone else in the community?

Running on Windows, 6*EVGA 1070, Latest driver, Latest release Multipoolminer, on MPH 
no OC, 100% power

**Comment by fonyo** [comment]
That seems to be a 1070 specific issue with ccminer forks such of palgin and turekaj (vertminer). I have never seen that issue coming up on a 1080 rig. Use excavator with a 1070 rig when mining lyra2rev2, it is also the fastest for these rigs.
