### ISSUE TITLE
libcurl.dll missing nvidia win10

### ISSUE THREAD

**Issue by Dminch1** [aaronsace/MultiPoolMiner#592]
cant seem to make it past the benchmarks keeps crashing my rigs

**Comment by aaronsace** [comment]
MultiPoolMiner itself can't crash your rigs but if you have hardware/driver issues then the various miners it launches could push your system to fail. 

Not sure what libcurl.dll is; not part of MultiPoolMiner. 

Couple of things to check: 
reset clock/voltage settings, set power limit and increase fan speed. 
check what miner is crashing your system then delete it from the folder called 'miners'. 

Maybe post your command-line and log(s) if your are still having problems.

**Comment by Dminch1** [comment]
aaronsace thank you for your timely response

i will post shortyl

**Comment by JimJamUrCode** [comment]
I was getting this same error. It appears that Ethash-Claymore uses libcurl.dll. I was able to find this file and place it in the correct folder /Bin/Ethhash-claymore and the error stopped happening.

**Comment by robl45** [comment]
I was having a number of these issues with missing files and miners not working including the one you had.  What I did with most of them is just find the miner online, download it and put it in the bin file.  It appears that multipool miner at least on my system wasn't putting in all the files.

**Comment by aaronsace** [comment]
Those miners are manually included in the release. You probably downloaded the source code by mistake. 

https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip

**Comment by robl45** [comment]
No, a few of them just had the miner .exe instead of the accompanying files with it.  updating the miner from the web in the bin allowed them to work correctly.  Maybe just a flaw in my system.
