### ISSUE TITLE
Disabling and enabling again excavator miner

### ISSUE THREAD

**Issue by Atexor** [aaronsace/MultiPoolMiner#593]
I'm mining one crypto with one miner. I noticed that sometimes MultiPoolMiner disables excavator miner, then run it again and mine the same crypto (MonaCoin).

Logs:
1. https://pastebin.com/LggC29wW
2. https://pastebin.com/AaXt8DBV

**Comment by aaronsace** [comment]
At no point during those logs does the miner restart.

**Comment by Atexor** [comment]
Maybe it's not visible because MultiPoolMiner run the same miner again, not other. Or it's incompatibilities with excavator. Currently I'm using only one fork of ccminer and it doesn't happen.

**Comment by aaronsace** [comment]
When MultiPoolMiner launches a miner then it increments the activated counter: 
https://github.com/aaronsace/MultiPoolMiner/blob/0adb6e926ebf9a395d980e84c09773dca123840b/MultiPoolMiner.ps1#L445

If you have problems in future, post the logs again. I'll try and get to it quicker than 11 days next time.
