### ISSUE TITLE
Add Miner XMR-stak

### ISSUE THREAD

**Issue by laradji** [aaronsace/MultiPoolMiner#595]
Hi,

Can you add XMR-stak miner for AMD.

https://github.com/fireice-uk/xmr-stak

Tks

**Comment by aaronsace** [comment]
It's there...?

https://github.com/aaronsace/MultiPoolMiner/blob/master/Miners/XmrigAmd.txt

**Comment by laradji** [comment]
oh ok, the name confused me.
