### ISSUE TITLE
Incorrect config file name generated

### ISSUE THREAD

**Issue by station384** [aaronsace/MultiPoolMiner#596]
The configuration file name that is generated for excavator is different that what is called when executing excavator.

fine name requested to load when executing 
Bin\Excavator\excavator.exe -p 23456 -c Zpool_Lbry_2_Nvidia.json -na

config file name generated is
AHashPool_Lbry_2_Nvidia.json

This is on the master branch.

**Comment by fonyo** [comment]
Yes, this has been mentioned a few times before by other users but the above describes the issue the best. Please bear in mind the master can contain experimental code.

Thanks for the detailed report regardless!

**Comment by aaronsace** [comment]
aee83cc2852343be3d8e159f4dcd5f5380aafb08
