### ISSUE TITLE
Get an error "Null Value" in MultiPoolMiner.ps1

### ISSUE THREAD

**Issue by DragonStream** [aaronsace/MultiPoolMiner#60]
Hi guys,

Here you are a screenshot:
![multipoolmining_errorpath](https://cloud.githubusercontent.com/assets/21113644/23750784/757781f6-04c6-11e7-9891-384e783bccd7.jpg)

I'm on Win10 last version, Nvidia graphic card. 

Thank you in advance for your Help.

**Comment by aaronsace** [comment]
The link isn't working; can you upload to github?

**Comment by DragonStream** [comment]
It's work when you copy the link into a new window...I dont know how to send it on github...I'm really noob on github :)

**Comment by DragonStream** [comment]
Ok I have fixed the problem but I dont know how, I just downloaded again the package and erase the bin rep content. But I got a warning from my anti-viral software (eset-nod32) on the zip packed file. He tell me what it's infected by [http://www.virusradar.com/en/Win64_CoinMiner.BB/description](url)
I have forced the extract and scan the all rep but not found any virus....Perhaps the first time the extract goes wrong ?

**Comment by aaronsace** [comment]
Add the whole folder to antivirus exceptions list. Miners all over the web get flagged; the ones I'm using are definitely safe.
