### ISSUE TITLE
Can more info be provided on watchdog?

### ISSUE THREAD

**Issue by ThomasSRL** [aaronsace/MultiPoolMiner#600]
Example usage, value in min/sec/hr?
Will failed miners get relaunched?

**Comment by nostrakhan** [comment]
I'm also curious about this.  Is there a default time for the miners to get attempted for a relaunch?  If so, is this setting configurable?

**Comment by aaronsace** [comment]
The whole miner works on a unified interval that is defaulted to 60 seconds. Watchdog timers expire if three of those intervals pass without being kicked. 

There are three stages as to what action is taken when watchdog timers expire and is determined by the number of number of related expired timers. 
Stage 1: when 1 timer expires relating to one miner/algorithm combo, the one miner/algorithm combo is kicked
Stage 2: when 2 timers expire relating to one miner file, the one miner file is kicked
Stage 3: when 3 timers expire relating to one pool, the pool is kicked

Watchdog timers resets after three times the number of seconds that it takes to get to stage 3.

**Comment by fonyo** [comment]
added
