### ISSUE TITLE
Tuning tolerance

### ISSUE THREAD

**Issue by Golempl** [aaronsace/MultiPoolMiner#601]
How to increase tolerance limit ?
Sometimes GPU throttle clocks because of temperatures etc. 
This affect hashing speed, somtimes like 20-30% 
example:
CcminerPalgin       Skein                               284,72 MH/s

i had 340MH/s on cold start and it was outside tolerance. How to setup tolerance range to like 30% ?

**Comment by fonyo** [comment]
That solely depends on your GPUs and not MPM. You can set the "tolerance" with MSI Afterburner.

**Comment by grantemsley** [comment]
I think he means the tolerance of where it updates the stats.  If the new value differs too much from the old one, it doesn't update stats.

In Include.psm1 function Set-Stat:

` if ($Value -lt $ToleranceMin -or $Value -gt $ToleranceMax) {
            Write-Warning "Stat file ($Name) was not updated because the value ($([Decimal]$Value)) is outside fault tolerance. "
        }
`

**Comment by fonyo** [comment]
@grantemsley yes, makes more sense now, thanks for the clarification.
Not sure why it differs so much. You could reset stats by deleting the respective stat file so benchmark is redone and you are good to go.

@aaronsace, for your consideration as a feedback/test-case.

**Comment by Golempl** [comment]
Removing stat file don't helps, becase different algoritms got different heat and sometimes it cause some performance increase/decrease, it causes sometimes problem with tolerance.

**Comment by aaronsace** [comment]
@Golempl Is this actually causing any issues?

**Comment by Golempl** [comment]
Cause failed event on minner. Can i mod somewhere tolerance ?

**Comment by aaronsace** [comment]
I think you have a heat problem but you can change this line in 'include.psm1'. 

From: 
`[Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.1), 0.9)`

To: 
`0.3`

**Comment by fonyo** [comment]
*To be added to FAQ*

**Comment by Golempl** [comment]
Thanks, work like a charm.

**Comment by fonyo** [comment]
Added.

**Comment by Mrjank** [comment]
@aaronsace When you say From:

"[Math]::Min([Math]::Max($Stat.Week_Fluctuation * 2, 0.1), 0.9)

To:
0.3"

What part are we supposed to change to 0.3?

**Comment by ParthibanPeriyasamy18** [comment]
@Mrjank 

I think He meant Remove everything and replace with 0.3.
