### ISSUE TITLE
Ahashpool payment

### ISSUE THREAD

**Issue by abinsraj** [aaronsace/MultiPoolMiner#602]
Hi guys I'm a newbie to GitHub and crypto-mining. Currently I'm mining in **Ahashpool**, I want to know how they pay or when they pay. I got payment in nicehash and now they are down.
![github](https://user-images.githubusercontent.com/34397058/33796142-e6108936-dd14-11e7-8167-562c65ef1c03.PNG)

**Comment by UselessGuru** [comment]
@abinsraj 

Why do you post this here? Payout schemes are defined by the respective pool.
For AHAshPool read here: [https://www.ahashpool.com/](https://www.ahashpool.com/)

**Comment by abinsraj** [comment]
@UselessGuru  Hey Guru I saw the payout scheme in Ahashpool but my doubt is that what is my payout amount? Is balance or total unpaid? And what is the difference between that two?

**Comment by UselessGuru** [comment]
_Paid_ is what has been sent to your address
_Unpaid_ is what is still waiting to be paid. -> will become _paid_ at payment schedule.

**Comment by fonyo** [comment]
Welcome @abinsraj!
MultiPoolMiner is an external software and even though it is often endorsed by the pools it supports, it is not maintained or associated by any those pools. Please refer to the info provided on the pools' website. Alternatively, we can provide some help on getting you up-and-running (and we are happy to do so) but our support is mostly limited to MPM, so we have a "Know Your Pool" practice in place in general. Please let me know if you have any other questions or queries and will try to help as soon as I can.
