### ISSUE TITLE
BTC/GH/Day wrong on many algorithms

### ISSUE THREAD

**Issue by yEinFallsLos** [aaronsace/MultiPoolMiner#603]
I have 2 1080s which mine at around ~10EUR/Day confirmed by [whattomine.com](https://whattomine.com/coins?utf8=%E2%9C%93&adapt_q_280x=0&adapt_q_380=0&adapt_q_fury=0&adapt_q_470=0&adapt_q_480=0&adapt_q_570=0&adapt_q_580=0&adapt_q_750Ti=0&adapt_q_1050Ti=0&adapt_q_10606=0&adapt_q_1070=0&adapt_q_1080=2&adapt_1080=true&adapt_q_1080Ti=0&eth=true&factor%5Beth_hr%5D=46.6&factor%5Beth_p%5D=280.0&grof=true&factor%5Bgro_hr%5D=89.0&factor%5Bgro_p%5D=300.0&x11gf=true&factor%5Bx11g_hr%5D=27.0&factor%5Bx11g_p%5D=290.0&cn=true&factor%5Bcn_hr%5D=1160.0&factor%5Bcn_p%5D=200.0&eq=true&factor%5Beq_hr%5D=1100.0&factor%5Beq_p%5D=260.0&lre=true&factor%5Blrev2_hr%5D=93000.0&factor%5Blrev2_p%5D=300.0&ns=true&factor%5Bns_hr%5D=2120.0&factor%5Bns_p%5D=300.0&lbry=true&factor%5Blbry_hr%5D=720.0&factor%5Blbry_p%5D=300.0&bk2bf=true&factor%5Bbk2b_hr%5D=4300.0&factor%5Bbk2b_p%5D=300.0&bk14=true&factor%5Bbk14_hr%5D=6600.0&factor%5Bbk14_p%5D=300.0&pas=true&factor%5Bpas_hr%5D=2500.0&factor%5Bpas_p%5D=300.0&skh=true&factor%5Bskh_hr%5D=73.0&factor%5Bskh_p%5D=300.0&factor%5Bl2z_hr%5D=420.0&factor%5Bl2z_p%5D=300.0&factor%5Bcost%5D=0.0&sort=Profitability24&volume=0&revenue=24h&factor%5Bexchanges%5D%5B%5D=&factor%5Bexchanges%5D%5B%5D=abucoins&factor%5Bexchanges%5D%5B%5D=bitfinex&factor%5Bexchanges%5D%5B%5D=bittrex&factor%5Bexchanges%5D%5B%5D=bleutrade&factor%5Bexchanges%5D%5B%5D=cryptopia&factor%5Bexchanges%5D%5B%5D=hitbtc&factor%5Bexchanges%5D%5B%5D=poloniex&factor%5Bexchanges%5D%5B%5D=yobit&dataset=Main&commit=Calculate) or the [zpool ming rates](http://zpool.ca/site/mining).
However MPM calculates completely different figures:
![Rates](https://user-images.githubusercontent.com/25830681/33796346-b6b134fa-dcf2-11e7-9d31-9e09c05bfe28.PNG)
For example Lyra2Rev2 is too low (0.00435 instead of ~0.007) where blake2s is way too high (0.00017 (20 EUR/month!) instead of 0.00003).
Also, many other algos are off as well, leading to a completely wrong order.

Has this something to do with the recent problems with NiceHash and his API?

**Comment by Ciechom** [comment]
If I'm right it looks like it is not updating BTC/GH/Day at all in my case.

**Comment by yEinFallsLos** [comment]
Is the script taking its numbers only from miningpoolhub.com? Why is there then also a zpool/nicehash/hashrefinery api?

But the example for blake2s is weird anyways .. i mean when was it that profitable?

**Comment by aaronsace** [comment]
@yEinFallsLos Coin difficulties go up and down all the time. Sometimes exchanges rates may fluctuate but it's mainly coin difficulties.

**Comment by Ciechom** [comment]
I used miningpoolhub.com as an example (I'm not using other ones). Maybe something is cacheing http://www.zpool.ca/api/status in case of zpool.

**Comment by yEinFallsLos** [comment]
@aaronsace ok if you say thats normal..
@Ciechom ok thanks you just confused me :D

**Comment by houston1784** [comment]
must have

**Comment by crashbash2020** [comment]
@Ciechom hi i think i am having the same issue as you, how do you clear the "Caching proxy"?
