### ISSUE TITLE
WARNING: Pool API (NiceHash) has failed. WARNING: No pools available.

### ISSUE THREAD

**Issue by wrkettlitz** [aaronsace/MultiPoolMiner#604]
Thank you for this amazing programs, can you please help me i am not getting it to work.

This is my .bat file : 

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 

-username example
-workername x 
-region europe 
-currency btc,usd,eur 
-type amd,nvidia,cpu 
-poolname miningpoolhub
-algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2z,neoscrypt,siaclaymore 
-donate 10
-watchdog"

And this is my log: 

**********************
Windows PowerShell transcript start
Start time: 20171209174618
Username: DESKTOP-8QD05KB\Miner1000
RunAs User: DESKTOP-8QD05KB\Miner1000
Machine: DESKTOP-8QD05KB (Microsoft Windows NT 10.0.15063.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command &.\multipoolminer.ps1 
Process ID: 8096
PSVersion: 5.1.15063.0
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.0
BuildVersion: 10.0.15063.0
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-12-09_17-46-18.txt
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
WARNING: No pools available.
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
WARNING: No pools available.
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
WARNING: No pools available.

As you can see i get an error about nicehash when i dont have nicehash selected at all. Can you explain what i am doing wrong? thanks

**Comment by Vxrl** [comment]
You can delete NiceHash.ps1 from the Pools folder if you don't want to see the "WARNING: Pool API (NiceHash) has failed." message.

**Comment by wrkettlitz** [comment]
Thanks but that did not fix my problem

**Comment by Vxrl** [comment]
The PowerShell arguments need to all be on one line, so your .bat file should look like this:

```
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username example -workername x -region europe -currency btc,usd,eur -type amd,nvidia,cpu -poolname miningpoolhub -algorithm cryptonight,ethash,ethash2gb,equihash,groestl,lyra2z,neoscrypt,siaclaymore -donate 10 -watchdog"
```

Try this, then if you're still having problems, please post the new log file.

**Comment by wrkettlitz** [comment]
Thank you that did the trick!

**Comment by fonyo** [comment]
Please do not put line breaks between commands! Everything should be a in a single line after "&.\multipoolminer.ps1 ...........
