### ISSUE TITLE
https://github.com/JayDDee/cpuminer-opt/releases - can not be downloaded!

### ISSUE THREAD

**Issue by thezenofless** [aaronsace/MultiPoolMiner#605]

**Comment by spoonwzd** [comment]
You can manually place the files, but then I just get continual cpuminer-gw64-avx2.exe crashes

**Comment by fonyo** [comment]
Has it been working for you before?

**Comment by thezenofless** [comment]
Yes it has worked before, at least there was no error when downloading that particular miner.

I Think there is something wrong with the download link:
![image](https://user-images.githubusercontent.com/34401193/33800090-d7504b96-dd39-11e7-925c-04745d52e6a3.png)

The only associated File is this one:
![image](https://user-images.githubusercontent.com/34401193/33800096-f7aa8ee2-dd39-11e7-82f2-aaa6d001e87e.png)

**Comment by fonyo** [comment]
That looks like an incomplete download, please delete it so a download can be triggered again.

**Comment by aaronsace** [comment]
Your virus checker removed it; it's included in here: 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip
