### ISSUE TITLE
Warning: Pool API (NiceHash) has failed. Warning: No pools available

### ISSUE THREAD

**Issue by Silverplatimun** [aaronsace/MultiPoolMiner#607]
Whenever i try running MultiPoolMiner.ps1 it always comes up with Warning: Pool API (NiceHash) has failed. Warning: No pools available
This is my Start.bat 

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username SilverPlatimun -workername worker1 -region us -currency btc,usd,eur -type nvidia,cpu -poolname miningpoolhub -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib -donate 10 -watchdog"
Im new to this i have no idea wtf im doing

**Comment by aaronsace** [comment]
What about the other pools inside the folder called 'pools'?

**Comment by Silverplatimun** [comment]
They open and then close,

**Comment by aaronsace** [comment]
Did it create any logs? Can you upload them?

**Comment by Silverplatimun** [comment]
![image](https://user-images.githubusercontent.com/34406507/33800594-de3ab366-dcf7-11e7-9173-719c3c0e8507.png)

**Comment by aaronsace** [comment]
There is a folder called 'logs'.

**Comment by Silverplatimun** [comment]
Transcript started, output file is .\Logs\2017-12-09_15-19-27.txt
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
WARNING: No pools available.

**Comment by Silverplatimun** [comment]
thats what all the log files say

**Comment by aaronsace** [comment]
Please can you upload the whole file?

**Comment by Silverplatimun** [comment]
**********************
Windows PowerShell transcript start
Start time: 20171209153819
Username: SILVERPLATIMUN\SilverPlatimun
RunAs User: SILVERPLATIMUN\SilverPlatimun
Configuration Name: 
Machine: SILVERPLATIMUN (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\SilverPlatimun\Desktop\l\MultiPoolMiner.ps1'
Process ID: 14852
PSVersion: 5.1.16299.64
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.64
BuildVersion: 10.0.16299.64
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-12-09_15-38-19.txt
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
WARNING: No pools available.

**Comment by aaronsace** [comment]
You are not clicking on 'start.bat'.

**Comment by Silverplatimun** [comment]
**********************
Windows PowerShell transcript start
Start time: 20171209155949
Username: SILVERPLATIMUN\SilverPlatimun
RunAs User: SILVERPLATIMUN\SilverPlatimun
Configuration Name: 
Machine: SILVERPLATIMUN (Microsoft Windows NT 10.0.16299.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command &.\multipoolminer.ps1 -username SilverPlatimun -workername worker1 -region us -currency btc,usd,eur -type nvidia,cpu -poolname miningpoolhub -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib -donate 10 -watchdog
Process ID: 14972
PSVersion: 5.1.16299.64
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.64
BuildVersion: 10.0.16299.64
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2017-12-09_15-59-49.txt
PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
Remove-Job : The command cannot remove the job with the job ID 36 because the job is not finished. To remove the job, 
first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], 
ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand
Remove-Job : The command cannot remove the job with the job ID 36 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand

Remove-Job : The command cannot remove the job with the job ID 38 because the job is not finished. To remove the job, 
first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], 
ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand
Remove-Job : The command cannot remove the job with the job ID 38 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand



   Type: NVIDIA

Miner                  Algorithm                                       Speed                      BTC/Day         BTC/GH/Day Pool
-----                  ---------                                       -----                      -------         ---------- ----
ClaymoreNvidiaSia30    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia20    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia40    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
Dstm                   Equihash                                 Benchmarking                 Benchmarking          385.49514 MiningPoolHub-Zcash
Ewbf                   Equihash                                 Benchmarking                 Benchmarking          385.49514 MiningPoolHub-Zcash
ClaymoreNvidia2gbSia40 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00477, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}
ClaymoreNvidia         Ethash                                   Benchmarking                 Benchmarking            0.00512 MiningPoolHub-EthereumClassic
CcminerLyra2z          Lyra2z                                   Benchmarking                 Benchmarking            0.13957 MiningPoolHub-Zcoin
ClaymoreNvidia         Ethash2gb                                Benchmarking                 Benchmarking            0.00477 MiningPoolHubCoins-Musicoin
ClaymoreNvidia2gbSia20 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00477, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}
ClaymoreNvidia2gbSia30 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00477, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}


   Type: CPU

Miner                   Algorithm          Speed      BTC/Day BTC/GH/Day Pool
-----                   ---------          -----      ------- ---------- ----
CpuminerJayddeeSse42    CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeSse2     Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeAesavx   Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeSse42    Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeSse2     CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeAesavx2  CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeAesavx   CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeAesavx2  Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeAessse42 Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeAessse42 CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero




   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\CPU-JayDDee\cpuminer-sse2.exe -a cryptonight -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024 -u SilverPlatimun.worker1 -p x
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal SilverPlatimun.worker1 -epsw x -esm 3 -allpools 1 -allcoins 1 -dpool
                                               hub.miningpoolhub.com:17022 -dwal SilverPlatimun.worker1 -dpsw x -dcoin sc -dcri 30 -platform 2


PS>TerminatingError(Invoke-RestMethod): "The operation has timed out."
WARNING: Pool API (NiceHash) has failed.
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Ethash_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Equihash_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Ethash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Equihash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Ethash_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Equihash_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Ethash_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\SilverPlatimun\Desktop\l\Bin\Excavator\MiningPoolHub_Equihash_3_Nvidia.json'."
Remove-Job : The command cannot remove the job with the job ID 40 because the job is not finished. To remove the job, 
first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], 
ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand
Remove-Job : The command cannot remove the job with the job ID 40 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand

Remove-Job : The command cannot remove the job with the job ID 42 because the job is not finished. To remove the job, 
first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], 
ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand
Remove-Job : The command cannot remove the job with the job ID 42 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\SilverPlatimun\Desktop\l\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand



   Type: NVIDIA

Miner                  Algorithm                                       Speed                      BTC/Day         BTC/GH/Day Pool
-----                  ---------                                       -----                      -------         ---------- ----
ClaymoreNvidia2gbSia40 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00486, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia20    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
ClaymoreNvidia2gbSia20 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00486, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}
ClaymoreNvidia2gbSia30 {Ethash2gb, SiaClaymore} {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00486, 0.00005} {MiningPoolHubCoins-Musicoin, MiningPoolHub-Siacoin}
ClaymoreNvidiaSia30    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
Dstm                   Equihash                                 Benchmarking                 Benchmarking          385.49514 MiningPoolHub-Zcash
EthminerNvidia         Ethash                                   Benchmarking                 Benchmarking            0.00512 MiningPoolHub-EthereumClassic
ClaymoreNvidiaSia40    {Ethash, SiaClaymore}    {Benchmarking, Benchmarking} {Benchmarking, Benchmarking} {0.00512, 0.00005} {MiningPoolHub-EthereumClassic, MiningPoolHub-Siacoin}
Ewbf                   Equihash                                 Benchmarking                 Benchmarking          385.49514 MiningPoolHub-Zcash
ClaymoreNvidia         Ethash2gb                                Benchmarking                 Benchmarking            0.00486 MiningPoolHubCoins-Musicoin
CcminerLyra2z          Lyra2z                                   Benchmarking                 Benchmarking            0.13957 MiningPoolHub-Zcoin
CcminerTpruvot         CryptoNight                              Benchmarking                 Benchmarking          190.91492 MiningPoolHub-Monero
CcminerNanashi         NeoScrypt                                Benchmarking                 Benchmarking            0.18508 MiningPoolHub-Feathercoin
CcminerNanashi         Lyra2z                                   Benchmarking                 Benchmarking            0.13957 MiningPoolHub-Zcoin
CcminerTpruvot         Equihash                                 Benchmarking                 Benchmarking          385.49514 MiningPoolHub-Zcash
CcminerTpruvot         NeoScrypt                                Benchmarking                 Benchmarking            0.18508 MiningPoolHub-Feathercoin
ClaymoreNvidia         Ethash                                   Benchmarking                 Benchmarking            0.00512 MiningPoolHub-EthereumClassic
CcminerTpruvot         Lyra2z                                   Benchmarking                 Benchmarking            0.13957 MiningPoolHub-Zcoin
CcminerTpruvot         Groestl                                  Benchmarking                 Benchmarking            0.00347 MiningPoolHub-Groestlcoin


   Type: CPU

Miner                   Algorithm          Speed      BTC/Day BTC/GH/Day Pool
-----                   ---------          -----      ------- ---------- ----
CpuminerTpruvotCore2    NeoScrypt   Benchmarking Benchmarking    0.18508 MiningPoolHub-Feathercoin
CpuminerTpruvotCore2    Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerTpruvotAvx2     NeoScrypt   Benchmarking Benchmarking    0.18508 MiningPoolHub-Feathercoin
CpuminerTpruvotCore2    CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerTpruvotCore2    Groestl     Benchmarking Benchmarking    0.00347 MiningPoolHub-Groestlcoin
CpuminerTpruvotCorei7   NeoScrypt   Benchmarking Benchmarking    0.18508 MiningPoolHub-Feathercoin
CpuminerJayddeeAessse42 Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerTpruvotCorei7   Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerTpruvotCorei7   CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerTpruvotCorei7   Groestl     Benchmarking Benchmarking    0.00347 MiningPoolHub-Groestlcoin
CpuminerJayddeeAesavx2  Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeAessse42 CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeSse2     CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeAesavx   CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeAesavx   Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeAesavx2  CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerTpruvotAvx2     CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerTpruvotAvx2     Groestl     Benchmarking Benchmarking    0.00347 MiningPoolHub-Groestlcoin
CpuminerTpruvotAvx2     Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeSse2     Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin
CpuminerJayddeeSse42    CryptoNight Benchmarking Benchmarking  190.91492 MiningPoolHub-Monero
CpuminerJayddeeSse42    Lyra2z      Benchmarking Benchmarking    0.13957 MiningPoolHub-Zcoin


   Type: {AMD, NVIDIA}

Miner  Algorithm        Speed      BTC/Day BTC/GH/Day Pool
-----  ---------        -----      ------- ---------- ----
Eminer Ethash2gb Benchmarking Benchmarking    0.00486 MiningPoolHubCoins-Musicoin
Eminer Ethash    Benchmarking Benchmarking    0.00512 MiningPoolHub-EthereumClassic




   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a cryptonight -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024 -u SilverPlatimun.worker1 -p x
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-Nanashi\ccminer.exe -a neoscrypt -o stratum+tcp://hub.miningpoolhub.com:17012 -u SilverPlatimun.worker1 -p x


   Status: Idle

                 Speed Active                      Launched Command
                 ----- ------                      -------- -------
             0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\CPU-JayDDee\cpuminer-sse2.exe -a cryptonight -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024 -u SilverPlatimun.worker1 -p x
{0.00 PH/s, 0.00 PH/s} 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal SilverPlatimun.worker1 -epsw x -esm 3 -allpools 1 -allcoins 1
                                                            -dpool hub.miningpoolhub.com:17022 -dwal SilverPlatimun.worker1 -dpsw x -dcoin sc -dcri 30 -platform 2
