### ISSUE TITLE
Prospector can't connect during benchmarking

### ISSUE THREAD

**Issue by zoglun** [aaronsace/MultiPoolMiner#608]
Using MultiPoolMinerV2.7.0.2.zip & GTX 1070 Ti

Prospector keep showing:
ERROR  Signatum: network client disconnected, Trying to reconnect
with 0 H/s

Why it doesn't work?
Does it connect to NiceHaced?

**Comment by aaronsace** [comment]
Not sure, best reporting it here: https://github.com/semtexzv/Prospector/issues

There are plenty of other miners included though so you can delete it from the folder called 'miners' if you are having problems.

**Comment by zoglun** [comment]
Cool! Thank you for your lighting fast respond!
