### ISSUE TITLE
truvpot sia cpu miner not working properly

### ISSUE THREAD

**Issue by newmzy** [aaronsace/MultiPoolMiner#61]
whenever multipool miner tries to run the above miner it gets an error "stratum extranonce answer not correct" or something similar. This also happens with ccminer 1.8.4 for sia

**Comment by aaronsace** [comment]
The miners may not support Sia or the pool isn't setup correctly. Don't worry, it will skip past it. 

If anyone has a Sia miner that works it knows what the issue is then I'll change it.

**Comment by muzzy124** [comment]
i've disabled sia and yescrypt in ccminer-tpruvot config, they don't work
