### ISSUE TITLE
Dev Donation Forced

### ISSUE THREAD

**Issue by AmINick** [aaronsace/MultiPoolMiner#612]
It seems like the Dev donation time is forced @ 24min no matter what I change, even 0

**Comment by garyng** [comment]
or 10?
https://github.com/aaronsace/MultiPoolMiner/blob/f2f1371631530cd67feb631922d0d2a765f3c7d2/MultiPoolMiner.ps1#L75-L76

**Comment by AmINick** [comment]
Thx! resolve my concerns! I think 10 is fair
