### ISSUE TITLE
Get-ChildItem Access is denied

### ISSUE THREAD

**Issue by MasterMartbob** [aaronsace/MultiPoolMiner#615]
I have the following error.
WARNING: Cannot download D:\Miner\MultiPoolMiner-master\Bin\Equihash-DSTM\zm.exe.
WARNING: Searching for D:\Miner\MultiPoolMiner-master\Bin\Equihash-DSTM\zm.exe.
Access is denied
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.GetChildItemCommand
    + PSComputerName        : localhost

I run the batch script with Administrator privileges. I try downloading manually the zm.exe and put it at the right place. Nothing worked. I am on Windows 10.

Thanks for the help.

**Comment by aaronsace** [comment]
Please download the latest release not the code: 
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by MasterMartbob** [comment]
Yep that was my error. Thanks
