### ISSUE TITLE
GPU 1 has halve hash rate of GPU 0 

### ISSUE THREAD

**Issue by wrkettlitz** [aaronsace/MultiPoolMiner#616]
![ssss](https://user-images.githubusercontent.com/16758470/33806113-30160156-ddc3-11e7-8103-ec82a59ea987.PNG)

Whats wrong? Please help

**Comment by aaronsace** [comment]
That looks like one of the ccminer versions; MultiPoolMiner is not causing the drop in speed. 

Try contacting the developer directly if it is just that one miner. If all the miners are having the same issue then there is something wrong with your system.
