### ISSUE TITLE
CPU Miners Hashrate out of range so miner is removed  out of rotation

### ISSUE THREAD

**Issue by station384** [aaronsace/MultiPoolMiner#617]
Miner hashrate will drop out of normal range due to powershell grabbing cycles.
Suggest changing hashrate monitoring for cpu miners to only detect failures if rate is within 90% of calculated benchmark.  this will reduce the amount of false positives failures in cpu miners.

Expanding on symptoms:
XMRigCPU usually hashes around 200h/s Cryptonight
during MPM processing hashing drops to 100h/s, when processing completes XMRig continues to hash at 200h/s.  this effects the average causing a high variance between the benchmarked hashrate and the current detected hashrate, this in turn causes MPM to detect a failure and remove this miner out of rotation.

**Comment by aaronsace** [comment]
Should be more tolerable in the latest code branch: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip
