### ISSUE TITLE
Nicehash API Error plus another

### ISSUE THREAD

**Issue by Renegade5399** [aaronsace/MultiPoolMiner#618]
Despite removing the Nicehash file from the API folder, I still see the API connection failure message in yellow. Will this be fixed in the next version? Is there a way I can make this stop?

Next issue:
https://imgur.com/a/zuduS

After getting the Nicehash API error, this happens. Not sure what is causing it. I tried clearing logs, resetting benchmarks and profits just to see if that helped and it does not. The app still mines and every minute or so I see the stats in the prompt window. Then the yellow NH API error comes up followed by the above image.

[2017-12-10_11-04-00.zip](https://github.com/aaronsace/MultiPoolMiner/files/1545847/2017-12-10_11-04-00.zip)

**Comment by UselessGuru** [comment]
@Renegade5399 
Remove the NiceHash file in the pool folder, not the API!
