### ISSUE TITLE
Qubit profit calc seems off by 10x

### ISSUE THREAD

**Issue by Lanik42** [aaronsace/MultiPoolMiner#62]
All of a sudden MPM started saying that my profitability for ~42MH/s was > .009 BTC/day, which is way off what I see elsewhere.  [WhatToMine](https://whattomine.com/coins/135-geo-qubit?utf8=%E2%9C%93&hr=42&p=200.0&fee=0.0&cost=0.1&hcost=0.0&commit=Calculate) indicates it's closer to .0007 BTC/day.  This means I basically can't use MPM, as it's running unprofitable coins

**Comment by aaronsace** [comment]
The data is more accurate than WhatToMine as it comes from the pool that is paying you (MiningPoolHub). You can check it with a calculator from the data on the main page but I think it's just a spike in price.
