### ISSUE TITLE
Enhancement / Compatibility / Backwardability ;0

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#621]
I wish that Claymore Cryptonote 9.7 is back because 10.x is not working for me, i get slow speed on my 3rd GPU not sure why.
XMRIG AMD also an issue, not getting full speed on GPUs - 590 hashes instead of 633 (RX470)
SGMiner and Claymore Cryptonote 9.7 are the most usable/compatible

**Comment by aaronsace** [comment]
RX 480 and GTX 1080Ti work. 

You can always just downgrade them in the 'bin' folder but I can't imagine RX 470 having compatibly issues and is more likely a problem with your system setup.

**Comment by imrecsoka** [comment]
Well i can say that SGMiner 5.x.x and Claymore Cryptonote Miner 9.7 work fine, I get what i should for my RX470 cards.
I get less speed on the first 2 GPUs, and then half speed on my 3rd GPU for Cryptonote Miner 10.2 and XMRIG-AMD as well as XMR-STAK-AMD, so i dont get why.
I can say that i have old version drivers, 16.x.x and not 17.x.x 
This is 3 different windows instances on the same machine, so i do this to test that i am not providing false positives, as much as possible.
I hope i am the only crayon in the box with this issue, but somehow i dont think i am.

**Comment by aaronsace** [comment]
I'm going to close this as this is a system issue and is effecting the miners themselves, not MultiPoolMiner.

**Comment by imrecsoka** [comment]
System issue, i dont follow.
Anyways i will have time on Friday to test the stuff more for you and report back.
I think i need a new json file to use Claymore 9.,7  and as for XMR-STAK-.... im not sure how to solve those, maybe i can use an old version where it only uses that for CPU mining?
Something is cooked with the AMD mining as it is speed limited. Very weird.
Maybe i can try version 11 of Claymore Cryptonote and let you know how it goes.
Thanks for the hard work and efforts.
I am always donating so dont forget, regardless if it is a miner specific issue but for your work arounds and making the mining suite better, its for this purpose :)
