### ISSUE TITLE
profit not showing the correct miner

### ISSUE THREAD

**Issue by razorseal** [aaronsace/MultiPoolMiner#623]
Hello,

Currently mining for equihash using EWBF on MPH. however, the profit share info at the bottom is showing me that I'm mining for lyra2rev2 with excavator...

Also, I'm confused because the miner that is being used is shown on the "idle" miner, and not in the "active" miner.

Can anyone tell me what is wrong, or what I'm doing wrong?

Thanks

Here is the image... https://s17.postimg.org/mcqyuf64v/2017-12-10_6.png

**Comment by aaronsace** [comment]
It's simply showing you a comparison between MultiPoolMiner and the best miner available.

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/blob/master/README.md#q5-multipoolminer-is-xx-more-profitable-what-does-this-mean

**Comment by razorseal** [comment]
Aaron,

I understand, but do you mean the profit calculator won't show what you are mining? 

That was a low quality pic, perhaps you didn't see it. Here is high rez. You can see I'm mining equihash on EWBF (actually at that screenshot, mining for your donation lol) but the profit calculator says I'm mining excavator lyra2rev2

https://s17.postimg.org/ud59ivzxb/2017-12-10_6.png

**Comment by aaronsace** [comment]
Status 'running' is what you are currently mining.

**Comment by razorseal** [comment]
Right... Which is equihash. Now look at my profit calculator line 2. Why is it telling me profit of lyra2re2? Doesn't line 2 show me my actual (estimated) profit? That's not even the algorithm I'm running...

**Comment by aaronsace** [comment]
Line one is MultiPoolMiner miner, line two is the comparison.
