### ISSUE TITLE
Issue Still Remains With PS Error

### ISSUE THREAD

**Issue by Renegade5399** [aaronsace/MultiPoolMiner#627]
The Nicehash API error was fixed with your suggestion in:

https://github.com/aaronsace/MultiPoolMiner/issues/618

However the other issue mentioned remains.

See:
https://imgur.com/a/zuduS

Line 148, Char 71 Seen here:

https://imgur.com/a/cVNLR

Not sure what is causing this.

**Comment by Jacobknight** [comment]
ya I am also getting that.

**Comment by Renegade5399** [comment]
Forgot to mention that this is happening on 2 different mining boxes with different hardware.

**Comment by aaronsace** [comment]
Try the latest code branch: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

Please note that you will have to add the 'bin' folder yourself.

**Comment by Jacobknight** [comment]
I have downloaded from the link you provided but I am getting this version is outdated and telling me to download version 2.7.0.2 is it alright?

**Comment by aaronsace** [comment]
Yes, it was not been released as of yet.

**Comment by Renegade5399** [comment]
I have been out of town. i will test this today. So i download the above and copy over my current bin folder?

**Comment by Renegade5399** [comment]
That release fixed it. Thank you. 

Will this be the next release?

**Comment by aaronsace** [comment]
Few minor things left but yes; that will be V2.7.1.

**Comment by Renegade5399** [comment]
Again, thanks for your level of support. You do a great job.
