### ISSUE TITLE
@ aaronsace 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#628]
Is there a way I can email you? My questions really do fall outside of any functionality issues / non-issues of the multipoolminer, and therefor I think to ask those questions here would not be appropriate. However, I do have some legit questions regarding the miner overall, and I am trying to be respectful to you and your work, AND the work of all of those who have made this miner possible. 

Thank you for consideration. (a throw away email is fine) One of mine is zodiac1@protonmail.com if you want to reach out to me first.

**Comment by aaronsace** [comment]
You can PM me on Bitcointalk.
