### ISSUE TITLE
ExcavatorNvidia crashing with different errors

### ISSUE THREAD

**Issue by feernandobraga** [aaronsace/MultiPoolMiner#629]
So I've noticed that MPM was closing and re-opening the same miner over and over again, randomly. Sometimes it would 'reset' within 1 min, sometimes after 30.
So I've turned on the miner log and I came across with two different errors and possible explanation for the miner "reboot"
Please find the logs attached and I hope they mean something to you so I can try to fix it. I've googled the error but there are no similar conditions to my problem.
I thought it would be a problem with Excavator, but I've never had any issues using Nicehash (which I believe that was using the same miner).

[log_2017-12-11_18-50-43.002.log](https://github.com/aaronsace/MultiPoolMiner/files/1547286/log_2017-12-11_18-50-43.002.log)
[log_2017-12-11_20-05-56.005.log](https://github.com/aaronsace/MultiPoolMiner/files/1547287/log_2017-12-11_20-05-56.005.log)

**Comment by UselessGuru** [comment]
You are better off posting this on the excavator  miner page. MPM ist just launching the fastest miner.

I assume you are overclocking. Excavator is very sensitive in terms of OC.
Most likely you well see the same errors when you run the miner manually using the same parameters.
