### ISSUE TITLE
Tpruvot Related Hash BTC/GH/Day Data is Inaccurate

### ISSUE THREAD

**Issue by pdonket** [aaronsace/MultiPoolMiner#63]
It would appear that whatever data the program is scraping from MPH is inaccurate. The most recent example has been with the Qubit algo (but it has happened for Tpruvot X11 as well). I've even pulled up the links your PS files reference, and the BTC/GH/Day are not consistent with that information either.

![image](https://cloud.githubusercontent.com/assets/10300806/24074131/b3f1cbe2-0bd0-11e7-803e-b25ddfe210d1.png)

**Comment by aaronsace** [comment]
I've just tested it and it seems fine. 
Please can you attach the DigibyteQubit stat file from the stats folder.

**Comment by pdonket** [comment]
So I re-downloaded the latest release and that appears to have resolved the problem - the restored copy of the file stat file appears to have had a more realistic number than what was being displayed. 

[MiningPoolHubCoins_DigibyteQubit_Profit.txt](https://github.com/aaronsace/MultiPoolMiner/files/852633/MiningPoolHubCoins_DigibyteQubit_Profit.txt)
[CcminerTpruvot_Qubit_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/852634/CcminerTpruvot_Qubit_HashRate.txt)

I was running into this issue for roughly 24 hours, is there any good way to force a refresh of the BTC/GH/Day data? Mainly trying to make sure I can avoid having to re-benchmark if this pops up again.

**Comment by aaronsace** [comment]
Just delete the stat file to reset. 
The latest build is less susceptible to that issue.
