### ISSUE TITLE
gpu selection

### ISSUE THREAD

**Issue by JhonJhonny** [aaronsace/MultiPoolMiner#630]
i already know that you can't select which gpu use to mine unless you edit the config of all miners inside but my question is, are you planning on adding a faster way to do it? like a parameter in the start.bat that override the miners option which tells how many gpu use? just asking

**Comment by aaronsace** [comment]
I plan on using OpenCL for GPU detection. 

You can actually split the miners with the current code base. 

In the miner configuration files you can add an variable called 'Index' then specify some GPUs. 

```
Type = "AMD"
Path = 
Arguments = 
API = 
Port = 
Wrap = 
URI = 
Index = 1,2,3 #GPU Numbers
```

```
Type = "AMD"
Path = 
Arguments = 
API = 
Port = 
Wrap = 
URI = 
Index = 4,5,6 #GPU Numbers
```

**Comment by UselessGuru** [comment]
@aaronsace 
Had you told me the index thingy earlier I could have save myself a lot of fun :-)

Where in your code do you hide the bit that tells the miner to only use the devices listed in 'index'?

I resorted to something like this in each miner file:
`$Command = "$(Get-CcminerCommandPerDevice -Command "$Command" -Devices $Type_Device.Devices) -d $($Type_Device.Devices -join ',')"`
Whereby the exact syntax, e.g. ' -d  0,1,n' is different per API

I add  the device name to the $Name variable to create separate stat files.
```
...
$Name = Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName

$Type_Devices | ForEach-Object {
	$Type_Device = $_

	$Commands | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name | Where {$_ -cnotmatch "^_.+" -and $Pools.$(Get-Algorithm($_)).Name -and {$Pools.$(Get-Algorithm($_)).Protocol -eq "stratum+tcp" <#temp fix#>}} | ForEach-Object {

		$Algorithm = Get-Algorithm($_)
		$Command =  $Commands.$_

		if ($Type_Devices.count -gt 1) {
			$Name = "$(Get-Item $MyInvocation.MyCommand.Path | Select-Object -ExpandProperty BaseName)_$($Type_Device.Device_Norm)"
			$Command = "$(Get-CcminerCommandPerDevice -Command "$Command" -Devices $Type_Device.Devices) -d $($Type_Device.Devices -join ',')"
			$Index = ($Type_Device.Devices -join ',')
		}

		{while (Get-NetTCPConnection -State "Listen" -LocalPort $($Port) -ErrorAction SilentlyContinue){$Port++}} | Out-Null

		[PSCustomObject]@{
			Miner_Device= $Name
			Type		= $Type
			Device		= $Type_Device.Device
			Path		= $Path
			Arguments	= "-a $_ -o $($Pools.$Algorithm.Protocol)://$($Pools.$Algorithm.Host):$($Pools.$Algorithm.Port) -u $($Pools.$Algorithm.User) -p $($Pools.$Algorithm.Pass) -b $Port$Command$CommonCommands"
			HashRates	= [PSCustomObject]@{$Algorithm = ($Stats."$($Name)_$($Algorithm)_HashRate".Week)}
			API		= "Ccminer"
			Port		= $Port
			Wrap		= $false
			URI		= $Uri
			PowerDraw	= $Stats."$($Name)_$($Algorithm)_PowerDraw".Week
			ComputeUsage	= $Stats."$($Name)_$($Algorithm)_ComputeUsage".Week
			Pool		= "$($Pools.$Algorithm.Name)"
			Index		= $Index
		}
	}
	$Port ++
}
```
Ideally the number of executet miners should be reduced as much as possible. E.G. in a 3 card config you have to cards ($Index 0,2) where CcMiner is best, and one ($Index = 1) where Excavator ist best, MPM should run one instance of Ccminer (with $Index 0,2) and one Excavator with ($Index 2).
For pure cmd line miners I see no problem with this, but json configs this might cause headaches :-(

**Comment by aaronsace** [comment]
@UselessGuru Sorry mate, hard to get everything across. 

There is two combo finders in the code; currently nothing is using the second one. It can work like how OpenCL does; 'type' represents the OpenCL platform and index represents the OpenCL index. 

Ye, it's a pain ATM that's why I'm not using it anymore but the code is still there.

**Comment by UselessGuru** [comment]
@aaronsace 

> Ye, it's a pain ATM that's why I'm not using it anymore but the code is still there

I use it now without any issue (but with one miner per device). Device in my code represents all cards of the the same model (). If I were to have only GTX1080s, then I would only run one miner for all cards.

I use the code in [https://github.com/aaronsace/MultiPoolMiner/issues/519](https://github.com/aaronsace/MultiPoolMiner/issues/519):
Have a look at 'Get-GPUdevices' and 'Get-CcminerCommandPerDevice'. Feel free to modify them :-)

**Comment by RyanHope** [comment]
The Index feature does not appear to be working in HEAD.
