### ISSUE TITLE
Getting BSOD on one laptop

### ISSUE THREAD

**Issue by ailocha** [aaronsace/MultiPoolMiner#631]
Not sure if you can figure this out but here's the dump file from the blue screen, the only thing running is the miner.  looks like a problem w/ the video card?  It's an Intel HD 620.  Also the miner logfile is attached

Crash Dump Analysis provided by OSR Open Systems Resources, Inc. (http://www.osr.com)
Online Crash Dump Analysis Service
See http://www.osronline.com for more information
Windows 8 Kernel Version 16299 MP (4 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS Personal
Built by: 16299.15.amd64fre.rs3_release.170928-1534
Machine Name:
Kernel base = 0xfffff803`7fc05000 PsLoadedModuleList = 0xfffff803`7ff66fb0
Debug session time: Mon Dec 11 11:15:55.483 2017 (UTC - 5:00)
System Uptime: 0 days 0:46:55.188
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

THREAD_STUCK_IN_DEVICE_DRIVER_M (100000ea)
The device driver is spinning in an infinite loop, most likely waiting for
hardware to become idle. This usually indicates problem with the hardware
itself or with the device driver programming the hardware incorrectly.
If the kernel debugger is connected and running when watchdog detects a
timeout condition then DbgBreakPoint() will be called instead of KeBugCheckEx()
and detailed message including bugcheck arguments will be printed to the
debugger. This way we can identify an offending thread, set breakpoints in it,
and hit go to return to the spinning code to debug it further. Because
KeBugCheckEx() is not called the .bugcheck directive will not return bugcheck
information in this case. The arguments are already printed out to the kernel
debugger. You can also retrieve them from a global variable via
"dd watchdog!g_WdBugCheckData l5" (use dq on NT64).
On MP machines it is possible to hit a timeout when the spinning thread is
interrupted by hardware interrupt and ISR or DPC routine is running at the time
of the bugcheck (this is because the timeout's work item can be delivered and
handled on the second CPU and the same time). If this is the case you will have
to look deeper at the offending thread's stack (e.g. using dds) to determine
spinning code which caused the timeout to occur.
Arguments:
Arg1: ffffc20cfca03700, Pointer to a stuck thread object.  Do .thread then kb on it to find
	the hung location.
Arg2: 0000000000000000, Pointer to a DEFERRED_WATCHDOG object.
Arg3: 0000000000000000, Pointer to offending driver name.
Arg4: 0000000000000000, Number of times "intercepted" bugcheck 0xEA was hit (see notes).

Debugging Details:
------------------

TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\modclass.ini, error 2

FAULTING_THREAD:  ffffc20cfca03700

DEFAULT_BUCKET_ID:  GRAPHICS_DRIVER_FAULT

CUSTOMER_CRASH_COUNT:  1

BUGCHECK_STR:  0xEA

PROCESS_NAME:  System

CURRENT_IRQL:  0

LAST_CONTROL_TRANSFER:  from fffff80b75226d73 to fffff8037fd690e0

STACK_TEXT:  
ffff9803`f24e6968 fffff80b`75226d73 : 00000000`000000ea ffffc20c`fca03700 00000000`00000000 00000000`00000000 : nt!KeBugCheckEx
ffff9803`f24e6970 fffff80b`75226e3e : ffff9803`f24e6a48 fffff80b`79e21898 ffff9803`f24e6a48 ffff9803`f24e6b30 : dxgkrnl!TdrTimedOperationBugcheckOnTimeout+0x3f
ffff9803`f24e69e0 fffff80b`79dc59e0 : ffffc20c`f9a00000 00000000`00000000 ffff9803`f24e6b30 fffff80b`79e21884 : dxgkrnl!TdrTimedOperationDelay+0xbe
ffff9803`f24e6a20 ffffc20c`f9a00000 : 00000000`00000000 ffff9803`f24e6b30 fffff80b`79e21884 00000000`00002710 : atikmdag+0x559e0
ffff9803`f24e6a28 00000000`00000000 : ffff9803`f24e6b30 fffff80b`79e21884 00000000`00002710 ffffc20c`fc9d0028 : 0xffffc20c`f9a00000

STACK_COMMAND:  .thread 0xffffc20cfca03700 ; kb

FOLLOWUP_IP: 
dxgkrnl!TdrTimedOperationBugcheckOnTimeout+3f
fffff80b`75226d73 cc              int     3

SYMBOL_STACK_INDEX:  1

SYMBOL_NAME:  dxgkrnl!TdrTimedOperationBugcheckOnTimeout+3f

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: dxgkrnl

IMAGE_NAME:  dxgkrnl.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  0

FAILURE_BUCKET_ID:  X64_0xEA_IMAGE_dxgkrnl.sys

BUCKET_ID:  X64_0xEA_IMAGE_dxgkrnl.sys

Followup: MachineOwner
---------

**Comment by fonyo** [comment]
You should not mine with a laptop unless you want to kill it.
