### ISSUE TITLE
Cannot connect CIM servers 

### ISSUE THREAD

**Issue by heltucosta** [aaronsace/MultiPoolMiner#634]
When starting multipoolminer, I immediately get a error "cannot connect to CIM servers". 
Some downloads starts to occur, the CPU mining windows starts running and mining just fine, but the downloads never finishes with some CPU-JayDee errors and no benchmarks occurs for the algos.
Also, no GPU mining starts. I updated all CUDA files for my nVidia card and the CCMiner install says I already have a newer version ( I have VS2017 installed and updated )

I am running 1GPU for start and learning cruve, but plan on improving my setup.
Sorry if this is a basic issue, been searching for about 3 days and couldn't find much to go on.
If there's any info I can provide to improve debugging, would gladly update here.

**Comment by aaronsace** [comment]
Sorry, not even sure what a CIM server is. 

Are you using this version? 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip

**Comment by heltucosta** [comment]
Yes, trying with the latest release. I'll be home in a few minutes so I can upload an image here.

I also never heard of CIM servers before, but to what I could understand, It has something to do with Windows virtualization.

**Comment by aaronsace** [comment]
Attach the log(s) and screenshots of what you are seeing.

**Comment by heltucosta** [comment]
I first run the start.bat and this happens almost immediately.

![cimerror](https://user-images.githubusercontent.com/18036894/33849937-500f3c76-de99-11e7-9474-8ba9a4064923.png)

Than, the CPU miner starts running, some downloads would occur and them, this would show up.
![jaydeeerror](https://user-images.githubusercontent.com/18036894/33849938-50336af6-de99-11e7-8d82-dc9354c8bb7b.png)

I tried all the possibilities to continue with the script but it always comes back to the JayDee Error.

Here are the logs.
[2017-12-11_17-18-16.txt](https://github.com/aaronsace/MultiPoolMiner/files/1549125/2017-12-11_17-18-16.txt)

**Comment by lee-aaron** [comment]
Is everything updated? It's definitely not an MPM problem. It sounds like you have some outdated frameworks or something. Try searching around for updates for software updates from Microsoft. Perhaps the Windows Management Framework is a good start because it contains updates for PowerShell.

**Comment by aaronsace** [comment]
What operating system is this?

**Comment by heltucosta** [comment]
Windows 10. I`ll take a look at WMF, but I`ve done some C# .Net development on this and worked fine.

**Comment by aaronsace** [comment]
Maybe try the latest code branch that uses PowerShell 6. It relies less on the operating system. 

https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

**Comment by heltucosta** [comment]
I'm starting to believe it's my operating system. I'll reinstall everything and make sure it's ok and try again so I can give some feedback.

Thanks for the quick answers.

**Comment by heltucosta** [comment]
Reinstalled, updated and checked my OS installation. 
Now I didn't get any CIM server errors and it's been running for a while.

I'm not completely sure if the benchmarking is over already, but the GPU window is running fine, where now, the CPU is showing a lot of  "stratum_recv_line failed. Stratum connection interrupted.", but I believe it has nothing to do with miner issues.

I believe the issue can be closed. Thanks @aaronsace  @lee-aaron
