### ISSUE TITLE
Noob lyra2v2 Question/problem

### ISSUE THREAD

**Issue by ijardine** [aaronsace/MultiPoolMiner#635]
Sorry noob question, nicehash refugee :)

Running nvidia 1080ti card Got everything working as per the directions. So far so good, all works is mining .

I tried to add the lyra2v2 algorithm to the start file. Only change was to add
lyra2v2
to the -algorithm list (the rest work fine equihash, lbry, etc...)

Getting .... -c MiningPoolHub_Lyra2RE2_2_Nvidia.json -na
then nothing..

So clearly I am missing something a mis-config or missing miner or something?

![screenshot 1](https://user-images.githubusercontent.com/34457307/33850570-22dface8-de69-11e7-9ce8-f702737e796c.png)

**Comment by aaronsace** [comment]
I cannot include Excavator due to legal reasons so it just runs the version it finds on your PC. 

Update Excavator in the folder called 'bin': 
https://github.com/nicehash/excavator/releases

**Comment by ijardine** [comment]
Aha ok. Thanks for the quick response!
