### ISSUE TITLE
Issue - Import-Module: The given assembly name or codebase was invalid.

### ISSUE THREAD

**Issue by WJSM5** [aaronsace/MultiPoolMiner#636]
Having an issue when running MultiPoolMiner.bat. Same issue occurs with start.bat. Tried almost everything I could think of. I imagine its something stupid I am just looking over.
![capture](https://user-images.githubusercontent.com/34459936/33855747-e97b92c0-de93-11e7-973d-6109c7bf3065.PNG)

Edited to include a larger picture.

**Comment by WJSM5** [comment]
![capture](https://user-images.githubusercontent.com/34459936/33855769-fe77f952-de93-11e7-9516-bef7209b92b0.PNG)

**Comment by lee-aaron** [comment]
Could u attach ur logs and also what version of Windows do you have? Have you tried updating powershell or your windows software? I think this might be a software version issue.

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
