### ISSUE TITLE
Different Username on some miners

### ISSUE THREAD

**Issue by matticus04** [aaronsace/MultiPoolMiner#638]
Sometime when switching miners it doesnt use my username in the start.bat

   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\Equihash-DSTM\zm.exe --telemetry --server us-east.equihash-hub.miningpoolhub.com --port 17023 --user m.multipoolminer --pass x
0.00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\CPU-JayDDee\cpuminer-sse42.exe -a cryptonight -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024 -u m.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\CryptoNight-Claymore\NsGpuCNMiner.exe -r -1 -mport 13333 -xpool stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:17024 -xwal m.multipoolminer -xpsw x

   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\CPU-JayDDee\cpuminer-aes-avx2.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u m.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 01 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 13333 -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal m.multipoolminer -epsw x -esm 3 -allpools 1 -allcoins 1 -dpool
                                               hub.miningpoolhub.com:17022 -dwal m.multipoolminer -dpsw x -dcoin sc -dcri 20 -platform 1
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\NVIDIA-Nanashi\ccminer.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u m.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 13333 -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal matticus04.multipoolminer -epsw x -esm 3 -allpools 1 -allcoins 1 -dpool
                                               hub.miningpoolhub.com:17022 -dwal matticus04.multipoolminer -dpsw x -dcoin sc -dcri 20 -platform 1
0.00 PH/s 00 Days 00 Hours 02 Minutes Once     Bin\NVIDIA-KlausT\ccminer.exe -a groestl -o stratum+tcp://hub.miningpoolhub.com:17004 -u matticus04.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 06 Minutes 2 Times  Bin\CPU-JayDDee\cpuminer-aes-avx2.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u matticus04.multipoolminer -p x
0.00 PH/s 00 Days 00 Hours 12 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a neoscrypt -o stratum+tcp://neoscrypt.us.hashrefinery.com:4233 -u 19WuDHKneM2Sx293s9MFwP3tkaYgREeNRy -p multipoolminer,c=BTC
0.00 PH/s 00 Days 00 Hours 16 Minutes Once     Bin\CryptoNight-AMD\xmrig-amd.exe --api-port 3336 -a cryptonight -o stratum+tcp://us-east.cryptonight-hub.miningpoolhub.com:20580 -u matticus04.multipoolminer -p x --keepalive --nicehash
                                               --donate-level 1
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\Equihash-EWBF\miner.exe --eexit 1 --api --server us-east.equihash-hub.miningpoolhub.com --port 20594 --user matticus04.multipoolminer --pass x --fee 0 --intensity 64
0.00 PH/s 00 Days 00 Hours 03 Minutes Once     Bin\Equihash-Claymore\ZecMiner64.exe -r -1 -mport 13333 -zpool stratum+tcp://us-east.equihash-hub.miningpoolhub.com:20594 -zwal matticus04.multipoolminer -zpsw x -allpools 1

Miner                  Pool               Algorithm   Watchdog Timer
-----                  ----               ---------   --------------
ClaymoreAmd            MiningPoolHub      CryptoNight    128 Seconds
CcminerNanashi         MiningPoolHub      Lyra2z         198 Seconds
CpuminerJayddeeSse42   MiningPoolHubCoins Lyra2z       1,523 Seconds
XmrigCpu               MiningPoolHubCoins CryptoNight  1,303 Seconds
ClaymoreAmd            MiningPoolHubCoins Equihash     1,302 Seconds
Ewbf                   MiningPoolHubCoins Equihash     1,301 Seconds
XmrigAmd                                  CryptoNight    852 Seconds
FireiceCpu                                CryptoNight  1,301 Seconds
CcminerKlaust          Hashrefinery       NeoScrypt    1,301 Seconds
CcminerTpruvot         Hashrefinery       NeoScrypt    1,088 Seconds
CpuminerJayddeeAesavx2 MiningPoolHub      Lyra2z         198 Seconds
CpuminerJayddeeSse42   MiningPoolHub      CryptoNight      0 Seconds
Dstm                   MiningPoolHub      Equihash         0 Seconds

MultiPoolMiner is between 0% and 14% more profitable than the fastest miner:

Miner                                                                      BTC                             USD                             EUR
-----                                                                      ---                             ---                             ---
MultiPoolMiner                                                             0.00051 ±15 % (0.00044-0.00059) 8.60051 ±15 % (7.45450-9.92269) 7.17623 ±15 % (6.22001-8.27946)
{Dstm-Equihash, ClaymoreAmd-CryptoNight, CpuminerJayddeeSse42-CryptoNight} 0.00048 ±6 % (0.00045-0.00051)  8.04237 ±6 % (7.58079-8.53204)  6.71052 ±6 % (6.32539-7.11911)

**Comment by aaronsace** [comment]
Please can you attach the log file(s)?

**Comment by matticus04** [comment]
[2017-12-11_17-30-33(1).txt](https://github.com/aaronsace/MultiPoolMiner/files/1550130/2017-12-11_17-30-33.1.txt)

**Comment by aaronsace** [comment]
Really odd, I can't think what could possibly cause this. 

Can you try getting a fresh download and delete the old one?

**Comment by matticus04** [comment]
Sure, I'll let you know what happens.

**Comment by matticus04** [comment]
Well, it hasn't happened since the reload. Something must have gotten corrupted.

**Comment by dwayneem** [comment]
Very much still an issue using the latest version, 2.7.1.2 downloaded from Github. Don't you notice all of the  extra coins you are getting out of nowhere? Sounds a bit like a scam to me.
