### ISSUE TITLE
How to get crash log?

### ISSUE THREAD

**Issue by zoglun** [aaronsace/MultiPoolMiner#639]
I used to able to ran Nicehacked for week without crash and/or reboot.
However, MultiPoolMiner generally crash everyday or shorter period of time. This does not resolve even if I under clock GPU.

I tried to find info in system log but found nothing. Guessing this problem caused by 1 specific mining software, but I have no idea which one to remove.

How to get useful crash log for debug?

**Comment by aaronsace** [comment]
As it's not MultiPoolMiner that's crashing all you can see is the last running miner in the log.

**Comment by aaronsace** [comment]
You can gut the miners folder, just keep a few ones that work well on your system.

**Comment by zoglun** [comment]
Not the same mining software crash each time. Either they all have problem or problem exist some where else. 
If this is problem in MultiPoolMiner, I will tried to submit patch for that.
Thank you for your reply!

**Comment by UselessGuru** [comment]
@zoglun 
Have you overclocked you GPU memory? -> reduce to stock, same for CPU & GPU
As aaronsace has said: It is NOT MPM that's crashing, it's one of the miners.
MPM uses some of the same miners as NH, but it can use a lot of others. I suspect that one of the new miners is causing the crashes.
I have also seen crashes when the power supply unint n the PC is old / too weak. This only happened only with some algos, e.g. Skunkhash that causes high current peaks.
