### ISSUE TITLE
My powershell is not working. It never has. 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#640]
Yes, I followed the links and installed powershell for my windows 7 x 64. (yes, the correct file) When I tried to install it, it said it was already installed. Cool!

But yet when I run multipoolminer, I never see the powershell window and the pretty light blue background. All I get is the old style cmd window with the black background. Is there some sort of setting I'm missing? Do I need to adjust the cmd window size? 

Everybody else I see who posts screenshots has the nicer powershell / blue background window. I want that. :)

**Comment by milewski** [comment]
well i im on window 10 and i do not bothered downloading any new version of powershell i guess i might be using the latest already... and when i open the start.bat for example.. i do see the powershell opening once to setup some firewall rules and then gone,.... back to the "black old cmd screen" but everything works fine as expected... what is your problem in specific?

**Comment by aaronsace** [comment]
Ha, it's because it launches PowerShell in command prompt. 

You can get the pretty background by putting the word 'start' before the word 'powershell' inside the 'bat' file.

**Comment by cmbconcretefire** [comment]
Yeah, I like the pretty colors. :) Thanks. I'll give it a shot.

**Comment by cmbconcretefire** [comment]
@aaronsace , I swear I'm not trying to be dense......but could you perhaps SHOW me with an actual example from the start.bat WHERE I am supposed to put the word 'start' before the word powershell? YES, I see the first mention of the word 'powershell' but it is preceeded by %COMMAND%powershell. So do I erase the %command%powershell and put 'start powershell?' ---- a straight cut and paste from an actual start bat would help. Or edit what I put in below with your word 'start' in all caps. START ????

2) AFTER this > -donate 24 -watchdog" in the new start.bat, are all these additional lines of code necessary? IE: What do they do? pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qn; %command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause

**Comment by milewski** [comment]
```diff

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -wallet ...... -username ...... -workername ...... -region asia -currency btc,usd,cny -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool -algorithm ..... -watchdog"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
- powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command 
+ start powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "msiexec -a https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qn; %command%"
msiexec -a https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause
```

**Comment by cmbconcretefire** [comment]
Thank you @milewski , I tried to follow your example. I assume Red means delete, Green means add. That's what I did. Have a look for yourself. My entire start.bat 

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -username drog1 -workername mpm -region us -currency btc,usd -type nvidia -poolname miningpoolhub -algorithm lyra2re2 -donate 24 -watchdog"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%" start 
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qn; %command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
pause

Either I am not doing something right, OR, my powershell just isn't working for some reason.

**Comment by milewski** [comment]
you shouldnt add any line break on these commands.. everything should be on a single line.. the formatting on the github forced me to add them... sorry

```
setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=&.......

pwsh -noexit -executi......
pwsh -noexit -executi......
pause
```

**Comment by cmbconcretefire** [comment]
Sir, here is my actual start.bat. I'm going to ask flat out, can you fix it please? Apparently, even though I have tried, I cannot get the powershell to work. Soon, I'm going to be running with scissors. Lol. If you fix it, then I can compare it to the original and see where I went wrong. I honestly believe I've done everything you and aaronsace asked me to do and it's either not working, or I did something wrong. Please? Then I can finally move on to more pressing issues in this miner. 

[Start-MiningPoolHub.txt](https://github.com/aaronsace/MultiPoolMiner/files/1554367/Start-MiningPoolHub.txt)

**Comment by milewski** [comment]
[Start-MiningPoolHub.txt](https://github.com/aaronsace/MultiPoolMiner/files/1554437/Start-MiningPoolHub.txt)

**Comment by cmbconcretefire** [comment]
Thank you sir. I just tried it. I'm still getting the old cmd style window with the black background. Any suggestions on how to fix this issue? At this point, and with your help, I believe the problem is definitely on my end. Any way to un-install powershell and re-install it? And should I try the new powershell rc? I'm at a loss.

**Comment by milewski** [comment]
well when i start that bat.. it does open the black screen.. starts installing the powershell-rc-something... and then open that blue screen u are talking about... i dont know whats wrong with your setup... but what have of so special in that blue screen? its just heavier than having the old B&W cmd

**Comment by cmbconcretefire** [comment]
That's a fair question. However, I will tell you on my setup / rig / it does NOT start installing the powershell-rc. As to your question of why I want it to work so badly, it's because everybody else's seems to work fine. 
And it stretches horizontal accross the screen where you can see everything better IMHO, where as the old cmd stretches vertical . I don't think there's anything special about the powershell , I'd just like to get it working like everyone else. 

As you were looking over my txt file, I'm sure you noticed I currently only have lyra2re2 selected. I have managed to get the correct miners in the \Bin folder and 4 miners benchmarked just fine. My fastest miner is the Palgin version and it's been running for a good bit, but down at the bottom where it's supposed to show your 'profits' (or at least estimates) < all that info is missing. But that was an issue I was going to bring up after I solved this powershell thing....... sigh. lol.
