### ISSUE TITLE
Excavator being a pain. Will not benchmark. 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#641]
See pic for error. 

![capture](https://user-images.githubusercontent.com/23691069/33877827-9710bf7e-def7-11e7-9941-b0d3fc500389.PNG)

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/commit/aee83cc2852343be3d8e159f4dcd5f5380aafb08
