### ISSUE TITLE
benchmark vs real results in pool

### ISSUE THREAD

**Issue by JhonJhonny** [aaronsace/MultiPoolMiner#644]
as the title says i have my rig which is composed by 3 gtx 1080 from the benchmarks should do with the most profitable algorithms around 0.0009-0.0010 btc a day but after some mining (btw i'm mining on miningpoolhub) i've noticed that the actual incomes are significantly lower around 0.0005-0.0006 btc a day.
i've already tried to reset and redo the benchamarks and even reset the profit (the .bat file inside the folder of multipoolminer), i've got no error whatsoever when doing all the things with the multipoolminer so.. any suggestion is accepted, thanks in advance

**Comment by aaronsace** [comment]
I doubt the benchmarks are wrong; try less algorithms as switch too much on MiningPoolHub is bad. 

Zpool has no switching loss so it is better for NVidia because Ethereum is not profitable and there is no top coin.

**Comment by JhonJhonny** [comment]
actually the rig is switching between lyra2z, lyra2re2, skein and neoscrypt and its up from this morning.
what do you mean with "switching loss" and why does zpool do not have this (i'm assuming is a bad thing to have this switching loss)
so for my rig you think its better to mine on zpool?
i know these are a lot of question lol, just try to open my knowledge

**Comment by aaronsace** [comment]
lyra2z is a bit dodgy as there are many people in the forums saying the hashrate is wrong. I may disable it by default on the next release. 

Search PPLNS vs PROP. 

I can't say anything for certain; experiment a bit and see what you find works best.

**Comment by JhonJhonny** [comment]
@aaronsace this is what i was talking about:
in these two photos you should see that miner says that i should be mining lyra2v2 at 147 mh/s
but actually the pool graph says that my highest peak was at about 72mh/s

maybe there is something i didnt understood
![a](https://user-images.githubusercontent.com/30692674/33908998-66121c40-df8a-11e7-9364-5a79151c6289.png)
![b](https://user-images.githubusercontent.com/30692674/33909000-663d7a2a-df8a-11e7-84e8-76b7cf0678fd.png)

**Comment by aaronsace** [comment]
It's a 1 hour average on that graph so mining for 30 minutes looks like half. There is also two coins not one, check the other graph as well.

**Comment by JhonJhonny** [comment]
can you explain a little better please?(the part about the 1 hour average and 30 minute and so on xD) sorry but english is not my native language.
Btw the graph i attached was about "monacoin", which one should be the other? "vertcoin"?

**Comment by aaronsace** [comment]
The graph uses an average speed over 1 hour so if you only mine for 30 minutes then it looks like half the speed. 

Yes, Vertcoin.

**Comment by JhonJhonny** [comment]
@aaronsace ok got it, so if using an algo switcher like yours the graphs are a bit inconsistent... 
btw this is the graph of vertcoin.
to be honest, do you suggest zpool for nvidia?
anyway i have the same problem, the effective balance that i've got for the time i mined is lower that what should be and i dont understand why. hope you could shout to me some hint to try and solve this problem
![c](https://user-images.githubusercontent.com/30692674/33910102-e98a47e8-df8d-11e7-98fd-f7925a4d14d6.png)

**Comment by aaronsace** [comment]
This particular algorithm does seem to cause problems. There are a few miners included; maybe try disabling the one you are using.

**Comment by JhonJhonny** [comment]
@aaronsace so there was something xD ok i tried to disable cc miner palgin, the one i was using for lyra2v2, hope it does something, thanks a lot, for the time and patience, i update here if the issue will be solved, in the meantime i'll leave the issue opened if it's not a problem.
what about the thing with zpool and nvidia, would you suggest it?

**Comment by aaronsace** [comment]
Zpool is better, faster API, uses PROP and has far more altcoins. Should be close to NiceHash PPS.
