### ISSUE TITLE
Option to restart miner instead of failing if tolerance falls below threshold

### ISSUE THREAD

**Issue by tavenger5** [aaronsace/MultiPoolMiner#645]
This would be especially helpful for AMD Vega miners using Cast XMR. Sometimes hash just drops by 200 and the miner just needs to be restarted to fix it. As it is, this causes Cast XMR to fail and another miner is used. 

Other times it drops by 500 h/s and the HBCC memory setting just needs to be toggled, but that is a different story. This usually only happens if another program interferes and uses too much GPU power.

**Comment by aaronsace** [comment]
There is no way for MultiPoolMiner to know what the problem is; it's safer to switch to another miner.

**Comment by aaronsace** [comment]
You'll find the latest code branch more tolerable because it uses a dynamic interval: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip
