### ISSUE TITLE
Virus in every single .exe file?

### ISSUE THREAD

**Issue by k4ppe** [aaronsace/MultiPoolMiner#648]
Avast was blocking all .exe files, even Defender found malware and nearly all .exe files looks like this result from virustotal:
 https://www.virustotal.com/da/file/0baae5bfc9153c33f1fe1c14320baca4b0abc6fcd194183e51f8f6f1ca2b7c5b/analysis/1512829121/

Why is that?

**Comment by aaronsace** [comment]
Add the whole folder to your virus exemptions. 

The reason why nobody complains here is because 99% of people use Windows Defender and MultiPoolMiner adds the exception for you. 

Why? Lazy companies that flag the miner instead of all the Trojans that use the miners.

**Comment by k4ppe** [comment]
A reply in 7 minutes? Wow! :)
Thank you for your explanation.

**Comment by aaronsace** [comment]
No worries, been a hectic week.

**Comment by BigLargeGay** [comment]
I'm having the same problem. Using bitdefender 2018. I whitelisted the files but whenever I extract them all it does is "disinfect" (delete) all the .exe files. I found that cgminer.exe is one that comes up more often with the problem being that it dosnt want to extract from the .zip. 

Help???

**Comment by aaronsace** [comment]
Disable bitdefender or add the folder to the exceptions list.
