### ISSUE TITLE
Multipoolminer.ps1 is not recognized...

### ISSUE THREAD

**Issue by WilliamSkyWalk** [aaronsace/MultiPoolMiner#649]
After I opened Start.bat, there is always a red message. And it tells me ''.\Multipoolminer.ps1'' cannot be recognized as a cmdlet, function or .... Please check your spelling, and try again.

**Comment by aaronsace** [comment]
Just double click on start.bat and don't move it.

**Comment by aaronsace** [comment]
You up and running?

**Comment by WilliamSkyWalk** [comment]
It seems that it doesn't solve the question although I followed your [instructions.](https://imgur.com/a/9rZGH) @aaronsace
