### ISSUE TITLE
State file was not updated because value is outside fault

### ISSUE THREAD

**Issue by hotlunch** [aaronsace/MultiPoolMiner#650]
Not sure what this warning means hope it isn't effecting anything. Any info to resolve? 

![capture4](https://user-images.githubusercontent.com/34494057/33915060-1f5d592e-df56-11e7-93c8-29246dcd8d8a.PNG)

**Comment by aaronsace** [comment]
No but don't mine Scrypt, X11, X13, X14, x15, Qubit or Quark

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip
