### ISSUE TITLE
Excavator Algos Not Benchmarking

### ISSUE THREAD

**Issue by nathanfsb** [aaronsace/MultiPoolMiner#651]
I downloaded and extracted the latest excavator files into /bin, however when I first ran my start.bat with these algos:

> Blake-Vanilla,Cryptonight,Equihash,Ethash,Groestl,Lyra2RE2,Myriad-Groestl,NeoScrypt,Quark,Qubit,Skein,lyra2z,x11,x13,x15

I found that those which used excavator didn't benchmark.

What can I do to fix this? It's causing my miner to default to Zcoin as the most profitable when it is close to half as much BTC/day.

Thanks

**Comment by UselessGuru** [comment]
Is excavator listed in the profit overview and says 'Benchmarking'?
If not then there is:
- MPM does not find the excavator binary (e.g. $Path = ".\Bin\NVIDIA-Excavator_138a\excavator.exe")
- no pool providing data for any of the excavator algos
- something wrong with the excavator miner file (re-download)

**Comment by aaronsace** [comment]
Also, if you have Windows 7 then use this version: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

Please note that you will need to copy the 'bin' folder over manually.

**Comment by aaronsace** [comment]
If you are still having issues then reopen.
