### ISSUE TITLE
just a question about scrypt mining

### ISSUE THREAD

**Issue by JhonJhonny** [aaronsace/MultiPoolMiner#652]
i tried pointing the mutli pool miner to zpool and after benchmarking all the algo that i choosed it turns out that the most profitable was and is scrypt and it seem be going fine but when i check the details on the site of zpool and i put the code of my wallet to check it says that i'm mining scrypt algo but does say  "hashrates --" and "shares 0%"
don't know what to think as it detect that 1 miner is mining but it seems it is not reporting hashrates or shares..
i'll leave it there this night and hope, i will report tomorrow morning
![d](https://user-images.githubusercontent.com/30692674/33916710-6dc12d3a-dfaa-11e7-9de2-b85615f38fbd.png)

**Comment by aaronsace** [comment]
Scrypt isn't profitable, nobody should mine Scrypt. Use the algorithms that I put in the start.bat file.

**Comment by aaronsace** [comment]
Note to self: add divisor for Scrypt

**Comment by JhonJhonny** [comment]
Well, it was in the read me file so I tried it. Btw after the benchmark it
was saying 0.004 so I thought it was profitable, thanks for the info

Il 13 Dic 2017 11:02, "aaronsace" <notifications@github.com> ha scritto:

**Comment by lmlim** [comment]
What about Lyra2RE2? it didnt show up in start.bat, but it is very profitable.
also Nist5? and some other algos that available in zpool? X17?

**Comment by aaronsace** [comment]
@lmlim Just don't mine ASIC algorithms: Scrypt, X11, X13, X14, x15, Qubit or Quark
