### ISSUE TITLE
Move Multi pool Miner to another PC?

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#653]
I am setting up a different machine to do my mining.

Can I just close the Miner, copy the the Miner and folders including the bin system32 folder to new computer?  Or should I just start over?

**Comment by UselessGuru** [comment]
It is best to start from scratch.
From the old PC take only the customized files, e.g start.bat
It the target has the same HW you can also copy the stats folder - this will skip the benchmark loops.
