### ISSUE TITLE
Difference Object Error

### ISSUE THREAD

**Issue by ADSpeelman** [aaronsace/MultiPoolMiner#655]
Just downloaded this tonight. I updated Start.bat with my wallet, user name and worker info and ran it as admin. Then I get a giant wall of red text stating Difference Object errors. Please help. I've deleted and redownloaded it a few times now but to no avail.  Below is my log.
[2017-12-12_23-15-48.txt](https://github.com/aaronsace/MultiPoolMiner/files/1554115/2017-12-12_23-15-48.txt)

**Comment by vulcan78** [comment]
I'm having the same exact problem. I've taken to the readme.txt and I've check all of the following. I have no idea why it's doing this: 

"If you are using Windows 7, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395
- CCMiner (NVIDIA cards only) may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784
- CCMiner (NVIDIA cards only) may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145
- You may need 'excavator.exe' if you don't already have it: https://github.com/nicehash/excavator/releases"

I have 32 GB of physical memory on tap (Win 7 Pro) so it can't be a lack of system memory.

**Comment by ADSpeelman** [comment]
I was running this in my main directory C:\. Once I moved it to a secondary harddrive I've not had any of the same issues. I believe that because it's the primary windows partition, windows securities prevents modification of those files. I've had to download a few other miners and such here and there and place them in folders, and restart this thing multiple times, but I believe I have it running correctly now. Try just moving your folder to a non-windows HD @vulcan78 ?

**Comment by vulcan78** [comment]
Ohhhhh, this might be the problem! I have it in C:/ProgramFiles DOH!

**Comment by vulcan78** [comment]
Now it's saying that I can't move the folder because Multipool Miner is open in another application (it isn't).

**Comment by ADSpeelman** [comment]
Make sure you don't have any of the .bat files or readme open.

**Comment by vulcan78** [comment]
It was the readme lol, thanks.

**Comment by ADSpeelman** [comment]
I only know because I did the same thing lol

**Comment by ADSpeelman** [comment]
Closing this as I was able to fix the issue by moving to a non root folder.
