### ISSUE TITLE
included "sgminer" causes BSOD with error code "THREAD_STUCK_IN_DEVICE_DRIVER"

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#657]
OS: windows 10 pro 64 bit version 1709 build 16299.125
CPU: intel core i5-6500
RAM: 16GB
GPU(s):
**1.AMD Radeon RX 570 4GB**
     =(ASUS) {bios modded Elpida} [main]
     =core 1150MHZ mem 1900MHZ
**2.AMD Radeon RX 470 4GB** 
     =(MSI Gaming X) {bios modded SK Hynix}
     =core 1305MHZ mem 1950MHZ
**3.AMD Radeon R9 370 4GB** 
     =(XFX) {Samsung}                                         
**CrossfireX disabled**
Driver version: Radeon Crimson Relive 17.11.4
Logs for MultiPoolMiner
Can't get sgminer logs
[2017-12-13_20-29-24.txt](https://github.com/aaronsace/MultiPoolMiner/files/1555514/2017-12-13_20-29-24.txt)

p.s. If you can't solve it, please report this issue to the author of sgminer.

**Comment by aaronsace** [comment]
@felix920506 Please delete Sgminer from the folder called 'miners'. Sorry but I can't report everyone's problems.
