### ISSUE TITLE
Multipoolminer.ps1 is not recognized... 

### ISSUE THREAD

**Issue by WilliamSkyWalk** [aaronsace/MultiPoolMiner#659]
After I opened Start.bat, there is always a red message. And it tells me ''.\Multipoolminer.ps1'' cannot be recognized as a cmdlet, function or .... Please check your spelling, and try again.
And I can't solve the problem although I tried (https://github.com/aaronsace/MultiPoolMiner/issues/649)
It just keeps giving this message (https://imgur.com/a/9rZGH)

**Comment by aaronsace** [comment]
Don't put it System32, just put it on your desktop.

**Comment by WilliamSkyWalk** [comment]
The problem seems to be not solved. (https://imgur.com/a/Lfy2m)

**Comment by aaronsace** [comment]
It's too blurry, I can't read it. 

You can upload files straight to GitHub; may be better quality.

**Comment by WilliamSkyWalk** [comment]
The Chinese above means The term '.\multipoolminer.ps1' is not recognized as the name of a cmdlet, function, script file, or operable prog
am. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![problem](https://user-images.githubusercontent.com/34493264/33942486-03d03bda-e051-11e7-9e11-64b0f22b46e6.png)

**Comment by aaronsace** [comment]
It not just says 'c:\'. 

It should be the location of the files: 
'C:\Users\[you name]\Desktop\MultiPoolMiner\'

**Comment by WilliamSkyWalk** [comment]
Thank you a lot, it's finally solved.
