### ISSUE TITLE
Issue running start

### ISSUE THREAD

**Issue by rafakortez** [aaronsace/MultiPoolMiner#66]
& : The term '.\multipoolminer.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:2
+ &.\multipoolminer.ps1 -username aaronsace -workername multipoolminer  ...
+  ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\multipoolminer.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by aaronsace** [comment]
Hi, please can you explain what you are doing?

**Comment by aaronsace** [comment]
If you have Windows 7, please update PowerShell:
https://www.microsoft.com/en-us/download/details.aspx?id=50395
