### ISSUE TITLE
Reorder - cgminer

### ISSUE THREAD

**Issue by uprise88** [aaronsace/MultiPoolMiner#660]
MPM cant downaload this

WARNING: Cannot download C:\Users\Upris\Desktop\MultiPoolMiner-master\Bin\Reorder\cgminer.exe.

Is there any way to download it manually like i did with Excavator?

Thx

**Comment by aaronsace** [comment]
There is a 'bin' folder in the release: 
https://github.com/aaronsace/MultiPoolMiner/releases/download/v2.7.0.2/MultiPoolMinerV2.7.0.2.zip

**Comment by uprise88** [comment]
Thx a lot
