### ISSUE TITLE
What's the problem with my commands ? 

### ISSUE THREAD

**Issue by orhnctnr** [aaronsace/MultiPoolMiner#661]
After i started "Start-MiningPoolHub" bat file , i am getting this error. P.S : MultiPoolMiner file is on Desktop.

![screenshot_1](https://user-images.githubusercontent.com/34513348/33943316-d12b192e-e029-11e7-9afe-bef65b878008.jpg)

And i also using Powershell v4.0 and i changed it as powershell -version 4.0 instead powershell -version 5.0
in .bat file. ( Couldnt Install v5.0 for win8.1 pro ) Is that matter ? 

Thanks in advance

**Comment by orhnctnr** [comment]
And this is my .bat file ;

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

powershell -version 4.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username xxx -workername xxx -region europe -currency usd -type amd,cpu -poolname miningpoolhub -algorithm cryptonight,Lyra2RE2,ethash,ethash2gb,equihash,groestl,neoscrypt -donate 10 -watchdog"

**Comment by aaronsace** [comment]
Someone else just has this problem, I don't understand how but you are launching it in the wrong folder. It should not say `C:\Users\Administrator`; it should be the path to MultiPoolMiner. 

BTW the minimum requirement is Version 5 but that is a separate issue.

**Comment by Vxrl** [comment]
@aaronsace I think it's because he's running the .bat file as Administrator. When I run my .bat file as administrator, the working directory is C:\WINDOWS\system32, instead of the actual .bat directory.

**Comment by aaronsace** [comment]
Nice, let's get that in the default 'bat' as I bet others must have this issue: 
`cd %~dp0`

**Comment by orhnctnr** [comment]
I just solved by changing it as C:\Users\Administrator\Desktop\MultiPoolMiner\.\Start_PoolMiningHub

[Another " .\ " after the File Name ]

**Comment by aaronsace** [comment]
@orhnctnr Did you manage to install PowerShell 5 as well?

**Comment by orhnctnr** [comment]
Nope . i am still trying to figure out

**Comment by aaronsace** [comment]
Try the new code branch as it uses PowerShell 6 and auto installs: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

You'll just have to copy the 'bin' folder from the release as it's not included in the code.

**Comment by orhnctnr** [comment]
@aaronsace 

Now , i am getting the first error ; 
![screenshot_1](https://user-images.githubusercontent.com/34513348/33951641-947ea0ec-e040-11e7-95ec-2fe169e22419.jpg)

Where should i add cd %~dp0 exactly ?

**Comment by orhnctnr** [comment]
Now , its okay. I just double click on .bat file instead typing it manually on cmd and it works.

**Comment by akarakucuk** [comment]
Hey, I have similar issue.  The think is, my desktop is not on C and it's on D. Windows is installed in C.
