### ISSUE TITLE
Opens cgminer in AMD type

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#663]
cgminer is for ASICs, just remove it.

**Comment by Tyserie** [comment]
Please, what is a proper way to remove cgminer so its not trying to use him for mining on AMD rig?

**Comment by fonyo** [comment]
@Tyserie [FAQ#2](https://github.com/aaronsace/MultiPoolMiner/blob/master/README.md#q2-a-miner-crashes-my-computer-or-does-not-work-correctly-i-want-to-exclude-it-from-miningbenchmarking-what-should-i-do)

**Comment by Tyserie** [comment]
thx man, really apreciate the help ;)
