### ISSUE TITLE
MultiPoolMiner is between X% and YY% more profitable than the fastest miner:

### ISSUE THREAD

**Issue by lmlim** [aaronsace/MultiPoolMiner#665]
Hi Aaronsace,

my rigs always shows this yellow warning after a couple minutes running.
and i noticed that if stop mining and resetprofit and run it again, the algos listing is different than before
thus it is running different algo than before "resetprofit". and the warning disappear.

and then after several minutes, the warning will show up again.
do i miss anything here?

thanks you

**Comment by aaronsace** [comment]
If you reset the profits then there is nothing to show. It will show after a few minutes once the comparable miner diverges from MultiPoolMiner.
