### ISSUE TITLE
Profitability

### ISSUE THREAD

**Issue by OGGrandma** [aaronsace/MultiPoolMiner#666]
Hi, currently I am mining cpu/gpu lyra2z and groest1

The profitability is being calculated as lower for miningpoolhub vs individual miners atm despite my hashrate staying the same, does anyone know what's up? I'm sure that my gpu isnt the problem as I've had more profit on miningpoolhub in the past

**Comment by OGGrandma** [comment]
Closing issue, seems to be addressed here.
https://github.com/aaronsace/MultiPoolMiner/issues/588#issue-280547912

**Comment by OGGrandma** [comment]
Looks like my cpu mining throws off and is added to the "typical" miner and as a result makes it look less profitable>?

**Comment by OGGrandma** [comment]
Confirming, looks like cpu adds only to the non multipool miner and as a result profits look "bad"

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
