### ISSUE TITLE
Mo questions

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#667]
1) I finally got the friggin' powershell thing working. It was an issue on my end as suspected. 
2) ethash2gb (or whatever it is) --- *IF* all of my Nvidia cards are all 6 & 8gb, do I need / should I still include this algo? There is nothing DEFINITIVE (IMHO) in the readme one way or the other. 

3) Can someone please explain this lyra situation? Example: There's several different variants of lyra, like lyra2re2, lyra2rev2, lyra2v2 < and according to the algo.txt all 3 of those = Lyra2RE2.....so, what's the difference? Wouldn't just ONE in the bat file suffice? 

4) And then there's lyra2z ??

**Comment by cmbconcretefire** [comment]
PS. ...
5) Hashrefinery API does not seem to be working. But their site is up. Should I delete that api in the pools folder or just wait for it to start working again? 

6) Excavator STILL fails to run - even though I downloaded the latest version (with the excavator fix included this morning) AND even though the miner automatically downloads what appears to be a good copy of excavator and creates the folder 'Excavator' inside the 'bin' folder. I look in there, and it appears to me that all of the excavator files , including the .exe file is there. So......???

**Comment by aaronsace** [comment]
There is a new release: 
https://github.com/aaronsace/MultiPoolMiner/releases

lyra2re2 and lyra2z are being investigated by @Korennya
