### ISSUE TITLE
Status: Failed, why?

### ISSUE THREAD

**Issue by giust** [aaronsace/MultiPoolMiner#668]
Hello,

There are several times that it fails when it switches between algos. It seems that it is always the same algos that fail, for example x17 was failing over and over. I don't know whether I need to download any package myself or this is a normal issue. As far as I know it tries to get some packages but some fail. As an example I'll drop the log here, I see that it fails but I don't see why so I cannot correct the issue.
[2017-12-13_09-11-28.txt](https://github.com/aaronsace/MultiPoolMiner/files/1557001/2017-12-13_09-11-28.txt)

Thanks

**Comment by giust** [comment]
It is getting worse, it fails almost every time. What can I do? 
[2017-12-13_20-58-40.txt](https://github.com/aaronsace/MultiPoolMiner/files/1557169/2017-12-13_20-58-40.txt)

**Comment by UselessGuru** [comment]
Remove the nicehash.ps1 from the pool folder (nicehash is dead for now).

**Comment by giust** [comment]
Ok I'll try that thanks. However errors come from other pools and algos, I'm having many errors from zpool. One common error is about memory allocation (I have a gtx 1080)

**Comment by UselessGuru** [comment]
> One common error is about illegal memory access

Overclocking???? <try with stock speed first.

**Comment by giust** [comment]
@UselessGuru thanks again, I had +200/+400. I'll try stock settings and let you know

**Comment by giust** [comment]
Still not working. For some reason the algo Scrypt in zpool is never working, but I did not get an error. It seemed it initialized but I don't get any shares. But other algos like nist5 in hashrefinery run smooth

**Comment by UselessGuru** [comment]
Do not mine Scrypt, it is NOT profitable. Stick to the algorithms in the default start.bat:
cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib

**Comment by giust** [comment]
Ok, I guess the profitability tool is broken then. I have seen several peaks of Scrypt at 0.0015 btc/day, more than 3 times more profitable than the second algo. I would also add lyra2rev2, that was the main algo I was mining when nicehash was running

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
