### ISSUE TITLE
Error when setting up pleas help Ben trouble shooting for days 

### ISSUE THREAD

**Issue by luke710** [aaronsace/MultiPoolMiner#670]
![img_1473](https://user-images.githubusercontent.com/34526026/33969245-3771d0dc-e03a-11e7-9009-1a619d93b36b.PNG)

![img_1474](https://user-images.githubusercontent.com/34526026/33969672-9061f4ea-e03c-11e7-8eb5-1f6be7191cea.PNG)

Iv download excavator 
Im running windows 10 64bit 
Iv download CCminer need visual studio 2013 but when I try to download 2015 version says I allready have it.  
But as soon has I start the minner it runs for about 5 second and then I get the error repeating endlessly 
If some one could pleas help me out or point me in the right direction it would very much appreciated.

**Comment by aaronsace** [comment]
Extract the contents onto your desktop not 'AppData\Local\Temp'

**Comment by luke710** [comment]
I have the program folder it's self extracted to my desktop. shuold I extract the temp folder do my desktop or the files in the temp folder ?

**Comment by aaronsace** [comment]
You need to double click on 'start.bat'.

**Comment by luke710** [comment]
I keep extracting every file when it throws the error. Then I close the program and start it agen it will say downloading and then throw anuther error then I have to repeat extracting the file agen and restarting the program. Do I nead to keep doing this till it's done or is the a better way to do it ?

**Comment by aaronsace** [comment]
Please post the log file.

**Comment by aaronsace** [comment]
Please also do a screenshot of the folder contents.

**Comment by luke710** [comment]
![img_1477](https://user-images.githubusercontent.com/34526026/34012112-8288a59a-e0e0-11e7-8aac-31786e6c84ef.PNG)
![img_1478](https://user-images.githubusercontent.com/34526026/34012121-888f653c-e0e0-11e7-8d89-931848b72ae5.PNG)
![img_1479](https://user-images.githubusercontent.com/34526026/34012158-ad3a0b8a-e0e0-11e7-8665-6bb46b5b5adf.PNG)
![img_1480](https://user-images.githubusercontent.com/34526026/34012159-ad59e6b2-e0e0-11e7-9d6e-dcbdabf42871.PNG)
Iv Ben extracting everything to my desktop form the temp folder when I throw a error 
Every time I run the start.bat I dubble klick it and iv tryed running as admin

**Comment by luke710** [comment]
Thank you for trying to help me out iv verry much a apresheat it this problem Ben driving me nuts

**Comment by luke710** [comment]
![img_1481](https://user-images.githubusercontent.com/34526026/34012582-591c335a-e0e2-11e7-98e4-2a3ae7755d55.PNG)
Here's more of the log

**Comment by aaronsace** [comment]
Not of that looks right, just delete everything. Simple extract the contents of the zip folder then this is what it should like: 

![image](https://user-images.githubusercontent.com/21113644/34012796-08f265fe-e10d-11e7-9766-877ca1cdb24c.png)

**Comment by aaronsace** [comment]
Then double click on the 'start.bat' file to launch it.

**Comment by luke710** [comment]
Should I put in my info befor I start the start.bat file or should I just run it with the info allready in there

**Comment by aaronsace** [comment]
Just double click; is it working now?

**Comment by luke710** [comment]
![img_1482](https://user-images.githubusercontent.com/34526026/34015322-17f77d80-e0ec-11e7-8318-59391a45103b.PNG)
 It booted up in to benchmark and 2 miners started but it's still throwing the error

**Comment by luke710** [comment]
![img_1483](https://user-images.githubusercontent.com/34526026/34015423-5e6ab052-e0ec-11e7-8324-21a2d3d8a07a.PNG)

**Comment by luke710** [comment]
![img_1484](https://user-images.githubusercontent.com/34526026/34015662-2d49825e-e0ed-11e7-9661-dc480559935f.PNG)

**Comment by aaronsace** [comment]
There is something wrong with your system. Seems like you've been locking it down or changing settings. 

Everything you are doing is correct.

**Comment by aaronsace** [comment]
The very first error indicates there must be a problem even opening PowerShell: 

> Cannot load PS Readline module.

**Comment by aaronsace** [comment]
Maybe you can bypass all your problems by move to PowerShell 6: 
https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

**Comment by aaronsace** [comment]
The only other option that I know will work is installing a fresh version of Windows 10 x64.

**Comment by luke710** [comment]
Thanks for trying to help but nothing ends up working and I don't have a fresh windows 10x64 to install so I can't even try that. Thank you thoug I appreciate all that youv done to try to help

**Comment by aaronsace** [comment]
Shame you didn't sort this. 

New release works well with PowerShell 6: 
https://github.com/aaronsace/MultiPoolMiner/releases
