### ISSUE TITLE
RemoveJob Error on launch

### ISSUE THREAD

**Issue by Lycerion** [aaronsace/MultiPoolMiner#671]
Transcript started, output file is .\Logs\2017-12-13_16-13-32.txt
Remove-Job : The command cannot remove the job with the job ID 73 because the job is not finished. To remove the job, 
first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\--\Desktop\Mining\MultiPoolMinerV2.7.0.2\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], 
ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand
Remove-Job : The command cannot remove the job with the job ID 73 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job
At C:\Users\--\Desktop\Mining\MultiPoolMinerV2.7.0.2\Include.psm1:294 char:12
+     $Job | Remove-Job
+            ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...n.PSRemotingJob:PSRemotingJob) [Remove-Job], ArgumentException
    + FullyQualifiedErrorId : JobObjectNotFinishedCannotBeRemoved,Microsoft.PowerShell.Commands.RemoveJobCommand

--------------------------------------------------------------------------------------------------------

I'm not sure if this affects anything, because the script still launches.

**Comment by aaronsace** [comment]
It will continue to function fine. It's has since been fix for the coming release. 
https://github.com/aaronsace/MultiPoolMiner/commit/1a8805575caae31acd2547132b53cda0d656702b
