### ISSUE TITLE
Fireice nvidia bfactor too low for 1070Ti

### ISSUE THREAD

**Issue by Braintelligence** [aaronsace/MultiPoolMiner#673]
Hi everyone.
I had to set the bfactor from 6 to 8 in bin/cryptonight-fireice/nvidia.txt or else xmr-stak wouldn't work on all of my GTX 1070Ti.
Anyone else experiencing this?

**Comment by paulpoco** [comment]
I have a GTX 1070, how do you check if it is working on all of it?

**Comment by UselessGuru** [comment]
> I had to set the bfactor from 6 to 8 in bin/cryptonight-fireice/nvidia.txt

You could also set the parameter in the miner file
For my 1070 (non TI) I also had to define bfactor 8

**Comment by Braintelligence** [comment]
Just set a key bfactor and value 8?

**Comment by UselessGuru** [comment]
@Braintelligence 

> You could also set the parameter in the miner file
> Just set a key bfactor and value 8?

For xmr-stak  it is not all that easy. xmr-stak reads the hw info file, e.g 'bin/cryptonight-fireice/nvidia.txt' and you will have to edit this file as you did.
For other Cryptonight miners, e.g. xmrig-nvidia it is more streight forward and you can add the required parameters to the miner file, e.g.:
        "Arguments":  "--api-port 3335 -a cryptonight -o $($Pools.CryptoNight.Protocol)://$($Pools.CryptoNight.Host):$($Pools.CryptoNight.Port) -u $($Pools.CryptoNight.User) -p $($Pools.CryptoNight.Pass) --keepalive --nicehash --donate-level 1 --cuda-bfactor=10,8,6 --cuda-launch=64x72,53x64,16x77",
(my extra parameters for GTX1080ti/GTX1070/GTX10603GB)

**Comment by aaronsace** [comment]
Please report this to FireIce-UK otherwise they won't know you are having issues with the default configuration.

**Comment by UselessGuru** [comment]
> Please report this to FireIce-UK otherwise they won't know you are having issues with the default configuration.

Done for GTX1080ti/GTX1070/GTX10603GB. Dunno the values for other models :-)

**Comment by Braintelligence** [comment]
I still need to manually set bfactor : 8 for my 1070 Ti and 1080 Ti ...
But it doesn't run stable on my rigs. Many times I get Memory VirtualAlloc failed and only some of my cards are actually running it then.
Maybe I should turn other knobs?
