### ISSUE TITLE
Deleted and started over - 2 windows asking for monero or aeon and then pool address

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#674]
CryptoNight-FireIce asking for currency and pool address.  Miningpoolhub.

I don't remember it asking for the pool address before.

**Comment by paulpoco** [comment]
I had a backup copy of the previous setup.
.
"pool_list":  [
                      {
                          "pool_address":  "us-east.cryptonight-hub.miningpoolhub.com:17024",
                          "wallet_address":  "user.multipoolminer",
                          "pool_password":  "x",
                          "use_nicehash":  true,
                          "use_tls":  true,
                          "tls_fingerprint":  "",
                          "pool_weight":  1

Another topic, the main window is popping up complaining about not finding 7z.exe

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by paulpoco** [comment]
Any tip for upgrading?  I read in the Readme about copying the Stat folder.

Do I just overwrite the new release over the old?
