### ISSUE TITLE
Popup complaining it cannot find 7z.exe

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#676]
Popup complaining it cannot find 7z.exe.
.

7z.exe is in the main directory, weird?

**Comment by aaronsace** [comment]
Check that the start.bat is in the same directory as 7x.exe and that the working directory is set to the same directory. 

Attach the log files and screenshots if you are still having issues.

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by paulpoco** [comment]
It seemed go away after awhile.
 
I made shortcut on my desktop that points to the start.bat in the working directory.
