### ISSUE TITLE
Switching from/closing Cast XMR resets wattman/HBCC, or crashes computer

### ISSUE THREAD

**Issue by tavenger5** [aaronsace/MultiPoolMiner#678]
When Cast XMR is shut down without hitting q, it doesn't like it. For example, when it switches to mine to something else for donation. Sometimes when being shut down, this crashes my whole computer, other times it causes HBCC to drop off, and wattman settings to revert, making hash go below tolerance. 

The log is from this morning, which crashed my whole computer. Any ideas?

[2017-12-14_06-18-18.txt](https://github.com/aaronsace/MultiPoolMiner/files/1559493/2017-12-14_06-18-18.txt)

**Comment by UselessGuru** [comment]
Might have to do with weak power supply. If too weak power peaks caused by algo changes cause random issues.
Can you reproduce the issue if you reduce the GPU powerlimit, eg, 60%?

**Comment by tavenger5** [comment]
It's possible, but it's a brand new 750w EVGA G3. Power limit is normally at 21%. If I reduce to 60% my hash also drops by 500. I'm using the blockchain driver too, which is a little buggy. That being said, I can't reproduce the problem when power limit is at 60%, or when q is pressed in Cast XMR to quit.

**Comment by aaronsace** [comment]
@tavenger Are the other miners working on your system? Why not just delete Cast XMR from the folder called 'miners'?

**Comment by tavenger5** [comment]
@aaronsace - they are, but cast xmr has a 500h/s advantage over everything else when using the blockchain driver. I guess that doesn't matter if it's not stable :) I'm going to try reducing the power limit and see how that works out.
