### ISSUE TITLE
Price sync error?

### ISSUE THREAD

**Issue by emoxing885** [aaronsace/MultiPoolMiner#679]
shows price cant sync first and then a long section of error. Miners work fine though, but this error pops up every round MultiPoolMiner updates.

Thanks!
[2017-12-14_09-31-21.txt](https://github.com/aaronsace/MultiPoolMiner/files/1559592/2017-12-14_09-31-21.txt)

**Comment by UselessGuru** [comment]
OpenCL.dll is missing in the MPM directory. Check prerequisites.

**Comment by aaronsace** [comment]
Is OpenCL.dll not included with the display drivers? I always seem to have it...

**Comment by emoxing885** [comment]
Thanks, are you referring to these? 
- CCMiner (NVIDIA cards only) may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784
- CCMiner (NVIDIA cards only) may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Or something else that I needed to do? I’m using the same settings and everything on another rig and it’s fine. Not sure which prerequisite you were referring to. Thanks in advance for the help

**Comment by emoxing885** [comment]
It was fine until yesterday. And suddenly these errors started to show. But also excavator is working fine. Confusing.

**Comment by aaronsace** [comment]
Try downloading the graphics driver from NVidia.

**Comment by SerpentDrago** [comment]
https://download.microsoft.com/download/9/1/4/914851c6-9141-443b-bdb4-8bad3a57bea9/vcredist_x64.exe

**Comment by emoxing885** [comment]
I used DDU and reinstalled the driver. Seems like the problem is fixed. It was odd though, happened all of a sudden. Thanks for the help.
