### ISSUE TITLE
Ahashpool support ? 

### ISSUE THREAD

**Issue by SerpentDrago** [aaronsace/MultiPoolMiner#681]
Wondering when you will get around to updating for for Ahashpool support . 

Seems like the miners and bench-marking / switching you do is better then sniffdogminer ahashpool fork is currently and would love to switch !

**Comment by UselessGuru** [comment]
HashPool is supported and working well:
[https://github.com/aaronsace/MultiPoolMiner/blob/master/Pools/AHashPool.ps1](https://github.com/aaronsace/MultiPoolMiner/blob/master/Pools/AHashPool.ps1
)

**Comment by SerpentDrago** [comment]
My bad ! thanks !

**Comment by SerpentDrago** [comment]
is Nist5 supported ? he added it recently (2 days ago )
