### ISSUE TITLE
NiceHash API warning

### ISSUE THREAD

**Issue by chabgood** [aaronsace/MultiPoolMiner#682]
I start the hubpool miner and I get this warning:

WARNING: Pool API (NiceHash) has failed.

**Comment by aaronsace** [comment]
NiceHash is still down. It's not an error; it's just warning you.

**Comment by chabgood** [comment]
What does that have to do with miningpoolhub?

**Comment by aaronsace** [comment]
There are several backup pools: 
https://github.com/aaronsace/MultiPoolMiner/tree/master/Pools

**Comment by chabgood** [comment]
Yes I understand that.  I am a programmer and it has to do with context.  If I am on miningpoolhub I should not see anything with Nicehash that is out of context to what is going on.

**Comment by aaronsace** [comment]
It still gathers stats from the backup pools. 

It's not a common warning; it's only because NiceHash got hacked.

**Comment by SerpentDrago** [comment]
You can just delete any other pools in the ./pools directory and you will not get the message
