### ISSUE TITLE
ahashpool not in release version 

### ISSUE THREAD

**Issue by SerpentDrago** [aaronsace/MultiPoolMiner#683]
so I just downloaded the repo directly instead of using the releases , as your release version is outdated for use in ahashpool among some other fixs 

I had to re add miners from releases into the clone version . and it seems to work . 

Request a new Proper release version , Thanks ! 

Again I thank you for all your work !

**Comment by SerpentDrago** [comment]
also minor issues > 

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

Does not work , returns a error , pwsh no command found on my system , windows 10 pro x64 fully updated , seems to work fine though !

**Comment by aaronsace** [comment]
If "pwsh" (PowerShell 6) fails then it reverts to "powershell -version 5.0".

**Comment by aaronsace** [comment]
I'll mark it as a release soon.

**Comment by SerpentDrago** [comment]
Roger , Thanks man !
