### ISSUE TITLE
Feature Request :  USD/Day per Algro in Algorithm list at Top

### ISSUE THREAD

**Issue by SerpentDrago** [aaronsace/MultiPoolMiner#684]
At the top of the main windows for the script it lists  miner/algorithm/speed/ >  BTC/DAY >  BTC/GH/DAY >  Pool 

Where would i go about finding where this is in the code so i could add a Conversion from BTC/DAY to USD/DAY . or add another Column with this info.  I'd like it to list current pools USD/DAY per algro in that list for reference ! thanks 

I've noticed  SniffDog miner displays this 

I can provide screenshots if needed .

**Comment by aaronsace** [comment]
After I have got this release out, I'll add this feature.

**Comment by SerpentDrago** [comment]
https://image.prntscr.com/image/UnDG_6b-SOOvjGE1o3IA_Q.png

Thanks good sir , I know i've been bugging you
