### ISSUE TITLE
Issue starting with multipool hub

### ISSUE THREAD

**Issue by ki4yvc** [aaronsace/MultiPoolMiner#686]
hello, i am running `powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username [myusername] -workername rig1 -ssl -region US -currency btc,usd -type nvidia -poolname miningpoolhub -algorithm ethash,equihash"` and getting `WARNING: Pool API (NiceHash) has failed.`. I don't understand, I have no references to NiceHash. Any suggestions?

**Comment by JhonJhonny** [comment]
Remove the nicehash pool file from the Pools folder

Il 14 Dic 2017 22:37, "ki4yvc" <notifications@github.com> ha scritto:

**Comment by ki4yvc** [comment]
Thanks for the quick response!! That seems to have done the trick 👍
