### ISSUE TITLE
Connection to zpool when only MPH configured

### ISSUE THREAD

**Issue by mmcmullen** [aaronsace/MultiPoolMiner#687]
[2017-12-14_12-35-01.txt](https://github.com/aaronsace/MultiPoolMiner/files/1560813/2017-12-14_12-35-01.txt)
[2017-12-14_08-30-35.txt](https://github.com/aaronsace/MultiPoolMiner/files/1560824/2017-12-14_08-30-35.txt)
[2017-12-14_09-51-43.txt](https://github.com/aaronsace/MultiPoolMiner/files/1560825/2017-12-14_09-51-43.txt)

Logs attached. Connected several times to zpool, despite it being configured for only MiningPoolHub. Could be for dev donation reasons, perhaps, but it's unclear.

Definitely more than 10 minutes collectively, but perhaps that 10 minutes is per-run? I've restarted several times today for various reasons.

Appreciate any feedback to clear it up; happy to donate, just want to make sure I'm not mining into the void accidentally.

**Comment by mmcmullen** [comment]
Second rig just went into an odd state where everything listed at the top was for zpool, and it spent at least 15 minutes mining for the dev on zpool until I manually stopped it.

[2017-12-14_13-36-19.txt](https://github.com/aaronsace/MultiPoolMiner/files/1560894/2017-12-14_13-36-19.txt)

**Comment by aaronsace** [comment]
Watchdog timer is expiring. Try the latest code branch: 
https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

**Comment by aaronsace** [comment]
As you have not entered a wallet, it's also causing the backup pools not to work correctly. I'll push a fix into today's release.

**Comment by mmcmullen** [comment]
Tried the new version overnight, and no more zpool, but... One rig did however connect to AHashPool once, only 3 minutes, and mined for you on MPH for 2 minutes. The other connected to HashRefinery with your address for a total of 39 minutes. 

I saw on the BTCtalk thread that there may have been a bug with no-wallet-address, which is how I run - perhaps the same happened to me?

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
