### ISSUE TITLE
Miners Launch in "Below Normal" priority

### ISSUE THREAD

**Issue by PengiPower** [aaronsace/MultiPoolMiner#688]
Is there any way to have the miners launch in normal or high priority CPU modes, as it defaults to "Below Normal" with this script. It is affecting my hashrates.

**Comment by aaronsace** [comment]
You'll make your system quite unusable. Have you tried turning CPU mining off?

**Comment by aaronsace** [comment]
This is where the priorities are set but if your CPU is maxing out then it's not a good sign: 
https://github.com/aaronsace/MultiPoolMiner/blob/01c00b8b6bccd95191589180bec41fc3dd4b6326/MultiPoolMiner.ps1#L447
