### ISSUE TITLE
Support for Solo Mining or...

### ISSUE THREAD

**Issue by Lanik42** [aaronsace/MultiPoolMiner#69]
This may be sort of related to the qubit issue earlier, but when MPM reports base prices _significantly_ higher than MPH, should MPM possibly allow directing to solo wallets, etc?  I know other pools are coming in future releases, but assuming the values are correct (and they seem unlikely), then it could be a big deal. 
![screen shot 2017-03-27 at 7 19 33 am](https://cloud.githubusercontent.com/assets/2965306/24355028/57781b48-12c2-11e7-98b8-ea18fdc9b448.png)

**Comment by aaronsace** [comment]
There something wrong with the stats. Have you just launched the miner or did that happen later?

**Comment by Lanik42** [comment]
I deleted the CCminerTpruvot Lyra2z hashrate file and MPH price file, and restarted - it doesn't show that price anymore.  Looks like it still gets the weird values in v2.5

**Comment by aaronsace** [comment]
Please can you attach the log file?

**Comment by Lanik42** [comment]
It was later - when I first launched, (after benchmarking) all prices / values were normal.  That eventually showed up after a few hours or so.

Log: 
[lyra2z-log.zip](https://github.com/aaronsace/MultiPoolMiner/files/872384/lyra2z-log.zip)

**Comment by aaronsace** [comment]
OK, I think it's reading the Lyra2z hash speed wrong. I will look into it and apply a fix. 
I assume 13.20 MH/s is the correct speed then, whilst mining, it starts reading the wrong/faster hash rate.

**Comment by Lanik42** [comment]
Roughly - after re-benchmarking, it's showing as 10.67 MH/s.  Thanks for
looking into it

**Comment by Lanik42** [comment]
Not sure if this is related, but it's failing to launch equihash - it shows the errors briefly, but then moves on to the normal display, but with no miner running.
I'd rather not have to have it re-benchmark everything, but if I need to start with a fresh download I can.

[2017-03-27-09-39-45.txt](https://github.com/aaronsace/MultiPoolMiner/files/872597/2017-03-27-09-39-45.txt)

**Comment by aaronsace** [comment]
I think you just need the bin files from the release: 
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by aaronsace** [comment]
Are you observing anything unusual happening when the speed jumps up to GH/s? 
Is ccminer reporting MH/s or GH/s on the ccminer window?

**Comment by aaronsace** [comment]
@lyolyalya Are you observing any issues with hashrates and ccminer? 
I've tested on new laptop but there is no issue.

**Comment by lyolyalya** [comment]
you mean in ccminer or in MPM?

**Comment by aaronsace** [comment]
Yes, MPM starts reading the hash rate way to high.

**Comment by Lanik42** [comment]
I'm quite certain it should be MH/s, but I haven't caught it in process since.  MPM has been running for around 16 hours and isn't showing the excessive hashrate, though most are showing 0 PH/s, and it never takes long for one runtime to be way off

        Speed Active                          Launched Command
        ----- ------                          -------- -------
    0.00 PH/s 608118 Days 10 Hours 29 Minutes 16 Times Bin\NVIDIA-SP\ccminer.exe -b 127.0.0.1:4068 -a skein -o stratum+tcp://hub.miningpoolhub.com:17016 -u Lanik42.CitraMiner1 -p x -i 27

This may be related to an issue I saw:

       Status: Running
    
          Speed Active                          Launched Command
          ----- ------                          -------- -------
    347.83 MH/s 456088 Days 17 Hours 09 Minutes 8 Times  Bin\NVIDIA-Nanashi\ccminer.exe -a lyra2v2 -o stratum+tcp://hub.miningpoolhub.com:17018 -u Lanik42.CitraMiner1 -p x

which involved errors of sort in the miner itself (with very occasional valid submissions)
![capture](https://cloud.githubusercontent.com/assets/2965306/24530049/6d69b480-157d-11e7-8ef4-ca1bcd8a53a8.JPG)

**Comment by lyolyalya** [comment]
so maybe don't need an automatic switching between measure unit?kh maybe for all gpu instances?

**Comment by aaronsace** [comment]
I am simply reading the KH/s value from ccminer which is leading me to think ccminer is reporting the speed wrong. I'll edit MultiPoolMiner to dump the data from the miner API into a log.

**Comment by aaronsace** [comment]
Replace you include.ps1 file with this one then, next time it happens, send me the log (it will contain the API data from ccminer): 
[Include.zip](https://github.com/aaronsace/MultiPoolMiner/files/885492/Include.zip)
