### ISSUE TITLE
how to setup asic miner

### ISSUE THREAD

**Issue by fusation** [aaronsace/MultiPoolMiner#690]
hi 

just wanted to know how to setup my asic miner. thanks

https://github.com/aaronsace/MultiPoolMiner/issues/480

**Comment by aaronsace** [comment]
You don't seem to have any idea of how your Ant Miner works and I'm not sure as to why you are posting on MultiPoolMiner. 

Use Zpool as it's the most profitable: 
```
URL: scrypt.mine.zpool.ca:3433#xnsub
Worker: <BTC Wallet>
Password: c=BTC,d=128000 
```
