### ISSUE TITLE
Mines to hashrefinery even though only miningpoolhub is selected

### ISSUE THREAD

**Issue by blogbytes** [aaronsace/MultiPoolMiner#691]
I see my rigs connect to hashrefinery every now and then using someone elses BTC address. I would assume it is your? I have donations set to disabled during my testing phase. 

How come it still mines to your wallets?

**Comment by aaronsace** [comment]
You never entered your wallet which appears to cause issues. I've now fixed the bug and will be part of today's release: 
eb8d100b1b20def27c6a13fa74469deab0dc2023

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by blogbytes** [comment]
Thanks for the new release. Will monitor.

Ive switched to ZPOOL now on the new version and it mines to mininghub as well. Why would that be?

**Comment by aaronsace** [comment]
Check what algorithms that you are selecting.

**Comment by blogbytes** [comment]
Ah, my bad. Thanks for the info.

**Comment by blogbytes** [comment]
How can I reset the benchmark for only one specific algo? For some reason one of my rigs benched NIST5 but its not being added to the list and does not mine it.

Thanks for the help
