### ISSUE TITLE
bitrep.A warning

### ISSUE THREAD

**Issue by thepeppi** [aaronsace/MultiPoolMiner#692]
on windows 10 there is a bitrepA trojan watning can this be fixed ?

**Comment by UselessGuru** [comment]
A bit more info? Screenshots maybe?

**Comment by aaronsace** [comment]
FYI any virus warnings are false positives so don't quarantine anything.

**Comment by aaronsace** [comment]
https://github.com/aaronsace/MultiPoolMiner/releases
