### ISSUE TITLE
Pool API (Nicehash) has failed

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#693]
![image](https://user-images.githubusercontent.com/25688628/34047489-5692982c-e1eb-11e7-9159-8bb464d6580d.png)

**Comment by uprise88** [comment]
as you ca read here https://www.nicehash.com/ nicehash got hacked and is down

**Comment by SerpentDrago** [comment]
Remove the Nicehash file under pools folder , Nicehash is down / hacked

**Comment by aaronsace** [comment]
This isn't a bug. Everything is working fine.
