### ISSUE TITLE
Hidden mining to author's wallet or Undocumented Features?

### ISSUE THREAD

**Issue by jslatone** [aaronsace/MultiPoolMiner#696]
Hidden mining to author's wallet or Undocumented Features?

I was working on setting up MPM on my new 4 GPU rig and noticed some unintended mining.
Start looking at the logs and the following came out (note, donation was set to 0!)…
The log file (attached) includes the following calls for mining:

61 times to wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb

64 time to aaronsace.multipoolminer

and this script only run 4 hours….

Any comments?

[2017-12-15_16-26-29.txt](https://github.com/aaronsace/MultiPoolMiner/files/1564379/2017-12-15_16-26-29.txt)

**Comment by aaronsace** [comment]
You haven't entered your wallet.

**Comment by aaronsace** [comment]
Checks are now in place: 
https://github.com/aaronsace/MultiPoolMiner/commit/eb8d100b1b20def27c6a13fa74469deab0dc2023
