### ISSUE TITLE
Pool prices are out of sync

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#697]
![image](https://user-images.githubusercontent.com/25688628/34067406-20f4fae6-e260-11e7-9099-611af93c526d.png)

**Comment by SerpentDrago** [comment]
could be your console font choice (thats not the default) , 

absolutly perfectly in sync here 
![image](https://user-images.githubusercontent.com/21133858/34067688-d8d04afa-e1fa-11e7-9aa6-fe520808dec7.png)

**Comment by SerpentDrago** [comment]
or it could be the fact you still have it checking nicehash , remove the nicehash pool file in the ./pool folder

**Comment by felix920506** [comment]
its the default
notice the language?
language: traditional chinese

**Comment by aaronsace** [comment]
The problem is MiningPoolHub's API still has a caching problem. MultiPoolMiner handles the issue and also throws a warning.
