### ISSUE TITLE
@aaronsace - part 2

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#699]
I read recently where you flat you said we'd make more money at zpool. You laid out reasons why and they made sense to me. So I'm switching over to zpool. I have 2 specific questions:
1) in your zpool bat, as of right now, what algos do you think I should add / remove...or, have you defaulted it to mine the best algos already? I have 6x 1060's and 6x 1070's.

2) In theory, if I were to go back to MPH and removed the miningpoolhubcoins section and only left miningpoolhub, would that eliminate the being penalized for jumping between algos and coin? 
I'm going out of town for 3 days tomorrow and I'm hard up for answers. Thanks.

**Comment by aaronsace** [comment]
If you're having problems with MiningPoolHub then try Zpool. The algorithms that I set are the popular ones; the are a few others that are profitable but can't remember off the top of my head.

**Comment by cmbconcretefire** [comment]
Thank you.
