### ISSUE TITLE
delta for triggering autoswitch?

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#7]
hello.i have an idea.can you insert a parametr(let's call it delta) that triggers autoswitch?
example...i mine neoscrypt now.and groestl profitability changes to 0.0078 btc\day while  neoscrypt 0.0076 btc\day... for 20-30 minutes this 0.0002 btc is nothing and i won't to autoswitch.but it autoswitches anyway.OR if we have delta that user can assing (for example) d=0.001 that means groestl need to be 0.0086  to autoswitch and THEN it autoswith.how do you think?

**Comment by aaronsace** [comment]
Good idea, will add in version 2. I've been indisposed for a bit but I'll release ASAP.

**Comment by lyolyalya** [comment]
glad you like it=)waiting.
