### ISSUE TITLE
sgminer is only using 1 GPU?

### ISSUE THREAD

**Issue by Deekor** [aaronsace/MultiPoolMiner#70]
Watching the benchmarks be performed, it seems whenever sgminer is used it only uses 1 of my 6 GPUs. Is there something i need to configure in order for all 6 to be utilized?

Running on windows 10.

**Comment by aaronsace** [comment]
The default option is for sgminer to use all compatible GPUs but you can set it manually by editing the file in notepad from the folder called 'miners': 
`--device|-d <arg>   Select device to use, one value, range and/or comma separated (e.g. 0-2,4) default: all`

**Comment by Deekor** [comment]
Interesting that it's only detection one of 6 then..

**Comment by aaronsace** [comment]
Yes, I assume someone must have had the same issue before. If they are not all the same card, maybe drivers could be the issue?

**Comment by Deekor** [comment]
hmm adding the `-d` argument crashes it on launch

**Comment by aaronsace** [comment]
You can replace the files in the 'bin' folder if you know of an sgminer version that works on your system. 
Also, stupid question but they are AMD GPUs right?

I recommend posting somewhere related to sgminer for assistance as I'm unlikely to be able resolve your issue.

**Comment by aaronsace** [comment]
If you know what was causing this then please post here for others that may experience the same issue.
