### ISSUE TITLE
Batch file error for MPH

### ISSUE THREAD

**Issue by umsiddiqui** [aaronsace/MultiPoolMiner#700]
I am trying to run the batch file and get this error. I have downloaded the excavator and other file. What is going wrong?
![error](https://user-images.githubusercontent.com/31167553/34069104-a442a43c-e1fe-11e7-8704-9cc28e08658b.jpg)

**Comment by aaronsace** [comment]
Check the original bat file; the edits you've made have broken it. 

I think you extra commas.

**Comment by aaronsace** [comment]
BTW there is a new release out as well: 
https://github.com/aaronsace/MultiPoolMiner/releases
