### ISSUE TITLE
Pool API (Hashrefinery) has failed

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#701]
![image](https://user-images.githubusercontent.com/25688628/34069903-edb28f9c-e294-11e7-925a-9ba4d2b622fe.png)

**Comment by aaronsace** [comment]
Warnings aren't errors. Errors are red.

**Comment by UselessGuru** [comment]
@felix920506
Warnings regarding 'ouside fault tolerance' mean that you have very inconsistent hashing speed (more than +/- 10% as what you had when benchmarking).
If the warnings persist you might re-benchmark the problematic algorithm.

**Comment by felix920506** [comment]
I removed 1 gpu after benchmarking from my system
