### ISSUE TITLE
AHashPoolL vs HashRefinery

### ISSUE THREAD

**Issue by iwtym** [aaronsace/MultiPoolMiner#705]
Hello,

Just an observation/question. It appears that AHashPool takes precedent over HashRefinery in the benchmark. Does MPM choose whichever has a higher BTC/GH/DAY?

https://imgur.com/a/DjbEb

Thank you

**Comment by aaronsace** [comment]
Please check the 'start.bat' example.

**Comment by iwtym** [comment]
Does using them all maximize the likeliness of hitting the most profitable all the time, no?

**Comment by aaronsace** [comment]
MultiPoolMiner selects a pool for each algorithm that, on average, performs the best. Unless you have huge hashrates, you should try to focus it for regular play-outs and monitoring sake.

**Comment by iwtym** [comment]
Ah, OK. It could be useful to allow me to use them all to maximize btc/hash.

**Comment by aaronsace** [comment]
Thanks! :)
