### ISSUE TITLE
2.7.1 Broken

### ISSUE THREAD

**Issue by joesixpack** [aaronsace/MultiPoolMiner#706]
PowerShell 6.0 is installed.

![image](https://user-images.githubusercontent.com/23145642/34075017-8442ace2-e26f-11e7-86dc-4174528080dd.png)

**Comment by aaronsace** [comment]
Very strange, not sure what it's referring to but I have noticed that I forgot to remove a line on the final release. 

Try this: 
```
cd %~dp0

setx GPU_FORCE_64BIT_PTR 1
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

set "command=& .\multipoolminer.ps1 -wallet 1Q24z7gHPDbedkaWDTFqhMF8g7iHMehsCb -username aaronsace -workername multipoolminer -region europe -currency btc,usd,eur -type amd,nvidia,cpu -poolname miningpoolhub,miningpoolhubcoins,zpool,nicehash -algorithm cryptonight,decred,decrednicehash,ethash,ethash2gb,equihash,groestl,lbry,lyra2re2,lyra2z,neoscrypt,pascal,sia,siaclaymore,sianicehash,sib,skunk -donate 24 -watchdog"

pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"
msiexec -i https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.msi -qb!
pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "%command%"

pause
```

**Comment by fitb84** [comment]
I did the same thing. The problem is: -version 5.0 should be -version 6.0

**Comment by joesixpack** [comment]
Yeah, why are two commands included, one for PowerShell 6 and one for Powershell 5 then PowerShell 6 is downloaded but it won't be able to install if first pwsh worked and then PowerShell 6.0 is tried again?  This makes absolutely zero sense.

**Comment by OneOfMany07** [comment]
I only see a "--version 5.0" mentioned in the current start.bat file, and thought that was a typo since the directions on here said to install the 6.0 (actually 6.0rc2) version manually.

**Comment by aaronsace** [comment]
pwsh is version 6
