### ISSUE TITLE
Add Pascal duel mine option?

### ISSUE THREAD

**Issue by tboy1337** [aaronsace/MultiPoolMiner#707]
Can you add this?

**Comment by aaronsace** [comment]
NiceHash is down; there are no pools.

**Comment by tboy1337** [comment]
Assuming nicehash is coming back can you add it when it does?

**Comment by tboy1337** [comment]
Also is stable mpm version able to take advantage of the new mph electroneum pool or is upgrade to pre release needed?

**Comment by aaronsace** [comment]
Pascal is in there, ready and waiting. 

The new coin (electroneum) should work straight off if MiningPoolHub has remembered to add it to the API.

**Comment by tboy1337** [comment]
Will you add both duel mining and solo mining options?

**Comment by aaronsace** [comment]
It's all already there; it's just waiting for a pool.

**Comment by tboy1337** [comment]
Ok seems there isnt a solo mining program at the moment
