### ISSUE TITLE
Just added a 2nd GPU of same type, do I need a SLI cable to connect the 2 cards?

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#708]
Just added a 2nd GPU of same type, do I need a SLI cable to connect the 2 cards?

I reinstalled Nvidia Drivers and on reboot Win 10 pooped up a message about the SLI cable.

**Comment by aaronsace** [comment]
Not for mining.

**Comment by paulpoco** [comment]
Ok thanks, got nothing hooked up to 2nd GPU anyways.

Trying the new release, benchmarking now.
