### ISSUE TITLE
Electroneum Pool Added to MPH

### ISSUE THREAD

**Issue by feernandobraga** [aaronsace/MultiPoolMiner#709]
You must be aware that MPH just added Electroneum Pool a few hours ago.
Is it already supported by the last MPM that you have released? If not, which file should I have to tweak to get my rig to mine on that pool?

**Comment by aaronsace** [comment]
It should already be in your 'stats' folder but the profit is currently zero. There is no exchange so I think that's why.

**Comment by aaronsace** [comment]
Odd for him to add a coin that's not tradable...

**Comment by feernandobraga** [comment]
Thank you @aaronsace.
I would ask on the forum, but since I use proxy my account has been blocked from posting. Apparently some people can remove the block, so if you have the extra time, my username is feernandobraga.
I appreciate your quick reply... Thank you

**Comment by UselessGuru** [comment]
Electroneum is currently only tradable on Cryptopia. MPH obviously is not using Cryptopia as exchange.
BTW: What exchange is MPH actually using?

**Comment by uprise88** [comment]
MPH is using Bittrex, Poloniex, Yobit

**Comment by pulseOXE** [comment]
I know this is closed, but is there a way to manually set a fake profit for ETN so we can let MPM mine it if it makes sense?
