### ISSUE TITLE
Miner do not work

### ISSUE THREAD

**Issue by Niduin** [aaronsace/MultiPoolMiner#710]
Running this command

```
    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\NVIDIA-SP\ccminer.exe -a x17 -o
                                               stratum+tcp://x17.mine.zpool.ca:3737 -u
                                               D5a8QsHfSNv5SEcuahech7vYukzY3pquCP -p Auto,c=XVG
```
Results in
```
PS>TerminatingError(Invoke-RestMethod): "A task was canceled."
```

**Comment by aaronsace** [comment]
Please post full log.

**Comment by Niduin** [comment]
[2017-12-17_02-22-16.txt](https://github.com/aaronsace/MultiPoolMiner/files/1565246/2017-12-17_02-22-16.txt)

**Comment by aaronsace** [comment]
The log just stops. Is MultiPoolMiner still running?

**Comment by Niduin** [comment]
I stop it by myself, nothing more is shown. It repeat it always. Nothing more.

**Comment by aaronsace** [comment]
I can't see any issue. You just have to wait longer.

**Comment by Niduin** [comment]
Well... when the miner starts, it closed by itself after some seconds. Here is a another log. 
[2017-12-17_02-27-46.txt](https://github.com/aaronsace/MultiPoolMiner/files/1565272/2017-12-17_02-27-46.txt)

**Comment by aaronsace** [comment]
It just doesn't work on your system. MultiPoolMiner will move on.

**Comment by UselessGuru** [comment]
@Niduin 

Remove the .\Pools\Nicehash.ps1 file.
Nicehash is dead for now.
