### ISSUE TITLE
Force autoswitch from Miningpoolhub

### ISSUE THREAD

**Issue by Wapp92** [aaronsace/MultiPoolMiner#712]
Hi, can you force MPM to mine what MPH tell is the most profitable?

My hubwork are set to nvidia equi, lyra2re and lyra2z, MPM is set to only mine those algo on nvidia. Butm as off right now, after bench it determine that Lyra2re is more profitable and start mining that algo even if MPH say equihash is the most profitable. 

what am i doing wrong? how can i force MPM to be "stupid" and mine what MPH order to mine?

**Comment by UselessGuru** [comment]
@Wapp92 

> after bench it determine that Lyra2re is more profitable and start mining that algo even if MPH say equihash is the most profitable.

I have noticed this too. Just give MPM a little bit of time to settle after benchmarking.
If an algos price fluctuates a lot, then the short time profit might appear to be higher, but by the time you have mined it for a while and coins are being exchanged for a (by now) much lower price and you get less profit.
To mitigate this effect MPM uses an 24h mean price (if provided by the pool) to determine the most profitable algo.
With each run MPM updates the profit info (in the profit files) and the profit information will become more reliable.

**Comment by Wapp92** [comment]
Thanks UselessGuru
So what you saying is that MPM gather it s own DB of profitable algo witch is send by miningpoolhub. in my case, at a interval of 24h by default, or should i change it my self?
I need to wait at least a week to let MPM settle down and get more reliable.

**Comment by UselessGuru** [comment]
@Wapp92 

> So what you saying is that MPM gather it s own DB of profitable algo witch is send by miningpoolhub, in my case, at a interval of 24h by default, or should i change it my self?

No need to change anything by yourself.

> I need to wait at least a week to let MPM settle down and get more reliable.

Just watch MPM and see that will come closer to be a millionaire with every run :-)
Stats will get more precise with every run (more available data sets). There is no point jumping onto the fastest algo on every loop for the forementionied reason.


With each loop MPM gathers the princing information from each pool. Have a look at the pool files an try to spot the values it retrieves from the web request (Price and StablePrice).
This data is then used to build stable price information (function set-stat in .\include.ps1).

**Comment by Wapp92** [comment]
Thanks i get it. Hope your comments helps others better understand how MPM works.

**Comment by fonyo** [comment]
I added to FAQ, however, this feature should be exluded (or reduced) for Nicehash mining as it does not really matter how often do you switch on that "pool". The regular delta should still apply to prevent unnecessary switches. @aaronsace
