### ISSUE TITLE
gtx 970m/970

### ISSUE THREAD

**Issue by Mooglee** [aaronsace/MultiPoolMiner#714]
Getting no kernal image when trying to use these GPU's, however if i sneakly slip in a cuda 8 ver compiled ccminer, i drop from like 800 / sec to 400 / sec,

however multi pool miner does not clarify if the kernal error is stopping anything, it just keeps popping up

**Comment by UselessGuru** [comment]
@Mooglee 

Any log? Screnshot maybe?
What happens when you run the exact same command manually? Just copy/paste it from the running miner section :-)

**Comment by aaronsace** [comment]
Reopen if you are still having problems.

**Comment by Mooglee** [comment]
Apologise for the slow reply, this happens when i am running 9 Series GPU's i think its to do with the fact CC miner runs with CUDA 9 and there is no built support or option in multi pool miner for CUDA 8.

"GPU 0: no kernel image is available for execution on the device" is the error that comes up, im getting it on a 970, 970m & SLI Titan black rigs.

**Comment by aaronsace** [comment]
So you just need an older miner that uses CUDA 8?

**Comment by Mooglee** [comment]
Yeah im sure thats what the issue is, i think it may be a issue with a FLAG for when you run the CC miner or you compile it, i need to do a little more research to 100% say thats the issue.  so u may be able to hook that in, your multi pool miner will open up to alot more people, since older gen people will be able to use it.
