### ISSUE TITLE
Warning stat file: was not updated

### ISSUE THREAD

**Issue by imulision** [aaronsace/MultiPoolMiner#715]
Hello,

I know you already answered same issues, that the value updated is wrong but in my case the value looks fine:

http://puu.sh/yIkCf/8c2e9428ef.png

http://puu.sh/yIkCE/6f633d42eb.png

**Comment by UselessGuru** [comment]
@imulision 

You are looking at the wrong information here.

Both your screenshots make perfect sense and must match.
Have a look at the stat file for this miner/algo combo (.\stats\NvidiaExcavator3_Lyra2RE2_hashrate.txt) and you will see values much bigger or smaller.

If these values are not with the 10% range you will see yellow. If the message persists, then delete the _hashrate-txt file and MPM will re-benchmark the miner/algo.

It is essential that the hashrate stats match the real hashrate. MPM relies on the stored hashrates to determine the most profitable miner/algo combination.

**Comment by imulision** [comment]
Oh okay, thanks for the reply.
