### ISSUE TITLE
Profitability broken

### ISSUE THREAD

**Issue by giust** [aaronsace/MultiPoolMiner#716]
Hi,

Multipoolminer has just been mining keccak for the last 3h, it shows this profitability: 
![image](https://user-images.githubusercontent.com/27696823/34081396-4567abde-e34c-11e7-9527-b876aadc4298.png)

Obviously it is not returning 0,17 btc/day for my gtx 1080. Any way to fix this and let it mine other profitable algos?

**Comment by uprise88** [comment]
maybe this can help
https://bitcointalk.org/index.php?topic=1751272.msg26485785#msg26485785
https://github.com/tpruvot/yiimp/commit/6b6866048e2e5a1ab0fb373e0c65da296bb055

**Comment by giust** [comment]
@uprise88 thanks for sharing. I see I need to change the units but I'm not sure what .ps1 should I change and what part of the coude I should change, any ideas?

**Comment by uprise88** [comment]
i have no idea meanwhile ive just removed the algo from star.bat

**Comment by giust** [comment]
That will fix the issue for sure, I'll do that until someone finds out how to fix the algo profitablity, thanks!

**Comment by aaronsace** [comment]
It's the diviser variable. Wish there API had the unit of measurement then problems like this wouldn't happen.

**Comment by thericeking** [comment]
What my message saying that I can confirm having this same issue deleted? If so then why? I was trying to help.

**Comment by aaronsace** [comment]
No idea...?

**Comment by paulpoco** [comment]
Mine is out of wack too.  Only using 2 x 1070 and Ryzen 5 1600 CPU.

Miner                                              BTC                             CAD
-----                                              ---                             ---
MultiPoolMiner                                     0.01607 ±377% (0.00337-0.07670) 403.79016 ±377% (84.62593-1,926.67306)
{CcminerPalgin-Keccak, CpuminerTpruvotAvx2-Keccak} 0.16075 ±10% (0.14645-0.17644)  4,037.92042 ±10% (3,678.81969-4,432.07406)

**Comment by aaronsace** [comment]
Right, got it guys. Turn that algorithm off until I update unless you know how to change the divisor in the pool file (quite simple).

**Comment by grantemsley** [comment]
I created a pull request to fix it if you want to just merge that.

**Comment by meiskam** [comment]
pr without the wonky capitalization https://github.com/aaronsace/MultiPoolMiner/pull/720/commits/4a15ffac9a668d206a4db24edd452d86b2456e32

**Comment by grantemsley** [comment]
Huh...my capslock key seems like it went rogue.  Powershell isn't case sensitive, so mine worked, but meiskam's is better.  Closed my request.

**Comment by aaronsace** [comment]
Great job!
