### ISSUE TITLE
Request for GPU status (Online/Offline) | Temperature | Fan Speed

### ISSUE THREAD

**Issue by thericeking** [aaronsace/MultiPoolMiner#717]
Forgive me if this isn't the correct way to make a feature request. I am very new to GitHub. 

First of all thank you for your work. I recently switched from Claymore-Dual Miner and started using your wonderful MultiPoolMiner.

The first time I built a mining right (6 GPU) Claymore syntax showed me how many GPU's were online, offline, Temp. This information is very useful to me. My mining rig is super stable but I really like to have an easy way to check if is using all GPU's available. I don't like to use AwesomeMiner just for this, I prefer to use just your software. Maybe there's a way I don't know about that can help monitor my GPU status? Thank you again for your time.

**Comment by paulpoco** [comment]
I have GPU Tweak II running and from the graphs, I can tell the clocks,memory,temp, fan speed on both of my cards.

I think some of the individual Miners do display the GPU temps.

**Comment by aaronsace** [comment]
Not a feature of MultiPoolMiner yet. There is other software that you can use for monitoring.
