### ISSUE TITLE
Problem with xmrig

### ISSUE THREAD

**Issue by migdiluca** [aaronsace/MultiPoolMiner#722]
Hi, i just installed MPM with MPH, i have a RX 480 nitro+. on benchmarks i get the same equihash hashrate that i get with other miners (320H/s aprox) but when i mine i start at that speed and then it drops down to 200H/s aprox, until the program change the algorithm. Also with Ethash i get normal hashrate but sometimes it drops to 1-2Mh/s and then it continues as normal (i don't know if this is a normal behaviour). With other miners equihash is working fine.

[1513543219_log.txt](https://github.com/aaronsace/MultiPoolMiner/files/1566048/1513543219_log.txt)

EDIT: I think i found the problem. While mining equihash on MPM i was cpu mining monero with xmrig, if i don't mine monero it works fine, but with another miner program i can do that without seeing an impact on equihash hashrate.

EDIT2: If i mine with xmrig with MPM it doesnt affect the hashrate but xmrig closes after some minutes.

Thanks in advance.[](url)

**Comment by aaronsace** [comment]
You're CPU is too slow; turn off CPU mining in the bat file.

**Comment by paulpoco** [comment]
How fast does the CPU have to be?

My Ryzen 5 1600 benchmarks about :
Type: CPU

Miner                   Algorithm         Speed BTC/Day BTC/GH/Day Pool
-----                   ---------         ----- ------- ---------- ----
FireiceCpu              CryptoNight 381.06  H/s 0.00006  165.72350 MiningPoolHubCoins-Monero
CpuminerJayddeeAesavx2  Lyra2z      465.17 KH/s 0.00006    0.12814 MiningPoolHub-Zcoin
CpuminerJayddeeSse2     Lyra2z      325.48 KH/s 0.00004    0.12814 MiningPoolHub-Zcoin
CpuminerJayddeeAessse42 Lyra2z      313.48 KH/s 0.00004    0.12814 MiningPoolHub-Zcoin
CpuminerJayddeeSse42    Lyra2z      303.28 KH/s 0.00004    0.12814 MiningPoolHub-Zcoin
CpuminerTpruvotAvx2     Yescrypt      5.05 KH/s 0.00003    6.53395 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerTpruvotCorei7   Yescrypt      5.01 KH/s 0.00003    6.53395 MiningPoolHubCoins-MyriadcoinYescrypt
CpuminerTpruvotCore2    Yescrypt      4.87 KH/s 0.00003    6.53395 MiningPoolHubCoins-MyriadcoinYescrypt

**Comment by aaronsace** [comment]
@paulpoco I've not got an exact answer but every GPU miner requires varying amounts of CPU power to run effectively.

**Comment by fonyo** [comment]
@paulpoco generally CPU mining is a bad idea, and even though your CPU is great for mining, you should do so as long as you don't push it too hard. PCI-E lanes are controlled by CPU, if your CPU doesn't have time (enough cycles) to process the data it is getting from your GPU(s), then you are basically rendering your GPU mining useless or at least less effective. The losses due to this will definitely outweigh the earnings from your CPU.

**Comment by migdiluca** [comment]
Thanks for the answer, i set low affinity to xmrig.exe in task manager and now every is working fine, same hashrate on GPU and even better hashrate on cpu for some reason.

**Comment by aaronsace** [comment]
MultiPoolMiner already sets it to low... was it not set to low?
