### ISSUE TITLE
Claymore-Equihash

### ISSUE THREAD

**Issue by dekkyy1111** [aaronsace/MultiPoolMiner#723]
Claymore-Equihash is not reading from config.txt file. Wanted to set the intensity for each card, but for some reason it uses default settings. what could be the problem?

**Comment by aaronsace** [comment]
Miner settings are in the folder called 'miners'.

**Comment by dekkyy1111** [comment]
Thanks. Will try to change it there.

**Comment by thericeking** [comment]
@dekkyy1111 Can you give me an idea of what changes to make in order to push the miner?

**Comment by fonyo** [comment]
You can find appropriate settings for each card model on forums like BTCtalk or reddit.
