### ISSUE TITLE
Redo failed benchmark

### ISSUE THREAD

**Issue by SaintPistachio** [aaronsace/MultiPoolMiner#726]
Is there a way to determine if a miner benchmark is failed? I would like to try and rerun any failed benchmarks.

**Comment by aaronsace** [comment]
If they failed then they will most likely fail again. 

You can flick through the profit files in the 'stats' for ones that are '0'.

**Comment by SaintPistachio** [comment]
I found a bunch that were not benched probably because I downloaded a master.zip and forgot the miners that were normally included. I will just wipe out my stats folder and let it benchmark everything.

**Comment by fonyo** [comment]
https://github.com/aaronsace/MultiPoolMiner/blob/master/README.md#q6-i-want-to-re-run-the-benchmarks-changed-oc-settings-added-new-cards-etc

**Comment by SaintPistachio** [comment]
I knew about bat file but I was wondering how to tell if a benchmark was not ran. I found a lot that were not ran so I reset the entire stats folder.

**Comment by n3cr0cr0w** [comment]
Just go into your stats folder and put this in the search box in the top right. Three double quotes in the beginning and two in the middle and only one at the end. I know the quotes are strange but in Microsoft's wisdom, they made escaping double quotes in the search box possible by doubling them up.

`"""Live"": 0.0,"`

**Comment by SaintPistachio** [comment]
Cool. I used this to find the files with missing benchmarks. I was trying to figure out to the right syntax for searching.

`"""Live"": 0.0," hashrate`
