### ISSUE TITLE
Which pools are good

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#727]
-poolname miningpoolhub,miningpoolhubcoins,zpool  ##using these right now

So basically I have to wait for 2 pools to get large enough for withdrawal.

Say if I add hashrefinery I would just be waiting for 3 pools all together.

**Comment by jayntguru** [comment]
Yup. Painful at first.

**Comment by fonyo** [comment]
Yes. Spreading hashrate is generally a good idea but for smaller miners it is not so beneficial nor safe (see Nicehash). If you have high enough hashrate to accumulate enough for a weekly payout on all pools then it should be OK.
