### ISSUE TITLE
NetFirewallRule - Access denied

### ISSUE THREAD

**Issue by ailocha** [aaronsace/MultiPoolMiner#728]
it keeps erroring out.  logfiles and SS attached.
[2017-12-17_23-18-50.txt](https://github.com/aaronsace/MultiPoolMiner/files/1566680/2017-12-17_23-18-50.txt)

![untitled](https://user-images.githubusercontent.com/34426086/34090764-4a15676c-e387-11e7-9c7f-e344de67c58f.jpg)

**Comment by aaronsace** [comment]
You can't put it inside program files. Just put it in a normal folder like on your desktop.

**Comment by ailocha** [comment]
Still getting access denied on a diff PC.  Moved the miner to C:\MultiPoolMiner

[2017-12-18_14-43-47.txt](https://github.com/aaronsace/MultiPoolMiner/files/1569366/2017-12-18_14-43-47.txt)

**Comment by symalla** [comment]
Depending on the Windows version you may not be able to run from root of C:/ try suggestion of running from folder on Desktop.

**Comment by ailocha** [comment]
same error when it was on the desktop

**Comment by ChriscomIT** [comment]
Did you try to run as admin? Maybe reset you FW rules in Windows settings and try again.

**Comment by aaronsace** [comment]
Now that it's not your desktop. Please can you post the new log?

**Comment by ailocha** [comment]
[2017-12-18_14-43-47.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570615/2017-12-18_14-43-47.txt)

**Comment by UselessGuru** [comment]
I cannot see any reference to your listed issue in the log. Does the issue still exist?
If yes: Are you using any non-microsoft antivirus / firewall software (e.g. Avast or Norton)?

BTW: You should remove the NiceHash pool file  NH ist dead!

**Comment by ailocha** [comment]
It does still popup and give the same error.  I have Avast.  But I have C:\MultiPoolMiner\* excluded.  should I add anything else?

**Comment by ailocha** [comment]
I did remove nicehash from the poolname and the other algorithms but not sure why it's still searching for nicehash.

**Comment by ailocha** [comment]
![untitled](https://user-images.githubusercontent.com/34426086/34164318-42a6b384-e4a7-11e7-8f62-ca32fee29b86.jpg)

**Comment by jayntguru** [comment]
Are you double clicking the shortcut? Looks like it.

Try opening a powershell window as administrator, then going there and starting the file from inside the path inside the window.

**Comment by ailocha** [comment]
that didn't work, also tried running start.bat as admin, didn't work either.  still seeing the popup error.

**Comment by jayntguru** [comment]
you can try a whoami /all and make sure your effective permissions in that shell match what you expect.

**Comment by ailocha** [comment]
Avast FW has always been disabled...it's using the  MS FW.

**Comment by UselessGuru** [comment]
@ailocha 

> Avast FW has always been disabled...it's using the MS FW.
Problem still there?

**Comment by ailocha** [comment]
yes

**Comment by aaronsace** [comment]
@ailocha

Run PowerShell as an administrator then type: 
`New-NetFirewallRule -DisplayName "test"`

If it throws "Access is denied" error then there is a problem with your system.

**Comment by ailocha** [comment]
![untitled](https://user-images.githubusercontent.com/34426086/34179435-e30cf514-e4d8-11e7-8dfe-274b0daa2732.jpg)

**Comment by ailocha** [comment]
![untitled](https://user-images.githubusercontent.com/34426086/34179471-05c97622-e4d9-11e7-8851-38bc0be1ac2f.jpg)

**Comment by aaronsace** [comment]
@ailocha Sorry, use version 5.

**Comment by ailocha** [comment]
![untitled](https://user-images.githubusercontent.com/34426086/34179559-6d2257d0-e4d9-11e7-9f2e-99d4b8ab7dc1.jpg)

**Comment by aaronsace** [comment]
System working, so now lets test PowerShell 6 in admin mode: 
```
Import-Module "$env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1"
New-NetFirewallRule -DisplayName "test"
```

**Comment by ailocha** [comment]
![untitled](https://user-images.githubusercontent.com/34426086/34193975-6a148cf2-e524-11e7-857d-ee7aa4c028b8.jpg)

**Comment by ailocha** [comment]
i'm still getting the error

**Comment by ailocha** [comment]
from the start.bat script

**Comment by ailocha** [comment]
figured it out...deleted the folder and unzipped it again.
