### ISSUE TITLE
CPU mining, why not only Cryptonight?

### ISSUE THREAD

**Issue by komer83** [aaronsace/MultiPoolMiner#730]
I've updated my MPM this morning, and I've notice that it also benchmarks other algorithms beside Cryptonight. Is there any reason for that? 
As far as I'm aware, right now, Cryptonight is still the only one good for CPU.

**Comment by fonyo** [comment]
That is the whole point of benchmarking. First it needs to determine and evaluate what the most profitable algorithm is for your CPU or GPU. Once that is done, it will start mining the most profitable for you.
