### ISSUE TITLE
Multi wallet mining

### ISSUE THREAD

**Issue by giust** [aaronsace/MultiPoolMiner#732]
Hi,

I have a simple question, is there any option to mine to 2 different wallets? Say I want to mine 80% of the time to wallet A and 20% of the time to wallet B. I know I could change the donate wallet and set a time per day, but I was wondering if there was a more natural way to do this.

**Comment by aaronsace** [comment]
No; what would the reason be to do that?

**Comment by giust** [comment]
To share the reward between different people who own a single rig

**Comment by aaronsace** [comment]
Maybe try this: https://coinsplit.io/

**Comment by giust** [comment]
Thanks! I'll give it a check

**Comment by fonyo** [comment]
added to FAQ
