### ISSUE TITLE
No pools available.

### ISSUE THREAD

**Issue by Sham3R** [aaronsace/MultiPoolMiner#734]
I've been trying to get this running however i keep getting the no pools available warning. I have tried a fresh bat file from updating and only changing the basic info along with removing the nicechash ps1 from the pools folder. Most recent log as follows.

**********************
PowerShell transcript start
Start time: 20171218054601
Username: DESKTOP-96TMMQK\shado
RunAs User: DESKTOP-96TMMQK\shado
Configuration Name: 
Machine: DESKTOP-96TMMQK (Microsoft Windows NT 6.2.9200.0)
Host Application: C:\Program Files\PowerShell\6.0.0-rc.2\pwsh.dll -noexit -executionpolicy bypass -windowstyle maximized -command & .\multipoolminer.ps1 
Process ID: 596204
PSVersion: 6.0.0-rc.2
PSEdition: Core
GitCommitId: v6.0.0-rc.2
OS: Microsoft Windows 10.0.15063 
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is .\Logs\2017-12-18_05-46-01.txt
WARNING: No pools available.

**Comment by aaronsace** [comment]
Please download the release, extract it onto your desktop then double click on 'start.bat'. 
https://github.com/aaronsace/MultiPoolMiner/releases

**Comment by aaronsace** [comment]
There is no command-line options on your post.
