### ISSUE TITLE
Lyra2z non-cuda9 temp fix

### ISSUE THREAD

**Issue by iwtym** [aaronsace/MultiPoolMiner#735]
Problem: Non-CUDA 9 GPU gets "no kernel image is available for execution on the device" error on cuda9 miner (such as the Lyra2Z miner)

Workaround:
1. Download djm34/ccminer-msvc2015/releases/download/v0.2.1/ccminer.exe
2. Rename (and replace) ccminer.exe to ccminer_cuda9.exe in Bin\Lyra2z-NVIDIA\
3. Download _Visual C++ Redist Visual Studio 2015_ through the links provided in the readme ([here](https://www.microsoft.com/en-us/download/details.aspx?id=48145))
4. Optional: Reset Lyra2Z hashrate by deleting file Stats\CcminerLyra2z_Lyra2z_HashRate.txt
5. Re-run MPM

Feel free to include this in readme as a temporary fix.

**Comment by UselessGuru** [comment]
This miner is broken. See [https://github.com/djm34/ccminer-msvc2015/issues/23](https://github.com/djm34/ccminer-msvc2015/issues/23)

**Comment by ChriscomIT** [comment]
@iwtym Thanks for the hint. Will check it out later.

@UselessGuru Why ship it then at all? Would be more logical to exclude it then until a fixed release is available. Did it manual for the time being. Just my 2 cents.

**Comment by UselessGuru** [comment]
@ChriscomIT
>  Why ship it then at all? 

Good question - If it was not then people would probably scream for it.
Me for my part have done away with the Lyra2Z algo altogether - other algos are more profitable.

If you really want to use CcminerLyra2z then you might use the following trick to make MPM see lower (closer to reality) hashrates:
Let it complete the benchmark. Then edit the resulting stat file (.\Stats\CcminerLyra2z_Lyra2z_hashrate.txt) and reduce all big numbers by factor x, e.g. 148.495 -> 120 (approx. 20%) then save the file.
On subsequent runs MPM will display a yello msg about hashrate being out of tolerance, but this is to be expected. Just ignore it.
