### ISSUE TITLE
PowerShell  Updater notificaton nag

### ISSUE THREAD

**Issue by AymanEG** [aaronsace/MultiPoolMiner#737]
Hello there,

Thanks for this awesome software.

I use the last version from GitHub directly sync by GitHub desktop. It works just fine, Yesterday started to show 

```
Updater
    PowerShell

    Acquiring Online (https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc.2/PowerShell-6.0.0-rc.2-win-x64.msi)
```

Although I have it installed,  it still appears.

Note : Power-Shell V.5 is still installed as well
![powershell](https://user-images.githubusercontent.com/23207050/34126674-1ac15f7c-e443-11e7-9b19-f24ceb59d672.PNG)

**Comment by aaronsace** [comment]
Have you got the log(s)?

**Comment by aaronsace** [comment]
Also, screenshot the cmd window before it disappears at the start.

**Comment by AymanEG** [comment]
last 3 logs.

[2017-12-18_22-02-40.txt](https://github.com/aaronsace/MultiPoolMiner/files/1569880/2017-12-18_22-02-40.txt)
[2017-12-18_22-07-48.txt](https://github.com/aaronsace/MultiPoolMiner/files/1569881/2017-12-18_22-07-48.txt)
[Uploading 2017-12-18_23-12-06.txt…]()

**Comment by AymanEG** [comment]
Also How I can add ETH to the comparison logic if possible ?! I mean you can calculate ETH/BTC price or it is complicated ?! Having GTX 1070 by the way.

Thanks man

**Comment by AymanEG** [comment]
One more request : Disabling NiceHash api request since they are down ?

**Comment by aaronsace** [comment]
You're using an old bat file, please use the new one to fix your problem.

**Comment by aaronsace** [comment]
To add Ethereum: 
`-currency btc,eth`

**Comment by aaronsace** [comment]
NiceHash API is disabled automatically as indicated by the failure warning.

**Comment by AymanEG** [comment]
Oh, did not notice new files
what number beside : switchingprevention mean ?!

-currency btc,eth means I assign eth as output correct ?! I meant to mine ETH not as output.
Thanks

**Comment by AymanEG** [comment]
Used the new command line ,reset stats and settings ,but the notification still appears
[2017-12-19_05-08-28.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570204/2017-12-19_05-08-28.txt)

**Comment by aaronsace** [comment]
SwitchingPrevention: zero doesn't prevent switching at all and can be set as high as you want

Ethereum uses the algorithm called Ethash

**Comment by aaronsace** [comment]
The new 'PowerShell' is called 'PWSH' in command prompt.

**Comment by AymanEG** [comment]
But still I dont understand what if I put : SwitchingPrevention: 10 like default what it will do ?! Please update  readme page as well

Thanks

**Comment by jayntguru** [comment]
Discussed here. https://github.com/aaronsace/MultiPoolMiner/commit/82770d2d1c0a9f8285905e2ece0600d1bd219906#commitcomment-26348629

**Comment by AymanEG** [comment]
I am confused cuz check this :
![miner-9](https://user-images.githubusercontent.com/23207050/34174611-3ab49ac8-e502-11e7-8c53-6c4d38678790.PNG)

**Comment by AymanEG** [comment]
So it is like mining for 10 minutes in the same pool before switching ?! what does the "10" parameter mean ?

**Comment by AymanEG** [comment]
I am using zpool by the way, so it should coin hoping safe ,correct ?!

**Comment by aaronsace** [comment]
Yes but don't set it to zero though; you'll just be opening and closing miners.

**Comment by AymanEG** [comment]
Thanks ,it is time to close the issue, marked as solved
