### ISSUE TITLE
Warning about NiceHash being down even though removed related flags?

### ISSUE THREAD

**Issue by OneOfMany07** [aaronsace/MultiPoolMiner#738]
Seems like even after removing anything nicehash related in the command line the tool still tries to talk to NiceHash, and I get an error.  In case it matters I see the same for Hash Refinery too.  I've already whitelisted this app in my antivirus (Bitdefender) since it was quarantining all the downloads, and even the log file was flagged as suspect!

`C:\Users\<username>\Downloads\MultiPoolMinerV2.7.1.1>pwsh -noexit -executionpolicy bypass -windowstyle maximized -command "& .\multipoolminer.ps1 -wallet <address> -username <MiningPoolHub Username> -workername multipoolminer -region us -currency btc,usd,eth -type nvidia,cpu -poolname miningpoolhub,miningpoolhubcoins,zpool -algorithm cryptonight,decred,ethash,ethash2gb,equihash,groestl,lbry,neoscrypt,pascal,sia,siaclaymore,sib,skunk -donate 24 -watchdog"
Transcript started, output file is .\Logs\2017-12-18_17-18-47.txt
WARNING: Pool API (NiceHash) has failed.`

**Comment by ChriscomIT** [comment]
It's not altering the proper function of MPM in any way. If you want to get rid of the error message just delete the pool files you don't need in the "Pools" folder from MPM main directory. I would advise to save them to a backup folder if you wish to use them later.

**Comment by OneOfMany07** [comment]
Good to know.  I'd suggest mentioning that in the warning then.  Or moving it to a "debug" level output, meaning something only enabled for developers so they'll see it if they care.

**Comment by aaronsace** [comment]
I think users would like to know when a pool is down; warnings are not errors.
