### ISSUE TITLE
Time running stat is incorrect

### ISSUE THREAD

**Issue by newt0this** [aaronsace/MultiPoolMiner#741]
MPM shows that ccminer has been running on my computer for 152,292 days.  I'm not sure if this is a problem with the miner or the MPM but it's obviously not right.  I could have something set up wrong too.  It's not a big issue but any help is appreciated.
[2017-12-18_14-52-02.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570355/2017-12-18_14-52-02.txt)

**Comment by UselessGuru** [comment]
This issue has been reported before and is purely cosmetic. It is very rare and cannot be reproduced. I had looked at the code and cannot see anything wrong - therefore I suspect a powershell bug.

**Comment by aaronsace** [comment]
Can't remember that last time this has happened; think it's safe to say it's rare and doesn't effect the running. When I overhual the miner lauch the this problem will no longer exsist.

**Comment by aaronsace** [comment]
BTW, you're not on the latest version either.
