### ISSUE TITLE
Is it normal to mine GPUs on 2 different pools at the same time?

### ISSUE THREAD

**Issue by paulpoco** [aaronsace/MultiPoolMiner#742]
Bin\Ethash-Claymore\EthDcrMiner64.exe -r -1 -mport 23333 -epool us-east.ethash-hub.miningpoolhub.com:17020 -ewal paulpoco.multipoolminer -epsw x -esm
                                                            3 -allpools 1 -allcoins 1 -dpool lbry.mine.zpool.ca:3334 -dwal 1LA867GKG2VGxZS2iAtGab1WPFDJ3XnPtU -dpsw multipoolminer,c=BTC -dcoin lbc -dcri 40
                                                            -platform 2

If that is what I infer from the above?

**Comment by fonyo** [comment]
If you added the lbry algo which is not supported by MPH but supported by zpool, then yes, this is normal. I used to do this as well. Not a bad practice.

**Comment by OneOfMany07** [comment]
Neat!  Thanks for the explanation.

I can totally see how paulpoco could have questioned the validity/sanity of allowing that to happen, but if you need to upload results to two pools then you need to access 2.
