### ISSUE TITLE
Speed for almost all idle log entries is "0.00 PH/s" (sometimes you'll see one at the top that isn't 0)

### ISSUE THREAD

**Issue by OneOfMany07** [aaronsace/MultiPoolMiner#745]
I noticed this while benchmarking, that often the most recent thing to go idle would have a hash rate listed, but everything else would appear as "0.00 PH/s" in the tabular format.

I would expect all previous rates of hashing to be saved and reported until the line falls off the list.  Meaning if something was moved to idle the rate it had run at should be recorded at the top of the list.  And that entry should move down the list as it adds lines.

**Comment by UselessGuru** [comment]
@OneOfMany07 
This is purely cosmetic, The listed hashrate is the hashrate detected during the previous iteration. They are NOT kept for later!
Getitng hashrates from the miners is done AFTER the list of active / idle miners is displayed.

**Comment by OneOfMany07** [comment]
Yes, I realize this is cosmetic.  And I'd like to see the numbers you're claiming are 0.  Or not see the 0.

The value is printed as lines are added, so I'd say it should be saved...or not printed.

**Comment by OneOfMany07** [comment]
Maybe a better answer here is "shift the scale from forced PH/s to something that will show at least 1-2 significant digits"?  Meaning show H/s, or KH/s, or MH/s, or...

**Comment by UselessGuru** [comment]
0 PH/s = 0 H/s... 
For $null hashrate values MPM uses the unit PH/s.
