### ISSUE TITLE
null-valued expression error

### ISSUE THREAD

**Issue by jayvin100** [aaronsace/MultiPoolMiner#746]
<img width="326" alt="screenshot_21" src="https://user-images.githubusercontent.com/34394301/34143818-a7f88ab0-e4c9-11e7-8017-1162721d7814.png">

**Comment by OneOfMany07** [comment]
Did you edit either of those two files?  Looks like on line 17 character 5, of both files, it sees an error.  I'd guess a trailing ; isn't there, or a trailing newline (some programs seem to require that in any file...a line with nothing on it except a return/enter press).

**Comment by UselessGuru** [comment]
Update to the latest release, or update at least all the pool files. Your issue is fixed in these changes:
https://github.com/aaronsace/MultiPoolMiner/commit/754e061bee1217a07de88c00d746364d825832a9#diff-25fb404d69aaac5d6c98a0c8193de52d
