### ISSUE TITLE
Focus can be stolen from other programs.

### ISSUE THREAD

**Issue by OneOfMany07** [aaronsace/MultiPoolMiner#747]
No idea precisely what just happened, but I'm running MPM currently, and trying to use a web page otherwise to file bugs.  While typing the "focus" of the app was removed to somewhere else, so typing produced no output until I clicked again in the textbox I was typing in.

If at all possible this should be prevented.  Otherwise I won't run this program on my computer...it would interrupt usage too much.

**Comment by UselessGuru** [comment]
See [https://github.com/aaronsace/MultiPoolMiner/issues/712](https://github.com/aaronsace/MultiPoolMiner/issues/712)
