### ISSUE TITLE
Serious CPU time (12-13%) being used to process output.

### ISSUE THREAD

**Issue by OneOfMany07** [aaronsace/MultiPoolMiner#748]
At least I assume that is where the often >12% of my CPU time is going for "Windows Command Processor ...".  Don't know if there is a more efficient way to get output from those programs, but I'd suggest we try to find it.

**Comment by UselessGuru** [comment]
This is normal. These peaks happen once per MPM cycle and cannot be changed. The most CPU intense parts of the code  have already been analyzed and optimized as far as possible.
BTW: Finding ways to make most money is costly too (costs CPU cycles) :-)
