### ISSUE TITLE
zpool does not start CPU mining

### ISSUE THREAD

**Issue by komer83** [aaronsace/MultiPoolMiner#749]
Works fine with the MPH start file.

[2017-12-19_09-51-28.txt](https://github.com/aaronsace/MultiPoolMiner/files/1570793/2017-12-19_09-51-28.txt)

**Comment by UselessGuru** [comment]
Does Zpool have an algorithm that can be mined by CPU?
MPM just reads all supported algorithms from the pool (incl. pricing information) and then starts the most profitable miner. If there is no CPU mineable algorithm available on the pool then it will not use the CPU.
BTW: Remove your NiceHash pool file  - NH is dead!

**Comment by komer83** [comment]
failed :-/ please delete this :-D
