### ISSUE TITLE
ccminer not launching 

### ISSUE THREAD

**Issue by Wtcheesecakes** [aaronsace/MultiPoolMiner#750]
0.00 PH/s 00 Days 00 Hours 00 Minutes 3 Times  Bin\Lyra2RE2-NVIDIA\ccminer.exe -a lyra2v2 -o stratum+tcp://hub.miningpoolhub.com:17018 -u Englishsuccc.Englishsuccc -p x

status failed

**Comment by UselessGuru** [comment]
From a MPM point of view there is nothing wrong. The parameter is correct - there is something wrong with your computer. Are you overclocking?
You might have better luck posting this issue on the miners page.

**Comment by aaronsace** [comment]
There are many miner versions included; MultiPoolMiner will skip past the failed miner.
