### ISSUE TITLE
Disable Lyra2z-AMD on Windows 7

### ISSUE THREAD

**Issue by richardg867** [aaronsace/MultiPoolMiner#752]
djm34/sgminer-msvc2015 is compiled against Windows 8 system libraries and will not run on Windows 7. The author attempted to rectify the issue by providing a "nomincorelib" binary, which did not work. MPM should not attempt to download and run sgminer-msvc2015 under Windows 7.

![The program can't start because api-ms-win-core-libraryloader-l1-2-0.dll is missing from your computer. Try reinstalling the program to fix this problem.](https://i.imgur.com/rBWWKQ8.png)

**Comment by aaronsace** [comment]
It'll skip past the issue; I wouldn't worry.

**Comment by richardg867** [comment]
In a similar note, Excavator is enabled for AMD cards, however only the old 1.2.11 version supports AMD cards.
