### ISSUE TITLE
job ID 95 cannot be removed

### ISSUE THREAD

**Issue by newt0this** [aaronsace/MultiPoolMiner#753]
[error.txt](https://github.com/aaronsace/MultiPoolMiner/files/1572387/error.txt)

I get this error when starting MPM.  I cannot figure out the cause or the effect.  Everything seems to be running correctly.  

This is unrelated, but are there plans to add an interval option to the start files?  That would be a convenient way to be able to tweak the switching to maximize profits. 

Thanks for any help

**Comment by jayntguru** [comment]
https://github.com/aaronsace/MultiPoolMiner/issues/671

**Comment by aaronsace** [comment]
What version are you using?

**Comment by newt0this** [comment]
2.7.0.2

**Comment by aaronsace** [comment]
There is a new version: 
https://github.com/aaronsace/MultiPoolMiner/releases
