### ISSUE TITLE
Benchmarking taking an hour plus

### ISSUE THREAD

**Issue by Wtcheesecakes** [aaronsace/MultiPoolMiner#755]
have been running this for an hour now and its not finished benchmarking any idea what the issue is?

**Comment by symalla** [comment]
Depending on the number of algorithms it can take a lot longer. It takes me 4 hours to re benchmark  my system.

**Comment by aaronsace** [comment]
Select less algorithms.

**Comment by aaronsace** [comment]
Also note that you are actually mining whilst it's benchmarking so it's not fully wasted time.
