### ISSUE TITLE
Wrong fault tolerance vaules for Statfiles?

### ISSUE THREAD

**Issue by Joern85** [aaronsace/MultiPoolMiner#757]
Hi,
started to use MultiPoolMinerV2.7.1.1 since yesterday. I did a clean install and benchmark. 
On NVIDIA-Palgin ccminer.exe, blake2s, lyra2v2 and CryptoNight-CPU xmrig.exe and most probably other miners MPM is detecting valid hashrates as faulty. Here is an example:

WARNING: Stat file (XmrigCpu_CryptoNight_HashRate) was not updated because the value (219) is outside fault tolerance.

xmrig is runing with arround 220 H/s thus it's a valid value. This behavior leads to many miners/algos are being kicked out by watchdog over time.

Is this a bug or am i doing something wrong?

**Comment by aaronsace** [comment]
Are you using your computer whilst it's mining? 
Can you upload 'XmrigCpu_CryptoNight_HashRate.txt' and the log(s)?

**Comment by Joern85** [comment]
thx for your quick answer! 👍  

yes, i'm using my computer whilst mining. But i realized, that the benchmarked values maybe were to low. so i deleted the stat files of the mentioned algos and rerun the script. seems working now. i'll gladly upload logs if it occurs again.

**Comment by Joern85** [comment]
Here are some logs from the last hours where i didn't use my computer

[2017-12-20_23-52-17.txt](https://github.com/aaronsace/MultiPoolMiner/files/1580308/2017-12-20_23-52-17.txt)
[XmrigCpu_CryptoNight_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1580310/XmrigCpu_CryptoNight_HashRate.txt)
[FireiceCpu_CryptoNight_HashRate.txt](https://github.com/aaronsace/MultiPoolMiner/files/1580322/FireiceCpu_CryptoNight_HashRate.txt)
