### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Lagarinhos** [aaronsace/MultiPoolMiner#766]
Would be possible for updates, release with the version an alternative option like a zip file with a *.bat to update the current version we are using instead of a full new setup just to replace the files u did changes? We could avoid benchmark again and lose all the statistics we got with the new codes u inserted like profit switching prevention and so.
Is that possible? 
Thks for the hardwork though
Ive tried many different softwares like MPM and yourse rocks. Congrats!

**Comment by paulpoco** [comment]
Copy Stats folder?

**Comment by jayntguru** [comment]
If there's newer miner versions I wouldn't do that.

**Comment by aaronsace** [comment]
@Lagarinhos Cheers. 

For minor changes, copy the stats folder; if there are updates to miners with a widely different speed then the stats will be incorrect.
