### ISSUE TITLE
Is it possible to use GPU 0 to 13 for one start.bat and GPU 14 to 18 for another start.bat ?

### ISSUE THREAD

**Issue by Braintelligence** [aaronsace/MultiPoolMiner#770]
Hi everyone!
Is it possible to use specific GPU for different start.bat ?

My use-case is that I have a mainboard that isn't able to boot up as soon as you connect the 14th nVidia GPU (as long as it's not a (G)P106 GPU) but it may work with Polaris cards; I haven't tested this yet.

This would only make sense, though, if I could set the Polaris cards to only work with Ethash, while the nVidia cards will run the most profitable thing.

So is this possible?

**Comment by UselessGuru** [comment]
> Is it possible to use GPU 0 to 13 for one start.bat and GPU 14 to 18 for another start.bat

Currently not. The only choice for you now:
Keep two copies of MPM and in both instances edit all the miner files (in both copies) to mine only on the selected cards.
For this you would have to look for the following section (an example for a Ccminer[...].ps1):
$Commands = [PSCustomObject]@{
    "bitcore"      = " -d 0,1,2,3,4,5,6,7,8,9,10,11,12,13" # 14 Nvidia Cards
...

Please also note that not all miners can work with a counter greater 9 (two digits).
The actual command to select the chosen devices is different per miner type.

**Comment by Braintelligence** [comment]
I see.
Well, this use-case will only become necessary, if I actually manage to make a Polaris run as 14th+ GPU.
Thank you for explaining what I'd have to do.

It would be cool if this would be implemented tho in future versions for people who run drastically different GPUs on a system.

For example I wouldn't want to run the same algos on a GTX 1070, 1080 and 1080 Ti.

No hurries, tho.

**Comment by UselessGuru** [comment]
@Braintelligence

>  I wouldn't want to run the same algos on a GTX 1070, 1080 and 1080 Ti.

Nor do I :-)
If you you are interested I can provide you my code - it differs a bit from MPM (but I try to backport most changes) and it can do exactly this. It always runs the fastest algo for each card (1080ti,1070,1060GB, others untested)
I don't have AMD hardware so some stuff is for NVIDIA only (e.g. power consumption measurement)

**Comment by carlo0000** [comment]
why just have not 2 rings ?

i notice it s far ways better to have more small rrng than 1 big what always have a lot of trouble

**Comment by Braintelligence** [comment]
Because I do not have "a lot of trouble" and can save CPU/RAM/SSD/Ethernetport thus having a significantly lower ROI.

**Comment by fonyo** [comment]
@Braintelligence 

That's true, ROI time is definitely far less but I consider your post here already a "case of having trouble". No offense but with a rig that has so many cards attached to, you will always find hard limitations with some if not most of the software. Good luck and grats for making a rig like that, though! :)

**Comment by Braintelligence** [comment]
@fonyo The trouble is, that Asus doesn't allow a 14th Nvidia gpu upwards, as long as it's not a (G)P106. Other than that I had no problems whatsoever and the board has still by far the best ROI.
I just want to try to get the ROI even further by combining Polaris cards.
