### ISSUE TITLE
Cpuminer is attempting to mine unsupported Lyra2z

### ISSUE THREAD

**Issue by dabnpits** [aaronsace/MultiPoolMiner#771]
Cpuminer is attempting to mine Lyra2z, which it doesn't appear to support. From the log:

`Bin\CPU-TPruvot\cpuminer-gw64-core2.exe -a lyra2z -o stratum+tcp://us-east.lyra2z-hub.miningpoolhub.com:17025 -u xxx.xxx -p x`

Here's the message from cpuminer:

```
** cpuminer-multi 1.3.1 by tpruvot@github **
BTC donation address: 1FhDPLPpw18X4srecguG3MxJYe4a1JsZnd (tpruvot)

[2017-12-20 10:24:08] Unknown algo parameter 'lyra2z'
```

**Comment by iwtym** [comment]
cpuminer jaydee does support lyra2z - mine uses the JayDee-aes avx version to do mine it. Does it try it perpetually? I believe mine sometimes tries various miners on benchmark, some that get no good result and eventually get removed.

**Comment by UselessGuru** [comment]
Removed unsupported algo in miner file -> Re-download the miner file
[https://github.com/aaronsace/MultiPoolMiner/commit/e879995403bf6aaaa985015f544bbadf0fdaa190](url)
