### ISSUE TITLE
Serious issues. Need prompt answers. Rigs are down. 

### ISSUE THREAD

**Issue by cmbconcretefire** [aaronsace/MultiPoolMiner#774]
Info: Running 2 rigs. Both on Windows 8.1. (all updates installed as far as I know) 
1 rig - 6x1060's
1 rig - 6x1070's

I am / was using 2 different methods to connect to these rigs remotely. Remote Desktop inside of windows itself, and Teamviewer for when I am out of town. 

Immediately after installing MPM v 2.7.1.1 AND installing the new (?) powershell v 6 AND the excavator as per the instructions. < I opened the main MPM folder located on my DESKTOP and began adjusting the start zpool.bat. I got everything like I wanted and am only mining algos > Equihash, Lyra2re2, and neoscrypt. I deleted the Nicehash "thing" in the pools folder. I then launched the start zpool bat. 

Everything started off fine. It was running through the benchmarks and then all of a sudden I basically get disconnected from the rig. Remote Desktop tells me it will try to reconnect, but it never does. I have to go shut my rigs completely down, and reboot them. This issue is a rinse and repeat loop. It never does finish the benchmarking. That's problem #1 

#2 > the palgin ccminer 1.1.1_x64.zip at Github apparently no longer exists. Go to github and see for yourself. MPM wants it, but it isn't there anymore. Luckily I had a backup copy of it. 

I ASSURE YOU > I have never had this 'disconnecting' problem before. Ever. And trust me, I'm not mad, I just want to figure out what could have caused this, and more importantly, how to fix it, because right now, I am dead in the water.

**Comment by aaronsace** [comment]
Just delete the miner that is crashing inside the folder called 'miners'. Also, check your OC settings.

**Comment by cmbconcretefire** [comment]
Ok, you make a good point about OC settings. I'll default them. And report back. But the odd thing is, I can run the LAST edition of MPM with the same exact settings all day long...... it doesn't make any sense. I assume it's running the same exact miners for the given algos I listed above.

**Comment by cmbconcretefire** [comment]
I guess it had / has to be excavator. I deleted that on a hunch from @fonyo a while back. Both rigs are back up and mining. I don't know what is wrong with excavator. Also, I put my rigs back to my regular OC that I've been running for months.....and everything is smooth. Has to be excavator. ????

**Comment by platinum4** [comment]
Depends, but we don't have nearly enough information, no OC settings or anything.
