### ISSUE TITLE
0 PH/s and watchdog did not stop the mininer?

### ISSUE THREAD

**Issue by zoglun** [aaronsace/MultiPoolMiner#777]
I got 0 hash rate with lyra2z on TPruvot/ccminer-x64.exe with lyra2z.mine.zpool.ca
Also 0 hash rate for Palgin/ccminer.exe with lbry.mine.zpool.ca

For some reason the MiningPoolHub watch dog did not kill the miner with no hash rate.

==================
MultiPoolMinerV2.7.1.1.zip

start.bat
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\MultiPoolMiner.ps1 -wallet 38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA -username baskice -workername gtx1070ti -region US -currency btc,usd -type nvidia -poolname miningpoolhub,miningpoolhubcoins,zpool -algorithm cryptonight,decred,ethash,ethash2gb,equihash,groestl,lbry,lyra2z,neoscrypt,sia,siaclaymore,sib -watchdog"`

```
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_1.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_1.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Lbry_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_NeoScrypt_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Lbry_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\zoglun\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_NeoScrypt_38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA_3_Nvidia.json'."

   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 21 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a lyra2z -o stratum+tcp://lyra2z.mine.zpool.ca:4553 -u 38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA -p gtx1070ti,c=BTC
0.00 PH/s 00 Days 00 Hours 30 Minutes 2 Times  Bin\NVIDIA-Palgin\ccminer.exe -a lbry -o stratum+tcp://lbry.mine.zpool.ca:3334 -u 38LyFdFTpe3LhmvVhfnj4fUQsdZkvmbcBA -p gtx1070ti,c=BTC
```

**Comment by aaronsace** [comment]
Please upload the log files.

**Comment by zoglun** [comment]
By further running my two card mining pc 24h. I have not encounter no hash rate problem. Did not change anything. Have no idea why.

This is the full log of last line in the 0 PH/s period yesterday.
==========================
WARNING: Pool API (Hashrefinery) returned nothing.
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_1.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_*************************_1.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_*************************_2.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_3.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_*************************_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Lbry_*************************_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_NeoScrypt_*************************_2_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\MiningPoolHub_Ethash_baskice.gtx1070ti_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Equihash_*************************_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_Lbry_*************************_3_Nvidia.json'."
PS>TerminatingError(Set-Content): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path 'C:\Users\baskice\Desktop\MultiPoolMiner\Bin\Excavator\Zpool_NeoScrypt_*************************_3_Nvidia.json'."


   Type: NVIDIA

Miner                     Algorithm                                    Speed            BTC/Day         BTC/GH/Day Pool
-----                     ---------                                    -----            -------         ---------- ----
CcminerKlaust             NeoScrypt                                2.14 MH/s            0.00092            0.42966 Zpool
CcminerNanashi            NeoScrypt                                1.75 MH/s            0.00075            0.42966 Zpool
CcminerPalgin             Sib                                     27.66 MH/s            0.00071            0.02576 Zpool
CcminerTpruvot            Lyra2z                                   4.19 MH/s            0.00071            0.16907 Zpool
CcminerSib                Sib                                     26.90 MH/s            0.00069            0.02576 Zpool
CcminerTpruvot            NeoScrypt                                1.58 MH/s            0.00068            0.42966 Zpool
CcminerLyra2z             Lyra2z                                   3.75 MH/s            0.00063            0.16907 Zpool
XmrigNvidia               CryptoNight                              1.47 KH/s            0.00059          403.80180 MiningPoolHub-Monero
CcminerTpruvot            Sib                                     23.02 MH/s            0.00059            0.02576 Zpool
CcminerTpruvot            CryptoNight                              1.45 KH/s            0.00059          403.80180 MiningPoolHub-Monero
Dstm                      Equihash                                 1.01 KH/s            0.00056          553.80000 Zpool
Ewbf                      Equihash                               977.81  H/s            0.00054          553.80000 Zpool
ClaymoreNvidiaLbry40      {Ethash, Lbry}            {62.78 MH/s, 73.24 MH/s} {0.00045, 0.00005} {0.00710, 0.00062} {MiningPoolHub-Musicoin, Zpool}
ClaymoreNvidia2gbLbry40   {Ethash2gb, Lbry}         {62.72 MH/s, 73.17 MH/s} {0.00045, 0.00005} {0.00710, 0.00062} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidia2gbLbry30   {Ethash2gb, Lbry}         {63.13 MH/s, 60.50 MH/s} {0.00045, 0.00004} {0.00710, 0.00062} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidiaLbry30      {Ethash, Lbry}            {63.08 MH/s, 60.45 MH/s} {0.00045, 0.00004} {0.00710, 0.00062} {MiningPoolHub-Musicoin, Zpool}
ClaymoreNvidia2gbDecred40 {Ethash2gb, Decred}      {63.03 MH/s, 840.40 MH/s} {0.00045, 0.00004} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidiaDecred40    {Ethash, Decred}         {62.94 MH/s, 839.25 MH/s} {0.00045, 0.00004} {0.00710, 0.00004} {MiningPoolHub-Musicoin, Zpool}
ClaymoreNvidia2gbLbry20   {Ethash2gb, Lbry}         {63.34 MH/s, 47.50 MH/s} {0.00045, 0.00003} {0.00710, 0.00062} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidiaLbry20      {Ethash, Lbry}            {63.23 MH/s, 47.42 MH/s} {0.00045, 0.00003} {0.00710, 0.00062} {MiningPoolHub-Musicoin, Zpool}
ClaymoreNvidia2gbSia40    {Ethash2gb, SiaClaymore} {63.05 MH/s, 840.65 MH/s} {0.00045, 0.00003} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidia2gbSia30    {Ethash2gb, SiaClaymore} {63.96 MH/s, 639.62 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidiaSia30       {Ethash, SiaClaymore}    {63.92 MH/s, 639.16 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHub-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidiaSia40       {Ethash, SiaClaymore}    {62.87 MH/s, 838.32 MH/s} {0.00045, 0.00003} {0.00710, 0.00004} {MiningPoolHub-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidia2gbDecred30 {Ethash2gb, Decred}      {63.19 MH/s, 631.89 MH/s} {0.00045, 0.00003} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidiaDecred30    {Ethash, Decred}         {63.08 MH/s, 630.80 MH/s} {0.00045, 0.00003} {0.00710, 0.00004} {MiningPoolHub-Musicoin, Zpool}
CcminerTpruvot            Equihash                               850.00  H/s            0.00047          553.80000 Zpool
ClaymoreNvidiaSia20       {Ethash, SiaClaymore}    {63.97 MH/s, 426.45 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHub-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidia2gbSia20    {Ethash2gb, SiaClaymore} {63.85 MH/s, 425.70 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, MiningPoolHubCoins-Siacoin}
ClaymoreNvidia2gbDecred20 {Ethash2gb, Decred}      {63.33 MH/s, 422.23 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHubCoins-Musicoin, Zpool}
ClaymoreNvidiaDecred20    {Ethash, Decred}         {63.26 MH/s, 421.73 MH/s} {0.00045, 0.00002} {0.00710, 0.00004} {MiningPoolHub-Musicoin, Zpool}
ClaymoreNvidia            Ethash2gb                               64.38 MH/s            0.00046            0.00710 MiningPoolHubCoins-Musicoin
ClaymoreNvidia            Ethash                                  64.31 MH/s            0.00046            0.00710 MiningPoolHub-Musicoin
EthminerNvidia            Ethash                                  63.97 MH/s            0.00045            0.00710 MiningPoolHub-Musicoin
CcminerNanashi            Lyra2z                                   2.65 MH/s            0.00045            0.16907 Zpool
EthminerNvidia            Ethash2gb                               62.92 MH/s            0.00045            0.00710 MiningPoolHubCoins-Musicoin
CcminerPalgin             Lbry                                   655.85 MH/s            0.00041            0.00062 Zpool
CcminerKlaust             Groestl                                 74.79 MH/s            0.00039            0.00515 Zpool
CcminerTpruvot            Groestl                                 72.79 MH/s            0.00037            0.00515 Zpool
CcminerTpruvot            Decred                                   5.93 GH/s            0.00025            0.00004 Zpool


   Type: {AMD, NVIDIA}

Miner      Algorithm        Speed BTC/Day BTC/GH/Day Pool
-----      ---------        ----- ------- ---------- ----
Prospector CryptoNight  1.40 KH/s 0.00056  403.80180 MiningPoolHub-Monero
Prospector Ethash      63.07 MH/s 0.00045    0.00710 MiningPoolHub-Musicoin
Eminer     Ethash2gb   62.50 MH/s 0.00044    0.00710 MiningPoolHubCoins-Musicoin
Eminer     Ethash      62.37 MH/s 0.00044    0.00710 MiningPoolHub-Musicoin




   Status: Running

    Speed Active                      Launched Command
    ----- ------                      -------- -------
2.14 MH/s 00 Days 00 Hours 58 Minutes 2 Times  Bin\NVIDIA-KlausT\ccminer.exe -a neoscrypt -o stratum+tcp://neoscrypt.mine.zpool.ca:4233 -u ************************* -p gtx1070ti,c=BTC


   Status: Idle

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0.00 PH/s 00 Days 00 Hours 21 Minutes Once     Bin\NVIDIA-TPruvot\ccminer-x64.exe -a lyra2z -o stratum+tcp://lyra2z.mine.zpool.ca:4553 -u ************************* -p gtx1070ti,c=BTC
0.00 PH/s 00 Days 00 Hours 30 Minutes 2 Times  Bin\NVIDIA-Palgin\ccminer.exe -a lbry -o stratum+tcp://lbry.mine.zpool.ca:3334 -u ************************* -p gtx1070ti,c=BTC



Miner         Pool  Algorithm Watchdog Timer
-----         ----  --------- --------------
CcminerKlaust Zpool NeoScrypt      0 Seconds

**Comment by aaronsace** [comment]
There are no issues with what you posted but if you require further assistant then upload the log files(s).

**Comment by vitor900000** [comment]
"WARNING: Pool API (Hashrefinery) returned nothing"
is it normal? i looked in to the API folder and there isn't a Hashrefinery API there...

**Comment by aaronsace** [comment]
Their API is just glitching; MultiPoolMiner just warns you but it's handled the problem and moved on.
