### ISSUE TITLE
DLL missing yet it's clearly there?

### ISSUE THREAD

**Issue by lee-aaron** [aaronsace/MultiPoolMiner#78]
I have a NVIDIA GTX 960 so I'm sure it affects the fact that I see this issue but it's odd that the file wouldn't be found yet it's in the BIN\AMD-Reorder folder. It says another DLL is missing as well when it's in the same folder. This doesn't hinder my mining progress as there are other profitable algos and miners but I think it would be useful to solve.

![capture](https://cloud.githubusercontent.com/assets/21045039/25115241/bc93e608-23b9-11e7-861d-5ea6efd5910c.JPG)

**Comment by imrecsoka** [comment]
This is not an MS Visual Runtime error right ? im not sure?

**Comment by aaronsace** [comment]
It's this sgminer version that's not working:
djm34/sgminer-msvc2015#4

Just let it skip past the benchmark.
