### ISSUE TITLE
MultiPoolMiner not mining most profitable?

### ISSUE THREAD

**Issue by clownfish44** [aaronsace/MultiPoolMiner#782]
What it says I should run
https://gyazo.com/be7f9b56f4c761015b7bf59827fc9e3a 

Hours I have been running which ones
https://gyazo.com/fe046376aadc32497af4e0db74dab10f

why do they not match up

**Comment by fonyo** [comment]
@clownfish44 
On your screenshots, it says lyra2z is the most profitable and that is exactly what it is mining (active). It also shows you what it mined before (idle).

Business as usual. I think you are misreading the information.
