### ISSUE TITLE
HSR miner using wrapper, should use Ccminer API

### ISSUE THREAD

**Issue by grantemsley** [aaronsace/MultiPoolMiner#786]
The new HSR algorithm for NVIDIA-Alexis78hsr is using the wrapper instead the API.
It wouldn't run properly for me with the wrapper, but seems to work perfectly with the Ccminer API, which I would think would be the preferred method?

Unless there's something I'm missing that makes it work better with the wrapper?

**Comment by UselessGuru** [comment]
Correct - my mistake!
Fixed - just redownload the miner file.
