### ISSUE TITLE
Excludue coin within an algo?

### ISSUE THREAD

**Issue by Nexworks** [aaronsace/MultiPoolMiner#789]
Is there any way to exclude a coin within an algo? Like I want to mine equihash (bitcoin-gold, zcash, zencash) but not Zclassic (which is also equihash). Any way this can be done?

**Comment by UselessGuru** [comment]
This is not generally possible. Not all pools/poolfiles include the coin name through their API.
For the ...Coins.ps1 pool files this is possible, You need to modify the ps1 file yourself - 'out of the box' it is not supported. by MPM.

**Comment by fonyo** [comment]
Not sure why you want to exclude it when sometimes it can bring you better profit than all the others. You should let it be mined when most profitable and if you don't want to keep it, set it up to be auto-exchanged to another coin of your choice on MPH.
