### ISSUE TITLE
"all" option for -algorithm flag

### ISSUE THREAD

**Issue by felix920506** [aaronsace/MultiPoolMiner#798]
Setting up the bat file is a nightmare when choosing algorithm
I want to mine all algorithms so I had to copy in the algorithms from the "Algorithms".txt
Example file (I hope it was like this) : 
[Start.bat.zip](https://github.com/aaronsace/MultiPoolMiner/files/1583869/Start.bat.zip)

**Comment by aaronsace** [comment]
@felix920506 It's an optional field. You don't need to specify any.
