### ISSUE TITLE
v2 improvements?

### ISSUE THREAD

**Issue by lyolyalya** [aaronsace/MultiPoolMiner#8]
hey.is it any changes in v2 vs v1.3 or it is benchmark only?
update.see delta but now with benchark i more confused what to change for ccminer and where...can you adapt delta for v1.3??it is simplier for me and i don't need benchmark at all...

**Comment by aaronsace** [comment]
Mainly benchmarking. You use ccminer, correct? 

I don't have a NVIDIA card; please could you try running this powershell script let us know what ccminer sends back: 

`$server = "localhost"
$port = 4028
$message = @{command="summary"; parameter=""} | ConvertTo-Json

$client = New-Object System.Net.Sockets.TcpClient $server, $port
$stream = $client.GetStream()

$writer = New-Object System.IO.StreamWriter $stream
$writer.Write($message)
$writer.Flush()

$reader = New-Object System.IO.StreamReader $stream

$reader.ReadToEnd()`

**Comment by lyolyalya** [comment]
any nvidia card or 1070 maybe?

**Comment by lyolyalya** [comment]
![image](https://cloud.githubusercontent.com/assets/16507768/21405038/d9e31998-c7cc-11e6-91c2-22a9452fa231.png)
on my rig 3x1070 with ccminer running

**Comment by aaronsace** [comment]
Sorry, try port '4068' instead of '4028'.

**Comment by lyolyalya** [comment]
already tried=)just nothing=)
![image](https://cloud.githubusercontent.com/assets/16507768/21405289/f277bdfa-c7cd-11e6-83f7-4634c1aac037.png)

**Comment by aaronsace** [comment]
There is like no documentation. I'm sure it must be something simple. 

Try this: 
`$server = "localhost"
$port = 4068
$message = "summary"
$client = New-Object System.Net.Sockets.TcpClient $server, $port
$stream = $client.GetStream()
$writer = New-Object System.IO.StreamWriter $stream
$writer.Write($message)
$writer.Flush()
$reader = New-Object System.IO.StreamReader $stream
$reader.ReadToEnd()`

**Comment by lyolyalya** [comment]
not starting at all...

**Comment by aaronsace** [comment]
Is there an error message?

**Comment by lyolyalya** [comment]
oops...i refresh page and your scrypt is changing a little=)
![image](https://cloud.githubusercontent.com/assets/16507768/21405776/a408f1a4-c7d0-11e6-828b-517d71eca9f2.png)

**Comment by aaronsace** [comment]
Nice!

**Comment by lyolyalya** [comment]
guess it's working now=)

**Comment by aaronsace** [comment]
I'll get that added into version 2. Thank you very much.

**Comment by lyolyalya** [comment]
welcome.so how about delta for v1.3?=)

**Comment by aaronsace** [comment]
It's in v2 but you are best waiting until I've added NVidia support.

**Comment by lyolyalya** [comment]
i saw it=)but i like v1.3.nvidia is already working good with my changes.i'm just scared so many files to change in v2.but if you think so...waiting.
