### ISSUE TITLE
Not related to Multioolminer app BUT website - please assist if possible

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#80]
hi, i have been wondering how on earth to ask the Miningpoolhub guys for help.
I dont know how or if it is possible to mine and then convert your mined data into bitcoin like Nicehash Miner does.

Please can somebody let me know...

Appreciate the help

**Comment by vinaosb** [comment]
Login, go to Auto Exchange Coin
then in Auto Exchange Coin
then in Auto exchange to select Bitcoin
then click in the button Set Auto Exchange Coin

**Comment by imrecsoka** [comment]
Is that it ?

**Comment by aaronsace** [comment]
Yep 😁

**Comment by imrecsoka** [comment]
Okay guys thanksm, i think i managed , i also had to click the right arrow to put the coins i had although it was probably not even 1 dollar, but i did it anyways.

the coins that i do mine now will automatically be transfered to btc i guess.
I will start now

Im not sure which is better Nicehash Miner or Miningpoolhub

I just feel so behind and slow , i only have one little graphics card and cpu....

**Comment by aaronsace** [comment]
I may integrate NiceHash pool at some point but MiningPoolHub is definitely worth supporting over the  NiceHash monolith.
