### ISSUE TITLE
Lyra2z GPU1 invalid device function

### ISSUE THREAD

**Issue by crellmonf** [aaronsace/MultiPoolMiner#800]
Getting invalid device function message when Lyra2z-NVIDIA is ran .
I have a GTX 1070 TI
and a GTX 970

also getting ridiculous hashrate reported on it.
Tried deleting it's folder at "BIN" to see if the downloaded file was bad but it still has the same issue

![image](https://user-images.githubusercontent.com/8564960/34319645-68662180-e822-11e7-9b4f-fc11388b01aa.png)

**Comment by UselessGuru** [comment]
This is a miner software issue. Please report it on the software developer page. MPM has nothing to do with it.
