### ISSUE TITLE
XMR_STAK_CPU - performance is poor not sure how to tweak or configure?

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#81]
Hi, i would like to know how to configure the XMR_STAK_CPU to run on all CORES.... since i have 4 but it is only using 2 from what it seems.

I need to hack it by write protecting the config.txt file after it has already been searched and replaced but this is a ball ache if u ask me and i am probably not smart enough to know the simple way?
Im sure there is flexibility  build in to this nice little UK powered application but i am obviously not understand it.

I have tried to edit the config.txt file but it keeps getting rewritten it seems, i notice this with Nicehashminer and Multipoolminer.

Dont know what i am doing but if it is possible that somebody can help me here that would be great.

Thanks

**Comment by aaronsace** [comment]
It's because that miner doesn't support command line options (real pain TBH). 
Edit the file in the folder called miners instead. 

I'm making improvements to accommodate FireIce's miners.

**Comment by imrecsoka** [comment]
Looking forward to the improvements.
Please just let me know how i update my extracted Multipool Miner : 
MultiPoolMinerV2.5.zip
Im guessing i just extract and over write files?
