### ISSUE TITLE
Added zpool

### ISSUE THREAD

**Issue by jakewarren81** [aaronsace/MultiPoolMiner#82]
I've been working on adding zpool to the miner and I believe its to a point where its fully functional.  This was mainly to allow for Lbry and decred, as well as a number of equihash and skein coins zpool has.

The PoolName parameter works perfect to filter it out and minimal changes were made to the MiningPoolHub.ps1 files to adjust case so duplicates don't show up when comparing the pools.

Let me know what you think and if you want to pull it in.  Thanks.

**Comment by aaronsace** [comment]
Do a pull request and I will think about it. 

I had some code for Zpool and Nicehash but never publicly released them.

**Comment by imrecsoka** [comment]
How do you add new files to the extracted folder of the original download?
Do you simply just browse 👍 
https://github.com/aaronsace/MultiPoolMiner/tree/master/Miners      and
https://github.com/aaronsace/MultiPoolMiner/tree/master/Pools    
then do you just save individual files? and over write the original ?

**Comment by aaronsace** [comment]
Yep, that will work.

**Comment by snakethejake81** [comment]
Made some additional adjustments to allow for more algos that run good profits like:  Sib, Blake2s, Nist5, Timetravel, x17 and x11evo.  All working with the tpruvot's ccminer.  I don't have any AMD cards to test sgminer with for these so I didn't change any of those.

**Comment by imrecsoka** [comment]
Hi , which files do i update for your  Sib, Blake2s, Nist5, Timetravel, x17 and x11evo improvements ?
Thanks and regards.
Also, if i want to donate i have edited the batch file called start.bat, which is in the root of the folder which i originally extracted maybe 2 months ago, so that it includes "-donate 15"   is this correct?

**Comment by somidax** [comment]
Hi,

do anyone khows where i can get this missing file for sgminer
"api-ms-win-core-libraryloader-l1-2-0.dll "

thanks!

**Comment by snakethejake81** [comment]
Only the Miners folder and the Pools folder are needed to update.

**Comment by imrecsoka** [comment]
1. Thanks, and this will allow me to see performance increase in "Sib, Blake2s, Nist5, Timetravel, x17 and x11evo "  as i mentioned above provided i include them in the start.bat file?
2. Donation parameter of -15, is this also correct?

**Comment by imrecsoka** [comment]
Dear  **somidax,** it is with great news that i come to deliver to thee that by the honer of internet there lays a treasure called Microsoft https://answers.microsoft.com/en-us/windows/forum/windows_10-files/missing-api-ms-win-core-dlls/d99d1368-0f92-43db-bbdb-7d080f1f96e9?auth=1

**Comment by somidax** [comment]
hello imrecsoka,

i have done it but the sgminer used for Lyra2z(zcoin) by djm34 will not
start.

This is the reason i asked for i have done it before all scan.

Please advise @aaronsace/MultiPoolMiner

Thanks!

**Comment by imrecsoka** [comment]
Oh okay, sorry man.
So you did install the Microsoft Visual Runtime Libraries right?
I have installed 2013 for 64 bit

**Comment by merlinsbeard69** [comment]
Is a zpool version ready to test? I would love if multipoolminer added zpool compatibility.

**Comment by snakethejake81** [comment]
I've been running my own custom version for the last couple weeks on zpool exclusively and haven't had time to make any commits.  But, I see @aaronsace has been adding some zpool related things to the base code (his code is so much better than my hacks).  I'll start testing his updates this weekend.

**Comment by merlinsbeard69** [comment]
Would you mind sharing your custom version? I would like to check it out.

Also, I suggest testing ccminer-Alexis78 version if you are using skein algo at all. It has noticeably better hashrate on my 1080 ti. https://github.com/alexis78/ccminer . 
compiled version: https://mega.nz/#F!5vIGUCzC!nLsQtAwDRiV8MYA_P-q9yg

**Comment by snakethejake81** [comment]
I have found the Alexis is only slightly faster than SP in some situations, but far less reliable.  With 6 GPUs the Alexis version sometimes will not spin up all GPUs.  SPmod is within the same speed and always works.

**Comment by snakethejake81** [comment]
Zpool Testing:  I downloaded the latest source files and added the bin folder from the latest release zip.  I set the following:

-Wallet <your wallet>
-Location US
-PoolName zpool
-Type nvidia
-Algorithm equihash,skein,neoscrypt,x17,blake2s,nist5,lyra2v2,lbry,timetravel,groestl,lyra2z,x11evo,decred,sib

I also remove all miner files from the Miners folder except for the following:

CcminerKlaust
CcminerLyra2z
CcminerSp
CcminerTpruvot
EWBF0

These I find to be the most stable and cause the least issues with NVIDIA cards, plus is reduces the clutter.

With this, I have no issues mining on zpool exclusively.

**Comment by imrecsoka** [comment]
Hello, is there anything i can do to mine Skein with AMD graphics?I tried to download Alexis but they all say i need nvidia ;-(
Im still learning so please forgive me.
I will also donate if you help me, i appreciate it.
I also want to confirm, what the algorithm is, this is very confusing for me.
Is it skein  or digibyte skein or skiencoin? i dont really fully understand in the command line what to put.

**Comment by snakethejake81** [comment]
I really only know nvidia and gave up on AMD months ago.

Skein is the Algorithm.  Digibyte is a coin that can be mined using the algorithm.  Skeincoin is also a coin that can also be mined with the algorithm.  Many coins can use the same algorithm.

**Comment by imrecsoka** [comment]
Hi snake, thanks for the information and clarifying it.
hmm so do i have hope to mine skein with AMD then?
I dont know what to mine with my AMD man ;-(

**Comment by merlinsbeard69** [comment]
with AMD, just do claymore dual mining with ETH + SC or ETH + DCR. That will be your best bet.

I tried doing exactly what you said snake (d/l latest files, copy working Bin, remove unnecessary miners, set username to wallet and set poolname to zpool) but mine just says "No Pools!". How did you get yours working?

**Comment by auavenger** [comment]
Same issue I had, I think wallet needs to be set directly in zpool.ps1 and user name adjusted somehow.  Going to try a few different fixes later.

**Comment by snakethejake81** [comment]
You set the Wallet parameter to your BTC wallet right?

Another alternative is the modify the MultiPoolMiner.ps1 directly.  All the parameters are at the top of the file.  The bat file is simply passing these into the file when run.

**Comment by merlinsbeard69** [comment]
That fixed it. Thank you guys!

**Comment by auavenger** [comment]
I have tried this a variety of different ways and I am still getting a "No Pools" error.  I have set username to the BTC address in the batch, in the MPM.ps1, then tried to define it in zpool.ps1.  Tried using -wallet in the batch, no dice.  Something is wrong with my zpool.ps1 or the series of events that tries to call Zpool, but I can't figure it out what it is because the logs contain nothing more than "No Pools".  Can you create a fork and drop a working zpool.ps1 and start.bat in it?  I need see what is missing in my files and calls that is creating the problem.

**Comment by snakethejake81** [comment]
The username parameter isn't used when on zpool.  You need to set the -Wallet parameter in the batch file or modify if directly in the MultiPoolMiner.ps1 file.

**Comment by auavenger** [comment]
I fixed it, but keep getting "no miners" error when I use all of the algos, must have missing/broken bins for some.

**Comment by auavenger** [comment]
Thank you for responding.  I really appreciate what you did with this.  This project has come a long way from when it was first introduced.  Pretty neat to see the progress.

**Comment by jjziets** [comment]
@snakethejake81 and @aaronsace should I wait for this to become released?

**Comment by Dubardo** [comment]
The current code doesn't seem to work :(

**Comment by btcbotter** [comment]
aaronsace any plans to release that nicehash code you mentioned? More curious if it is ever more profitable to mine there, though I think between MPH and zpool it would never be.

**Comment by aaronsace** [comment]
Not at the moment.

**Comment by scaras** [comment]
i would like to know that to. stopped using nicehash when they started with the v2.
been trying to get NH to work, but somehow i keep missing some things (maybe brains...)
