### ISSUE TITLE
Nsgminer.exe shows black screen with blinking terminal cursor 

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#84]
I can't get nsgminer.exe to work. Just shows blank screen with blinking terminal cursor. 

nsgminer.exe --api-listen -k neoscrypt -o stratum+ssl://hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

I only get a cmd window with the title nsgminer.exe and a blinking cursor

Tried it on:
rig1 RX480 4GBs
 on windows 10 64 bit
amd driver 16.11.3

Rig2 R9 390s
Windows 10
Amd 15.12

Rig3 Furyx
Windows 7 64bit 
Amd 16.3.2 
 

Rig4 hd7990s
Windows 10
Amd 15.12

what can I do to get nsgminer to run?

If i run nsgminer.exe --benchmark --neoscrypt it does start but not results.

**Comment by jjziets** [comment]
Also tried stratum+tcp same effect.

**Comment by jjziets** [comment]
i got it to work. your powersheel scrip start command looks like this. 

nsgminer.exe --api-listen **-k neoscrypt** -o stratum+**ssl**//hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

that does not work.

What worked is this
nsgminer.exe --api-listen **--neoscrypt** -o stratum+**tcp**://hub.miningpoolhub.com:17012 -u Etherion.ws10 -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64

bottom one works top one does not.

**Comment by jjziets** [comment]
$Path = '.\Bin\NeoScrypt-AMD\nsgminer.exe'
$Uri = 'https://github.com/ghostlander/nsgminer/releases/download/nsgminer-v0.9.2/nsgminer-win64-0.9.2.zip'

$Name = (Get-Item $script:MyInvocation.MyCommand.Path).BaseName

$Algorithms = [PSCustomObject]@{
    NeoScrypt = 'neoscrypt'
}

$Optimizations = [PSCustomObject]@{
    NeoScrypt = ' --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64'
}

$Algorithms | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = 'AMD'
        Path = $Path
        Arguments = -Join ('--api-listen --', $Algorithms.$_, ' -o stratum+tcp://$($Pools.', $_, '.Host):$($Pools.', $_, '.Port) -u $($Pools.', $_, '.User) -p x', $Optimizations.$_)
        HashRates = [PSCustomObject]@{$_ = -Join ('$($Stats.', $Name, '_', $_, '_HashRate.Week)')}
        API = 'Xgminer'
        Port = 4028
        Wrap = $false
        URI = $Uri
    }
}

**Comment by imrecsoka** [comment]
I get the same issue i cant stand SGMiner or any of the similar miners because they clear the screen and even verbose doesnt seem to help.
I also dont understand how u know what algorithms it supports.
Like minerd and cpuminer at least show you what algorithms are suppirted wghen you type --help
As for Sgminer and friends, it doesnt show you anything,
U need to guess, its a pain.

**Comment by aaronsace** [comment]
@jjziets thank you for getting the command line correct, works perfectly now: 
`nsgminer.exe --api-listen --neoscrypt -o stratum+tcp://hub.miningpoolhub.com:17012 -u aaronsace.multipoolminer -p x --gpu-threads 1 --worksize 64 --intensity 13 --thread-concurrency 64`
