### ISSUE TITLE
I need to understand what this means , please

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#86]
Hello, please help me understand these statistics as i am not sure what they mean?
      Speed Active                      Launched Command
      ----- ------                      -------- -------
241.00  H/s 00 Days 00 Hours 33 Minutes 2 Times  Bin\Equihash-Claymore\ZecMiner64.exe
                                                 -zpool stratum+ssl://europe.equihash-hub.
                                                 miningpoolhub.com:17023 -zwal lanky.1
                                                 -zpsw x
164.30  H/s 00 Days 00 Hours 34 Minutes Once     Bin\Cryptonight-CPU\xmr-stak-cpu.exe

*******Please ignore my MINUS SIGNS as i had to try and align this text******
Miner--------------------------------------------------btc----usd
----- -------------------------------------------------------------
MultiPoolMiner------------------------------------0.00151 2.16502
{Claymore-Equihash, FireiceCpu1-Cryptonight}----0.00165  2.31389

I dont quite understand the last part, is that the earnings per day right?
Which is it that i refer to because i see 2 lines? is one of them more accurate or how does this work?

I am using 1 RX470 and an Intel i7 2600K.

Thanks and kind regards
Some guy trying to not just let things go by , but also understand what the hell things mean.

**Comment by jjziets** [comment]
I also don't understand why MultiPoolMiner would be lower. Surely it should be equal or higher than Claymore-Equihash+ FireiceCpu1-Cryptonight

**Comment by jjziets** [comment]
Miner           btc     usd
-----           ---     ---
MultiPoolMiner  0.00320 4.60641
Claymore-Ethash 0.01362 19.63419

I don't get that

**Comment by aaronsace** [comment]
Delete the stats folder to rerun the benchmark.

**Comment by imrecsoka** [comment]
jjziets  it must be Chritmas for you.  I am assuming you have more that 1 Graphics card as it is probably  unlikely to get more than 0.0018 btc/day in most cases on 1 RX470 GPU.... at least the Dash forums say this... i would assume Zcash and Ether are similar ?

What i would like for the master AARONSACE to confirm and give his legislation of the nation.

**Comment by imrecsoka** [comment]
AARON i deleted the stats folder and re-started the start.bat , it now says 5.5 dollars of the 2 Radeons i have , is this fine?  Is something dodge.... i really want to sort it out of it is dodge , so please keep honest , thanks.

**Comment by aaronsace** [comment]
Red text is most likely that you are missing miner exe files; not a major issue as there is many miners. 
As long as the hashrate is correct the profit will be correct. 

I don't hide the miner windows so you can check it with a calculator. 

I'm really busy at the moment and I am trying to be as active as possible here. I aiming to push some updates today.

**Comment by imrecsoka** [comment]
hi Aaron,


Thanks for the information, though i dont know how to measure with a calculator, if you can show one day i can contribute to you for good deed, thank yuo very much Sir,


Regards

Imre

________________________________

**Comment by aaronsace** [comment]
MiningPoolHub have done all the calculations: https://miningpoolhub.com/

Just multiply it by your hashrate (in gh/s; not kh/s and not h/s)

**Comment by imrecsoka** [comment]
Please can you give me an example? i dont follow , really

**Comment by aaronsace** [comment]
Just multiply your hash rate measured in gh/s by MiningPoolHub's BTC/GH/Day value.
