### ISSUE TITLE
miner.exe still blacklisted by most antivirus

### ISSUE THREAD

**Issue by reppolice** [aaronsace/MultiPoolMiner#88]
I would not want to fight a lost war with the 3-4 antivirus programs that delete miner.exe at home and at work etc. Am I right to assume the scripts are supposed to be immune to its absence and will simply decide that some other miner is "faster"? Also, how long is this benchmarking supposed to last, and how many miners are supposed to be running at the end? Windows popping left and right has been happening for an hour, and quite a few of the miners have been left running, I thought at worst it should be one program for GPU and one for CPU, with replacements if profitability changes beyond a threshold. Obviously neither do I understand the scripts, nor the auto-max profitability yet :)

**Comment by aaronsace** [comment]
Run the 'start.bat' file for a quicker benchmark. Also, edit the command in file and remove cpu or amd or nvidia for even faster benchmark.

**Comment by reppolice** [comment]
I did use the start, but I am unable to say if it correctly handled my "issues", for example the missing miner.exe and no AMD GPU.

**Comment by aaronsace** [comment]
To remove AMD, take 'amd' out of the start.bat. 
Add the whole folder to your antivirus exceptions list.
