### ISSUE TITLE
Groestl support please 

### ISSUE THREAD

**Issue by fonyo** [aaronsace/MultiPoolMiner#89]
Otherwise, I am very impressed with this. Config options per miner/algo would be great.

Edit: Also, documentation please!

**Comment by zaptrem** [comment]
I know, it looks like there is some sort of support but I've never seen my rig mine Groestl, despite it being significantly more profitable than other alt-coins at the time.

**Comment by aaronsace** [comment]
Is there an issue with Groestl?

**Comment by zaptrem** [comment]
It is never benchmarked. In addition, no matter how profitable it is (it's
usually at the top of the list) it is never, ever mined.

**Comment by aaronsace** [comment]
Are you using the 'start.bat'? Did you add Groestl to the command line?

**Comment by zaptrem** [comment]
I am using start.bat. How do I "add Groestl to the command line?"

**Comment by aaronsace** [comment]
Edit it in notepad and add it to the list Equihash,Ethash etc

**Comment by zaptrem** [comment]
Just like that it will start working? How does that happen?

**Comment by aaronsace** [comment]
There is a lot of algorithms; I only enabled the popular ones in the example.

**Comment by zaptrem** [comment]
Okay, what other algorithms did you leave disabled in the example? Don't I
need to dig into one of the PowerShell files to tell it which pool and
miner exe to point at?

**Comment by aaronsace** [comment]
If you delete the algorithm option then it will use all the algorithms: 

Skein
Myriad_Groestl
Ethash
NeoScrypt
Cryptonight
Equihash
Sia
Groestl
Qubit
Lyra2z
X11
Lyra2RE2
Scrypt
Yescrypt
Keccak

**Comment by zaptrem** [comment]
Okay. While I've got you here, are you close to the main developer of the pools this connects to? I wanted to request a way to see an overview of what/where/at what speed my miners were mining from the web interface.

**Comment by aaronsace** [comment]
I and others have requeted that also; each pool has it's own page but there needs to be a unified dashboard. Post it on the MiningPoolHub forum; he is very active on there.

**Comment by zaptrem** [comment]
Is there a thread I can join so our support isn't spread out?

**Comment by zaptrem** [comment]
Also, how exactly does the script pick the most profitable algo? I'm watching it make some pretty confusing choices, such as mining Digibit-Qubit despite it being near the bottom of the MultiMiningPool profit list.

**Comment by aaronsace** [comment]
I select the most sustainable, profitable algorithm based on the hashrate of your system and how much MiningPoolHub is paying. 

MiningPoolHub does not know what your hashrate so it is not accurate for algorithm switching.

**Comment by zaptrem** [comment]
Okay, thanks. Finally, I'm not sure I understand the numbers listed at the bottom, they say

MultiPoolMiner --  5.31462USD
(MyriadGroestl, CPU Lyra2z) -- 9.18USD

Which one represents me? Why is the one on the top so far from the bottom?

**Comment by aaronsace** [comment]
MultiPoolMiner is what you have been earning over the week. 

(MyriadGroestl, CPU Lyra2z) is what you would earn over the week mining using just these two miners. 

They are obviously wrong though; I assume you have changed the settings so it will take time to adjust or you can delete the profit stat in the stats folder.

**Comment by zaptrem** [comment]
When I add new algorithms should I delete the stats folder to rebenchmark
everything?

**Comment by aaronsace** [comment]
No, just delete the one stat called 'profit' if you want it to readjust straight away what profit it says next to MultiPoolMiner.

**Comment by aaronsace** [comment]
I'll close this issue as it appears to be working.

**Comment by zaptrem** [comment]
Good idea, thanks for the help.

**Comment by imrecsoka** [comment]
Lol that was a long conversation.
I hope zaptrem is going to donate 30 minutes of mining time.
