### ISSUE TITLE
why enter hash rate

### ISSUE THREAD

**Issue by boysie123** [aaronsace/MultiPoolMiner#9]
surely the current hash rate can be taken from the running miner either locally or from the pool. going through the large amt of different coins knowing exactly what hash rate you will get is very odd, and I wont know this unless I watch every one of them in turn and run it a second time...you also don't say where to add it, you have to scan through the code trying to find where you should enter it. While I think what you are doing is a good thing it seems very odd layout and quite unfriendly.

looking forward to the next version.

Boysie

**Comment by aaronsace** [comment]
It took a day to write for someone; not my best work. Version 2 will be much better for everyone.

**Comment by aaronsace** [comment]
ETA Christmas eve.

**Comment by lyolyalya** [comment]
strange thing=)i like it=)i rewrote it by myself for nvidia and it works well=)v2 is scaring me=)

**Comment by aaronsace** [comment]
V2 is out! Please test, specifically NVIDIA because I don't have a card to test that on. Thank you!
