### ISSUE TITLE
How is profit calculated?

### ISSUE THREAD

**Issue by lee-aaron** [aaronsace/MultiPoolMiner#90]
I have a nvidia GTX 960 and I'm seeing some weird differences. Normally, I'm able to mine about 20-30 DGB in about 30-40 minutes with Skein algo. However, with the MYR-GR algo, I can only produce about 2-3 DBG in the same timeframe. I know I can just remove the MYR-GR algo using start.bat but I'm curious about how profitability is calculated.

**Comment by aaronsace** [comment]
It's simply based on what the pool estimates that it will pay but mining is luck based so you aren't guaranteed consistent payments. Lower difficulty algorithms are more consistent.

**Comment by imrecsoka** [comment]
What are pool estimates , how do you work it out manually?
Do i need to know or can i just use your main screen that i launch to do this for me?
mine says 5.5 roughly for the 2 Graphics cards i have and CPU  combined.
It seems to be the same as Nicehashminer....
Besides your application and nicehashminer showing you the rate/day i also wanted to know how you work it out but it sounds like rocket science. Unless somebody can laymans terms it for me.

**Comment by somidax** [comment]
Is there a way one can find out why miningpoolhub implemented "cloud flare"
for their "ssl" was working fine but as of today, one can not access his
mining account.

Kindly advice how to reach them.


thanks

**Comment by aaronsace** [comment]
MiningPoolHub is suffering a DDOS attack and will be back ASAP. 
Cloud flare is meant to prevent it but must be really bad.

**Comment by somidax** [comment]
thanks but my mining is still going on well. However the MPM stopped
working and i m using the individual miners as fail-over.

Will shift my hashing power to  surpnovva or zpool for now until they are
back.

I hope they come back soon for they are really trust worthy and one gets
value for mining in their pool.

cheers!

**Comment by aaronsace** [comment]
The program adapts over time even if the benchmark is incorrect. Just check the hashrate on multipoolminer and the external miner window matches then it will be fine.
