### ISSUE TITLE
No pools

### ISSUE THREAD

**Issue by jjziets** [aaronsace/MultiPoolMiner#92]
Getting an message no pool with 2.5. How do I fix this?

**Comment by aaronsace** [comment]
MiningPoolHub is suffering a DDOS attack and will be back ASAP.
Cloud Flare is meant to prevent this but it must be really bad.

**Comment by imrecsoka** [comment]
I get the same issue i thought it was that malware or  "mysterious" thing i told u about yesterday.
I have just reloaded windows , now for the drivers and all that jazz
