### ISSUE TITLE
unrelated but i am really struggling to install powershell 5 on windows 7

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#95]
unrelated but i am really struggling to install powershell 5 on windows 7 i downloaded the management framework from microsoft and it started installing an update before it installed it self but it then rolled back the changes as it failed.
I tried this 2 times
No ideas what to do now

**Comment by aaronsace** [comment]
Run this in command prompt to check your windows system files: 
`sfc /scannow`

Running this file should fix any problems with windows update: 
https://aka.ms/wudiag
