### ISSUE TITLE
excavator miner

### ISSUE THREAD

**Issue by gazm** [aaronsace/MultiPoolMiner#97]
What is the feasibility of adding this miner?

**Comment by aaronsace** [comment]
Can you provide a link and I will check. If I can add it then I will.

**Comment by gazm** [comment]
It is made by nicehash, no open source but has API and is allowed on all
pools

https://bitcointalk.org/index.php?topic=1777827.0

**Comment by imrecsoka** [comment]
nheqminer for me never works , God knows what the issue is  with that miner. it connects fine but then it always results in 0 solutions per second

**Comment by gazm** [comment]
thanks for this will definitely be donating an increased amount for a few weeks.
