### ISSUE TITLE
No idea what this error / warning message is 2.5.1

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#98]
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1>setx GPU_FORCE_64BIT_PTR 0
 Writing web request
  Writing request stream... (Number of bytes written: 539218)
SUCCESS: Specified value was saved.
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1>setx GPU_USE_SYNC_OBJECTS 1
SUCCESS: Specified value was saved.
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1>setx GPU_MAX_ALLOC_PERCENT 100
SUCCESS: Specified value was saved.
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1>setx GPU_SINGLE_ALLOC_PERCENT 100
SUCCESS: Specified value was saved.
C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1>powershell -version 5.0 -noexit -executionpol
icy bypass -windowstyle maximized -command "&.\multipoolminer.ps1 -username lankyman -work
ername multipoolminer -interval 60 -location europe -ssl -type amd,nvidia,cpu -algorithm c
ryptonight,ethash,equihash,lyra2z -poolname miningpoolhub -currency btc,usd -donate 10"
**Get-MpPreference : The term 'Get-MpPreference' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At C:\Users\icsoka\Desktop\MultiPoolMinerV2.5.1\MultiPoolMiner.ps1:35 char:5
+ if((Get-MpPreference).ExclusionPath -notcontains (Convert-Path .)){St ...
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-MpPreference:String) [], CommandNotFo
   undException
    + FullyQualifiedErrorId : CommandNotFoundException**
Transcript started, output file is .\Logs\2017-05-14_10-35-50.txt

**Comment by aaronsace** [comment]
I think Windows Defender is missing on your windows installation. I will wrap it to ignore this problem.

**Comment by imrecsoka** [comment]
Yeh, i have disabled the services.msc 's windows defender and also windows updates, cant stand that stuff. it slows your machine down and removes .exe work like yours.
I need to donate to you so how the hell can i if things are horrible.
Unless i can have windows defender up and then let it ignore your stuff? i dont know actually
I dont even run antivirus, not sure if that is very bad?
I have been randomwared many times already and lost precious files.

**Comment by aaronsace** [comment]
I've never noticed any speed issues. If you use the machine other than mining then I recommend enabling it again. 

The error is because I am adding an antivirus exception to avoid the very issue that you were having.

**Comment by imrecsoka** [comment]
Oh okay so i will enabled the services again.
I am using windows 7 hey m, not windows 10.
I dont think i have the right computer for windows 10, strong enough even, not sure.
