### ISSUE TITLE
New errors here or miners failing

### ISSUE THREAD

**Issue by imrecsoka** [aaronsace/MultiPoolMiner#99]
![2 5 1-error1](https://cloud.githubusercontent.com/assets/25494601/26032367/140d6886-3892-11e7-84f7-bd02b2216233.PNG)

:-(

**Comment by aaronsace** [comment]
That's fine; you will get that during benchmark. It is using all your GPUs correctly now.

**Comment by aaronsace** [comment]
Sorry, didn't zoom in to see the socket errors. Looks a you are failing to connect to the pool...?

**Comment by imrecsoka** [comment]
- No i dea why the socket error on the cryptonight server, what can the issue be? Was working fine 6 hours ago.
- The index failed on the XMR-STAK-AMD , i must ignore?

**Comment by aaronsace** [comment]
Must have been a server issue for a minute. 

I assume you have 2 AMD GPUs so the other 4 failing is correct and will only appear during the benchmark.
